In [1]:
# import libraries
import os
import pandas as pd
import json
import gzip
import fasttext 
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [2]:
path = '../../../src/data/schemafiltereddata/TrainTestTables/Large/Test'
l = [file for file in os.listdir(path) if file.startswith('Product')]
len(l)

4239

In [28]:
l2 = l[2000:2200]
l2

['Product_dekkodesignstore.com_September2020.json.gz',
 'Product_playforever.com.au_September2020.json.gz',
 'Product_lestyleparfait.com_September2020.json.gz',
 'Product_bricotoolspack.com_September2020.json.gz',
 'Product_catkhacmica.com_September2020.json.gz',
 'Product_lightmybricks.com.au_September2020.json.gz',
 'Product_nakednation.co.uk_September2020.json.gz',
 'Product_leonorsilva.com_September2020.json.gz',
 'Product_maioranamoda.com_September2020.json.gz',
 'Product_geniebeauty.com_September2020.json.gz',
 'Product_jarvistech.co.uk_September2020.json.gz',
 'Product_warehouse-lighting.com_September2020.json.gz',
 'Product_nejomisfindings.com_September2020.json.gz',
 'Product_roselawnpueblo.org_September2020.json.gz',
 'Product_blp.com_September2020.json.gz',
 'Product_annajewelbox.com_September2020.json.gz',
 'Product_themodernsportsmanonline.com_September2020.json.gz',
 'Product_ukcarglass.co.uk_September2020.json.gz',
 'Product_liondunk.com_September2020.json.gz',
 'Product_donscarz.com_September2020.json.gz',
 'Product_beadwholesaler.com_September2020.json.gz',
 'Product_vinyljunkies.net_September2020.json.gz',
 'Product_ljung.net_September2020.json.gz',
 'Product_jimfalkbeverlyhillslexus.com_September2020.json.gz',
 'Product_enova-connectors.com_September2020.json.gz',
 'Product_mirfar.com_September2020.json.gz',
 'Product_dakarwebstore.com_September2020.json.gz',
 'Product_supplemented.co.uk_September2020.json.gz',
 'Product_autoworldomaha.com_September2020.json.gz',
 'Product_mesatactical.com_September2020.json.gz',
 'Product_disco.com.uy_September2020.json.gz',
 'Product_trendywelt.com_September2020.json.gz',
 'Product_wholesalepumps.com_September2020.json.gz',
 'Product_bdswimmingpool.com_September2020.json.gz',
 'Product_gaatha.com_September2020.json.gz',
 'Product_spanishpublishers.net_September2020.json.gz',
 'Product_mexgrocer.com_September2020.json.gz',
 'Product_discobliss.com_September2020.json.gz',
 'Product_tws-store.com_September2020.json.gz',
 'Product_p90workoutschedule.com_September2020.json.gz',
 'Product_narecza.com_September2020.json.gz',
 'Product_prechic.com_September2020.json.gz',
 'Product_sokios.com_September2020.json.gz',
 'Product_allstarsdirect.co.uk_September2020.json.gz',
 'Product_treefrogtreasures.com_September2020.json.gz',
 'Product_baublesnbling.com_September2020.json.gz',
 'Product_cosasempotrables.com_September2020.json.gz',
 'Product_reliks.com_September2020.json.gz',
 'Product_ardemadrid.com_September2020.json.gz',
 'Product_stoneandtileshoppe.com_September2020.json.gz',
 'Product_adv3nture.com_September2020.json.gz',
 'Product_fiesta-mascotte.com_September2020.json.gz',
 'Product_oznaturals.com_September2020.json.gz',
 'Product_livestreetlife.com_September2020.json.gz',
 'Product_hotlistproducts.com_September2020.json.gz',
 'Product_art50.net_September2020.json.gz',
 'Product_bentongluntandtappfuneralhome.com_September2020.json.gz',
 'Product_thebearknows.com_September2020.json.gz',
 'Product_thehungrypuppy.com_September2020.json.gz',
 'Product_shopgreatfallsgames.com_September2020.json.gz',
 'Product_castlebeachclubcondosforsale.com_September2020.json.gz',
 'Product_octopusbrand.com_September2020.json.gz',
 'Product_babevn.com_September2020.json.gz',
 'Product_drdmotorbikes.com_September2020.json.gz',
 'Product_rabat.net_September2020.json.gz',
 'Product_evosensors.com_September2020.json.gz',
 'Product_paddlegang.com_September2020.json.gz',
 'Product_wildercdjr.com_September2020.json.gz',
 'Product_xtremevwparts.com_September2020.json.gz',
 'Product_concordefrench.com_September2020.json.gz',
 'Product_softballbats-sale.com_September2020.json.gz',
 'Product_jacksturner.com_September2020.json.gz',
 'Product_beautyencounter.com_September2020.json.gz',
 'Product_stikets.co.uk_September2020.json.gz',
 'Product_buymedstoday.com_September2020.json.gz',
 'Product_w-wohnen.com_September2020.json.gz',
 'Product_cluckeyo.com_September2020.json.gz',
 'Product_interiorshowplace.com_September2020.json.gz',
 'Product_cainbmw.com_September2020.json.gz',
 'Product_rivieramayahaciendas.com_September2020.json.gz',
 'Product_plumbworld.co.uk_September2020.json.gz',
 'Product_senatshop.com.ua_September2020.json.gz',
 'Product_golfersauthority.com_September2020.json.gz',
 'Product_fotoflits.com_September2020.json.gz',
 'Product_parafarmacianatural.com_September2020.json.gz',
 'Product_carheroesusa.com_September2020.json.gz',
 'Product_ropesdirect.co.uk_September2020.json.gz',
 'Product_renoautowarehouse.com_September2020.json.gz',
 'Product_direct-drones.com_September2020.json.gz',
 'Product_flowers4almaty.com_September2020.json.gz',
 'Product_minhanhshops.com_September2020.json.gz',
 'Product_socksaddict.com_September2020.json.gz',
 'Product_a-zdarts.com_September2020.json.gz',
 'Product_gantri.com_September2020.json.gz',
 'Product_oakparquetflooring.co.uk_September2020.json.gz',
 'Product_esskateboarding.com_September2020.json.gz',
 'Product_lifeandlibertymotors.com_September2020.json.gz',
 'Product_carterchevrolet.com_September2020.json.gz',
 'Product_scottfhsj.com_September2020.json.gz',
 'Product_abracadaroom.com_September2020.json.gz',
 'Product_stickershoppe.com_September2020.json.gz',
 'Product_jalebe.com_September2020.json.gz',
 'Product_theurbanflair.com_September2020.json.gz',
 'Product_acaciawoodusa.com_September2020.json.gz',
 'Product_slikhaarshop.co.uk_September2020.json.gz',
 'Product_xn--80ameqebfb1b3c.net_September2020.json.gz',
 'Product_chaussurecassis.com_September2020.json.gz',
 'Product_luxbeautymall.com_September2020.json.gz',
 'Product_bouchermazda.com_September2020.json.gz',
 'Product_keystonedistributing.com_September2020.json.gz',
 'Product_floursacktowels.com_September2020.json.gz',
 'Product_degzou.com_September2020.json.gz',
 'Product_shop-komakino.com_September2020.json.gz',
 'Product_lygiay.com_September2020.json.gz',
 'Product_bridetribes.com.au_September2020.json.gz',
 'Product_iclothing.com_September2020.json.gz',
 'Product_dkhardware.com_September2020.json.gz',
 'Product_sinaimemorialchapelsinc.com_September2020.json.gz',
 'Product_workingperson.com_September2020.json.gz',
 'Product_cosmeticosonline.com_September2020.json.gz',
 'Product_wavecentral99.com_September2020.json.gz',
 'Product_authenticyixing.com_September2020.json.gz',
 'Product_dlabelonline.com_September2020.json.gz',
 'Product_vinico.com_September2020.json.gz',
 'Product_indogolok.com_September2020.json.gz',
 'Product_sollu.com.br_September2020.json.gz',
 'Product_tresemme.com_September2020.json.gz',
 'Product_justcerts.com_September2020.json.gz',
 'Product_brightonmotorgrp.com.au_September2020.json.gz',
 'Product_purple-cat.co.uk_September2020.json.gz',
 'Product_healthcabin.net_September2020.json.gz',
 'Product_matthewsandsonfuneralhome.net_September2020.json.gz',
 'Product_antelopebeads.com_September2020.json.gz',
 'Product_gahostel.com_September2020.json.gz',
 'Product_clicknorder.co.uk_September2020.json.gz',
 'Product_elgot.com_September2020.json.gz',
 'Product_googansquad.com_September2020.json.gz',
 'Product_fixparts-online.com_September2020.json.gz',
 'Product_nanotrun.com_September2020.json.gz',
 'Product_lockpickworld.com_September2020.json.gz',
 'Product_cortezcigars.com_September2020.json.gz',
 'Product_ecrans-telephone.com_September2020.json.gz',
 'Product_bluesky-filter.com_September2020.json.gz',
 'Product_capitalgolf.com_September2020.json.gz',
 'Product_powerbulbs.com_September2020.json.gz',
 'Product_highcountrygardens.com_September2020.json.gz',
 'Product_1800getlens.com_September2020.json.gz',
 'Product_almgwinnett.com_September2020.json.gz',
 'Product_placedespop.com_September2020.json.gz',
 'Product_culinarydepotinc.com_September2020.json.gz',
 'Product_thegreenhousepnw.com_September2020.json.gz',
 'Product_wingstuff.com_September2020.json.gz',
 'Product_braecosales.com.au_September2020.json.gz',
 'Product_forsake.com_September2020.json.gz',
 'Product_latestbuy.com.au_September2020.json.gz',
 'Product_stanleyschmitzinc.com_September2020.json.gz',
 'Product_cpperformance.com_September2020.json.gz',
 'Product_mississaugahardware.com_September2020.json.gz',
 'Product_blackparrotmaine.com_September2020.json.gz',
 'Product_mercymotorsllc.com_September2020.json.gz',
 'Product_gushgush.com_September2020.json.gz',
 'Product_mundofantasma.com_September2020.json.gz',
 'Product_furnitalia.com_September2020.json.gz',
 'Product_cotshirt.com_September2020.json.gz',
 'Product_vinpet.com.vn_September2020.json.gz',
 'Product_uicflames.com_September2020.json.gz',
 'Product_takaski.com_September2020.json.gz',
 'Product_tynansvolkswagen.com_September2020.json.gz',
 'Product_balkanenergy.net_September2020.json.gz',
 'Product_acerobotasloja.com.br_September2020.json.gz',
 'Product_naughtypossessions.co.uk_September2020.json.gz',
 'Product_royalqueenseeds.com_September2020.json.gz',
 'Product_welovebags.co.uk_September2020.json.gz',
 'Product_bayometric.com_September2020.json.gz',
 'Product_charleslstevensfuneralhome.com_September2020.json.gz',
 'Product_yourdeal24.com_September2020.json.gz',
 'Product_kinghandlighting.com_September2020.json.gz',
 'Product_uomocollezioni.com_September2020.json.gz',
 'Product_bluelightful.com_September2020.json.gz',
 'Product_shoplovestitch.com_September2020.json.gz',
 'Product_kolaypazar.com_September2020.json.gz',
 'Product_outletonweb.com_September2020.json.gz',
 'Product_autosalesandserviceinc.com_September2020.json.gz',
 'Product_overtide.com_September2020.json.gz',
 'Product_leatherjacket4.com_September2020.json.gz',
 'Product_pushys.com.au_September2020.json.gz',
 'Product_farmacias1000.com_September2020.json.gz',
 'Product_macpartstore.com_September2020.json.gz',
 'Product_officialmemorabilia.com_September2020.json.gz',
 'Product_vote5shirt.com_September2020.json.gz',
 'Product_jimellishyundaiparts.com_September2020.json.gz',
 'Product_getnatty.com_September2020.json.gz',
 'Product_metaformtools.com_September2020.json.gz',
 'Product_birlikte.com.tr_September2020.json.gz',
 'Product_trollingmotors.net_September2020.json.gz',
 'Product_thefemwear.com_September2020.json.gz',
 'Product_chefbakers.com_September2020.json.gz',
 'Product_pouceetlina.com_September2020.json.gz',
 'Product_staticsolutions.com_September2020.json.gz',
 'Product_haixusa.com_September2020.json.gz']

In [29]:
listcolt = pd.read_csv('../../../src/data/data/CSV_files/stats_filtered_and_cleaned_tables.csv')
listcolt = listcolt.set_index('filename')
listcolt = listcolt[listcolt.index=='Product']
listcolt

                                              listofcolumns  numtables
filename
Product   ['name', 'offers', 'brand', 'aggregaterating',...      33203

In [30]:
path = '/work-ceph/bizer-tp2021/data_integration_using_deep_learning/src/data/data/CSV_files'
stats = pd.read_csv(path + '/all_files_stats.csv')
files = pd.read_csv(path + '/all_files_cleaned.csv')
files = files.drop(columns={'Unnamed: 0'})
listcol= files.groupby('filename')['column_name'].apply(list).reset_index(name='listofcolumns')
listcol.filename = listcol.filename.str.split('_', expand=True)[0]
listcol.index = listcol['filename']
listcol = listcol[listcol['filename']=='Product']
listcol

         filename                                      listofcolumns
filename
Product   Product  [name, offers, brand, aggregaterating, mpn, ca...

In [31]:
path='../../../src/data/schemafiltereddata/TrainTestTables/Large/Test'
files = [file for file in os.listdir(path) if file.endswith('.json.gz')]
for index in listcol.filename:
    setcol = listcol.loc[index]['listofcolumns']
    for file in l2:
    # read file
        df = pd.read_json(os.path.join(path, '{}'.format(file)), compression='gzip', lines=True)
        display(file)
        display(df[df.columns.intersection(setcol)].head())

'Product_dekkodesignstore.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Still Life with Vase and Three Branches,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",{'name': 'Society6'},"{'reviewcount': '1', 'ratingvalue': '5'}",0
1,Let the rain sing you a lullaby,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",{'name': 'Society6'},"{'reviewcount': '1', 'ratingvalue': '5'}",0
2,Mud cloth - Black and White Arrowheads,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",{'name': 'Society6'},"{'reviewcount': '1', 'ratingvalue': '5'}",0
3,Life happens coffee helps,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",{'name': 'Society6'},"{'reviewcount': '1', 'ratingvalue': '5'}",0
4,HOW MANY ARMS DO YOU HAVE,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",{'name': 'Society6'},"{'reviewcount': '1', 'ratingvalue': '5'}",0

'Product_playforever.com.au_September2020.json.gz'

,name,offers,brand,mpn,model,gtin13
0,Heat Blue Police,"{'price': '99.95', 'pricecurrency': 'AUD', 'av...",Playforever,PLM103,PLM103,5060346820521
1,Verve Velocita Jacques,"{'pricecurrency': 'AUD', 'availability': 'http...",Playforever,PLVF303,PLVF303,5060346820750
2,Mini Red,"{'pricecurrency': 'AUD', 'availability': 'http...",Playforever,PL701,PL701,5060346820200
3,Midi Bonnie GB,"{'price': '110.00', 'pricecurrency': 'AUD', 'a...",Playforever,PL407,PL407,5060346820644
4,Midi Rufus Weller,"{'price': '110.00', 'pricecurrency': 'AUD', 'a...",Playforever,PLR802,PLR802,5060346820842

'Product_lestyleparfait.com_September2020.json.gz'

,name,offers,brand,mpn,weight
0,Buy Summer White 2-Piece Wedding Suit at LeSty...,[{'itemcondition': 'http://schema.org/NewCondi...,{'name': 'LeStyleParfait.Com Online Shop'},13119989-custom-color-xxs,1.5kg
1,"Buy Men Linen Pants, Casual Loose Trousers, St...",[{'itemcondition': 'http://schema.org/NewCondi...,{'name': 'LeStyleParfait.Com'},PRS15YM01,1.0kg
2,Dashiki African Shirt For Men - African Clothi...,[{'itemcondition': 'http://schema.org/NewCondi...,{'name': 'LeStyleParfait.Com'},32487722-white-usa-s,1.0kg
3,Buy Reach For The Best Hooded Jacket at LeStyl...,[{'itemcondition': 'http://schema.org/NewCondi...,{'name': 'LeStyleParfait.Com'},5576398-black-m,1.0kg
4,Bodysuit Sexy V Neck Floral Women Bodysuit,"[{'name': 'Floral / M', 'itemcondition': 'http...",{'name': 'LeStyleParfait.Com Online Shop'},20611739-color-s,1.0kg

'Product_bricotoolspack.com_September2020.json.gz'

,name,offers,brand,category,mpn,itemcondition
0,BANCO SSM ESMERILADORA /BF 20 VARIO,"{'price': '374.30', 'availability': 'http://sc...",{'name': 'OPTIMUM'},SECTOR METAL &gt; Deformación de Material &gt;...,3107101,http://schema.org/NewCondition
1,"Tope de arrastre 3, piezas",{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'HOLZSTAR'},SECTOR MADERA &gt; Accesorios,5931056,http://schema.org/NewCondition
2,BANCO PARA TORNO TU2304/2406/2506/2807/3008,"{'price': '519.72', 'availability': 'http://sc...",None,SECTOR METAL &gt; Tornos,None,http://schema.org/NewCondition
3,PISTOLA DE CARTUCHOS KP PRO - R,"{'price': '139.85', 'availability': 'http://sc...",{'name': 'AIRKRAFT'},AIRE COMPRIMIDO &gt; Pistolas,2102260,http://schema.org/NewCondition
4,TROLLEY PORTAHERRAMIENTAS WAT22TR,"{'pricecurrency': 'EUR', 'availability': 'http...",{'name': 'METALWORKS'},HERRAMIENTAS MANUALES &gt; Portaherramientas,WAT22TR,http://schema.org/NewCondition

'Product_catkhacmica.com_September2020.json.gz'

                                 name price shop-currency
0          Khung Mica Chống Tĩnh Điện    0₫           VND
1              Kệ tờ rơi mica - KTR03    0₫           VND
2  Biểu Trưng Phale Giá Rẻ Tại Hà Nội    0₫           VND
3             Biểu trưng Mica - BTM11    0₫           VND
4    Biển chức danh mica theo yêu cầu    0₫           VND

'Product_lightmybricks.com.au_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,gtin12
0,Adhesive Squares (10 pack),{'itemcondition': 'http://schema.org/NewCondit...,Light My Bricks,None,adhesive-squares-10PK,7.935912e+11
1,LEGO The Big Bang Theory #21302 Light Kit,{'itemcondition': 'http://schema.org/NewCondit...,Light My Bricks,"{'itemreviewed': 'The Big Bang Theory #21302',...",thebigbangtheory-21302,7.935912e+11
2,Bit Lights (Red) 30cm - (4 pack),"{'price': '14.99', 'itemcondition': 'http://sc...",Light My Bricks,None,bit-light-red-30cm4PK,7.935912e+11
3,LEGO Star Wars UCS Imperial Star Destroyer #75...,{'image': 'https://cdn.shopify.com/s/files/1/0...,Light My Bricks,"{'worstrating': '1', 'itemreviewed': 'Star War...",ucsimperialstardestroyer,7.935912e+11
4,LEGO London Bus #10258 Light Kit,{'itemcondition': 'http://schema.org/NewCondit...,Light My Bricks,"{'worstrating': '1', 'bestrating': '5', 'ratin...",londonbus-10258,7.935912e+11

'Product_nakednation.co.uk_September2020.json.gz'

,name,offers,brand,category,gtin13
0,"Sterling Silver Heart, Butterfly & Round Desig...","{'pricevaliduntil': '2020-10-05', 'pricecurren...",{'name': 'Naked Nation'},Necklace,5.060570e+12
1,925 Sterling Silver Oval Pendant - Evil Eye Ne...,"{'price': '1.899E1', 'pricevaliduntil': '2020-...",{'name': 'Naked Nation'},Necklace,5.060570e+12
2,925 Sterling Silver with Cubic Zirconia Stones...,"[{'name': 'Silver', 'availability': 'https://s...",{'name': 'Naked Nation'},Earrings,NaN
3,Snowflake 925 Sterling Silver Cubic Zirconia S...,"[{'sku': 'BRL0818', 'pricecurrency': 'GBP', 'n...",{'name': 'Naked Nation'},Bracelet,5.060570e+12
4,"Tree of Life Rose Gold with Crystals, Sterling...","[{'name': 'Silver', 'sku': 'SBRL0048-02', 'pri...",{'name': 'Naked Nation'},Bracelet,NaN

'Product_leonorsilva.com_September2020.json.gz'

,name,offers,price,shop-currency
0,Blue Striped Origami Pants,Blue Striped Origami Pants Origami inspired hi...,$140.00 USD,USD
1,Knit Bolero,Knit Bolero Angora wool and nylon blend knit b...,$220.00 USD,USD
2,The Gypsie Dress,The Gypsie Dress Blue plaid tea-length dress w...,$210.00 USD,USD
3,Long White Cape,Long White Cape Almost floor-length white cape...,$620.00 USD,USD
4,The Mademoiselle Grey Dress,"The Mademoiselle Grey Dress Round neck \""sweat...",$158.00 USD,USD

'Product_maioranamoda.com_September2020.json.gz'

,name,offers,brand,aggregaterating,review,gtin8
0,ABITO - GAELLE PARIS,{'url': 'https://maioranamoda.com/m7124121-abi...,GAELLE,"{'bestrating': '5', 'ratingvalue': '5', 'ratin...",{'author': 'MaioranaModa'},m7124121
1,BORSA A TRACOLLA CON CATENA,{'url': 'https://maioranamoda.com/m4833551-bor...,TWINSET,"{'bestrating': '5', 'ratingvalue': '5', 'ratin...",{'author': 'MaioranaModa'},m4833551
2,SNEAKERS UOMO MASTER,{'url': 'https://maioranamoda.com/m5400536-sne...,WUSHU RU-YI,"{'bestrating': '5', 'ratingvalue': '5', 'ratin...",{'author': 'MaioranaModa'},m5400536
3,CARA BAG SUEDE,{'url': 'https://maioranamoda.com/m895843-cara...,LA CARRIE BAG,"{'bestrating': '5', 'ratingvalue': '5', 'ratin...",{'author': 'MaioranaModa'},m895843
4,GONNA IN RASO,"{'price': '0', 'url': 'https://maioranamoda.co...",VICOLO,"{'bestrating': '5', 'ratingvalue': '5', 'ratin...",{'author': 'MaioranaModa'},m9499013

'Product_geniebeauty.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review
0,Million Dollar Lash Kit (Mascara+Booster),"{'pricecurrency': 'USD', 'availability': 'http...",Genie Beauty,"{'reviewcount': '7', 'ratingvalue': '5.00'}",GMDLK,[{'datepublished': '2019-04-28T17:04:12-07:00'...
1,Make Me Blush Anti-Aging Cream Blush with Smal...,"{'pricecurrency': 'USD', 'availability': 'http...",Genie Beauty,"{'reviewcount': '1', 'ratingvalue': '5.00'}",GMMB 3KBS,"{'datepublished': '2019-04-29T04:23:26-07:00',..."
2,"In the Buff Hand, Foot &amp; Body Spa Set","{'pricecurrency': 'USD', 'availability': 'http...",Genie Beauty,None,buff,None
3,GENIE Dream Cream + FREE GENIE H'eye'drator PL...,"{'pricecurrency': 'USD', 'availability': 'http...",Genie Beauty,None,GDC-HPEC,None
4,Superglide Waterproof Gel Eyeliner,"{'mpn': 'GSGE', 'sku': 'GSGE', 'price': '20.00...",Genie Beauty,"{'reviewcount': '13', 'ratingvalue': '4.92'}",None,[{'datepublished': '2018-09-15T04:37:09-07:00'...

'Product_jarvistech.co.uk_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,850 G2 i55300 15F Wc/8/500/FP/W8P64,"{'pricecurrency': 'GBP', 'availability': 'http...",{'name': 'hp'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",H0JW9EC
1,HP 650/655 G2/G3 KEYBOARD NO B/L ITALIAN,"{'availability': 'https://schema.org/InStock',...",{'name': 'hp'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",841136-061
2,Folio 1020 G1 M5Y71 12Q TS 8/512SD/10P64,"{'pricecurrency': 'GBP', 'availability': 'http...",{'name': 'hp'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",X2G24ES
3,470 G3 i56200 17F 8/256SD/DVRW/F/W7P610L,"{'pricecurrency': 'GBP', 'availability': 'http...",{'name': 'hp'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",W4P79EA
4,800 35W G4 DM i58500T 8/1TB/WIFI/W10P64,"{'pricecurrency': 'GBP', 'availability': 'http...",{'name': 'hp'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",2YH11AV

'Product_warehouse-lighting.com_September2020.json.gz'

,name,offers,brand,mpn,itemcondition
0,Emergency Lighting 90 Minute Small Backup Powe...,"[{'price': '681.82', 'itemcondition': 'http://...",{'name': 'WareLight'},NaN,http://schema.org/NewCondition
1,Gardner Bender MCS-100W SnapSHOT Multi-Cable S...,"{'mpn': '032076057657', 'itemcondition': 'http...",{'name': 'Gardner Bender'},3.207606e+10,http://schema.org/NewCondition
2,"CounterMax 3K 6\"" LED Under Cabinet, 3 Watts, ...",[{'itemcondition': 'http://schema.org/NewCondi...,{'name': 'Maxim Lighting'},7.832092e+11,http://schema.org/NewCondition
3,Millennium Lightings Pendant Offered in Bronze...,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Millennium Lighting'},NaN,http://schema.org/NewCondition
4,GE-F26DBX/827/ECO (10 pack),"{'pricevaliduntil': '2020-10-06', 'itemconditi...",{'name': 'General Electric'},4.316898e+10,http://schema.org/NewCondition

'Product_nejomisfindings.com_September2020.json.gz'

,name,offers,brand,mpn,releasedate
0,Slash Neck Sleeveless Career Elegant Women Dre...,"{'pricecurrency': 'USD', 'offercount': '4', 'l...",{'name': 'Aliexpress'},32882447765_771_100014064,2019-10-13 13:22:33 -0500
1,Bodysuits Women Sleeveless Halter Stretch Soli...,"{'lowprice': '19.97', 'highprice': '19.97', 'o...",{'name': 'Came On Apparel Store US'},4000715039768_200004891_100014065_201336106,2020-09-07 07:43:46 -0500
2,Eternity Eau De Toilette Spray By Calvin Klein,"{'pricecurrency': 'USD', 'offercount': '4', 'l...",{'name': 'Calvin Klein'},413058,2019-10-01 00:14:56 -0500
3,Azzaro Eau De Toilette Spray By Azzaro,"{'pricecurrency': 'USD', 'offercount': '4', 'l...",{'name': 'Azzaro'},417251,2020-07-28 10:25:59 -0500
4,Women Canvas Shoes Flat Sneakers Open Back Sli...,"{'lowprice': '26.97', 'highprice': '26.97', 'o...",{'name': 'brc1978 Store'},1000008057919_193_200000333,2019-10-30 12:17:45 -0500

'Product_roselawnpueblo.org_September2020.json.gz'

,name,offers,aggregaterating,review,itemcondition,model
0,Cross Wind Chime - Personalized,"{'highprice': '109.95', 'pricecurrency': 'USD'...",None,None,NewCondition,[{'name': 'Cross Wind Chime - Personalized (Me...
1,Strength & Solace Spray,"{'pricecurrency': 'USD', 'highprice': '119.95'...","{'reviewcount': '115', 'ratingvalue': '4.90'}","[{'name': 'Strength & Solace Spray', 'author':...",NewCondition,"{'name': 'Strength & Solace Spray (Standard)',..."
2,Touching Tribute Spray,"{'pricecurrency': 'USD', 'highprice': '187.95'...","{'ratingvalue': '5.00', 'reviewcount': '12'}","[{'name': 'Touching Tribute Spray', 'descripti...",NewCondition,"{'sku': 'T234-1A', 'image': 'https://res.cloud..."
3,Love Carries on Pendant,"{'pricecurrency': 'USD', 'lowprice': '79.95', ...",None,None,NewCondition,{'image': 'https://res.cloudinary.com/picasso/...
4,Lovely One Spathiphyllum Plant,"{'pricecurrency': 'USD', 'highprice': '74.95',...","{'reviewcount': '23', 'ratingvalue': '4.96'}",[{'description': 'PAID $125.00 FOR A $15 FLOWE...,NewCondition,"{'sku': 'T272-1A', 'url': 'https://www.roselaw..."

'Product_blp.com_September2020.json.gz'

,name,offers,model,manufacturer,weight
0,<strong>390cfm 4-hole base gasket</strong>,{'price': '2.85'},None,None,NaN
1,<strong>30cc HD Pump Diaphragm</strong>,{'price': '8.52'},351936,Holley®,0.003968
2,<strong>BLP T-Shirt BLK Historical</strong>,{'price': '18.95'},BLP SHIRT SM-HST,BLP,0.030000
3,<strong>5/16 x 7.700 x .080 Wall Pushrods 6600...,{'price': '3.99'},6600-7.700,BLP,0.375000
4,<strong>3C Gas billet block .610 thick 51700-4...,{'price': '25'},51700-4R-P,BLP,0.000000

'Product_annajewelbox.com_September2020.json.gz'

,name,offers,brand,review,price,pricecurrency
0,Gold Dreamcatcher Charm Beaded Bracelet,"{'price': '5.99', 'pricecurrency': 'GBP'}",AnnaJewelBox,{'datepublished': '2011-03-25'},5.99,GBP
1,Queen's Crown and Lion King Matching Couple Br...,"{'price': '8.99', 'pricecurrency': 'GBP'}",AnnaJewelBox,{'datepublished': '2011-03-25'},8.99,GBP
2,Crystal Cubic Zirconia Evening Party Dress Bel...,"{'price': '12.99', 'pricecurrency': 'GBP'}",AnnaJewelBox,{'datepublished': '2011-03-25'},12.99,GBP
3,Sparkling Silver Crystal Hoop Bridal Earrings,"{'price': '4.99', 'pricecurrency': 'GBP'}",AnnaJewelBox,{'datepublished': '2011-03-25'},4.99,GBP
4,Stunning 3 Rows Silver Crystal Flexible Tennis...,"{'price': '12.99', 'pricecurrency': 'GBP'}",AnnaJewelBox,{'datepublished': '2011-03-25'},12.99,GBP

'Product_themodernsportsmanonline.com_September2020.json.gz'

,name,offers,brand,mpn,gtin12
0,Permit to Carry &amp; Renewal Multi-State - Sa...,"{'pricecurrency': 'USD', 'itemcondition': 'New...",{'name': 'The Modern Sportsman'},PTC10102020,PTC10102020
1,Permit to Carry &amp; Renewal Multi-State - Mo...,"{'pricecurrency': 'USD', 'itemcondition': 'New...",{'name': 'The Modern Sportsman'},PTC10052020,PTC10052020
2,Gold Membership,"{'pricecurrency': 'USD', 'availability': 'InSt...",{'name': 'The Modern Sportsman'},GOLD,555555400000
3,Permit to Carry &amp; Renewal Multi-State - Sa...,"{'pricecurrency': 'USD', 'itemcondition': 'New...",{'name': 'The Modern Sportsman'},PTC053020202,PTC053020202
4,Permit to Carry &amp; Renewal Multi-State - Sa...,"{'pricecurrency': 'USD', 'itemcondition': 'New...",{'name': 'The Modern Sportsman'},PTC09192020,PTC09192020

'Product_ukcarglass.co.uk_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,itemcondition
0,Ford Transit 2008 Rear Window Replacement,"{'price': '312.68', 'url': '/book/?window_id=8...",Mercedes,"{'ratingvalue': '5', 'reviewcount': '3'}",8545,None
1,Renault Clio 2011 Rear Windscreen Replacement,"{'pricevaliduntil': '2025-11-05', 'price': '28...",Renault,"{'ratingvalue': '5', 'reviewcount': '3'}",8429,None
2,Mercedes C-class 2013 Front Passenger Side Win...,{'url': '/book/?window_id=595&make=mercedes&mo...,Mercedes,"{'ratingvalue': '5', 'reviewcount': '3'}",595,None
3,Volkswagen Up 2013 Front Passenger Side Window...,"{'price': '211.26', 'url': '/book/?window_id=2...",Volkswagen,"{'ratingvalue': '5', 'reviewcount': '3'}",2014,None
4,Audi Q3 2015 Front Windscreen Replacement,{'url': '/book/?window_id=2874&make=audi&model...,Audi,"{'ratingvalue': '5', 'reviewcount': '3'}",2874,None

'Product_liondunk.com_September2020.json.gz'

,name,offers,brand,category,mpn
0,Basketball ball shooting trainer training acce...,"[{'pricevaliduntil': '2020-10-27', 'availabili...",{'name': 'liondunk.com'},Coach`s Corner - Training Accessories,19575
1,Basketball Stands Toy Set Basketball,"{'pricevaliduntil': '2020-10-27', 'availabilit...",{'name': 'liondunk.com'},Basketball Toys,13592
2,"Basketball Charms, Antique Tibetan silver Tone...","{'name': 'Basketball Charms, Antique Tibetan s...",{'name': 'liondunk.com'},Basketball Fashion,19613
3,Outdoor Sports Football Basketball Ball One Sh...,"[{'pricevaliduntil': '2020-10-27', 'availabili...",{'name': 'liondunk.com'},Basketball Bags,13617
4,Basketball sports bags football volleyball soc...,"{'pricevaliduntil': '2020-10-27', 'availabilit...",{'name': 'liondunk.com'},Basketball Bags,13620

'Product_donscarz.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,2012 Chevrolet Malibu 4dr Sdn LT w/1LT,"{'availability': 'https://schema.org/InStock',...",{'name': 'Chevrolet'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",1G1ZC5E04CF323952
1,2015 GMC Terrain AWD 4dr SLE w/SLE-1,"{'availability': 'https://schema.org/InStock',...",{'name': 'GMC'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",2GKFLVEK1F6200513
2,2015 Subaru Forester 4dr CVT 2.0XT Touring,"{'availability': 'https://schema.org/InStock',...",{'name': 'Subaru'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",JF2SJGWC7FH519459
3,2012 Ford F-150 4WD SuperCrew 145 XLT,"{'availability': 'https://schema.org/InStock',...",{'name': 'Ford'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",1FTFW1ET0CFB87159
4,2014 Kia Soul 5dr Wgn Auto Base,"{'availability': 'https://schema.org/InStock',...",{'name': 'Kia'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",KNDJN2A27E7032119

'Product_beadwholesaler.com_September2020.json.gz'

,name,offers,model,color,width
0,Strand Pewter Spacer Bead,"{'price': ['$5.00', '$4.50', '$4.75']}",PBF218,Silver Plated,13mm 2 Strand Pewter Spacer Bead
1,Sterling Silver Grapes Charm,"{'price': ['$11.53', '$8.65', '$9.51']}",SP200,Silver,"No jumpring, 18.25x12mm"
2,50 gram 8/0 MEDIUM BLUE HEX CUT Miyuki Delicas,"{'price': ['$11.42', '$10.82', '$12.02']}",DBLH0005-50,None,50gram 8/0 MEDIUM BLUE HEX CUT Miyuki Delicas
3,Rice Jewelry making startup kit with 200 assor...,None,RICEKIT-2,None,Rice Jewelry making startup kit with 200 assor...
4,5.5mm Sterling Silver Number 4,"{'price': ['$2.73', '$2.47', '$2.39']}",SQREG-4,Silver,5.5mm Sterling Silver Number 4

'Product_vinyljunkies.net_September2020.json.gz'

,name,offers,brand,aggregaterating,review,gtin12
0,Various Artists - Sno Babies (Original Soundtr...,"{'price': '15.98', 'url': 'https://shop.vinylj...",ELEVEN SEVEN MUSIC,"{'reviewcount': '100', 'ratingvalue': '5'}","{'datepublished': '2011-04-01', 'author': 'unk...",849320089322
1,Vinyl Junkies - Buddy In Space - Women's Blue ...,"{'url': 'https://shop.vinyljunkies.net', 'pric...",None,"{'reviewcount': '100', 'ratingvalue': '5'}","{'datepublished': '2011-04-01', 'author': 'unk...",Vinyl237
2,Vinyl Junkies - Buddy In Space - Women's Blue ...,"{'url': 'https://shop.vinyljunkies.net', 'pric...",None,"{'reviewcount': '100', 'ratingvalue': '5'}","{'datepublished': '2011-04-01', 'author': 'unk...",Vinyl325
3,The Flaming Lips - American Head [2LP],"{'url': 'https://shop.vinyljunkies.net', 'gtin...",WARNER RECORDS,"{'reviewcount': '100', 'ratingvalue': '5'}","{'datepublished': '2011-04-01', 'author': 'unk...",093624893011
4,Charli XCX - how i'm feeling now [LP],"{'price': ['13.98', '19.98', '9.99'], 'url': '...",ATLANTIC,"{'reviewcount': '100', 'ratingvalue': '5'}","{'datepublished': '2011-04-01', 'author': 'unk...",190295209285

'Product_ljung.net_September2020.json.gz'

,name,offers,brand,gtin13,additionalproperty
0,CORE TEE - DUSTY BLUE,[{'itemcondition': 'http://schema.org/NewCondi...,{'name': 'Ljung'},7.332890e+12,{'value': '1232214818931'}
1,CORE TEE - BORDEAUX,[{'itemcondition': 'http://schema.org/NewCondi...,{'name': 'Ljung by Marcus Larsson'},7.332890e+12,{'value': '4442775945331'}
2,PLATED CREWNECK SWEATER - DK PEACH,[{'itemcondition': 'http://schema.org/NewCondi...,{'name': 'Ljung by Marcus Larsson'},7.332890e+12,{'value': '4432478896243'}
3,GRUDE LEATHER GLOVES - DEEP WINE,[{'description': 'Gloves in textured sheep lea...,{'name': 'Ljung by Marcus Larsson'},7.332890e+12,{'value': '1232210624627'}
4,TAILORED JACKET - SAFARI GREEN,[{'description': 'Tailored outwear/ indoor jac...,{'name': 'Ljung'},7.332890e+12,{'value': '4431169683571'}

'Product_jimfalkbeverlyhillslexus.com_September2020.json.gz'

,name,offers,brand,mpn,model,manufacturer,color
0,New 2020 Lexus ES 300h 300h,{'itemcondition': 'http://schema.org/NewCondit...,Lexus,9040,ES 300h,{'name': 'Lexus'},Obsidian
1,New 2020 Lexus RX 350 350,{'itemcondition': 'http://schema.org/NewCondit...,Lexus,9420,RX 350,{'name': 'Lexus'},Atomic Silver
2,New 2020 Lexus ES 300h 300h Luxury,{'itemcondition': 'http://schema.org/NewCondit...,Lexus,9042,ES 300h,{'name': 'Lexus'},Atomic Silver
3,New 2021 Lexus,{'itemcondition': 'http://schema.org/NewCondit...,Lexus,JTJSJRDZXM5010592,None,{'name': 'Lexus'},Obsidian
4,New 2020 Lexus RX 350 350,{'itemcondition': 'http://schema.org/NewCondit...,Lexus,9420,RX 350,{'name': 'Lexus'},Obsidian

'Product_enova-connectors.com_September2020.json.gz'

,name,offers,brand,weight,releasedate,width,height,depth
0,"3 m Jack 3.5 mm 3 pole - 1/4\"" plug 2 pole ada...","{'pricecurrency': 'CHF', 'url': 'https://enova...",ENOVA,0.202 kg,-0001-11-30,70 cm,260 cm,3000 cm
1,6 m RCA Jack Adapter cable stereo,"{'pricecurrency': 'CHF', 'url': 'https://enova...",ENOVA,0.354 kg,-0001-11-30,100 cm,280 cm,6000 cm
2,1 m XLR female to XLR male microphone cable 3-...,"{'pricecurrency': 'CHF', 'url': 'https://enova...",ENOVA,0.126 kg,2019-08-01,75 cm,250 cm,1000 cm
3,"2 m 1/4\"" plug 3 pole balanced jack jack cable","{'pricecurrency': 'CHF', 'url': 'https://enova...",ENOVA,0.164 kg,-0001-11-30,75 cm,260 cm,2000 cm
4,RJ45 cable connector protection black metal ho...,"{'pricecurrency': 'CHF', 'url': 'https://enova...",ENOVA,0.017 kg,-0001-11-30,18.8 cm,18.8 cm,52.2 cm

'Product_mirfar.com_September2020.json.gz'

,name,offers,brand,aggregaterating,category
0,Левое стекло фары Toyota Camry XV50 2011-2014,"{'pricecurrency': 'RUB', 'price': '2500'}",Toyota,"{'bestrating': '5', 'reviewcount': '1', 'worst...",Toyota/Camry/Camry XV50/Camry XV50 2011-2014
1,Правое стекло фары BMW 7 series F01 2008-2015,"{'pricecurrency': 'RUB', 'price': '4500'}",BMW,"{'bestrating': '5', 'reviewcount': '1', 'worst...",BMW/7 Series/7 series F01 2008-2015
2,Стекла фар Mini Hatch R56 2010-2013 Рестайлинг,"{'pricecurrency': 'RUB', 'lowprice': '6000', '...",None,"{'reviewcount': '2', 'ratingvalue': '5'}",None
3,Левое стекло фары Mitsubishi Pajero Sport II 2...,"{'pricecurrency': 'RUB', 'price': '4000'}",Mitsubishi,None,Mitsubishi/Pajero Sport/Pajero Sport II 2008-2016
4,Левое стекло фары Mazda 6 GJ 2012-2015,"{'pricecurrency': 'RUB', 'price': '3000'}",Mazda,"{'bestrating': '5', 'reviewcount': '1', 'worst...",Mazda/6/GJ 2012-2015

'Product_dakarwebstore.com_September2020.json.gz'

,name,offers,brand,mpn,manufacturer
0,CARTOUCHE LEXMARK LASER T420,"{'pricecurrency': 'XOF', 'price': '76000'}",None,CARTOUCHE LEXMARK LASER T420,None
1,TELEVISEUR SAMSUNG LED 55D7000,"{'pricecurrency': 'XOF', 'price': '2350000'}",{'name': 'SAMSUNG'},TELEVISEUR SAMSUNG LED 55D7000,{'name': 'SAMSUNG'}
2,TETE IMPRESSION HP 940 (C4900) ( YELLOW BLACK),"{'pricecurrency': 'XOF', 'price': '45000'}",{'name': 'HP'},TETE IMPRESSION HP 940 (C4900) ( YELLOW BLACK),{'name': 'HP'}
3,HABILLEMENT ENFANTS - 1 Piece grenouillere ani...,"{'pricecurrency': 'XOF', 'price': '6900'}",None,HABILLEMENT ENFANTS - 1 Piece grenouillere (3-...,None
4,"TV LCD SAMSUNG 46\"" LA46C550","{'pricecurrency': 'XOF', 'price': '899000'}",{'name': 'SAMSUNG'},"TV LCD SAMSUNG 46\"" LA46C550",{'name': 'SAMSUNG'}

'Product_supplemented.co.uk_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Coenzyme Q10 30mg Softgel Capsules,"[{'pricevaliduntil': '2020-10-22', 'pricecurre...",{'name': 'Supplemented'},"{'ratingcount': '4', 'ratingvalue': '4.75E0'}",CQ1030/90
1,Glucosamine And Chondroitin Tablets 500/400mg,"[{'pricecurrency': 'GBP', 'availability': 'htt...",{'name': 'Supplemented'},"{'ratingcount': '3', 'ratingvalue': '4.6666666...",GLCH54/90
2,Ginkgo Biloba Extract 6000mg Tablets,"[{'sku': 'GINKG6000/360', 'pricecurrency': 'GB...",{'name': 'Supplemented'},"{'ratingvalue': '5.0E0', 'ratingcount': '7'}",GINKG6000/90
3,Capsicum Extract 1000mg Capsules,"[{'sku': 'CAPS1000/180', 'pricevaliduntil': '2...",{'name': 'Supplemented'},"{'ratingcount': '4', 'ratingvalue': '4.75E0'}",CAPS1000/90
4,Vitamin B Complex 400mg Tablets,"[{'pricevaliduntil': '2020-10-22', 'sku': 'VIT...",{'name': 'Supplemented'},"{'ratingvalue': '5.0E0', 'ratingcount': '4'}",VITBCOM400/90

'Product_autoworldomaha.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,2011 HONDA CIVIC LX,"{'availability': 'https://schema.org/InStock',...",{'name': 'HONDA'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",19XFA1F56BE034888
1,2016 MAZDA 3 SPORT,"{'availability': 'https://schema.org/InStock',...",{'name': 'MAZDA'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",JM1BM1U74G1337897
2,2016 RAM 1500 ST,"{'availability': 'https://schema.org/InStock',...",{'name': 'RAM'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",1C6RR7FG8GS213925
3,2009 NISSAN ALTIMA 2.5,"{'availability': 'https://schema.org/InStock',...",{'name': 'NISSAN'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",1N4AL21E49N561289
4,2013 FORD C-MAX SEL,"{'price': '8499', 'availability': 'https://sch...",{'name': 'FORD'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",1FADP5BU4DL506838

'Product_mesatactical.com_September2020.json.gz'

,name,offers,brand,aggregaterating,review
0,SureShell® Polymer Carrier And Rail For Berett...,"{'availability': 'http://schema.org/InStock', ...",{'name': 'BERETTA'},"{'reviewcount': '1', 'ratingcount': '1', 'rati...",{'name': 'Better Attention To Detail Is Necess...
1,"Adapter Mount Pic Rail For Rem 870 (12-GA, 9½ In)","{'availability': 'http://schema.org/InStock', ...",{'name': 'REMINGTON'},None,None
2,"Picatinny Rail For Moss 500 (Standard Profile,...","{'availability': 'http://schema.org/InStock', ...",{'name': 'MOSSBERG'},"{'reviewcount': '1', 'ratingvalue': '5', 'rati...","{'author': 'Joseph', 'reviewbody': 'Rail fit p..."
3,LEO® Gen II Telescoping Stock Adapter for Rem ...,"{'availability': 'http://schema.org/InStock', ...",{'name': 'REMINGTON'},"{'reviewcount': '5', 'ratingvalue': '4', 'rati...",[{'reviewbody': 'Like the first review I got t...
4,Urbino® Pistol Grip Stock For Remington 870/11...,"{'availability': 'http://schema.org/InStock', ...",{'name': 'REMINGTON'},"{'ratingcount': '7', 'reviewcount': '7', 'rati...","[{'name': 'Urbino Pistol Grip Stock, Remington..."

'Product_disco.com.uy_September2020.json.gz'

,name,offers,brand,gtin13,weight,additionalproperty
0,Botella sport capsula Star Wars,"{'pricecurrency': 'UYU', 'price': '269.00'}",{'name': '-'},7730586189846,"{'value': '10,0000', 'unitcode': 'GRM'}","{'value': 'GeantUN', 'name': 'sellers'}"
1,Whisky Americano Buffalo Trace 1 L,"{'price': '2175.00', 'pricecurrency': 'UYU'}",{'name': 'BUFFALO TRACE'},0080244009229,"{'value': '10,0000', 'unitcode': 'GRM'}","{'value': 'Disco', 'name': 'sellers'}"
2,Cigarrillo LUCKY STRIKE 20,"{'pricecurrency': 'UYU', 'price': '165.00'}",{'name': 'LUCKY STRIKE'},None,"{'value': '1,0000', 'unitcode': 'GRM'}","{'value': 'Disco', 'name': 'sellers'}"
3,Espumoso Demi Sec Delice Chandon,"{'price': '715.00', 'pricecurrency': 'UYU'}",{'name': 'CHANDON'},7790975003139,"{'value': '1,0000', 'unitcode': 'GRM'}","{'value': 'GeantUN', 'name': 'sellers'}"
4,Galletitas Club Social Integral 144g,"{'pricecurrency': 'UYU', 'price': '65.00'}",{'name': 'CLUB SOCIAL'},7622300992293,"{'value': '1,0000', 'unitcode': 'GRM'}","{'value': 'GeantUN', 'name': 'sellers'}"

'Product_trendywelt.com_September2020.json.gz'

,name,offers,category,itemcondition,isrelatedto
0,"Torten-& Dessertring D 7cm, Höhe 7,5cm, Edelstahl",{'url': 'https://trendywelt.com/Torten-Dessert...,Dessert__Tortenringe,http://schema.org/NewCondition,None
1,"Flügel 44x14mm, Loch 2mm",{'url': 'https://trendywelt.com/Fluegel-44x14m...,110,http://schema.org/NewCondition,"[{'price': '2.50', 'pricecurrency': 'EUR'}, {'..."
2,"Edelstahlhalsreif 45cm nylonummantelt, goldfarben","{'price': '1.00', 'url': 'https://trendywelt.c...",Halsreifen,http://schema.org/NewCondition,"[{'price': '0.40', 'pricecurrency': 'EUR'}, {'..."
3,Hohlkugel Glasanhänger zum selber befüllen,{'url': 'https://trendywelt.com/Hohlkugel-Glas...,341422275147726,http://schema.org/NewCondition,"[{'price': '6.99', 'pricecurrency': 'EUR'}, {'..."
4,100 Stück silberfarben,"{'price': '1.80', 'url': 'https://trendywelt.c...",41,http://schema.org/NewCondition,"[{'price': '0.99', 'pricecurrency': 'EUR'}, {'..."

'Product_wholesalepumps.com_September2020.json.gz'

,name,offers,category,weight,releasedate,width,height,depth
0,Little Giant PE-A pump replace with RPE-A-6 ~ ...,"{'pricecurrency': 'USD', 'price': '39.99', 'av...",Little Giant Pond pumps,2.00 lbs,2015-12-03 18:41:54,0.00 inches,0.00 inches,0.00 inches
1,"CP3-115 15,000 1/30 hp 21,000 CFM","{'pricecurrency': 'USD', 'price': '55.99', 'av...",Specialty Pumps,5.00 lbs,2015-12-02 19:03:17,0.00 inches,0.00 inches,0.00 inches
2,OPWG-46 Koi 1/8 hp 2760 gph,{'itemcondition': 'http://schema.org/Condition...,External Pond Pumps,14.00 lbs,2015-12-03 13:41:16,0.00 inches,0.00 inches,0.00 inches
3,F-PES-100 95gph Replacement RPF-PES-100 Tile S...,{'itemcondition': 'http://schema.org/Condition...,Little Giant Pumps,2.00 lbs,2015-11-19 18:58:13,0.00 inches,0.00 inches,0.00 inches
4,Cal Pump 875FS 7A Replacement RW875FS-.7A,"{'price': '91.99', 'availability': 'http://sch...",Cal 875FS Model Replacements,4.00 lbs,2016-10-25 18:06:42,0.00 inches,0.00 inches,0.00 inches

'Product_bdswimmingpool.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review
0,STG SMOOTH SAND FILTER WITH PUMP,"{'price': '25000', 'availability': 'instock', ...",{'name': 'BD Swimming Pool'},"{'reviewcount': '1', 'ratingvalue': '5'}",279,"{'author': 'root', 'description': 'Others Info..."
1,Sauna stove SAV 02,"{'availability': 'instock', 'price': '00', 'pr...",{'name': 'BD Swimming Pool'},"{'reviewcount': '1', 'ratingvalue': '5'}",854,"{'author': 'root', 'datepublished': '2018-02-2..."
2,UV - STERILIZATION,"{'availability': 'instock', 'pricevaliduntil':...",{'name': 'BD Swimming Pool'},"{'reviewcount': '1', 'ratingvalue': '5'}",692,"{'author': 'root', 'datepublished': '2018-02-2..."
3,Swimming Pool Flower Fountain With Two Tower,"{'availability': 'instock', 'pricevaliduntil':...",{'name': 'BD Swimming Pool'},"{'reviewcount': '1', 'ratingvalue': '5'}",1276,"{'author': 'root', 'datepublished': '2018-04-1..."
4,SPOTLIGHT /BURIED LIGHTING,"{'availability': 'instock', 'price': '00', 'pr...",{'name': 'BD Swimming Pool'},"{'reviewcount': '1', 'ratingvalue': '5'}",495,"{'author': 'root', 'description': 'Call for Pr..."

'Product_gaatha.com_September2020.json.gz'

,name,offers,brand,mpn,model,manufacturer
0,Lapoo - Elephant Planter,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",OCHRE ~ Kavita Ganguly,11428,4091-OC-29,OCHRE ~ Kavita Ganguly
1,Vijul ❋ Assamese Handwoven ❋ Silk Saree ❋ 21,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",Bibaar ( By Bandita),18881,4007-BIB-21,Bibaar ( By Bandita)
2,White Light ✥ Dhyan Matsya,"{'pricecurrency': 'USD', 'price': '465.67', 'p...",White Light Elements,22281,1647-WL-17,White Light Elements
3,रितुपर्णा ⚘ Tussar Roller Printed Saree { L },"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",Weavers Studio,15478,0802-WS_G_S012,Weavers Studio
4,Miniature Painting ~ Maharaja,"{'price': '107.46', 'pricevaliduntil': '2099-1...",Devendra Gaur,21756,3750-DG01,Devendra Gaur

'Product_spanishpublishers.net_September2020.json.gz'

,name,offers,brand,mpn,model
0,"Alana, la bailarina del agua",{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Obelisco'},"Alice Cardoso, Serra Sandra",9788491451785
1,10 princesas juguetonas,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Obelisco'},"Rebecca Weerasekera,Jayne Schofield",9788491452133
2,El mago de Auschwitz,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Obelisco'},"Kathy Kacer, Newland Gillian",9788416648184
3,Dirigentes del mundo futuro,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Diamante'},Carlos Cuauhtémoc Sánchez,9786079830786
4,¡Fui yo!,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Obelisco'},"Mike Gordon, Easton Tom",9788416117703

'Product_mexgrocer.com_September2020.json.gz'

,name,offers,brand,aggregaterating,category,review,isrelatedto,gtin12
0,Cola de Caballo Herb Tea - .40 oz.40 oz,"{'pricevaliduntil': '01-06-2019', 'url': 'http...",{'name': 'El Sol de Mexico'},"{'ratingvalue': '5.0', 'ratingcount': '1'}",Spices & Herbs,{'description': 'I had kidney stones and with ...,[{'name': 'Lucia's Herbal Remedies Cola de Cab...,737714790001
1,Klass Atole Fresa - Strawberry (Pack of 3) - 1...,"{'price': '4', 'url': 'https://mexgrocer.com/5...",{'name': 'Klass'},"{'ratingvalue': '5.0', 'ratingcount': '1'}",Beverages,"{'author': 'Atole f.', 'description': 'It�€™s ...","[{'name': 'LALA UHT Strawberry Milk 3 Pack'}, ...",754177830402
2,Pulparindo -Tamarind Mexican Candy by De La Ro...,"{'price': '3.95', 'pricevaliduntil': '01-06-20...",{'name': 'Pulparindo'},"{'ratingcount': '15', 'ratingvalue': '4.9'}",Mexican Candy,"[{'author': 'L H.', 'datepublished': 'November...","[{'name': 'Pelon Pelo Rico Candy'}, {'name': '...",725226000206
3,Whole Poblano Peppers - Chiles Poblanos San Mi...,"{'gtin12': '024456063303', 'pricevaliduntil': ...",{'name': 'San Miguel'},"{'ratingcount': '16', 'ratingvalue': '4.8'}",Chile Peppers,[{'description': 'Being in NH can be tough fin...,[{'name': 'La Morena Jalapeno Peppers Filled w...,024456063303
4,McCormick Chamomile Tea Caffeine Free - Manzan...,"{'gtin12': '052100371498', 'pricevaliduntil': ...",{'name': 'McCormick'},"{'ratingvalue': '5.0', 'ratingcount': '2'}",Spices & Herbs,"[{'datepublished': 'September 18, 2011', 'auth...",[{'name': 'McCormick Guacamole Seasoning Mix (...,052100371498

'Product_discobliss.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,"4 Pack Color Rotating Bulb E26, RGB Color Chan...","{'pricecurrency': 'USD', 'price': '19.99', 'pr...",{'name': 'Bluex Bulbs'},"{'reviewcount': '89', 'ratingvalue': '5'}",1584
1,OTTFF 3W E27 Disco Ball Lamp RGB Rotating LED ...,"{'pricecurrency': 'USD', 'price': '17.99', 'av...",{'name': 'OTTFF'},"{'reviewcount': '89', 'ratingvalue': '5'}",1600
2,Sound Activated Party Lights with Remote Contr...,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",{'name': 'SOLMORE'},"{'reviewcount': '89', 'ratingvalue': '5'}",1577
3,"Bluetooth Disco Ball Light, LED Disco Ball Nig...","{'pricecurrency': 'USD', 'pricevaliduntil': '2...",{'name': 'Ansbarton'},"{'reviewcount': '89', 'ratingvalue': '5'}",1583
4,SleekLighting Red 3D Infinity Firework Light B...,"{'pricecurrency': 'USD', 'price': '24.89', 'pr...",{'name': 'SLEEKLIGHTING'},"{'reviewcount': '89', 'ratingvalue': '5'}",1606

'Product_tws-store.com_September2020.json.gz'

,name,offers,brand,category,mpn
0,Design male Purse Card Holder,"[{'pricecurrency': 'USD', 'price': '28.00', 'a...",tws-store.com,Men's Wallets,167
1,Luxury Brand Wallet Men Leather Men Wallets Pu...,[{'name': 'Luxury Brand Wallet Men Leather Men...,tws-store.com,Men's Wallets,106
2,New fashion Multi-card man wallet,[{'url': 'https://tws-store.com/brand-men-wall...,tws-store.com,Men's Wallets,135
3,Leather Small Billfold Wallet for Men,[{'url': 'https://tws-store.com/wardwolf-men-t...,tws-store.com,Men's Wallets,17
4,Swiss Knife + Money Clip,"[{'pricecurrency': 'USD', 'name': 'Swiss Knife...",tws-store.com,EDC Accessories,443

'Product_p90workoutschedule.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,gtin
0,OASIS FOX Home Gym Workout Fitness Roman Chair...,"{'price': '52.99', 'availability': 'https://sc...",OASIS FOX,"{'bestrating': '5', 'ratingcount': '59', 'rati...",None,6.550365e+11
1,Body Solid FID46 Flat Incline Decline Bench,"{'pricevaliduntil': '2020-12-21', 'availabilit...",Body-Solid,"{'bestrating': '5', 'ratingvalue': '4.1', 'rat...",FID46,6.384480e+11
2,"Body-Solid Tools Landmine Pivot Plate, Olympic...","{'availability': 'https://schema.org/InStock',...",Body-Solid Tools,"{'bestrating': '5', 'ratingvalue': '4.4', 'rat...",LMPP,6.384480e+11
3,"5 Exercise Bands / 2 Light, 1 Medium, 1 Heavy ...","{'availability': 'https://schema.org/InStock',...",Body Mind Spirit Fitness,"{'bestrating': '5', 'ratingvalue': '4.3', 'rat...",BMS-EXBND-5PCS,7.311579e+11
4,Finer Form Gym Quality Flat Bench with Wheels ...,"{'availability': 'https://schema.org/InStock',...",Finer Form,"{'bestrating': '5', 'ratingcount': '41', 'rati...",None,6.825004e+11

'Product_narecza.com_September2020.json.gz'

,name,offers,brand,category,mpn
0,Penis Development Krem,"{'price': '100.00', 'pricevaliduntil': '2020-0...",{'name': 'Penis Development'},Yetişkin Ürünleri > Özel Ürünler,14077
1,Physicians Formula Powder Palette Mineral Glow...,"{'pricevaliduntil': '2020-09-27', 'price': '11...",{'name': 'Physicians Formula'},Makyaj > Kapatıcı Ve BB Kremler,0044386070424
2,Elose Garlic Extract Shampoo 750 ml - Sarımsak...,"{'price': '24.00', 'availability': 'https://sc...",{'name': 'Elose'},Saç Bakımı > Şampuanlar,8697400691154
3,Zigavus Baby Shampoo 300 ml - Bebek Şampuanı,"{'pricevaliduntil': '2020-10-02', 'availabilit...",{'name': 'Zigavus'},Anne Bebek,8699349138332
4,Klorane Nourishing Body Lotion Cupuaçu 200 ml,"{'pricecurrency': 'TRY', 'price': '69.90', 'av...",{'name': 'Klorane'},Vücut Bakımı > Nemlendirici ve Losyon,3282770113181

'Product_prechic.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,White Fringe Spaghetti Straps Tiered Sexy Two ...,{'itemcondition': 'https://schema.org/NewCondi...,{'name': 'PreChic'},"{'reviewcount': '97', 'ratingvalue': '4.5'}",Chic390835
1,Star And Letter Patch Decorated PU Backpack,{'itemcondition': 'https://schema.org/NewCondi...,{'name': 'PreChic'},"{'reviewcount': '43', 'ratingvalue': '4.5'}",Chic255638_Pre
2,Tweed Chain Classic Plaid Chain Crossbody Bag,{'itemcondition': 'https://schema.org/NewCondi...,{'name': 'PreChic'},"{'reviewcount': '54', 'ratingvalue': '4.9'}",Chic232772_Pre
3,Candy Color Pu Leather Plain Crossbody Bag,{'itemcondition': 'https://schema.org/NewCondi...,{'name': 'PreChic'},"{'ratingvalue': '4.6', 'reviewcount': '30'}",Chic285028_Pre
4,Flower Embroidered Heart Backless Bowknot Prin...,"{'price': '22.99', 'itemcondition': 'https://s...",{'name': 'PreChic'},"{'ratingvalue': '4.7', 'reviewcount': '154'}",Chic109856_Pre

'Product_sokios.com_September2020.json.gz'

,name,offers,brand,mpn,itemcondition
0,FUNDA DE CUADRANTE ALGODÓN PERCAL AMARILLO MOS...,"[{'price': '14.95', 'availability': 'https://s...",{'name': 'sokios'},8445352003026,https://schema.org/NewCondition
1,FUNDA DE ALMOHADA ALGODÓN PERCAL ARENA 04,"[{'pricevaliduntil': '2020-10-29', 'gtin13': '...",{'name': 'sokios'},8445352006638,https://schema.org/NewCondition
2,JUEGO SÁBANAS LUX EN BLANCO CON RIBETE AZUL,"[{'mpn': '8445352020139', 'price': '39.95', 'a...",{'name': 'sokios'},8445352020122,https://schema.org/NewCondition
3,JUEGO DE FUNDA NÓRDICA CHECK 3 PIEZAS COLECCIÓ...,[{'availability': 'https://schema.org/InStock'...,{'name': 'sokios'},8445352019690,https://schema.org/NewCondition
4,FUNDA ALMOHADA RAYA MARRÓN COLECCIÓN SCANDI,[{'availability': 'https://schema.org/InStock'...,{'name': 'sokios'},8445352025141,https://schema.org/NewCondition

'Product_allstarsdirect.co.uk_September2020.json.gz'

,name,offers,brand,mpn,itemcondition
0,Petronas Yamaha MotoGP Team Beanie Hat Black O...,{'seller': 'All Stars Direct allstarsdirect.co...,None,NaN,None
1,Marc Marquez 93 Name Large Stickers MotoGP Off...,"{'itemcondition': 'New', 'seller': 'All Stars ...",None,NaN,None
2,Honda Repsol Marc Marquez 93 MotoGP Panel Blue...,{'seller': 'All Stars Direct allstarsdirect.co...,None,NaN,None
3,Marco Simoncelli Trucker Cap 58 MotoGP White O...,"{'price': '28.99', 'seller': 'All Stars Direct...",None,NaN,None
4,Nicky Hayden 69 Key Ring Helmet USA Design Mot...,"{'price': '7.99', 'seller': 'All Stars Direct ...",None,NaN,None

'Product_treefrogtreasures.com_September2020.json.gz'

,name,offers,brand,mpn,manufacturer,weight,width,height,depth
0,Sweeney Todd,"{'pricecurrency': 'USD', 'price': '40.00', 'av...",London Gothic,VG43,{'url': 'https://www.treefrogtreasures.com/m-8...,0.39 lbs,5.2 in,5.2 in,3 in
1,Arado Russian Seaplane,{'url': 'https://www.treefrogtreasures.com/p-2...,Thomas Gunn Miniatures,WOW169,"{'name': 'Thomas Gunn Miniatures', 'url': 'htt...",10.00 lbs,16 in,16 in,8 in
2,USMC Soldier Ready to Move,"{'pricecurrency': 'USD', 'url': 'https://www.t...",King & Country,USMC037,"{'name': 'King & Country', 'url': 'https://www...",0.65 lbs,5.85 in,5.85 in,3 in
3,Royal Marine Sergeant Presenting Arms,"{'pricecurrency': 'USD', 'url': 'https://www.t...",King & Country,CE047,"{'name': 'King & Country', 'url': 'https://www...",0.39 lbs,5.85 in,3.9 in,2.7 in
4,The JagdPanzer Pz. Kpfw. IV L/70 – Winter Version,"{'pricecurrency': 'USD', 'availabilitystarts':...",King & Country,WH091,"{'name': 'King & Country', 'url': 'https://www...",3.77 lbs,16.575 in,13.325 in,6.9 in

'Product_baublesnbling.com_September2020.json.gz'

,name,offers,title
0,Dog Dad Glass Ornament,"{'pricecurrency': 'USD', 'price': '$ 10.99'}",Products
1,Two Piece Cubic Zirconia Solitaire Bridal Rings,"{'pricecurrency': 'USD', 'price': '$ 74.00'}",Products
2,Chill and Relax Ceramic Beverage Mugs,"{'pricecurrency': 'USD', 'price': '$ 17.00'}",Products
3,Crackle Pottery Mason Jars,"{'price': '$ 21.50', 'pricecurrency': 'USD'}",Products
4,Calla Lily Wedding Day Guest Book,"{'price': '$ 17.24', 'pricecurrency': 'USD'}",CLEARANCE

'Product_cosasempotrables.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Soporte Pared Guitarra 2 Pieza,"{'pricevaliduntil': '2024-11-20', 'availabilit...",{'name': 'Cosas Empotrables'},"{'reviewcount': '670', 'ratingvalue': '4.4'}",92965
1,Woxter Dynamic Line 410 BT –,"{'pricevaliduntil': '2022-11-20', 'pricecurren...",{'name': 'Cosas Empotrables'},"{'reviewcount': '650', 'ratingvalue': '4.9'}",93682
2,ATR ART TO REAL Upgrades - Chi,"{'pricevaliduntil': '2022-11-20', 'price': '99...",{'name': 'Cosas Empotrables'},"{'reviewcount': '433', 'ratingvalue': '4.5'}",93328
3,Habitdesign 0F9940A - Alacena,"{'price': '139.95', 'pricevaliduntil': '2021-1...",{'name': 'Cosas Empotrables'},"{'ratingvalue': '4.7', 'reviewcount': '608'}",93323
4,Radio de Coche 2 DIN 7&quot;Android,"{'pricevaliduntil': '2024-11-20', 'availabilit...",{'name': 'Cosas Empotrables'},"{'reviewcount': '617', 'ratingvalue': '4.7'}",93616

'Product_reliks.com_September2020.json.gz'

,name,offers,brand,aggregaterating,review
0,4-Max Scout Knife,"{'pricecurrency': 'USD', 'sku': '6772', 'price...",Cold Steel,"{'reviewcount': '2', 'ratingvalue': '5'}",None
1,Pirate Wall Hangers,"{'pricecurrency': 'USD', 'price': '17.99', 'sk...",None,"{'reviewcount': '1', 'ratingvalue': '5'}",None
2,Rapier Gloves,"{'pricecurrency': 'USD', 'price': '51.99', 'sk...",None,None,None
3,Hardwood Bokken - Black,"{'pricecurrency': 'USD', 'sku': '450', 'price'...",None,"{'reviewcount': '35', 'ratingvalue': '5'}","[{'author': 'David', 'reviewbody': 'Great valu..."
4,Practical Viking Sword,"{'pricecurrency': 'USD', 'sku': '934', 'price'...",Paul Chen - Hanwei,"{'ratingvalue': '5', 'reviewcount': '22'}","[{'author': 'Tomas', 'reviewbody': 'Hand grip ..."

'Product_ardemadrid.com_September2020.json.gz'

,name,offers,brand,mpn,gtin13
0,BLACKSTAR ARTISAN 212 BAFLE,"{'price': '701', 'itemcondition': 'http://sche...",{'name': 'Blackstar'},BLACKS10477,8.456440e+11
1,BESPECO SILOS SLJJ600,"{'price': '8.9', 'availability': 'http://schem...",{'name': 'Bespeco'},BESSLJJ600,NaN
2,BESPECO PHYTON MICROFONO PYMAC900,"{'availability': 'http://schema.org/InStock', ...",{'name': 'Bespeco'},BESPYMAC900,NaN
3,ADMIRA ALBA 3/4,"{'price': '99', 'availability': 'http://schema...",{'name': 'Admira'},ADALBA3/4,8.436032e+12
4,ADMIRA ALBA 1/2,"{'availability': 'http://schema.org/InStock', ...",{'name': 'Admira'},ADALBA1/2,8.436032e+12

'Product_stoneandtileshoppe.com_September2020.json.gz'

,name,offers,brand,category,weight
0,Rosal Limestone Tile - Honed,[{'itemcondition': 'http://schema.org/NewCondi...,"Stone & Tile Shoppe, Inc.",Tile,{'value': '6'}
1,Lagos Gold Limestone Tile - Honed,[{'itemcondition': 'http://schema.org/NewCondi...,"Stone & Tile Shoppe, Inc.",Tile,{'value': '6'}
2,"Rojo Travertine Liner - 2\"" x 12\"" F1 Chair Rail",{'itemcondition': 'http://schema.org/NewCondit...,"Stone & Tile Shoppe, Inc.",Liner,{'value': '2'}
3,Full Tile Sample - Antique Gold Limestone Tile...,"{'price': '6.93', 'itemcondition': 'http://sch...","Stone & Tile Shoppe, Inc.",Sample,{'value': '6'}
4,Ramon Bone Limestone Tile - Polished,{'itemcondition': 'http://schema.org/NewCondit...,"Stone & Tile Shoppe, Inc.",Tile,None

'Product_adv3nture.com_September2020.json.gz'

,name,offers,brand,category,gtin8
0,Slouch Beanie,"[{'sku': '23900811', 'availability': 'https://...",{'name': 'Adv3nture'},Accessories,23900811.0
1,Miami Flannel,[{'availability': 'https://schema.org/InStock'...,{'name': 'Adv3nture'},fleece,24100713.0
2,CALIFORNIA USA,"[{'pricecurrency': 'USD', 'sku': '36300643', '...",{'name': 'Adv3nture'},None,NaN
3,Boulder Flannel,"[{'sku': '24100812', 'pricecurrency': 'USD', '...",{'name': 'Adv3nture'},fleece,24100814.0
4,S&#39;MORES AND BEERS,"[{'pricecurrency': 'USD', 'availability': 'htt...",{'name': 'Adv3nture'},None,NaN

'Product_fiesta-mascotte.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review
0,Camel Mascot Costume,{'url': 'https://fiesta-mascotte.com/en/Camels...,Peluche-Publicitaire.com,"{'ratingvalue': '5', 'ratingcount': '1'}",FM11098,"{'author': 'Fiesta Mascotte', 'datepublished':..."
1,Dromedary camel Mascot Costume,"{'price': '300', 'pricecurrency': 'EUR'}",Fiesta Mascotte,{'image': 'https://cdn3.fiesta-mascotte.com/37...,FM15085,"{'author': 'Fiesta Mascotte', 'datepublished':..."
2,Dromedary camel Mascot Costume,"{'price': '300', 'pricecurrency': 'EUR'}",Fiesta Mascotte,"{'ratingvalue': '5', 'image': 'https://cdn3.fi...",FM15086,"{'author': 'Fiesta Mascotte', 'datepublished':..."
3,Dromedary camel Mascot Costume,"{'price': '300', 'pricecurrency': 'EUR'}",Fiesta Mascotte,{'image': 'https://cdn2.fiesta-mascotte.com/26...,FM13217,"{'author': 'Fiesta Mascotte', 'datepublished':..."
4,Fruits and vegetables Mascot Costume,"{'price': '300', 'pricevaliduntil': '2021-12-3...",Peluche-Publicitaire.com,"{'ratingvalue': '5', 'ratingcount': '1'}",FM11288,"{'author': 'Fiesta Mascotte', 'datepublished':..."

'Product_oznaturals.com_September2020.json.gz'

,name,offers,brand,category,gtin12
0,Ocean Mineral Essentials,"{'price': '5.2E1', 'availability': 'https://sc...",{'name': 'OZNaturals'},None,NaN
1,Bamboo Enzyme Facial Scrub,"{'pricevaliduntil': '2020-10-05', 'price': '2....",{'name': 'OZNaturals'},Exfoliants,8.164570e+11
2,Vitamin C Essentials,"{'pricevaliduntil': '2020-10-06', 'price': '5....",{'name': 'OZNaturals'},None,NaN
3,Get Up & Glow,"{'availability': 'https://schema.org/InStock',...",{'name': 'OZNaturals'},None,NaN
4,Ocean Mineral Facial Cleanser,"{'pricevaliduntil': '2020-10-05', 'sku': 'OZ-F...",{'name': 'OZNaturals'},Facial Cleansers,8.164570e+11

'Product_livestreetlife.com_September2020.json.gz'

,name,offers,category,weight,releasedate,color,width,height,depth
0,Lloyd and Pryce Nash Beech Shoe,"{'availability': 'http://schema.org/InStock', ...",Footwear > Shoes,"{'unitcode': 'KGM', 'value': '1.6'}",2020-04-10T19:34:25+00:00,Beech,"{'value': '26', 'unitcode': 'CMT'}","{'value': '6', 'unitcode': 'CMT'}","{'value': '36', 'unitcode': 'CMT'}"
1,Galand Short Sleeved Shirt Magenta,"{'price': '28.00', 'availability': 'http://sch...",Shirts > Short sleeved,"{'unitcode': 'KGM', 'value': '0.4'}",2020-02-28T15:09:37+00:00,Magenta,"{'value': '26', 'unitcode': 'CMT'}","{'value': '5', 'unitcode': 'CMT'}","{'value': '33', 'unitcode': 'CMT'}"
2,Marc Darcy 3 Piece Suit Harry Indigo 2020,"{'pricecurrency': 'GBP', 'offercount': '24', '...",WEDDING PACKAGES > Suit Collection,"{'unitcode': 'KGM', 'value': '0.9'}",2019-11-26T15:26:24+00:00,Indigo,"{'value': '26', 'unitcode': 'CMT'}","{'value': '13', 'unitcode': 'CMT'}","{'unitcode': 'CMT', 'value': '40'}"
3,Cavani Rome Tan Brogues 2020,"{'availability': 'http://schema.org/InStock', ...",Footwear,"{'value': '1.7', 'unitcode': 'KGM'}",2020-09-02T15:17:48+00:00,Tan,"{'value': '26', 'unitcode': 'CMT'}","{'value': '13', 'unitcode': 'CMT'}","{'value': '36', 'unitcode': 'CMT'}"
4,XV Kings Broulee Marine Stripe Zip Jacket 2020,"{'price': '47.99', 'availability': 'http://sch...",Casual Jackets,"{'value': '0.5', 'unitcode': 'KGM'}",2020-04-27T13:24:22+00:00,Navy,"{'value': '26', 'unitcode': 'CMT'}","{'value': '6', 'unitcode': 'CMT'}","{'value': '33', 'unitcode': 'CMT'}"

'Product_hotlistproducts.com_September2020.json.gz'

,name,offers,brand,aggregaterating,category,mpn,review
0,Reflecting Harness & Leash Set for Cats/Small ...,"{'availability': 'https://schema.org/InStock',...",hotlistproducts.com,"{'ratingvalue': '4.90', 'reviewcount': '18'}",None,438,None
1,Silicone Gel Heel and Ankle Sleeve for Plantar...,"{'availability': 'https://schema.org/InStock',...",hotlistproducts.com,"{'ratingvalue': '4.90', 'reviewcount': '28'}",None,243,None
2,Car Electric Heated Seat,[{'availability': 'https://schema.org/InStock'...,{'name': 'hotlistproducts.com'},"{'ratingvalue': '4.9E0', 'reviewcount': '36'}",Automobiles &amp; Motorcycles,512,[{'reviewbody': 'Three days delivery of the pa...
3,Takoyaki Maker,"[{'price': '32.50', 'availability': 'https://s...",{'name': 'hotlistproducts.com'},"{'ratingvalue': '5', 'reviewcount': '43'}",Home &amp; Garden,217,[{'reviewbody': 'Товар до Перми дошел за 4 дня...
4,Charcoal Teeth Whitening,"{'availability': 'https://schema.org/InStock',...",{'name': 'hotlistproducts.com'},"{'ratingvalue': '4.9E0', 'reviewcount': '15'}",Beauty &amp; Health,287,"[{'reviewbody': 'Thanks'}, {'reviewbody': 'Del..."

'Product_art50.net_September2020.json.gz'

,name,offers,brand,manufacturer,mainentityofpage
0,Ufuksuz,"{'availability': 'http://schema.org/InStock', ...",{'name': 'Fatih Dülger'},{'name': 'Fatih Dülger'},"{'inlanguage': 'tr', 'datemodified': '2020-08-..."
1,Projection,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Elif Çelebi'},{'name': 'Elif Çelebi'},"{'name': 'Projection - Art50.net', 'descriptio..."
2,Şiirin Silüeti,"{'price': '7000.00', 'availability': 'http://s...",{'name': 'Müge Ceyhan'},{'name': 'Müge Ceyhan'},"{'datemodified': '2020-08-13T08:59:16+03:00', ..."
3,Geometry of the World,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Razi Razavi'},{'name': 'Razi Razavi'},"{'inlanguage': 'en-US', 'datepublished': '2020..."
4,Machine - Venue No: 5,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Osman Törer'},{'name': 'Osman Törer'},"{'description': 'Oil painting on canvas.', 'in..."

'Product_bentongluntandtappfuneralhome.com_September2020.json.gz'

,name,offers,aggregaterating,review,itemcondition,model
0,Angel Pendant & Chain,"{'pricecurrency': 'USD', 'highprice': '119.95'...","{'reviewcount': '1', 'ratingvalue': '5.00'}",{'description': 'The pendant is beautiful and ...,NewCondition,{'url': 'https://www.bentongluntandtappfuneral...
1,Pink Tribute Spray,"{'pricecurrency': 'USD', 'lowprice': '114.95',...","{'reviewcount': '82', 'ratingvalue': '4.95'}",[{'description': 'I purchased this spray for a...,NewCondition,{'image': 'https://res.cloudinary.com/picasso/...
2,Florist Choice Bouquet,"{'pricecurrency': 'USD', 'highprice': '89.95',...","{'reviewcount': '81', 'ratingvalue': '4.93'}","[{'author': 'from Phelps - Wisconsin', 'descri...",NewCondition,[{'url': 'https://www.bentongluntandtappfunera...
3,Simply Elegant Spathiphyllum,"{'pricecurrency': 'USD', 'highprice': '107.95'...","{'reviewcount': '315', 'ratingvalue': '4.97'}","[{'author': 'from -', 'description': 'I have b...",NewCondition,[{'url': 'https://www.bentongluntandtappfunera...
4,Medium Dish Garden,"{'pricecurrency': 'USD', 'lowprice': '59.95', ...","{'ratingvalue': '4.90', 'reviewcount': '40'}","[{'author': 'from -', 'datepublished': '6/7/20...",NewCondition,{'image': 'https://res.cloudinary.com/picasso/...

'Product_thebearknows.com_September2020.json.gz'

,name,offers,price,shop-currency
0,AMAYA,"AMAYA HB Furninova AB $6,500.00 Quantity: Subt...","$6,500.00",SGD
1,Saxophone 70cm x 90cm(H),Saxophone 70cm x 90cm(H) The Bear Knows Singap...,$530.00,SGD
2,Vesta Special High,"Vesta Special High HB Furninova AB $6,900.00 Q...","$6,900.00",SGD
3,GYRO ARMCHAIR FANTASY DOVE,"GYRO ARMCHAIR FANTASY DOVE Conform $3,100.00 Q...","$3,100.00",SGD
4,Panda Potrait 120cm x 120cm (H),Panda Potrait 120cm x 120cm (H) The Bear Knows...,$715.00,SGD

'Product_thehungrypuppy.com_September2020.json.gz'

,name,offers,brand,weight,gtin12
0,Midwest Contour Crate 836 36\,"{'pricevaliduntil': '2020-12-21', 'itemconditi...",{'name': 'Midwest'},0.0lb,NaN
1,Fromm Treats 4 Star Salmon with Sweet Potato,"{'pricevaliduntil': '2020-12-21', 'itemconditi...",{'name': 'Fromm'},0.0lb,7.270512e+10
2,Orijen Regional Red Dry Dog Food,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Orijen'},0.0lb,6.499211e+10
3,NiteHowl LED Safety Necklace Green,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'NiteHowl LED'},0.0lb,9.466404e+10
4,RAWZ 96% Chicken and Chicken Liver Wet Dog Food,"[{'pricevaliduntil': '2020-12-21', 'sku': '392...",{'name': 'RAWZ'},0.0lb,NaN

'Product_shopgreatfallsgames.com_September2020.json.gz'

,name,offers,brand,itemcondition,gtin13
0,Tomee 256KB Memory Pack for N64,"{'availability': 'https://schema.org/InStock',...",Tomee,https://schema.org/NewCondition,8.130480e+11
1,Games Workshop Bestigor Flesh paint pot,"{'pricevaliduntil': '2020-12-21', 'availabilit...",Games Workshop,https://schema.org/NewCondition,5.011921e+12
2,Toysmith Bamboo Kendama,"{'availability': 'https://schema.org/InStock',...",Toysmith,https://schema.org/NewCondition,8.576119e+10
3,Ty Inc. Bamboo Sequin Pencil Bag,"{'availability': 'https://schema.org/InStock',...",Ty Inc.,https://schema.org/NewCondition,8.421959e+09
4,Tomee AC Adapter for Nintendo DS/ Game Boy Adv...,"{'price': '12.99', 'availability': 'https://sc...",Tomee,https://schema.org/NewCondition,8.130480e+11

'Product_castlebeachclubcondosforsale.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Castle Beach Club Unit 620 - 0 bedroom condo f...,"{'price': '1500', 'itemcondition': 'http://sch...",{'name': 'apartment'},"{'reviewcount': '1', 'ratingvalue': '5'}",A10902354
1,Castle Beach Club Unit 424 - 0 bedroom condo f...,"{'price': '1400', 'itemcondition': 'http://sch...",{'name': 'apartment'},"{'reviewcount': '1', 'ratingvalue': '5'}",A10912099
2,Castle Beach Club Unit 1718 - 0 bedroom condo ...,{'itemcondition': 'http://schema.org/UsedCondi...,{'name': 'apartment'},"{'reviewcount': '1', 'ratingvalue': '5'}",A10888188
3,Castle Beach Club Unit 1612 - 0 bedroom condo ...,{'itemcondition': 'http://schema.org/UsedCondi...,{'name': 'apartment'},"{'reviewcount': '1', 'ratingvalue': '5'}",A10905092
4,Castle Beach Club Unit 1230 - 0 bedroom condo ...,{'itemcondition': 'http://schema.org/UsedCondi...,{'name': 'apartment'},"{'reviewcount': '1', 'ratingvalue': '5'}",A10902406

'Product_octopusbrand.com_September2020.json.gz'

,name,offers,brand,category,model
0,OCTOPUS TEE - Sublimated Print T-Shirt GLACIER,"{'availability': 'http://schema.org/InStock', ...",Octopus,FW20,Sublimated Print T-Shirt GLACIER
1,OCTOPUS ORIGINAL PENDANT - Silver Custom Penda...,"{'price': '79.00', 'availability': 'http://sch...",Octopus,FW20,Silver Custom Pendant With 70cm Necklace SILVER
2,OCTOPUS MORE FIRE HOODIE - Screen Printed Hood...,"{'price': '99.00', 'availability': 'http://sch...",Octopus,FW20,Screen Printed Hood Sweatshirt YELLOW BLACK
3,GUMBALL VARSITY HOODIE - Screen Printed Hoodie...,"{'price': '109.00', 'pricecurrency': 'EUR', 'a...",Octopus,FW20,Screen Printed Hoodie TURQUOISE WHITE
4,OCTOPUS ACE SOCKS - Jaquard Socks BLACKCAMO,"{'availability': 'http://schema.org/InStock', ...",Octopus,FW20,Jaquard Socks BLACKCAMO

'Product_babevn.com_September2020.json.gz'

,name,offers,brand,aggregaterating,category,mpn,review
0,Multi-funtion Pet Dog Cat Bath Brush Comb Rubb...,"[{'price': '15.77', 'pricecurrency': 'USD', 'n...",babevn.com,"{'ratingcount': '4', 'ratingvalue': '5'}",Dog Grooming,27954,"[{'reviewbody': 'Excellent calculation, well c..."
1,Hair Removal Comb for Dogs Cat Detangler Fur T...,[{'url': 'https://babevn.com/hair-removal-comb...,babevn.com,"{'ratingcount': '14', 'ratingvalue': '4.9'}",Dog Grooming,27040,"[{'author': 'G***n', 'reviewbody': 'Everything..."
2,Multifunction Pet Molar Bite Dog Toys Rubber C...,[{'name': 'Multifunction Pet Molar Bite Dog To...,babevn.com,None,Dog Toys,27509,None
3,2019 New Pet Dinosaur Shape Plush Chew Molar S...,"[{'price': '16.81', 'pricecurrency': 'USD', 'n...",babevn.com,"{'ratingvalue': '4.8', 'ratingcount': '5'}",Dog Toys,28051,[{'reviewbody': 'The article did not arrive bu...
4,6pcs Automatic Pet Drinking Fountain Cat Dog W...,"[{'price': '16.43', 'name': '6pcs Automatic Pe...",babevn.com,None,Cat Feeding & Watering Supplies,28487,None

'Product_drdmotorbikes.com_September2020.json.gz'

,name,offers,brand,category,mpn
0,SPIDI WORKER H2OUT 4 MEVSİM CEKET,"{'pricevaliduntil': '2020-09-26', 'pricecurren...",{'name': 'SPIDI'},SÜRÜCÜ EKİPMANLARI > MONTLAR > SU GEÇİRMEZ MON...,SPIDI.D138.064
1,SPIDI TRONIK WIND PRO TEK PARÇA DERI TULUM,"{'price': '11620.33', 'pricecurrency': 'TRY', ...",{'name': 'SPIDI'},SÜRÜCÜ EKİPMANLARI > TULUMLAR,SPIDI.Y138.014
2,NOLAN N-COM B901R BLUETOOTH INTERCOM SİSTEMİ (...,"{'pricecurrency': 'TRY', 'price': '2655.33', '...",{'name': 'NOLAN'},SÜRÜCÜ EKİPMANLARI > BLUETOOTH ve İNTERCOM,8030635870763
3,SPIDI X-TOUR H2OUT LAMINATED TOURING CEKET,"{'pricecurrency': 'TRY', 'price': '5358.41', '...",{'name': 'SPIDI'},SÜRÜCÜ EKİPMANLARI > MONTLAR > SU GEÇİRMEZ MON...,SPIDI.D161.026
4,SHOEI GT-AIR TEPE PED,"{'price': '533.00', 'pricecurrency': 'TRY', 'a...",{'name': 'SHOEI'},SÜRÜCÜ EKİPMANLARI > KASKLAR > KASK YEDEK PARÇ...,T2581

'Product_rabat.net_September2020.json.gz'

,name,offers,brand,category,isrelatedto
0,Love charm bracelet in silver,"{'price': '60€', 'pricecurrency': 'EUR'}",Amuletto,"[Amuletto Collection, Back to selection |]",None
1,Hublot Classic Fusion Automatic Zirconium 42,"{'price': '10250', 'pricecurrency': 'EUR'}",None,"[Hublot Classic Fusion, Back to selection |]",[{'name': 'Hublot Classic Fusion Ceramic Blue ...
2,IWC Portugieser Chronograph IW371445,"{'price': '7950', 'pricecurrency': 'EUR'}",None,"[IWC Schaffhausen Portugieser, Back to selecti...",[{'name': 'IWC Schaffhausen Portugieser Chrono...
3,Elastic golden beads bracelet,"[{'price': '1780', 'pricecurrency': 'EUR'}, {'...",RABAT Jewels,"[Bracelets, Back to selection |]",None
4,Riviere Bracelet with Black Diamonds,"{'price': '2550', 'pricecurrency': 'EUR'}",RABAT Jewels,"[Bracelets, Back to selection |]","[{'name': 'Tubogas Bangle with Diamonds'}, {'n..."

'Product_evosensors.com_September2020.json.gz'

,name,offers,brand,mpn,itemcondition
0,Infrared Camera for the Metals Industry,"{'availability': 'https://schema.org/InStock',...",{'name': 'evosensors'},IRC-PI-05M,https://schema.org/NewCondition
1,Thermocouple Extension Cable Type K PFA Insula...,"{'availability': 'https://schema.org/InStock',...",{'name': 'Evosensors'},K1X-CAPF-24S-FPMF-10FT-MPCX,https://schema.org/NewCondition
2,Thermocouple Connector Accessories Miniature G...,"{'availability': 'https://schema.org/InStock',...",{'name': 'Evosensors'},FIT-GROM-CON-FP-.118-MPCX,https://schema.org/NewCondition
3,Surface Thermocouple Type J with Surface Mount...,"{'pricevaliduntil': '2020-12-18', 'availabilit...",{'name': 'Evosensors'},J1X-TAPE-REC-FW-1-PFXX-80-STWL,https://schema.org/NewCondition
4,"Type J Thermocouple Probe Ungrounded 1/8\"" Inc...","{'price': '42.0', 'availability': 'https://sch...",{'name': 'Evosensors'},J1X-S304-125-UX-6-PFSB-40-STWL,https://schema.org/NewCondition

'Product_paddlegang.com_September2020.json.gz'

,name,offers,brand,category,mpn,itemcondition
0,Gorra Paddle GanG,"{'price': '12.00', 'itemcondition': 'http://sc...",{'name': 'PADDLE GANG'},Ropa y complementos,NaN,http://schema.org/NewCondition
1,"QUILLA US RAY, FALCON AIR","{'price': '69.00', 'availability': 'http://sch...",{'name': 'FANATIC'},Quillas de paddle surf,289.0,http://schema.org/NewCondition
2,FUSELAJE AERO FOIL,"{'price': '299.00', 'availability': 'http://sc...",{'name': 'FANATIC'},Foil accesorios,181.0,http://schema.org/NewCondition
3,ALA trasera FOIL FANATIC,"{'price': '229.00', 'availability': 'http://sc...",{'name': 'FANATIC'},Wing foil/Foil,184.0,http://schema.org/NewCondition
4,Hinchador TRIPLE acción FANATIC,"{'price': '99.00', 'availability': 'http://sch...",{'name': 'FANATIC'},Accesorios tabla hinchable,292.0,http://schema.org/NewCondition

'Product_wildercdjr.com_September2020.json.gz'

,name,offers,brand,mpn,model,manufacturer,releasedate,color
0,2017 Audi Q7 4d SUV 3.0T Premium+,"{'serialnumber': 'WA1LAAF71HD015853', 'itemcon...",Audi,WA1LAAF71HD015853,Q7,Audi,2017,BLACK
1,2016 Volkswagen Tiguan 4d SUV S,"{'serialnumber': 'WVGAV7AX2GW614254', 'itemcon...",Volkswagen,WVGAV7AX2GW614254,Tiguan,Volkswagen,2016,WHITE
2,2014 Volkswagen Passat TDI 4d Sedan SE w/Sunroof,"{'price': '14959', 'serialnumber': '1VWBN7A35E...",Volkswagen,1VWBN7A35EC018766,Passat TDI,Volkswagen,2014,SILVER
3,2012 Toyota Prius Four,"{'serialnumber': 'JTDKN3DU0C1494237', 'price':...",Toyota,JTDKN3DU0C1494237,Prius,Toyota,2012,WINTER GRAY METALLIC
4,2017 Jeep Compass 4d SUV 4WD Trailhawk,{'name': '2017 Jeep Compass 4d SUV 4WD Trailha...,Jeep,3C4NJDDB8HT681867,Compass,Jeep,2017,ORANGE

'Product_xtremevwparts.com_September2020.json.gz'

,name,offers,brand,mpn,manufacturer
0,Oil Filter,"{'pricecurrency': 'USD', 'itemcondition': 'htt...",{'name': 'Volkswagen'},079198405a,{'name': 'Volkswagen'}
1,Oil Filter,"{'pricecurrency': 'USD', 'itemcondition': 'htt...",{'name': 'Volkswagen'},059198405,{'name': 'Volkswagen'}
2,Oil Filter,"{'pricecurrency': 'USD', 'price': '5.1471E0', ...",{'name': 'Subaru'},15208aa12a,{'name': 'Subaru'}
3,Drive Shaft,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Subaru'},27111aj10e,{'name': 'Subaru'}
4,Oil Filter,"{'pricecurrency': 'USD', 'price': '9.144E0', '...",{'name': 'Volkswagen'},06j115403q,{'name': 'Volkswagen'}

'Product_concordefrench.com_September2020.json.gz'

,name,category,identifier,offerdetails
0,Rendez-vous Magazine Mai/Juin 2018,Back Issues,sku:RendezBIMJ18,"{'price': '£5.00', 'pricecurrency': 'GBP', 'av..."
1,Tuez Le Dragon 3,PDFs,sku:Tuez Le Dragon 3,"{'price': '£3.00', 'pricecurrency': 'GBP', 'av..."
2,Jacques Damour,Parallel Text,sku:Jacquesdamour,"{'price': '£8.99', 'pricecurrency': 'GBP', 'av..."
3,La Vie Outre-Manche Avril/Mai 2017,Back Issues,sku:LaVieBIAM17,"{'price': '£6.00', 'pricecurrency': 'GBP', 'av..."
4,La Vie Outre-Manche Février/Mars 2017,Back Issues,sku:LaVieBIFM17,"{'price': '£6.00', 'pricecurrency': 'GBP', 'av..."

'Product_softballbats-sale.com_September2020.json.gz'

,name,offers,brand,aggregaterating,review
0,Boombah Superpack Bat Pack -Backpack Version (...,"{'availability': 'http://schema.org/InStock', ...",BRAND,"{'ratingvalue': '5', 'reviewcount': '10'}","{'datepublished': '2020-01-04', 'name': 'Revie..."
1,EASTON Amethyst -11 Fastpitch Softball Bat | 2...,"{'availability': 'http://schema.org/InStock', ...",BRAND,"{'ratingvalue': '5', 'reviewcount': '10'}","{'datepublished': '2020-01-04', 'name': 'Revie..."
2,Modvel 2 Pack Knee Compression Sleeve | Knee B...,"{'price': '13.95', 'availability': 'http://sch...",BRAND,"{'ratingvalue': '5', 'reviewcount': '10'}","{'datepublished': '2020-01-04', 'name': 'Revie..."
3,"EASTON HAMMER Slowpitch Softball Bat, 12 in Ba...","{'price': '37.46', 'availability': 'http://sch...",BRAND,"{'ratingvalue': '5', 'reviewcount': '10'}","{'datepublished': '2020-01-04', 'name': 'Revie..."
4,EASTON GHOST -11 Girl's Youth Fastpitch Softba...,"{'availability': 'http://schema.org/InStock', ...",BRAND,"{'ratingvalue': '5', 'reviewcount': '10'}","{'datepublished': '2020-01-04', 'name': 'Revie..."

'Product_jacksturner.com_September2020.json.gz'

,name,offers,brand,manufacturer,mainentityofpage
0,Tahitian pearl drop diamond necklace,"{'price': '355.00', 'pricecurrency': 'GBP', 'a...",{'name': 'Necklaces'},{'name': 'Necklaces'},"{'datepublished': '2018-12-12T10:43:42+00:00',..."
1,Diamond trilogy ring,"{'lowprice': '1830.00', 'offercount': '2', 'pr...",{'name': 'Engagement Rings'},{'name': 'Engagement Rings'},"{'inlanguage': 'en-GB', 'name': 'Diamond trilo..."
2,Blue Sapphire & Diamond platinum ring,"{'price': '1350.00', 'availability': 'http://s...",{'name': 'Rings'},{'name': 'Rings'},{'name': 'Blue Sapphire & Diamond platinum rin...
3,Oval green sapphire platinum ring,"{'price': '1300.00', 'availability': 'http://s...",{'name': 'Rings'},{'name': 'Rings'},"{'datemodified': '2020-09-01T14:26:44+00:00', ..."
4,Ellipse gold plated studs,"{'pricecurrency': 'GBP', 'availability': 'http...",{'name': 'Earrings'},{'name': 'Earrings'},"{'datemodified': '2020-09-13T12:00:01+00:00', ..."

'Product_beautyencounter.com_September2020.json.gz'

,name,offers,brand,gtin12,reviewcount
0,Obsessed by Calvin Klein for Men 4.0 oz Eau de...,"{'pricecurrency': 'USD', 'price': '35.95', 'av...",{'name': 'Calvin Klein'},3614225473258,0.0
1,Burberry Body by Burberry for Women 2.0 oz Eau...,"{'pricecurrency': 'USD', 'price': '45.99', 'av...",None,3386460035637,0.0
2,Insolence by Guerlain for Women 3.3 oz Eau de ...,"{'pricecurrency': 'USD', 'price': '50.90', 'av...",{'name': 'Guerlain'},3346470132917,0.0
3,Eau Des Merveilles by Hermes for Women 6.5 oz ...,"{'pricecurrency': 'USD', 'price': '55.95', 'av...",{'name': 'Hermes'},3346131794393,0.0
4,Clinique Even Better Makeup SPF 15 Evens and C...,"{'pricecurrency': 'USD', 'price': '35.95', 'av...",{'name': 'Clinique'},020714977085,0.0

'Product_stikets.co.uk_September2020.json.gz'

,name,offers,brand,aggregaterating,itemcondition
0,Custom stamps for teachers,"{'availability': 'http://schema.org/InStock', ...",Stikets,"{'reviewcount': '1', 'ratingvalue': '5.0000'}",http://schema.org/NewCondition
1,Decorative Wall Stickers,"{'availability': 'http://schema.org/InStock', ...",Stikets,"{'reviewcount': '2', 'ratingvalue': '5.0000'}",http://schema.org/NewCondition
2,Gift Labels,"{'price': '3.95', 'availability': 'http://sche...",Stikets,"{'reviewcount': '2', 'ratingvalue': '5.0000'}",http://schema.org/NewCondition
3,Nose piece for Stikets masks size 3-5 years,"{'price': '1.50', 'availability': 'http://sche...",Stikets,None,http://schema.org/NewCondition
4,Masks,"{'price': '1.50', 'availability': 'http://sche...",Stikets,None,http://schema.org/NewCondition

'Product_buymedstoday.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review
0,Propofol (Diprivan),"{'lowprice': '390.00', 'pricecurrency': 'USD',...",buymedstoday.com,"{'reviewcount': '100', 'ratingvalue': '5'}",N/A,{'author': 'user'}
1,"3,4-Dimethylmethcathinone","{'offercount': '3', 'lowprice': '300.00', 'pri...",buymedstoday.com,"{'reviewcount': '100', 'ratingvalue': '5'}",N/A,{'author': 'user'}
2,Naproxen,"{'highprice': '877.00', 'lowprice': '388.00', ...",buymedstoday.com,"{'reviewcount': '100', 'ratingvalue': '5'}",N/A,{'author': 'user'}
3,Somatropin,"{'offercount': '6', 'pricecurrency': 'USD', 'l...",buymedstoday.com,"{'reviewcount': '100', 'ratingvalue': '5'}",N/A,{'author': 'user'}
4,Lorazepam,"{'offercount': '3', 'highprice': '530.00', 'pr...",buymedstoday.com,"{'reviewcount': '100', 'ratingvalue': '5'}",N/A,{'author': 'user'}

'Product_w-wohnen.com_September2020.json.gz'

,name,offers,category,model,manufacturer,weight,identifier,width,height,depth
0,BLANCO FLEXON II Abfalltrennsystem XL 60/3,"{'itemcondition': 'Neu &amp; OVP', 'price': '1...",item.,{'isvariantof': '5986'},{'name': 'Blanco'},{'value': '7000'},3727,{'value': '0'},{'value': '0'},{'value': '0'}
1,BLANCO AVONA-S Armatur Silgranit Hochdruck,"{'itemcondition': 'Neu &amp; OVP', 'serialnumb...",item.,"{'isvariantof': '5518', 'model': 'BLANCO AVONA...",{'name': 'Blanco'},{'value': '0'},7376,{'value': '0'},{'value': '0'},{'value': '0'}
2,BLANCO ANDANO 500-IF Spüle Edelstahl Seidengla...,"{'itemcondition': 'Neu &amp; OVP', 'price': '2...",item.,"{'isvariantof': '5956', 'model': 'BLANCO ANDAN...",{'name': 'Blanco'},{'value': '7000'},3697,{'value': '0'},{'value': '0'},{'value': '0'}
3,Schneidbrett Buche massiv,"{'price': '61.53', 'itemcondition': 'Neu &amp;...",item.,{'model': 'Schneidbrett aus massiver Buche Buc...,{'name': 'Blanco'},{'value': '0'},3540,{'value': '0'},{'value': '0'},{'value': '0'}
4,BLANCO ANDANO XL 6 S-IF Compact Spüle Edelstah...,"{'serialnumber': '523002', 'itemcondition': 'N...",item.,"{'isvariantof': '5905', 'model': 'BLANCO ANDAN...",{'name': 'Blanco'},{'value': '0'},3646,{'value': '0'},{'value': '0'},{'value': '0'}

'Product_cluckeyo.com_September2020.json.gz'

,name,offers,aggregaterating,model,manufacturer
0,Silicone 4 cup Measure,"{'price': '10.50€', 'pricecurrency': 'EUR'}","{'ratingvalue': '5.0000', 'ratingcount': '1'}",3016,{'name': 'Norpro'}
1,Kitchen Towels,"{'price': '18.75€', 'pricecurrency': 'EUR'}",None,None,{'name': 'Handmade by Cluckeyo'}
2,Paring Knife,"{'pricecurrency': 'USD', 'price': '$12.25'}","{'ratingvalue': '5.0000', 'ratingcount': '1'}",1212,{'name': 'Norpro'}
3,Ice Shaver,"{'price': '18.75€', 'pricecurrency': 'EUR'}","{'ratingvalue': '5.0000', 'ratingcount': '1'}",425,{'name': 'Norpro'}
4,Super Laundry Paste w/ Lavender Softner,"{'price': '$8.00', 'pricecurrency': 'USD'}",None,None,{'name': 'Cluckeyo's Kitchen'}

'Product_interiorshowplace.com_September2020.json.gz'

,name,brand,category,manufacturer,releasedate
0,Mitchell Gold + Bob Williams,None,None,None,None
1,CG_1 Tables,{'name': 'Steelcase'},"[Desks + Tables, Occasional Tables]",{'name': 'Steelcase'},2015-10-26T18:46:18+00:00
2,CH108 Glass Coffee Table,{'name': 'Steelcase'},"[Desks + Tables, Occasional Tables]",{'name': 'Steelcase'},2015-10-26T19:57:22+00:00
3,Air3,{'name': 'Steelcase'},Walls + Work Walls,{'name': 'Steelcase'},2019-06-25T15:52:18+00:00
4,Track B,{'name': 'Steelcase'},Guest Chairs + Stools,{'name': 'Steelcase'},2019-06-25T15:47:39+00:00

'Product_cainbmw.com_September2020.json.gz'

,name,offers,brand,mpn,model,manufacturer,color
0,New 2021 BMW X3 xDrive30i With Navigation &amp...,{'itemcondition': 'http://schema.org/NewCondit...,BMW,21XD,X3,{'name': 'BMW'},Black Sapphire Metallic
1,Certified Pre-Owned 2018 BMW 3 Series 320i xDr...,"{'price': '30877', 'itemcondition': 'http://sc...",BMW,18TM,3 Series,{'name': 'BMW'},Mineral White Metallic
2,New 2020 BMW X2 xDrive28i With Navigation &amp...,{'itemcondition': 'http://schema.org/NewCondit...,BMW,20XY,X2,{'name': 'BMW'},Blue Metallic
3,Pre-Owned 2019 BMW 5 Series 530i xDrive With N...,{'itemcondition': 'http://schema.org/UsedCondi...,BMW,195B,5 Series,{'name': 'BMW'},Bluestone Metallic
4,New 2021 BMW X3 xDrive30i With Navigation &amp...,"{'price': '56995', 'itemcondition': 'http://sc...",BMW,21XD,X3,{'name': 'BMW'},Glacier Silver Metallic

'Product_rivieramayahaciendas.com_September2020.json.gz'

,name,aggregaterating,address,geo
0,"Zen, 1BR","{'reviewcount': '2', 'ratingvalue': '4'}","{'addresslocality': 'Puerto Aventuras, Quintan...","{'latitude': '20.49846', 'longitude': '-87.222..."
1,Hacienda Magica 5-14 Suites,"{'reviewcount': '48', 'ratingvalue': '5'}","{'addresslocality': 'Puerto Aventuras, Quintan...","{'longitude': '-87.23122', 'latitude': '20.497..."
2,"Gran Peninsula, 3BR",None,"{'addresslocality': 'Puerto Aventuras, Quintan...","{'longitude': '-87.23547', 'latitude': '20.4977'}"
3,Hacienda Corazon 7-10 Suites,"{'ratingvalue': '5', 'reviewcount': '52'}","{'addresslocality': 'Puerto Aventuras, Quintan...","{'latitude': '20.49795', 'longitude': '-87.231..."
4,"Casa Familia, 3BR","{'reviewcount': '12', 'ratingvalue': '4.9'}","{'addresslocality': 'Puerto Aventuras, Quintan...","{'longitude': '-87.22833', 'latitude': '20.499..."

'Product_plumbworld.co.uk_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review,itemcondition,gtin13
0,Aurora White Gloss MDF Side & End Bath Panel P...,"{'price': '84.97', 'pricevaliduntil': '2020-10...",Aurora,"{'ratingvalue': '5.0', 'reviewcount': '2', 'ra...",None,[{'reviewbody': 'Provides a modern look in our...,NewCondition,5.056094e+12
1,Bordeaux Cloakroom Suite,"{'pricecurrency': 'GBP', 'availability': 'http...",Affine,"{'ratingvalue': '5.0', 'ratingcount': '4', 're...",N/A,"[{'author': 'Christine', 'datepublished': '201...",NewCondition,5.056094e+12
2,Mira Ascend 1000 x 800mm Offset Quadrant Showe...,"{'pricecurrency': 'GBP', 'availability': 'http...",Mira Showers,"{'ratingvalue': '5.0', 'ratingcount': '1', 're...",N/A,"{'reviewbody': 'Quality good ,service was quic...",NewCondition,0.000000e+00
3,Hunter Herald Select 6 Black Log Effect Natura...,"{'availability': 'https://schema.org/InStock',...",Hunter Herald,None,GTBST6NR2,None,NewCondition,5.056094e+12
4,"Heritage Henley Gloss 900mm, 1800mm & 900mm Si...","{'pricecurrency': 'GBP', 'availability': 'http...",Multipanel,None,N/A,None,NewCondition,5.056094e+12

'Product_senatshop.com.ua_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,gtin13
0,&#1058;&#1102;&#1083;&#1100; &quot;&#1055;&#10...,"{'sku': 'MI13-2233', 'pricecurrency': 'UAH', '...",SenatShop,"{'bestrating': '5', 'ratingvalue': '4.8', 'wor...",none,2000000007199
1,&#1058;&#1102;&#1083;&#1100;&quot;&#1052;&#108...,"{'sku': 'MI13-2233', 'pricecurrency': 'UAH', '...",SenatShop,"{'bestrating': '5', 'ratingvalue': '4.8', 'wor...",none,2000000007199
2,&#1047;&#1072;&#1085;&#1072;&#1074;&#1077;&#10...,"{'sku': 'MI13-2233', 'price': '429', 'pricecur...",SenatShop,"{'bestrating': '5', 'ratingvalue': '4.8', 'wor...",none,2000000007199
3,&#1058;&#1102;&#1083;&#1100; &quot;&#1054;&#10...,"{'sku': 'MI13-2233', 'pricecurrency': 'UAH', '...",SenatShop,"{'bestrating': '5', 'ratingvalue': '4.8', 'wor...",none,2000000007199
4,&#1058;&#1102;&#1083;&#1100; &quot;&#1055;&#10...,"{'sku': 'MI13-2233', 'pricecurrency': 'UAH', '...",SenatShop,"{'bestrating': '5', 'ratingvalue': '4.8', 'wor...",none,2000000007199

'Product_golfersauthority.com_September2020.json.gz'

,name,offers,brand,aggregaterating,review
0,Callaway Solaire Golf Clubs Set Review,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Callaway'},"{'reviewcount': '1', 'ratingvalue': '4.5E0'}",{'name': 'Callaway Solaire Golf Clubs'}
1,MNML Golf Bag Review,"{'pricecurrency': 'USD', 'price': '229.00', 'a...",{'name': 'MNML'},"{'reviewcount': '1', 'ratingvalue': '5'}",{'name': 'MNML Golf Bag Review'}
2,Best Driver Shafts for 2020,None,None,"{'bestrating': '5', 'worstrating': '0', 'ratin...",None
3,L.A.B. B.2 Blade Putter Review,"{'pricecurrency': 'USD', 'availability': 'http...",None,"{'reviewcount': '1', 'ratingvalue': '4.5E0'}",{'name': 'LAB B.2 Putter Review'}
4,Live View Pro Review,"{'price': '349.00', 'availability': 'http://sc...",{'name': 'Live View Pro'},"{'reviewcount': '1', 'ratingvalue': '4.6E0'}",{'name': 'Live View Pro'}

'Product_fotoflits.com_September2020.json.gz'

,name,brand,mpn,itemcondition,price,pricecurrency
0,Avenger Avenger Conka Bonka Extension C590,Avenger,AVC590,http://schema.org/NewCondition,227.88,EUR
1,Avenger Avenger Adapter 16MM Socket E255,Avenger,AVE255,http://schema.org/NewCondition,18.38,EUR
2,"Avenger Avenger 50 MM 2\"" Polyholder F1521",Avenger,AVF1521,http://schema.org/NewCondition,133.40,EUR
3,Avenger Avenger C-Stand Base A2009CB,Avenger,AVA2009CB,http://schema.org/NewCondition,121.08,EUR
4,Cameleon Shutter Release Cable adapter voor Ni...,None,TR-RTC-NA,http://schema.org/NewCondition,9.08,EUR

'Product_parafarmacianatural.com_September2020.json.gz'

,name,offers,brand,category,gtin13
0,Manzanilla Amarga Bio - 40 g,"{'pricevaliduntil': '2020-10-06', 'name': 'Def...",{'name': 'SORIA NATURAL'},Alimentación y Dieta,8.422947e+12
1,Composor 19 Depulan Complex (Fórmula XXI) - 50 ml,"{'availability': 'https://schema.org/InStock',...",{'name': 'SORIA NATURAL'},Alimentación y Dieta,8.422947e+12
2,Focus for Children Sabor Uva - 60 Comprimidos ...,"{'availability': 'https://schema.org/InStock',...",{'name': 'SOLARAY'},Suplementación,NaN
3,Té Verde 500mg - 45 Cápsulas,"{'price': '7.2E0', 'availability': 'https://sc...",{'name': 'DIETMED'},Suplementos,5.605481e+12
4,Tomillo - 50 g,"{'availability': 'https://schema.org/InStock',...",{'name': 'SORIA NATURAL'},Suplementación,8.422947e+12

'Product_carheroesusa.com_September2020.json.gz'

,name,offers,brand,model,manufacturer,releasedate,color
0,2019 Ford F-150 XLT,None,Ford,F-150,Ford,2019,Ingot Silver Metallic
1,2019 Ford F-150 XLT,None,Ford,F-150,Ford,2019,Ingot Silver Metallic
2,2019 Ford Super Duty F-250 SRW XLT,None,Ford,Super Duty F-250 SRW,Ford,2019,Agate Black Metallic
3,2019 Ford F-150 XLT,None,Ford,F-150,Ford,2019,Agate Black Metallic
4,2019 Ford F-150 Limited,"{'name': '2019 Ford F-150 Limited', 'serialnum...",Ford,F-150,Ford,2019,Ingot Silver Metallic

'Product_ropesdirect.co.uk_September2020.json.gz'

,name,offers,brand,category,gtin13,weight
0,3mm Rope Grip,{'itemcondition': 'http://schema.org/NewCondit...,Ropes Direct,Rope & Chain Fittings>Rope Grips,5032894210246,"{'unitcode': 'Kg', 'value': '0.01'}"
1,8mm Stainless Steel Quick Link,{'itemcondition': 'http://schema.org/NewCondit...,Ropes Direct,Rope & Chain Fittings>Stainless Steel Fittings,5032894210413,"{'unitcode': 'Kg', 'value': '0.08'}"
2,10mm Stainless Steel Rope Thimble AISI316,{'itemcondition': 'http://schema.org/NewCondit...,Ropes Direct,Rope & Chain Fittings>Stainless Steel Fittings,5032894212530,"{'unitcode': 'Kg', 'value': '0.06'}"
3,3/150 Sisal Twine 2.5kg ball,{'itemcondition': 'http://schema.org/NewCondit...,Ropes Direct,Twines and Strings,5032894090138,"{'unitcode': 'Kg', 'value': '2.5'}"
4,Soft Eye Splice For 28mm to 32mm Rope,{'itemcondition': 'http://schema.org/NewCondit...,Ropes Direct,Rope End Finishes>Soft Eye Splice,5032894250242,"{'unitcode': 'Kg', 'value': '0.01'}"

'Product_renoautowarehouse.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,2017 Dodge Grand Caravan SE Wagon,"{'availability': 'https://schema.org/InStock',...",{'name': 'Dodge'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",2C4RDGBG9HR713818
1,2013 Audi A4 4dr Sdn Auto quattro 2.0T Premium...,"{'availability': 'https://schema.org/InStock',...",{'name': 'Audi'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",WAUFFAFL3DN043382
2,2004 Ford Thunderbird 2dr Convertible Deluxe,"{'availability': 'https://schema.org/InStock',...",{'name': 'Ford'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",1FAHP60A74Y106923
3,2006 BMW Z4 Z4 2dr Roadster 3.0si,"{'price': '12750', 'availability': 'https://sc...",{'name': 'BMW'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",4USBU53566LX00995
4,2011 Ford F-150 4WD SuperCrew 145 XLT,"{'availability': 'https://schema.org/InStock',...",{'name': 'Ford'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",1FTFW1ET6BKE22461

'Product_direct-drones.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,SUNHAO Drone 2 Pro/Mavic 2 Zoom/Fly More Combo...,"{'pricevaliduntil': '2020-09-22 14:50:54', 'pr...",{'name': 'SUNHAO'},"{'reviewcount': '89', 'ratingvalue': '5'}",9172
1,Professional Carry Case from MC-Cases fits for...,"{'price': '125.00', 'availability': 'https://s...",{'name': 'MC-CASES'},"{'reviewcount': '89', 'ratingvalue': '5'}",7379
2,Hubsan X4 H107C 2.4G 4CH RC Quadcopter With 0....,"{'price': '46.78', 'availability': 'https://sc...",{'name': 'HUBSAN'},"{'reviewcount': '89', 'ratingvalue': '5'}",7376
3,PAW PATROL 6026594 Chase's Spy Cruiser Vehicle...,"{'price': '29.99', 'availability': 'https://sc...",{'name': 'Spin Master Toys Ltd'},"{'reviewcount': '89', 'ratingvalue': '5'}",8169
4,DJI - Mavic Pro Platinum - Quadcopter Drone wi...,"{'price': '715.00', 'availability': 'https://s...",{'name': 'DJI'},"{'reviewcount': '89', 'ratingvalue': '5'}",7536

'Product_flowers4almaty.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,model,manufacturer
0,Mixed Seasonal kukat,"{'price': '89.00', 'pricecurrency': 'USD', 'ur...",{'name': 'Paradise Promotions LTD.'},"{'reviewcount': '911', 'ratingvalue': '4.5'}",BQM156,Mixed Seasonal kukat,{'name': 'Paradise Promotions LTD.'}
1,13 Karanteri,"{'pricecurrency': 'USD', 'price': '99.00', 'ur...",{'name': 'Paradise Promotions LTD.'},"{'reviewcount': '911', 'ratingvalue': '4.5'}",BQW115,13 Karanteri,{'name': 'Paradise Promotions LTD.'}
2,16 Ferrero Rocher čokolade,"{'price': '23.00', 'url': 'hr/ferrero-rocher-c...",{'name': 'Paradise Promotions LTD.'},"{'reviewcount': '911', 'ratingvalue': '4.5'}",CHOC100,16 Ferrero Rocher čokolade,{'name': 'Paradise Promotions LTD.'}
3,Nyt Ilmapallo,"{'pricevaliduntil': '25-10-2020', 'pricecurren...",{'name': 'Paradise Promotions LTD.'},"{'reviewcount': '911', 'ratingvalue': '4.5'}",BAL104,Nyt Ilmapallo,{'name': 'Paradise Promotions LTD.'}
4,6 crvenih ruža i 3 Ljiljana,"{'pricevaliduntil': '30-10-2020', 'price': '11...",{'name': 'Paradise Promotions LTD.'},"{'reviewcount': '911', 'ratingvalue': '4.5'}",BQ111,6 crvenih ruža i 3 Ljiljana,{'name': 'Paradise Promotions LTD.'}

'Product_minhanhshops.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review
0,Nạ môi collagen,"{'availability': 'instock', 'pricecurrency': '...",{'name': 'Minh Anh Shop'},"{'reviewcount': '1', 'ratingvalue': '5'}",2218,"{'author': 'admin', 'datepublished': '2018-08-..."
1,son Tint Coco Color,"{'availability': 'instock', 'price': '40000.00...",{'name': 'Minh Anh Shop'},"{'reviewcount': '1', 'ratingvalue': '5'}",2933,"{'datepublished': '2018-09-29T16:18:06+07:00',..."
2,Gấu bông Bobby,"{'availability': 'instock', 'pricevaliduntil':...",{'name': 'Minh Anh Shop'},"{'reviewcount': '1', 'ratingvalue': '5'}",3657,"{'datepublished': '2018-11-19T17:12:04+07:00',..."
3,Son thỏi Crystal Lipstick,"{'availability': 'instock', 'pricevaliduntil':...",{'name': 'Minh Anh Shop'},"{'reviewcount': '1', 'ratingvalue': '5'}",2787,"{'datepublished': '2018-09-24T16:39:10+07:00',..."
4,Son thạch Skin Food - Hàn Quốc,"{'availability': 'instock', 'pricecurrency': '...",{'name': 'Minh Anh Shop'},"{'reviewcount': '1', 'ratingvalue': '5'}",2219,{'description': 'Son thạch Skin Food - Hàn Quố...

'Product_socksaddict.com_September2020.json.gz'

,name,offers,brand,category,gtin12
0,Smartwool PhD® Ski Ultra Light 25th Anniversar...,"{'offercount': '3', 'itemcondition': 'http://s...",Smartwool,Sold Out,1.923636e+11
1,Darn Tough Men's Hiker Micro Crew Cushion,"{'lowprice': '13.77', 'name': 'Darn Tough Men'...",Darn Tough,Clearance,6.422491e+11
2,Darn Tough Men's Juice No Show Tab Light,"{'highprice': '7.98', 'itemcondition': 'http:/...",Darn Tough,Socks,6.422492e+11
3,Darn Tough Men's Juice No Show Tab Light Cushion,{'itemcondition': 'http://schema.org/NewCondit...,Darn Tough,Socks,6.422492e+11
4,Smartwool Women's PhD® Cycle Ultra Light Print...,"{'sku': 'SW001264-513-L', 'itemcondition': 'ht...",Smartwool,Socks,1.941122e+11

'Product_a-zdarts.com_September2020.json.gz'

,name,offers,brand,category,mpn
0,Target Storm Steel Points - Surge Short Arctic...,{'itemcondition': 'http://schema.org/NewCondit...,A-Z Darts,Steel Points,15-108394
1,Target Firestorm Steel Points - Silver Diamond...,"{'price': '6.8', 'itemcondition': 'http://sche...",A-Z Darts,Steel Points,15-108422
2,Target Storm Steel Points - Surge Standard Bla...,{'itemcondition': 'http://schema.org/NewCondit...,A-Z Darts,Steel Points,15-108399
3,Harrows Retina Dart Flights - Slim Black & Red,"{'price': '1.59', 'itemcondition': 'http://sch...",A-Z Darts,Foldable Dart Flights,10-8313
4,Harrows Supergrip Polycarbonate Dart Shafts Wi...,{'itemcondition': 'http://schema.org/NewCondit...,A-Z Darts,Nylon / Poly,10-32982

'Product_gantri.com_September2020.json.gz'

,name,offers,brand,aggregaterating,review
0,Word Table Light in Snow,"{'pricecurrency': 'USD', 'itemcondition': 'htt...",{'name': 'Gantri'},"{'reviewcount': '4', 'ratingvalue': '5'}",[{'reviewbody': 'I love my new lamp. Planning ...
1,Arco Table Light in Sand,"{'pricecurrency': 'USD', 'price': '188', 'avai...",{'name': 'Gantri'},"{'reviewcount': '2', 'ratingvalue': '5'}",{'reviewbody': 'Knowing that my money supports...
2,Vollmond Table Light in Carbon,"{'pricecurrency': 'USD', 'price': '148', 'avai...",{'name': 'Gantri'},None,None
3,Dulce Table Light in Sand,"{'pricecurrency': 'USD', 'price': '168', 'avai...",{'name': 'Gantri'},"{'ratingvalue': '5', 'reviewcount': '18'}","[{'reviewbody': 'Great design, unique accent p..."
4,Iceberg Table Light in Snow,"{'pricecurrency': 'USD', 'price': '168', 'avai...",{'name': 'Gantri'},"{'ratingvalue': '4.888888888888889', 'reviewco...","[{'name': 'Unique lamps that provide the', 're..."

'Product_oakparquetflooring.co.uk_September2020.json.gz'

,name,offers,brand,mpn,additionalproperty
0,"Junckers Beech Solid 2-Strip Wood Flooring, Un...","{'pricecurrency': 'GBP', 'price': '49.08'}",Junckers,JUNBSUV14,"[{'value': 'Unfinished', 'name': 'Sealant Fini..."
1,"Tradition Solid Natural Oak Flooring, Rustic, ...","{'pricecurrency': 'GBP', 'price': '41.94'}",Tradition Flooring,20143DOS,"{'value': 'Solid Flooring', 'name': 'Product R..."
2,Junckers Beech SylvaKet Solid 2-Strip Wood Flo...,"{'price': '51.36', 'pricecurrency': 'GBP'}",Junckers,JUNBSKSV14,"[{'value': 'Lacquered', 'name': 'Sealant Finis..."
3,Junckers Beech SylvaKet Solid 2-Strip Wood Flo...,"{'price': '51.36', 'pricecurrency': 'GBP'}",Junckers,JUNBSKV14,"[{'value': 'Lacquered', 'name': 'Sealant Finis..."
4,Junckers Beech SylvaRed Solid 2-Strip Wood Flo...,"{'pricecurrency': 'GBP', 'price': '151.92'}",Junckers,JUNBSROC22,"[{'name': 'Grade', 'value': 'Prime'}, {'value'..."

'Product_esskateboarding.com_September2020.json.gz'

,name,offers,brand,aggregaterating,color
0,ACCEL SLIM,"{'pricecurrency': 'USD', 'price': '42.99'}",es,"{'ratingvalue': '4.83', 'reviewcount': '200'}",None
1,LA COURTSIDE JERSEY,"{'price': '26.99', 'pricecurrency': 'GBP'}",es,None,None
2,SCRIPT CREW FLEECE,"{'price': '29.99', 'pricecurrency': 'GBP'}",es,"{'ratingvalue': '5.0', 'reviewcount': '1'}",None
3,ACCEL SLIM PLUS LUX,"{'price': '59.95', 'pricecurrency': 'EUR'}",es,"{'ratingvalue': '4.88', 'reviewcount': '24'}",None
4,SQUARE THREE,"{'pricecurrency': 'USD', 'price': '54.99'}",es,"{'reviewcount': '21', 'ratingvalue': '4.71'}",None

'Product_lifeandlibertymotors.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,1998 Buick LESABRE CUSTOM,"{'availability': 'https://schema.org/InStock',...",{'name': 'Buick'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",1G4HP52K6WH488385
1,2011 KIA SEDONA EX,"{'price': '4549', 'availability': 'https://sch...",{'name': 'KIA'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",KNDMH4C76B6372601
2,2000 Toyota AVALON XL,"{'availability': 'https://schema.org/InStock',...",{'name': 'Toyota'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",4T1BF28B5YU105254
3,2005 Ford ESCAPE XLT,"{'availability': 'https://schema.org/InStock',...",{'name': 'Ford'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",1FMYU93185KB40675
4,2005 HONDA CIVIC DX VP,"{'availability': 'https://schema.org/InStock',...",{'name': 'HONDA'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",1HGES16355L017018

'Product_carterchevrolet.com_September2020.json.gz'

,name,offers,brand,mpn,model,manufacturer,color
0,Pre-Owned 2017 Hyundai Elantra,"{'pricecurrency': 'USD', 'availability': 'http...",Hyundai,KMHD84LFXHU190066,Elantra,{'name': 'Hyundai'},GRAY
1,Pre-Owned 2018 Volkswagen Tiguan 2.0T SE,{'itemcondition': 'http://schema.org/UsedCondi...,Volkswagen,3VV2B7AX5JM144795,Tiguan,{'name': 'Volkswagen'},Red
2,Certified Pre-Owned 2019 Honda Ridgeline RTL-T,"{'price': '35732', 'itemcondition': 'http://sc...",Honda,5FPYK3F68KB001709,Ridgeline,{'name': 'Honda'},White
3,Certified Pre-Owned 2017 Toyota Highlander XLE,{'itemcondition': 'http://schema.org/UsedCondi...,Toyota,5TDJZRFH9HS521061,Highlander,{'name': 'Toyota'},None
4,Pre-Owned 2012 Chrysler Town &amp; Country,"{'price': '8547', 'itemcondition': 'http://sch...",Chrysler,2C4RC1BG7CR123903,Town &amp; Country,{'name': 'Chrysler'},None

'Product_scottfhsj.com_September2020.json.gz'

,name,offers,aggregaterating,review,itemcondition,model
0,Joyful Memory,"{'pricecurrency': 'USD', 'highprice': '102.95'...","{'reviewcount': '8', 'ratingvalue': '5.00'}","[{'author': 'from -', 'name': 'Joyful Memory',...",NewCondition,{'image': 'https://res.cloudinary.com/picasso/...
1,Sweetest Sunrise Bouquet,"{'pricecurrency': 'USD', 'lowprice': '59.95', ...","{'ratingvalue': '4.95', 'reviewcount': '22'}","[{'name': 'Sweetest Sunrise Bouquet', 'author'...",NewCondition,[{'image': 'https://res.cloudinary.com/picasso...
2,Peaceful White Lilies Basket,"{'pricecurrency': 'USD', 'price': '89.95', 'av...","{'reviewcount': '250', 'ratingvalue': '4.93'}",None,NewCondition,None
3,Full Of Love Bouquet,"{'pricecurrency': 'USD', 'price': '49.95', 'av...","{'reviewcount': '122', 'ratingvalue': '4.98'}",None,NewCondition,None
4,Sentiments of Serenity Spray,"{'pricecurrency': 'USD', 'price': '139.95', 'a...","{'ratingvalue': '4.96', 'reviewcount': '181'}",None,NewCondition,None

'Product_abracadaroom.com_September2020.json.gz'

,name,offers,brand,aggregaterating,category
0,Drakkar,"{'lowprice': '121.00', 'pricecurrency': 'EUR'}",{'name': 'Fontaine Châtel'},"{'ratingvalue': '4.25', 'reviewcount': '8'}",Treehouse
1,La Roulotte du Cos,"{'lowprice': '70.00', 'pricecurrency': 'EUR'}",{'name': 'Ânes du Cos'},"{'reviewcount': '15', 'ratingvalue': '5'}",Gipsy Caravan
2,Bulle Cabernet &amp; Spa,"{'lowprice': '280.00', 'pricecurrency': 'EUR'}",{'name': 'Les Bulles de Bordeaux'},"{'reviewcount': '21', 'ratingvalue': '4.9048'}",Bubble
3,Bulle Spa Moonlight,"{'lowprice': '149.00', 'pricecurrency': 'EUR'}",{'name': 'La Noalha Insolit&#039;'},"{'reviewcount': '33', 'ratingvalue': '4.9091'}",Bubble
4,L&#039;Ourson Blanc,"{'lowprice': '80.00', 'pricecurrency': 'EUR'}",{'name': 'Le Refuge des 3 Ours'},"{'reviewcount': '1', 'ratingvalue': '5'}",Cabin on Stilts

'Product_stickershoppe.com_September2020.json.gz'

,name,offers,brand,category,mpn
0,Security Officer Blue and White - Embroidered ...,"{'seller': 'Sticker Shoppe', 'price': '3.99', ...",Sticker Shoppe,Security,PM4099
1,Alcorn State University Braves Logo - Static C...,"{'availability': 'https://schema.org/InStock',...",Rico Industries,Alcorn State Braves,SS150861
2,Baltimore Orioles - Sport Short Decal,"{'availability': 'https://schema.org/InStock',...",Rico Industries,Baltimore Orioles,SRT3801
3,Democrats For Romney Ryan - Bumper Sticker,"{'availability': 'https://schema.org/InStock',...",Sticker Shoppe,Mitt Romney,SSBS299
4,Dachshund Taxi Service - Yellow Transport Magnet,"{'price': '13.99', 'seller': 'Sticker Shoppe',...",Sticker Shoppe,Dachshund,YPT8-9

'Product_jalebe.com_September2020.json.gz'

,name,offers,brand,category,weight,color
0,Men Taupe Embroidery Work Kurta with Churidar,"{'pricecurrency': 'USD', 'itemcondition': 'New...",Jalebe Fashion,Kurta Pajama,1.5000 kgs,Taupe
1,Georgette Farasha in Red,"{'pricecurrency': 'USD', 'itemcondition': 'New...",Jalebe Fashion,Wedding Wear,1.5000 kgs,Red
2,Crepe Ombre Saree in Brown,"{'pricecurrency': 'USD', 'itemcondition': 'New...",Jalebe Fashion,Crepe,1.5000 kgs,Brown
3,Georgette Bridal Saree in Red,"{'pricecurrency': 'USD', 'price': '9.69E1', 'a...",Jalebe Fashion,Wedding Dress,2.5000 kgs,Red
4,Georgette Farasha in Purple,"{'pricecurrency': 'USD', 'availability': 'http...",Jalebe Fashion,Wedding Wear,1.5000 kgs,Purple

'Product_theurbanflair.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review,gtin13
0,Watercolor Zodiac Mystic Tough Phone Case,[{'availability': 'https://schema.org/InStock'...,{'name': 'The Urban Flair'},"{'bestrating': '5', 'worstrating': '1', 'revie...",IP11PM-TCB-CS-M-3637591,{'reviewbody': 'Customer Reviews No reviews ye...,P-1DDE2F338B58040
1,Khaki Camouflage Faux Leather Apple Watch Band,"[{'sku': 'AWS-PU-G-38mm-3153634', 'price': '37...",{'name': 'The Urban Flair'},"{'bestrating': '5', 'reviewcount': '4', 'worst...",AWS-PU-B-38mm-3153622,{'name': 'Khaki Camouflage Faux Leather Apple ...,P-DE96B266D320852
2,Blue Boho Mosaic Tile Clear Phone Case,"[{'mpn': 'IPXR-JIC-B-CS-3107180', 'availabilit...",{'name': 'The Urban Flair'},"{'bestrating': '5', 'reviewcount': '4', 'worst...",IP11PM-JIC-B-CS-3107466,"{'datepublished': '2020-05-09', 'reviewbody': ...",P-6ADF5B788DA0BF0
3,Nude Marble Faux Leather Apple Watch Band,"[{'price': '37.95', 'pricevaliduntil': '2021-0...",{'name': 'The Urban Flair'},"{'bestrating': '5', 'reviewcount': '18', 'wors...",AWB-BCA-MB3-712,"{'datepublished': '2020-05-10', 'name': 'Nude ...",None
4,Mystic Abalone Phone Grip,"[{'mpn': 'CKT-CS-M-3145140', 'price': '14.95',...",{'name': 'The Urban Flair'},"{'bestrating': '5', 'reviewcount': '5', 'worst...",CKT-CS-G-3145122,"{'name': 'Mystic Abalone Phone Grip', 'datepub...",P-747C74386A3A6E6

'Product_acaciawoodusa.com_September2020.json.gz'

,name,offers,brand,weight,gtin12
0,14&quot; Acacia Wood Cheeseboard/Cutting Board...,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Kalmar Home'},1.75lb,NaN
1,70&quot; Handcrafted Round Shape Finished Acac...,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'LTJ arbor'},0.0lb,NaN
2,124&quot; x 53&quot; Acacia Wood Live Edge Din...,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'LTJ arbor'},0.0lb,NaN
3,Acacia Wood Chip &amp; Dip Serving Tray with G...,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Kalmar Home'},2.25lb,8.500050e+11
4,7 Piece - Large Acacia Wood Salad Bowl &amp; S...,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Kalmar Home'},4.76lb,8.500050e+11

'Product_slikhaarshop.co.uk_September2020.json.gz'

,name,offers,brand,aggregaterating,review
0,By Vilain Sidekick Zero,"{'price': '18.50', 'itemcondition': 'http://sc...",By Vilain,"{'reviewcount': '9', 'ratingvalue': '5'}","[{'datepublished': '2020-10-06', 'name': 'Best..."
1,SHEH•VOO - Black Clay Condtioner,"{'price': '18.41', 'itemcondition': 'http://sc...",(sheh·voo),"{'reviewcount': '1', 'ratingvalue': '5'}","{'datepublished': '2020-12-06', 'name': 'Excel..."
2,Baxter Cream Pomade,"{'price': '17.00', 'itemcondition': 'http://sc...",Baxter of California,"{'reviewcount': '1', 'ratingvalue': '5'}","{'name': 'Wow!', 'datepublished': '2020-14-05'..."
3,Arcadian Conditioning Oil,"{'price': '16.00', 'pricecurrency': 'GBP', 'it...",Arcadian,"{'reviewcount': '2', 'ratingvalue': '5'}","[{'description': 'Perfection!', 'author': 'Car..."
4,Arcadian Conditioning Cream,"{'price': '16.00', 'pricecurrency': 'GBP', 'it...",Arcadian,"{'reviewcount': '1', 'ratingvalue': '5'}","{'author': 'Carlos 89', 'description': 'Amazin..."

'Product_xn--80ameqebfb1b3c.net_September2020.json.gz'

,name,offers,breadcrumb
0,Michelin Alpin 225/55/17,"{'pricecurrency': 'UAH', 'price': '700'}",Главная / Выбор б\\у шин / Зимняя б/у резина /...
1,Nokian WR 215/60/17,"{'pricecurrency': 'UAH', 'price': '700'}",Главная / Выбор б\\у шин / Зимняя б/у резина /...
2,Sava Eskimo HP 195/50/15,"{'pricecurrency': 'UAH', 'price': '700'}",Главная / Выбор б\\у шин / Зимняя б/у резина /...
3,Platin Rp30 Winter 195/55/15,"{'pricecurrency': 'UAH', 'price': '650'}",Главная / Выбор б\\у шин / Зимняя б/у резина /...
4,Dunlop Sp 30 175/65 R15,"{'price': '200', 'pricecurrency': 'UAH'}",Главная / Выбор б\\у шин / Летняя б\\у резина ...

'Product_chaussurecassis.com_September2020.json.gz'

,name,offers,condition
0,Mule denim NOZITA,"{'price': '50,00 €', 'pricecurrency': 'EUR'}",New
1,Baskets strass COBY,"{'price': '37,50 €', 'pricecurrency': 'EUR'}",New
2,Sandale plateforme CHARLEA,"{'price': '54,17 €', 'pricecurrency': 'EUR'}",New
3,Mule plate a volant GREGORY,"{'price': '29,17 €', 'pricecurrency': 'EUR'}",New
4,Baskets glitter CHUPAN,"{'price': '70,83 €', 'pricecurrency': 'EUR'}",New

'Product_luxbeautymall.com_September2020.json.gz'

,name,offers,category,weight,releasedate,color
0,16 Colors Eyeshadow Shimmer Highly Pigmented E...,"{'price': '24.00', 'availability': 'https://sc...",Makeup,"{'value': '0.0', 'unitcode': 'ONZ'}",2020-08-22T15:56:20-05:00,Mixed Color
1,"New Cosmetic Bag -School Supplies ,Gift, Make ...","{'price': '10.00', 'availability': 'http://sch...",Bags\\Purses,"{'value': '0.0', 'unitcode': 'ONZ'}",2020-08-28T13:28:25-05:00,"A, B, C, D"
2,Casual Women Romantic Starry Sky Wrist Watch L...,"{'pricecurrency': 'USD', 'availability': 'http...",Watches\\Jewelry,"{'value': '0.0', 'unitcode': 'ONZ'}",2020-08-14T20:36:54-05:00,"Black, Blue, coffee, Gray, Green, Pink, Purple..."
3,TEST PRODUCT - DO NOT DELETE,"{'pricecurrency': 'USD', 'price': '0.01', 'ite...",Skin Care,None,2020-09-02T12:18:56-05:00,None
4,2020 Women Sneaker Walking Running Shoes - Lac...,"{'pricecurrency': 'USD', 'price': '48.00', 'av...",Footwear,"{'value': '0.0', 'unitcode': 'ONZ'}",2020-08-22T21:54:37-05:00,Green

'Product_bouchermazda.com_September2020.json.gz'

,name,offers,brand,mpn,model,manufacturer,releasedate,color
0,2020 Mazda CX-5 Grand Touring,{'itemcondition': 'http://schema.org/NewCondit...,Mazda,JM3KFBDM7L0864751,CX-5,Mazda,2020,Soul Red Crystal Metallic
1,2020 Mazda Mazda3 Base,"{'price': '18705', 'name': '2020 Mazda Mazda3 ...",Mazda,3MZBPABL9LM118922,Mazda3,Mazda,2020,Sonic Silver Metallic
2,2018 Volkswagen Tiguan 2.0T SEL Premium,{'itemcondition': 'http://schema.org/UsedCondi...,Volkswagen,3VV4B7AXXJM002029,Tiguan,Volkswagen,2018,White Silver Metallic
3,2017 Volkswagen Golf Alltrack TSI S,"{'pricecurrency': 'USD', 'availability': 'http...",Volkswagen,3VWH17AU4HM540998,Golf Alltrack,Volkswagen,2017,Deep Black Pearl
4,2016 Mazda Mazda6 i Grand Touring,"{'price': '15900', 'availability': 'https://sc...",Mazda,JM1GJ1W53G1404158,Mazda6,Mazda,2016,Jet Black Mica

'Product_keystonedistributing.com_September2020.json.gz'

,name,offers,brand,category,mpn
0,Victory Motorcycle Single Rotor Trike Models 2...,{'url': 'https://www.keystonedistributing.com/...,keystonedistributing.com,Centramatic,CTMV100-109
1,Muth Blue Glass with Red Turn Signal Mirror Ki...,"{'price': '129', 'seller': 'keystonedistributi...",keystonedistributing.com,Honda Gold Wing F6B,MO22005790
2,Harley Davidson 2014-Newer Open Front Rotor Si...,"{'pricevaliduntil': '2020-10-27', 'seller': 'k...",keystonedistributing.com,Centramatic,CTMHD200-215
3,Muth Black Merge Master Signal Mirrors for Met...,{'url': 'https://www.keystonedistributing.com/...,keystonedistributing.com,Metric Motorcycles,MO22007112
4,Can-Am Spyder (Front Only),"{'price': '131', 'seller': 'keystonedistributi...",keystonedistributing.com,Centramatic,CTMCAS400-411

'Product_floursacktowels.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,itemcondition
0,"Classic Aprons for Women and Men, Aprons Chef,...",[{'itemcondition': 'http://schema.org/NewCondi...,{'name': 'Mary's Home Goods'},"{'ratingvalue': '5.0', 'ratingcount': '1'}",3929682968599,http://schema.org/NewCondition
1,"Unbleached Flour Sack Towels, Real Natural Tea...","[{'name': 'Natural', 'itemcondition': 'http://...",{'name': 'MARY'S KITCHEN FLOUR SACK TOWELS'},"{'ratingcount': '96', 'ratingvalue': '4.93'}",1555762741271,http://schema.org/NewCondition
2,"Tea Towels Blank for Kitchen, 19\""x28\"", 100% ...",[{'itemcondition': 'http://schema.org/NewCondi...,{'name': 'MARY'S KITCHEN FLOUR SACK TOWELS'},"{'ratingcount': '97', 'ratingvalue': '4.94'}",4451302473791,http://schema.org/NewCondition
3,"Wholesale Flour Sack Napkins Bulk, 19\""x19\"", ...","[{'pricecurrency': 'USD', 'availability': 'htt...",{'name': 'MARY'S KITCHEN FLOUR SACK TOWELS'},"{'ratingvalue': '5.0', 'ratingcount': '4'}",4464671653951,http://schema.org/NewCondition
4,Wholesale Classic Bib Aprons for Women and Men...,[{'itemcondition': 'http://schema.org/NewCondi...,{'name': 'Mary's Home Goods'},None,3933776085015,http://schema.org/NewCondition

'Product_degzou.com_September2020.json.gz'

,name,offers,brand,category,releasedate
0,Déguisement Twilight Sparkle fille - My Little...,"{'price': '51.53', 'availability': 'http://sch...",{'name': 'Rubies UK'},Déguisements,2020-05-26T02:19:28+02:00
1,Perruque longue multicolore femme,"{'pricecurrency': 'EUR', 'itemcondition': 'New...",None,Masques et perruques,2019-01-12T21:59:38+01:00
2,Sac machette grise,"{'availability': 'https://schema.org/InStock',...",None,Masques et perruques,2019-01-12T21:48:31+01:00
3,Chemise Gryffondor top enfant - Harry Potter,"{'availability': 'http://schema.org/InStock', ...",{'name': 'Rubies'},Accessoires et maquillage,2018-12-07T21:14:36+01:00
4,Kit Yoyo Pyjamasques garçon,"{'pricevaliduntil': '2021-12-31', 'price': '18...",{'name': 'AMSCAN'},Masques et perruques,2019-02-16T22:00:29+01:00

'Product_shop-komakino.com_September2020.json.gz'

,name,offers,brand,mpn,weight
0,Abonnement 1 an 4 numéros Reggae Vibes + 1 CD ...,"{'pricevaliduntil': '2026-02-01', 'availabilit...",{'name': 'REGGAE VIBES'},REGABO4N40,1.8
1,PLUGGED n°32,"{'pricevaliduntil': '2020-10-03', 'availabilit...",{'name': 'PLUGGED'},PLU32,0.3
2,REGGAE VIBES n°70,"{'price': '7.95', 'pricevaliduntil': '2020-10-...",{'name': 'REGGAE VIBES'},REG70,0.3
3,"Abonnement 1 an 6 numéros Plugged + 2CD \""Angu...","{'pricevaliduntil': '2025-02-01', 'price': '30...",{'name': 'PLUGGED'},PLUABO6N,1.8
4,MYROCK n°61,"{'pricevaliduntil': '2020-10-01', 'availabilit...",{'name': 'MYROCK'},MYR61,0.3

'Product_lygiay.com_September2020.json.gz'

                                                name    price shop-currency
0  Ly Giấy Phan Khang Có Quai Hoặc Cover Chống Nó...  Liên hệ           VND
1                                 ly-kem-tham-khao-1  Liên hệ           VND
2                                       Ly giấy 10oz  Liên hệ           VND
3                                       Ly giấy 12oz  Liên hệ           VND
4                                         Ly kem 4oz  Liên hệ           VND

'Product_bridetribes.com.au_September2020.json.gz'

,name,offers,price,shop-currency
0,Rosie Satin Robe in Ice Grey,-66% Rosie Satin Robe in Ice Grey No reviews $...,$10.00,AUD
1,Daisy Cotton Bridesmaid Robes,Daisy Cotton Bridesmaid Robes No reviews $29.9...,$29.99,AUD
2,Floral - Bridal Party Thank you Cards,Floral - Bridal Party Thank you Cards No revie...,$5.00,AUD
3,"\""MRS\"" Bride denim jacket","\""MRS\"" Bride denim jacket No reviews $74.99 o...",$74.99,AUD
4,Wifey denim jacket,Wifey denim jacket 5 reviews $74.99 or make 4 ...,$74.99,AUD

'Product_iclothing.com_September2020.json.gz'

,name,offers,brand,category,color
0,Mila Belted Lace Dress in Black,"{'price': '1.399E1', 'availability': 'http://s...",Only,Black Friday Dresses,black
1,Poppy Embellished Neckline Wedding Dress,{'availability': 'http://schema.org/OutOfStock...,city goddess,Sale,white
2,Eden Belted Jumpsuit in Blue,"{'price': '4.897E1', 'availability': 'http://s...",Marc Angelo,Brand Spotlight Marc Angelo,blue
3,Connie Rose Dipped Hem Dress in Black,"{'price': '1.399E1', 'availability': 'http://s...",Marc Angelo,Dresses,black
4,Lottie Court Shoe in Blue Suede,{'availability': 'http://schema.org/OutOfStock...,No Doubt,Heels,blue

'Product_dkhardware.com_September2020.json.gz'

,name,offers,brand,aggregaterating,gtin8
0,CRL GB535CH Polished Chrome 20&amp;quot; 135 D...,"{'pricevaliduntil': '2020-12-31T23:59:59Z', 'p...",CRL,"{'bestrating': '5', 'ratingvalue': '5.0', 'rev...",1.395339e+11
1,Tremco 942800 Clear Proglaze Silicone Sealant,"{'pricevaliduntil': '2020-12-31T23:59:59Z', 'i...",Tremco,"{'bestrating': '5', 'reviewcount': '1', 'ratin...",1.496971e+11
2,CRL GBE18MBL Matte Black Mitered 18&amp;quot; ...,"{'pricevaliduntil': '2020-12-31T23:59:59Z', 'i...",CRL,"{'bestrating': '5', 'reviewcount': '1', 'ratin...",NaN
3,CRL 33STW5GL Translucent White 4.5 Gallon Pail...,"{'pricevaliduntil': '2020-12-31T23:59:59Z', 'i...",CRL,"{'bestrating': '5', 'reviewcount': '1', 'ratin...",3.221361e+11
4,Dow Corning DC1W White Glazing Silicone Sealant,"{'pricevaliduntil': '2020-12-31T23:59:59Z', 'i...",Dow Corning,"{'bestrating': '5', 'ratingvalue': '5.0', 'rev...",5.919562e+11

'Product_sinaimemorialchapelsinc.com_September2020.json.gz'

,name,offers,aggregaterating,review,itemcondition,model
0,"8\"" Angel holding Dove","{'pricecurrency': 'USD', 'lowprice': '30.00', ...","{'reviewcount': '2', 'ratingvalue': '5.00'}","[{'author': 'from -', 'description': 'Have bee...",NewCondition,"{'name': '8\"" Angel holding Dove (Standard)', ..."
1,Loved One Vertical Blanket,"{'pricecurrency': 'USD', 'highprice': '54.99',...","{'reviewcount': '2', 'ratingvalue': '5.00'}","[{'datepublished': '4/17/2020', 'author': 'fro...",NewCondition,{'name': 'Loved One Vertical Blanket (Standard...
2,Grief After Suicide,"{'pricecurrency': 'USD', 'lowprice': '165.00',...",None,None,NewCondition,"{'name': 'Grief After Suicide (Standard)', 'ur..."
3,Memories In Crystal - Diamond Series,"{'pricecurrency': 'USD', 'lowprice': '109.95',...",None,None,NewCondition,"[{'sku': 'DI01', 'url': 'https://www.sinaimemo..."
4,Godiva Biscuit Gift Box (32 pc),"{'pricecurrency': 'USD', 'highprice': '24.95',...","{'reviewcount': '1', 'ratingvalue': '5.00'}",{'description': 'I do not know if the product ...,NewCondition,"{'sku': '12357', 'name': 'Godiva Biscuit Gift ..."

'Product_workingperson.com_September2020.json.gz'

,name,offers,brand,aggregaterating,model,color,reviews
0,Danner Boots: Trakwelt 13243 Men's Non-Metalli...,"{'price': '189.95', 'pricecurrency': 'USD', 's...",Danner Boots,"{'bestrating': '5', 'reviewcount': '1', 'ratin...",13243,Brown,"{'datepublished': '2017-11-08', 'description':..."
1,District Bags: DT715 RED Retro Backpack,"{'pricecurrency': 'USD', 'seller': 'The Workin...",None,None,DT715,Red,None
2,Dickies Coveralls: Men's 48700 DN Dark Navy De...,"{'price': '47.99', 'pricecurrency': 'USD', 'se...",Dickies Work Uniforms,"{'bestrating': '5', 'ratingvalue': '4.4', 'rev...",48700,Blue,[{'name': 'My husband really likes his coveral...
3,Dickies Shirts: Men's WS450 RB Royal Blue Cott...,"{'pricecurrency': 'USD', 'seller': 'The Workin...",Dickies,None,WS450,Blue,None
4,Carhartt Vests: Men's 104394BLK Black Sherpa L...,"{'price': '59.99', 'pricecurrency': 'USD', 'se...",Carhartt Clothing,"{'bestrating': '5', 'reviewcount': '8', 'worst...",104394,Black,"[{'author': 'Larry Crowell', 'description': 'I..."

'Product_cosmeticosonline.com_September2020.json.gz'

,name,offers,brand,category,mpn,gtin13
0,Paese - nail polish colour 418 9ml,"{'pricecurrency': 'EUR', 'price': '4.10', 'ava...",{'name': 'Paese'},nails,PS025,NaN
1,MASMI – Cotton Ultra-thin Pads With Wings – Night,{'itemcondition': 'https://schema.org/NewCondi...,{'name': 'Masmi'},intymate-higiene,MAS01,NaN
2,Nacomi - cold pressed cosmetic grade argan oil...,"{'price': '12.90', 'pricecurrency': 'EUR', 'av...",{'name': 'Nacomi'},oils-for-the-skin,NCM37,5.902540e+12
3,Bioline – Aleppo soap 55% 200g,{'itemcondition': 'https://schema.org/NewCondi...,{'name': 'Bioline'},face-gels-and-peelings,BIOL15,NaN
4,Paese - nail polish colour 107 9ML,"{'pricecurrency': 'EUR', 'price': '4.10', 'ava...",{'name': 'Paese'},nails,PS050,NaN

'Product_wavecentral99.com_September2020.json.gz'

,name,offers,brand,aggregaterating,category,mpn,review
0,Men&#8217;s Naruto Uchiha Sasuke Awesome Print...,"{'availability': 'https://schema.org/InStock',...",{'name': 'wavecentral99.com'},"{'ratingvalue': '5', 'reviewcount': '14'}",Best Sellers,9461,[{'reviewbody': 'Super Qualität. PERFECT !!!!'...
1,Women&#8217;s Pokemon Alluring Themed T-Shirt,"{'pricevaliduntil': '2020-10-27', 'availabilit...",{'name': 'wavecentral99.com'},None,Clothing,9247,None
2,Beautiful Pokemon Print Women&#8217;s Polyeste...,"{'availability': 'https://schema.org/InStock',...",{'name': 'wavecentral99.com'},"{'ratingvalue': '5', 'reviewcount': '3'}",Clothing,4007,[{'reviewbody': 'I love this shirt it’s adorab...
3,Naruto Cute Frog Shaped Plush Coin Purse,{'name': 'Naruto Cute Frog Shaped Plush Coin P...,{'name': 'wavecentral99.com'},"{'reviewcount': '1', 'ratingvalue': '5'}",Luggage &amp; Bags,8311,{'reviewbody': 'Good material'}
4,Women&#8217;s Naruto Printed Cotton Cute T-Shirt,[{'availability': 'https://schema.org/InStock'...,{'name': 'wavecentral99.com'},None,Clothing,9434,None

'Product_authenticyixing.com_September2020.json.gz'

,name,offers,brand,category,weight,releasedate
0,Lucky Bamboo 段泥招财竹段,"{'pricecurrency': 'USD', 'itemcondition': 'New...",{'name': 'Teapots over 400 ML (Large size)'},Teapots over 400 ML (Large size),"{'unitcode': 'KGM', 'value': '1.3'}",2014-12-11T14:58:10+08:00
1,Painting Phoenix 泥绘凤凰壶,"{'price': '300.00', 'itemcondition': 'NewCondi...",{'name': 'Teapots up to 400 ML (Medium size)'},Teapots up to 400 ML (Medium size),"{'unitcode': 'KGM', 'value': '1.1'}",2014-11-03T22:50:55+08:00
2,Ruyi Carved Round Teapot 如意刻字大圆壶,"{'pricecurrency': 'USD', 'itemcondition': 'New...",{'name': 'Teapots over 400 ML (Large size)'},Teapots over 400 ML (Large size),"{'unitcode': 'KGM', 'value': '1.3'}",2014-11-24T14:19:12+08:00
3,Hard to find Aged Raw Pu erh Tea Year 2000,"{'pricecurrency': 'USD', 'itemcondition': 'New...",{'name': 'Teas Aged teas Pu'erh Teas'},Teas Aged teas Pu'erh Teas,"{'value': '0.5', 'unitcode': 'KGM'}",2020-04-21T17:30:37+08:00
4,Fambe Gong Chun 窑变供春壶,"{'pricecurrency': 'USD', 'price': '299.00', 'i...",{'name': 'Teapots over 400 ML (Large size)'},Teapots over 400 ML (Large size),None,2014-11-27T23:01:39+08:00

'Product_dlabelonline.com_September2020.json.gz'

,name,offers,category,weight,releasedate,color,width,height,depth
0,Oppo A52 Dune Skins,"{'pricecurrency': 'SGD', 'availability': 'http...",Oppo > A52,"{'value': '0.1', 'unitcode': 'KGM'}",2020-07-21T01:43:41+08:00,None,"{'value': '20', 'unitcode': 'CMT'}","{'value': '1', 'unitcode': 'CMT'}","{'value': '30', 'unitcode': 'CMT'}"
1,iPhone 8 Plus Carbon Fiber Skins,"{'pricecurrency': 'SGD', 'availability': 'http...",iPhone > iPhone 8 Plus,"{'value': '0.1', 'unitcode': 'KGM'}",2020-02-19T12:40:22+08:00,"Black, Blue, Gold, Grey, Red, Silver, White","{'value': '20', 'unitcode': 'CMT'}","{'value': '1', 'unitcode': 'CMT'}","{'value': '30', 'unitcode': 'CMT'}"
2,Samsung Galaxy A50 Venom Skins &raquo; Officia...,"{'pricecurrency': 'SGD', 'availability': 'http...",Samsung > Galaxy A50,"{'value': '0.1', 'unitcode': 'KGM'}",2020-04-24T17:40:50+08:00,None,"{'value': '20', 'unitcode': 'CMT'}","{'value': '1', 'unitcode': 'CMT'}","{'value': '30', 'unitcode': 'CMT'}"
3,Samsung Galaxy S10+ Forged Carbon Skins,"{'pricecurrency': 'SGD', 'price': '14.99', 'it...",Samsung > Galaxy S10 Plus,"{'value': '0.1', 'unitcode': 'KGM'}",2020-02-11T14:21:13+08:00,None,"{'value': '20', 'unitcode': 'CMT'}","{'value': '1', 'unitcode': 'CMT'}","{'value': '30', 'unitcode': 'CMT'}"
4,Google Home Marble Skins,"{'availability': 'http://schema.org/InStock', ...",Google > Google Home,"{'value': '0.1', 'unitcode': 'KGM'}",2020-05-05T16:45:58+08:00,"Black, Grey, White","{'value': '20', 'unitcode': 'CMT'}","{'value': '1', 'unitcode': 'CMT'}","{'value': '30', 'unitcode': 'CMT'}"

'Product_vinico.com_September2020.json.gz'

,name,offers,brand,gtin13,isrelatedto,issimilarto
0,Anal Playbox,{'url': 'https://www.vinico.com/toys/anal-play...,{'name': 'You2Toys'},4.024145e+12,"[{'position': '7', 'url': 'https://www.vinico....",[{'url': 'https://www.vinico.com/toys/shots-me...
1,Joydivision Femme Fatale Massageöl Gold-V (100ml),"{'price': '13.60', 'itemcondition': 'new', 'pr...",{'name': 'Joydivision'},4.028403e+12,"[{'position': '6', 'url': 'https://www.vinico....",[{'url': 'https://www.vinico.com/massage/dona-...
2,Fun Factory LADY BI - ultramarine,{'url': 'https://www.vinico.com/toys/fun-facto...,{'name': 'Fun Factory'},4.032499e+12,[{'url': 'https://www.vinico.com/hygiene-pfleg...,[{'url': 'https://www.vinico.com/toys/satisfye...
3,Lylou Glamour Nipple Cream Orange Lime,{'url': 'https://www.vinico.com/hygiene-pflege...,{'name': 'Lylou'},4.035224e+12,[{'url': 'https://www.vinico.com/mut-zu-sextoy...,"{'position': '1', 'url': 'https://www.vinico.c..."
4,Eros Nuru Massagegel (250ml),"{'price': '10.67', 'url': 'https://www.vinico....",{'name': 'Eros'},4.035223e+12,"[{'position': '6', 'url': 'https://www.vinico....",[{'url': 'https://www.vinico.com/massage/swede...

'Product_indogolok.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,3 UNIT SAMURAI THE LAST SATU SET - Golok Indon...,"{'pricevaliduntil': '2112-12-12', 'availabilit...",Golok Indonesia,"{'reviewcount': '1', 'ratingvalue': '4'}",MPN-1594873145279832773
1,Golok 2 Stock Habis - Golok Indonesia,"{'pricevaliduntil': '2112-12-12', 'availabilit...",Golok Indonesia,"{'reviewcount': '1', 'ratingvalue': '4'}",MPN-5946621018352153802
2,Katana Kill Bill Red - Golok Indonesia,{'url': 'https://www.indogolok.com/2020/03/kat...,Golok Indonesia,"{'reviewcount': '1', 'ratingvalue': '4'}",MPN-5172282666129660753
3,Samurai 2 Stock Kosong - Golok Indonesia,"{'pricevaliduntil': '2112-12-12', 'availabilit...",Golok Indonesia,"{'reviewcount': '1', 'ratingvalue': '4'}",MPN-2489972202567310989
4,Samurai 7 Stock Kosong - Golok Indonesia,"{'pricevaliduntil': '2112-12-12', 'availabilit...",Golok Indonesia,"{'reviewcount': '1', 'ratingvalue': '4'}",MPN-1937757826125823652

'Product_sollu.com.br_September2020.json.gz'

,name,offers,brand,itemcondition,gtin13,weight,width,height,depth
0,Bota Masculina em Couro Soft Preto Pontiac Sol...,"{'pricecurrency': 'BRL', 'availability': 'http...",{'name': 'Sollu'},https://schema.org/NewCondition,7893740518422,1600 g,35.0 cm,13.0 cm,21.0 cm
1,Bota Social Masculina em Couro Napa Comfort Pr...,"{'pricecurrency': 'BRL', 'availability': 'http...",{'name': 'Sollu'},https://schema.org/NewCondition,7893740040541,1600 g,35.0 cm,13.0 cm,21.0 cm
2,Bota Masculina em Couro Soft Pinhao Pontiac So...,"{'pricecurrency': 'BRL', 'availability': 'http...",{'name': 'Sollu'},https://schema.org/NewCondition,7893740519122,1600 g,35.0 cm,13.0 cm,21.0 cm
3,Sandália Masculina em Couro Soft Comfort Preto...,"{'pricecurrency': 'BRL', 'availability': 'http...",{'name': 'Sollu'},https://schema.org/NewCondition,7893740016072,1600 g,35.0 cm,13.0 cm,21.0 cm
4,Bota Masculina em Couro Soft Pinhão New Absolu...,"{'pricecurrency': 'BRL', 'availability': 'http...",{'name': 'Sollu'},https://schema.org/NewCondition,7893740035530,1600 g,35.0 cm,13.0 cm,21.0 cm

'Product_tresemme.com_September2020.json.gz'

,name,brand,aggregaterating,review,gtin8
0,TRESemmé Between Washes Smooth Renew Anti-Friz...,tresemme,None,None,22400002354
1,Instant Refresh Translucent Dry Shampoo,tresemme,"{'bestrating': '5', 'reviewcount': '3', 'ratin...","[{'name': 'mrs', 'datepublished': '2018-06-16'...",8710908043376
2,Moisture Rich Nourishing Detangling Spray,tresemme,"{'bestrating': '5', 'reviewcount': '759', 'rat...","[{'author': 'christinehan90', 'datepublished':...",22400002187
3,Keratin Smooth Conditioner,tresemme,"{'bestrating': '5', 'ratingvalue': '4.1', 'rev...",{'description': 'I used this product yesterday...,8710908694868
4,Botanique Curl Hydration Shampoo,tresemme,"{'bestrating': '5', 'ratingvalue': '5.0', 'rev...","{'name': 'Finally the perfect product', 'datep...",22400681733

'Product_justcerts.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review,releasedate
0,Microsoft Dynamics 365 Core Finance and Operat...,"{'pricecurrency': 'USD', 'price': '100.00', 'a...",{'name': 'JustCerts'},"{'reviewcount': '115', 'ratingvalue': '4.8'}",MB300,"{'datepublished': '2020-09-18', 'author': 'Vic...","Sep 11,2020"
1,IBM Business Process Management Express or Sta...,"{'pricecurrency': 'USD', 'price': '100.00', 'a...",{'name': 'JustCerts'},"{'ratingvalue': '5.0', 'reviewcount': '115'}",C9550412,"{'datepublished': '2020-09-24', 'author': 'Sar...","Sep 19,2020"
2,Implementing and Operating Cisco Security Core...,"{'pricecurrency': 'USD', 'price': '100.00', 'a...",{'name': 'JustCerts'},"{'reviewcount': '188', 'ratingvalue': '4.7'}",350701,"{'datepublished': '2020-09-18', 'description':...","Sep 12,2020"
3,NetApp Certified Support Engineer,"{'pricecurrency': 'USD', 'price': '100.00', 'a...",{'name': 'JustCerts'},"{'reviewcount': '73', 'ratingvalue': '4.7'}",NS0192,{'description': 'I've recently passed my SAP C...,"Sep 16,2020"
4,Fortinet NSE 7 - Secure Access 6.2,"{'pricecurrency': 'USD', 'price': '100.00', 'a...",{'name': 'JustCerts'},"{'reviewcount': '73', 'ratingvalue': '4.7'}",NSE7SAC62,{'description': 'I've recently passed my SAP C...,"Sep 10,2020"

'Product_brightonmotorgrp.com.au_September2020.json.gz'

,name,offers,brand,model,audience
0,2020 LDV G10 Executive SV7A,"{'pricecurrency': 'AUD', 'price': '35888.00', ...",{'name': 'LDV'},G10,{'audiencetype': 'car buyers'}
1,2019 INFINITI Q30 Sport H15,"{'pricecurrency': 'AUD', 'price': '36888.00', ...",{'name': 'INFINITI'},Q30,{'audiencetype': 'car buyers'}
2,2019 LDV D90 Mode SV9A,"{'pricecurrency': 'AUD', 'price': '26950.00', ...",{'name': 'LDV'},D90,{'audiencetype': 'car buyers'}
3,2019 INFINITI Q30 Sport H15,"{'pricecurrency': 'AUD', 'price': '36888.00', ...",{'name': 'INFINITI'},Q30,{'audiencetype': 'car buyers'}
4,2019 NISSAN LEAF ZE1,"{'pricecurrency': 'AUD', 'price': '51888.00', ...",{'name': 'NISSAN'},LEAF,{'audiencetype': 'car buyers'}

'Product_purple-cat.co.uk_September2020.json.gz'

,name,offers,brand,mpn,manufacturer
0,iiyama ProLite TH4265MIS-B1AG touch screen mon...,"{'availability': 'http://schema.org/InStock', ...",{'name': 'iiyama'},TH4265MIS-B1AG,{'name': 'iiyama'}
1,EIKI Generic Complete Lamp for EIKI LC-XNB3S p...,"{'availability': 'http://schema.org/InStock', ...",{'name': 'EIKI'},54246,{'name': 'EIKI'}
2,Ra technology RA-Cent-XL-V1 Ceiling Grey proje...,"{'price': '1.7606E2', 'availability': 'http://...",{'name': 'RA Technology'},RA-CENT-XL-V1,{'name': 'RA Technology'}
3,Celexon Professional 2-Channel Radio Remote Set,"{'price': '1.578E2', 'availability': 'http://s...",{'name': 'Celexon'},1090852,{'name': 'Celexon'}
4,Epson EB-X39,"{'availability': 'http://schema.org/InStock', ...",{'name': 'Epson'},V11H855041,{'name': 'Epson'}

'Product_healthcabin.net_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,VOOPOO X217 TC Box Mod 217W,"{'availability': 'https://schema.org/InStock',...",{'name': 'Voopoo'},"{'reviewcount': '1', 'ratingvalue': '5'}",20630
1,30ml Aramax Max Apple E-Liquid (50PG/50VG),"{'availability': 'https://schema.org/InStock',...",{'name': 'Aramax'},"{'reviewcount': '5', 'ratingvalue': '4.2'}",11534
2,"UD Kanthal A1 Wire (24ga, 0.5mm)","{'availability': 'https://schema.org/InStock',...",{'name': 'Youde'},"{'reviewcount': '1', 'ratingvalue': '5'}",10100
3,Vaporesso Target PM30 Pod Mod Kit 1200mAh 3.5ml,"{'availability': 'https://schema.org/InStock',...",{'name': 'Vaporesso'},"{'ratingvalue': '5', 'reviewcount': '14'}",23600
4,Geekvape Aegis Pod Kit 800mAh 3.5ml,"{'availability': 'https://schema.org/InStock',...",{'name': 'Geekvape'},"{'ratingvalue': '5', 'reviewcount': '10'}",23424

'Product_matthewsandsonfuneralhome.net_September2020.json.gz'

,name,offers,aggregaterating,review,itemcondition,model
0,"Peace, Prayers, & Blessings- Lavender and White","{'pricecurrency': 'USD', 'lowprice': '59.99', ...","{'reviewcount': '7', 'ratingvalue': '4.86'}","[{'name': 'Peace, Prayers, & Blessings- Lavend...",NewCondition,[{'url': 'https://www.matthewsandsonfuneralhom...
1,Angel Wind Chime - Bronze,"{'pricecurrency': 'USD', 'highprice': '89.95',...",None,None,NewCondition,[{'url': 'https://www.matthewsandsonfuneralhom...
2,Heart Wind Chime - Personalized,"{'highprice': '109.95', 'pricecurrency': 'USD'...","{'reviewcount': '2', 'ratingvalue': '5.00'}","[{'author': 'from -', 'name': 'Heart Wind Chim...",NewCondition,[{'sku': 'Heart-Personalized-Bronze-Medium-FO'...
3,European Sympathy Dish Garden,"{'pricecurrency': 'USD', 'lowprice': '59.99', ...","{'ratingvalue': '4.83', 'reviewcount': '6'}","[{'datepublished': '1/17/2020', 'description':...",NewCondition,[{'url': 'https://www.matthewsandsonfuneralhom...
4,"5.5\"" EBN Kneeling & Praying Angel","{'pricecurrency': 'USD', 'highprice': '18.50',...",None,None,NewCondition,"{'name': '5.5\"" EBN Kneeling & Praying Angel (..."

'Product_antelopebeads.com_September2020.json.gz'

,name,offers,brand,aggregaterating,manufacturer
0,5mm Southwest Rhombus Flat Leather Cord Slider...,"{'pricevaliduntil': '2030-03-23', 'itemconditi...",BB Order,"{'bestrating': '5', 'ratingvalue': '0', 'revie...",BB Order
1,Large Cable Chain - Antique Silver - per foot,"{'pricevaliduntil': '2030-03-23', 'itemconditi...",BB Order,"{'bestrating': '5', 'ratingvalue': '0', 'revie...",BB Order
2,Cultured Sea Glass Bead Teardrop Baby 18x6mm -...,"{'pricevaliduntil': '2030-03-23', 'itemconditi...",Sea Glass_3940,"{'bestrating': '5', 'ratingvalue': '0', 'revie...",Sea Glass_3940
3,Twisted Curb Chain - Matte Gold - per foot,"{'pricevaliduntil': '2030-03-23', 'itemconditi...",BB Order,"{'bestrating': '5', 'ratingvalue': '0', 'revie...",BB Order
4,10mm Medium Plain Round Leather Cord Slider - ...,"{'pricevaliduntil': '2030-03-23', 'itemconditi...",BB Order,"{'bestrating': '5', 'ratingvalue': '0', 'revie...",BB Order

'Product_gahostel.com_September2020.json.gz'

                                                name     price shop-currency
0                                   梅州两天一夜 (普通的旅游方式)       20₫           VND
1                          BAI DINH-TRANG AN - 1 DAY  500.000₫           VND
2                               MOTOR/ BIKE SERVICES   Contact           VND
3                                        Common Room   Contact           VND
4  SAPA – CÁT CÁT – HÀM RỒNG 2 NGÀY 1 ĐÊM NGỦ KHÁ...   Contact           VND

'Product_clicknorder.co.uk_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Mercer Culinary Allergen Safety Pizza Wheel 2.75\,"{'pricecurrency': 'GBP', 'itemcondition': 'htt...",Mercer Culinary,"{'ratingvalue': '5', 'reviewcount': '27'}",765301915964
1,Churchill Stonecast Patina Triangular Bowls Ru...,"{'pricevaliduntil': '2020-09-29', 'pricecurren...",Churchill,"{'reviewcount': '29', 'ratingvalue': '5'}",5034414433043
2,Griddle Cleaning Pad (Pack of 10),"{'pricecurrency': 'GBP', 'itemcondition': 'htt...",Non Branded,"{'ratingvalue': '5', 'reviewcount': '30'}",5013174035698
3,Utopia Conic Coffee Mugs 250ml (Pack of 12),"{'pricecurrency': 'GBP', 'itemcondition': 'htt...",Utopia,"{'ratingvalue': '5', 'reviewcount': '27'}",5060020673740
4,Melamine Blue Rectangular Placemat,"{'pricevaliduntil': '2020-09-29', 'pricecurren...",Lady Clare,"{'reviewcount': '29', 'ratingvalue': '5'}",5036315500510

'Product_elgot.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,GE&reg; 27.7 Cu. Ft. Fingerprint Resistant Fre...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'GE Appliances'},"{'reviewcount': '439', 'itemreviewed': 'GE&reg...",GFD28GYNFS
1,GE&reg; ENERGY STAR&reg; 27.7 Cu. Ft. French-D...,"{'price': '3029.99', 'availability': 'http://s...",{'name': 'GE Appliances'},{'itemreviewed': 'GE&reg; ENERGY STAR&reg; 27....,GFE28GMKES
2,GE Profile&trade; 1.1 Cu. Ft. Countertop Micro...,"{'pricecurrency': 'USD', 'price': '400.99', 'a...",{'name': 'GE Appliances'},"{'ratingvalue': '4.0', 'reviewcount': '488', '...",PEM31SFSS
3,GE&reg; 36&quot; Built-In Gas Cooktop with Dis...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'GE Appliances'},{'itemreviewed': 'GE&reg; 36&quot; Built-In Ga...,JGP3036DLWW
4,GE&reg; 1.9 Cu. Ft. Over-the-Range Sensor Micr...,"{'pricecurrency': 'USD', 'price': '519.99', 'a...",{'name': 'GE Appliances'},{'itemreviewed': 'GE&reg; 1.9 Cu. Ft. Over-the...,JVM7195EKES

'Product_googansquad.com_September2020.json.gz'

,name,offers,brand,aggregaterating,category
0,Basshers Wristband,"{'name': 'Default Title', 'price': '5.00', 'pr...",{'name': 'Basshers'},"{'ratingvalue': '4.0', 'reviewcount': '1'}",ACCESSORY
1,Basshers Est. Zip up Hoodie,[{'availability': 'https://schema.org/InStock'...,{'name': 'Basshers'},"{'reviewcount': '2', 'ratingvalue': '4.5'}",HOODIE
2,Googan Sunrise Patch Hat,"{'sku': 'GS-SUNRISE-PATCH-HAT-ODC', 'pricevali...",{'name': 'Googan Squad'},"{'ratingvalue': '4.8', 'reviewcount': '6'}",Hat
3,OG Beefcake T-shirt,"[{'price': '26.99', 'pricevaliduntil': '2020-1...",{'name': 'Googan Squad'},"{'ratingvalue': '5.0', 'reviewcount': '27'}",TSHIRT
4,Team Googan Freedom X T-shirt,"[{'price': '26.99', 'pricevaliduntil': '2020-1...",{'name': 'Googan Squad'},None,TSHIRT

'Product_fixparts-online.com_September2020.json.gz'

,name,offers,brand,mpn,manufacturer
0,2411038003 Bosch Pre-Stroke Disc,"{'mpn': '2411038003', 'pricecurrency': 'EUR', ...",Bosch,2411038003,Bosch
1,2000102610 Bosch Stop Disc,"{'price': '8.08', 'mpn': '2000102610', 'pricec...",Bosch,2000102610,Bosch
2,1987949676 Bosch Toothed Belt,"{'mpn': '1987949676', 'price': '45.8', 'pricec...",Bosch,1987949676,Bosch
3,1457433795 Bosch Air-Filter Insert,"{'pricevaliduntil': '2020-10-29', 'mpn': '1457...",Bosch,1457433795,Bosch
4,2126610009 Bosch Pulley,"{'price': '72.04', 'pricevaliduntil': '2020-10...",Bosch,2126610009,Bosch

'Product_nanotrun.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review
0,Copper Oxide CuO powder CAS 1317-38-0,"{'price': '0.00', 'availability': 'http://sche...",TRUNNANO,"{'reviewcount': '1', 'ratingvalue': '5'}",TR-CuO,{'description': 'Copper Oxide CuO powder CAS 1...
1,Titanium Nitride TiN Powder CAS 25583-20-4,"{'price': '0.00', 'pricevaliduntil': '2140-08-...",TRUNNANO,"{'reviewcount': '1', 'ratingvalue': '5'}",Tr-TiN,{'name': 'Titanium Nitride TiN Powder CAS 2558...
2,Titanium Silicide TiSi2 Powder CAS 12039-83-7,"{'price': '0.00', 'pricevaliduntil': '2140-08-...",TRUNNANO,"{'reviewcount': '1', 'ratingvalue': '5'}",Tr-TiSi2,{'author': 'Titanium Silicide TiSi2 Powder CAS...
3,Cobalt Nanoparticles Nano Co Powder CAS 7440-48-4,"{'price': '0.00', 'pricevaliduntil': '2140-08-...",TRUNNANO,"{'reviewcount': '1', 'ratingvalue': '5'}",Tr- Co nanoparticles,{'name': 'Cobalt Nanoparticles Nano Co Powder ...
4,Zinc Selenide ZnSe Powder CAS 1315-09-9,"{'price': '0.00', 'availability': 'http://sche...",TRUNNANO,"{'reviewcount': '1', 'ratingvalue': '5'}",TR-ZnSe,{'author': 'Zinc Selenide ZnSe Powder CAS 1315...

'Product_lockpickworld.com_September2020.json.gz'

,name,offers,brand,aggregaterating,weight,gtin12
0,Dangerfield Premium Zip-around Lock Pick Case,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Dangerfield'},"{'ratingvalue': '3.25', 'reviewcount': '4', 'd...",0.1lb,6.959246e+11
1,Dangerfield Replacement Picks - Praxis,[{'itemcondition': 'http://schema.org/NewCondi...,{'name': 'Dangerfield'},{'description': 'Stamped.io Product Reviews Ad...,0.02lb,6.959246e+11
2,Peterson Knife Tool,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Peterson'},{'description': 'Stamped.io Product Reviews Ad...,0.33lb,6.959246e+11
3,LockpickWorld 8 Piece Beginner Lock Pick Set,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'LockpickWorld'},{'description': 'Stamped.io Product Reviews Ad...,0.18lb,6.407468e+11
4,Cylinder Jig and Drill Bit,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Brockhage'},"{'reviewcount': '2', 'description': 'Stamped.i...",0.07lb,6.407468e+11

'Product_cortezcigars.com_September2020.json.gz'

,name,offers,brand,category,releasedate,additionalproperty
0,Panatela San Andres Mexican & Nicaraguan 20ct,"{'pricecurrency': 'USD', 'itemcondition': 'New...",{'name': 'Box of 20 / Bundle of 20'},Yellow Label San Andres,2020-08-18T14:51:55-04:00,None
1,Panetela San Andres Mexican & Nicaraguan Single,"{'pricecurrency': 'USD', 'itemcondition': 'New...",{'name': 'Single'},Single,2020-08-18T14:57:11-04:00,None
2,Sky Blue Navesink Robusto Larga (20 Count) OUT...,"{'pricecurrency': 'USD', 'itemcondition': 'New...",{'name': 'Box of 20 / Bundle of 20'},Sky Blue Navesink,2020-04-29T17:36:52-04:00,"[{'name': 'pa_binder', 'value': 'Nicaragua'}, ..."
3,Gray Label Connecticut & DR Robusto,"{'pricecurrency': 'USD', 'itemcondition': 'New...",{'name': 'Single'},Gray Label Connecticut,2020-04-29T17:35:47-04:00,"[{'value': '5', 'name': 'pa_length'}, {'value'..."
4,Yellow Label San Andres Robusto-OUT OF STOCK,"{'pricecurrency': 'USD', 'itemcondition': 'New...",{'name': 'Single'},Robusto,2020-04-29T17:35:49-04:00,"[{'value': 'Nicaragua &amp; Dominican', 'name'..."

'Product_ecrans-telephone.com_September2020.json.gz'

,name,offers,brand,aggregaterating,review,gtin13
0,Vitre tactile écran LCD pour Huawei Nova 4E no...,"{'pricevaliduntil': '2021-04-14', 'price': '28...",{'name': 'Chronostocks'},"{'bestrating': '5', 'reviewcount': '1', 'ratin...","{'datepublished': '2020-08-13', 'name': 'bien'...",3760271272212
1,Ecran LCD vitre tactile pour Meizu MX4 noir,"{'pricevaliduntil': '2021-04-19', 'price': '20...",{'name': 'Chronostocks'},"{'bestrating': '5', 'reviewcount': '1', 'ratin...","{'name': 'nickel', 'author': 'lea', 'datepubli...",3760271270553
2,Ecran LCD vitre tactile pour Huawei P40 Lite n...,"{'pricevaliduntil': '2021-04-15', 'price': '28...",Chronostocks,None,None,3760271272700
3,Ecran LCD vitre pour tactile Nokia 2.3 noir (F...,"{'price': '41.583333', 'pricevaliduntil': '202...",{'name': 'Chronostocks'},"{'bestrating': '5', 'reviewcount': '1', 'ratin...","{'author': 'kym', 'datepublished': '2020-09-03...",3760271272724
4,Ecran LCD vitre tactile pour Blackberry Key2 L...,"{'price': '82.5', 'pricevaliduntil': '2021-04-...",Chronostocks,None,None,3760271272717

'Product_bluesky-filter.com_September2020.json.gz'

,name,offers,brand,category,mpn
0,Orange H11 HEPA Filter for Vorwerk VK135 VK136...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Customized'},"[Vacuum Cleaner Filters, HEPA Filters]",8508709000
1,Universal Race Car Air Filters Compatible with...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Blue Sky'},Automobile Filters,8421230000
2,Vacuum Cleaner Filter for Shark HV390 Replace ...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Blue Sky'},Vacuum Cleaner Filters,8508709000
3,VK120 Dust Filter Paper Bags for Vorwerk Kobol...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Blue Sky'},Vacuum Cleaner Dust Bags,5911900090
4,Replacement Dust Filter Bag for Electrolux Sty...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Blue Sky'},Vacuum Cleaner Dust Bags,5911900090

'Product_capitalgolf.com_September2020.json.gz'

,name,offers,brand,category,gtin13
0,JL NAVY 'Lee' Light jacket WITH Wind Pro - MEN...,"[{'pricevaliduntil': '2020-10-08', 'pricecurre...",{'name': 'J.Lindeberg'},SWEATERS & PULLOVERS,7.310428e+12
1,TRHT CW RANGEWEAR L/S POLO - SS17,"[{'pricecurrency': 'GBP', 'sku': 'CGLADAF05841...",{'name': 'Adidas'},GOLF POLO SHIRTS,NaN
2,CHARCOAL/LIME 'DRY SERIES' GOLF CART BAG,"{'pricevaliduntil': '2020-10-05', 'pricecurren...",{'name': 'Motocaddy'},Bags,5.060149e+12
3,Blue 'Essential' Golf Polo - JUNIOR / SS20,[{'availability': 'https://schema.org/InStock'...,{'name': 'Puma'},GOLF POLO SHIRTS,4.062451e+12
4,YELLOW/PURPLE JASSIRA SKIRT - SS17,"[{'sku': 'CV0YEL001', 'pricevaliduntil': '2020...",{'name': 'Chervò'},Golf Shorts,8.053267e+12

'Product_powerbulbs.com_September2020.json.gz'

,name,offers,brand,aggregaterating,review,gtin13
0,OSRAM Xenarc Night Breaker Laser D1S (Twin),None,None,"{'ratingvalue': '5.0', 'ratingcount': '9'}",None,NaN
1,OSRAM Xenarc Night Breaker Laser D2S (Twin),None,None,"{'ratingvalue': '5.0', 'ratingcount': '17'}",None,NaN
2,OSRAM H27 Standard Replacement Bulb (Single),"{'pricevaliduntil': '2020-09-27', 'availabilit...",{'name': 'OSRAM H27 Standard Replacement Bulb ...,None,None,4.008322e+12
3,Philips H4 Essentials Spare Bulb Kit,"{'pricevaliduntil': '2020-10-01', 'price': '7....",{'name': 'Philips H4 Essentials Spare Bulb Kit'},None,None,8.727901e+12
4,PIAA Hyper Arros 5000K H8 (Twin),"{'pricevaliduntil': '2020-10-01', 'price': '39...",{'name': 'PIAA Hyper Arros 5000K H8 (Twin)'},None,None,4.960311e+12

'Product_highcountrygardens.com_September2020.json.gz'

,name,offers,aggregaterating,category,weight,color
0,Agastache foeniculum,"{'pricecurrency': 'USD', 'itemcondition': 'New...","{'bestrating': '5', 'worstrating': '0', 'revie...",None,"Plant - 5\"" Deep Pot",3397
1,Akebono Double Darwin Tulip,"{'pricecurrency': 'USD', 'itemcondition': 'New...",None,Tulip Flower Bulbs,Bag of 10,3436
2,Golden Fleece Goldenrod (Solidago),"{'pricecurrency': 'USD', 'price': '8.99E0', 'a...","{'bestrating': '5', 'worstrating': '0', 'revie...",None,None,None
3,Kashmir False Sage (Phlomis),"{'pricecurrency': 'USD', 'price': '8.24E0', 'a...","{'bestrating': '5', 'worstrating': '0', 'revie...",None,None,None
4,Red Mountain® Flame Ice Plant,"{'pricecurrency': 'USD', 'price': '6.74E0', 'a...","{'bestrating': '5', 'reviewcount': '10', 'wors...",None,None,None

'Product_1800getlens.com_September2020.json.gz'

,name,offers,brand,aggregaterating,category,review,manufacturer,color,alternatename
0,MK8018 Prescription Eyeglasses,"{'pricecurrency': 'USD', 'price': '98.00', 'av...",None,None,None,None,None,None,None
1,RX7046 Prescription Eyeglasses,"{'pricecurrency': 'USD', 'availability': 'http...",None,None,None,None,None,None,None
2,RX6345 Prescription Eyeglasses,"{'pricecurrency': 'USD', 'price': '168', 'avai...",None,None,None,None,None,None,None
3,MK4026 Prescription Eyeglasses,"{'pricecurrency': 'USD', 'price': '134.99', 'a...",None,None,None,None,None,None,None
4,RX7074 Prescription Eyeglasses,"{'pricecurrency': 'USD', 'availability': 'http...",None,None,None,None,None,None,None

'Product_almgwinnett.com_September2020.json.gz'

,name,offers,brand,mpn,model,manufacturer,color
0,Pre-Owned 2017 Chevrolet Equinox LT FWD Sport ...,"{'price': '15660', 'itemcondition': 'http://sc...",Chevrolet,1LH26,Equinox,{'name': 'Chevrolet'},Mosaic Black Metallic
1,Pre-Owned 2018 Toyota Corolla FWD 4dr Car,{'itemcondition': 'http://schema.org/UsedCondi...,Toyota,5YFBURHE7JP804367,Corolla,{'name': 'Toyota'},None
2,Pre-Owned 2007 Honda CR-V EX-L 4WD,"{'price': '4999', 'itemcondition': 'http://sch...",Honda,RE4877JNW,CR-V,{'name': 'Honda'},None
3,Pre-Owned 2018 Kia Optima LX FWD 4dr Car,{'itemcondition': 'http://schema.org/UsedCondi...,Kia,53222,Optima,{'name': 'Kia'},Sparkling Silver
4,Pre-Owned 2018 Toyota Corolla FWD 4dr Car,"{'price': '12455', 'itemcondition': 'http://sc...",Toyota,2T1BURHE3JC108010,Corolla,{'name': 'Toyota'},None

'Product_placedespop.com_September2020.json.gz'

,name,offers,brand,category,model,releasedate
0,Figurine Funko Pop Suicide Squad [DC] #103 Diablo,"{'highprice': '43.54', 'offercount': '2', 'low...",Funko,Suicide Squad [DC],8362.0,2016
1,Figurine Funko Pop Bienvenue à Schitt's Creek ...,"{'offercount': '4', 'highprice': '18.69', 'low...",Funko,Bienvenue à Schitt's Creek,46932.0,2020
2,Figurine Funko Pop The Walking Dead #387 Rosit...,"{'highprice': '64.89', 'offercount': '2', 'low...",Funko,The Walking Dead,11067.0,2016
3,Figurine Funko Pop Star Wars : Le Mandalorien ...,"{'highprice': '28.95', 'offercount': '3', 'low...",Funko,Star Wars : Le Mandalorien,46091.0,2020
4,Figurine Funko Pop Marvel Comics #594 Vautour,"{'offercount': '9', 'highprice': '17.99', 'low...",Funko,Marvel Comics,46953.0,2019

'Product_culinarydepotinc.com_September2020.json.gz'

,name,offers,brand,mpn,itemcondition
0,Update International KR-1212 Knife Rack,None,Update International,KR-1212,http://schema.org/NewCondition
1,Update International CR-13FK Serving Fork,"{'pricecurrency': 'USD', 'url': 'https://www.c...",Update International,CR-13FK,http://schema.org/NewCondition
2,Advance Tabco SLB-32R-X Special Value 2 Compar...,"{'pricecurrency': 'USD', 'url': 'https://www.c...",Advance Tabco,SLB-32R-X,http://schema.org/NewCondition
3,Carter-Hoffmann EPD4S10 Round Enclosed Plate D...,"{'pricecurrency': 'USD', 'url': 'https://www.c...",Carter-Hoffmann,EPD4S10,http://schema.org/NewCondition
4,Update International SSP-3 SuperSteel Inductio...,"{'pricecurrency': 'USD', 'url': 'https://www.c...",Update International,SSP-3,http://schema.org/NewCondition

'Product_thegreenhousepnw.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review,gtin13
0,Jewel of Desert Topaz Ice Plant,"{'availability': 'https://schema.org/InStock',...",{'name': 'The Greenhouse'},None,40176-3,None,7.662873e+11
1,Blue Arrows Rush,"{'pricevaliduntil': '2021-09-30', 'availabilit...",{'name': 'The Greenhouse'},None,58307A,None,NaN
2,Dwarf Maiden Grass 'Little Kitten',"{'availability': 'https://schema.org/InStock',...",{'name': 'The Greenhouse'},None,30045-3,None,7.662873e+11
3,Azalea 'Hino Crimson',"[{'gtin12': '766287320131', 'availability': 'h...",{'name': 'The Greenhouse'},"{'bestrating': '5', 'reviewcount': '12', 'rati...",50089A,"{'name': 'Azalea &#39;Hino Crimson&#39;', 'dat...",7.662873e+11
4,'Dainty Bess' Hybrid Tea Rose,"{'availability': 'https://schema.org/InStock',...",{'name': 'The Greenhouse'},"{'bestrating': '5', 'ratingvalue': '5.0', 'rev...",50223A,{'name': '&#39;Dainty Bess&#39; Hybrid Tea Ros...,NaN

'Product_wingstuff.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review
0,Deluxe Luggage Rack Bag w/Rain Cover,"{'availability': 'https://schema.org/InStock',...",{'name': 'WingStuff'},"{'reviewcount': '181', 'ratingcount': '181', '...",WSRACKBAG,"[{'description': 'Great bag, well made and lot..."
1,Stormgear Gordito Face Mask,"{'pricevaliduntil': '2020-10-05', 'price': '26...",{'name': 'Schampa'},None,SPVNG004,None
2,EXO-R320 Full-Face Helmet Matte Black,"{'price': '99.99', 'availability': 'https://sc...",{'name': 'Scorpion'},None,PG37948,None
3,CL-Max 3 Modular Helmet Anthracite,"{'availability': 'https://schema.org/InStock',...",{'name': 'HJC'},None,PG37997,None
4,Roadhawk Black Foam Grips w/Chrome End Cap,"{'availability': 'https://schema.org/InStock',...",{'name': 'House Brand'},"{'ratingcount': '9', 'reviewcount': '9', 'rati...",PUDS243210,[{'description': 'I've had mine on for 3 years...

'Product_braecosales.com.au_September2020.json.gz'

,name,offers,breadcrumb
0,MV310 Diaphragm Valve (UPVC/CPVC/PP/PVDF),{'pricecurrency': 'AUD'},Our Products / Brands / Stubbe / MV310 Diaphra...
1,DMV750 Pressure Reducing Valve DN65-80 (UPVC/P...,{'pricecurrency': 'AUD'},Our Products / Brands / Stubbe / DMV750 Pressu...
2,Model HL8SP 316SS Pressure Relief Valve,{'pricecurrency': 'AUD'},Our Products / Valves / Pressure Relief Valve ...
3,Mondeo Idrja 304SS or 316SS Poppet Style Check...,{'pricecurrency': 'AUD'},Our Products / Valves / Check Valves / Mondeo ...
4,Actuated MV310 Diaphragm Valve,{'pricecurrency': 'AUD'},Our Products / Brands / Stubbe / Actuated MV31...

'Product_forsake.com_September2020.json.gz'

,name,offers,aggregaterating,category,review
0,Tract,"{'pricecurrency': 'USD', 'price': '97.95'}","{'bestrating': '5', 'reviewcount': '20', 'rati...",187,"[{'author': 'Janet', 'name': 'Noice!', 'descri..."
1,Loop Gift Card,"{'pricecurrency': 'USD', 'price': '100.0'}",None,166,None
2,Range Low,"{'pricecurrency': 'USD', 'price': '139.95'}","{'bestrating': '5', 'reviewcount': '14', 'rati...",187,"[{'datepublished': '2020-01-03', 'author': 'Ca..."
3,Forsake.com Gift Card,"{'pricecurrency': 'USD', 'price': '25.0'}",None,166,None
4,Snapback Logo Cap,"{'pricecurrency': 'USD', 'price': '24.95'}",None,166,None

'Product_latestbuy.com.au_September2020.json.gz'

,name,offers,brand,aggregaterating,gtin8
0,The Floating Mug,"{'pricecurrency': 'AUD', 'availability': 'http...",Latest Buy,"{'ratingvalue': '4.67', 'reviewcount': '3'}",12132
1,Micro Motorz Stunt Playset,"{'pricecurrency': 'AUD', 'price': '22.95', 'av...",Latest Buy,"{'ratingvalue': '5', 'reviewcount': '10'}",50906
2,Doctor Who Dalek Collector's Watch,"{'pricecurrency': 'AUD', 'availability': 'http...",Doctor Who,"{'ratingvalue': '5', 'reviewcount': '10'}",12159
3,Unicorn and Native Girl Dreamcatcher,"{'pricecurrency': 'AUD', 'availability': 'http...",William Valentine,"{'ratingvalue': '5', 'reviewcount': '10'}",34298
4,Journeyman Designs Stubby Short of a Six Pack ...,"{'pricecurrency': 'AUD', 'availability': 'http...",Journeyman Designs,"{'ratingvalue': '5', 'reviewcount': '10'}",32087

'Product_stanleyschmitzinc.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Frigidaire Gallery 24&#39;&#39; Built-In Dishw...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Frigidaire'},{'itemreviewed': 'Frigidaire Gallery 24&#39;&#...,FGID2476SF
1,Frigidaire Gallery 36&#39;&#39; Electric Cooktop,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Frigidaire'},"{'ratingvalue': '4.5', 'itemreviewed': 'Frigid...",FGEC3648UB
2,Frigidaire Gallery 30&#39;&#39; Freestanding G...,"{'price': '1049.96', 'availability': 'http://s...",{'name': 'Frigidaire'},{'itemreviewed': 'Frigidaire Gallery 30&#39;&#...,GCRG3038AF
3,Frigidaire Gallery 30&#39;&#39; Freestanding G...,"{'pricecurrency': 'USD', 'price': '948.96', 'a...",{'name': 'Frigidaire'},{'itemreviewed': 'Frigidaire Gallery 30&#39;&#...,GCRG3060AF
4,30&#39;&#39; Gas Range,"{'pricecurrency': 'USD', 'price': '674.96', 'a...",{'name': 'Frigidaire'},"{'reviewcount': '249', 'ratingvalue': '4.7', '...",FFGF3054TW

'Product_cpperformance.com_September2020.json.gz'

,name,offers,brand,manufacturer,weight
0,1/4-20 Hex Nut,"{'sku': '152-F0420HN', 'pricecurrency': 'USD',...",American Turbine,"{'name': 'American Turbine', 'url': 'https://w...",0.10 lbs
1,Hand Hole Cover O-Ring,"{'sku': '150-S13734', 'pricecurrency': 'USD', ...",Berkeley Jet Drive,"{'name': 'Berkeley Jet Drive', 'url': 'https:/...",0.10 lbs
2,SCREW Mercruiser 10-805400,"{'pricecurrency': 'USD', 'price': '1.3000'}",None,{'url': 'https://www.cpperformance.com/m-84-me...,0.02 lbs
3,CLAMP Mercruiser 54-815504224,"{'pricecurrency': 'USD', 'price': '4.0000'}",None,{'url': 'https://www.cpperformance.com/m-84-me...,0.06 lbs
4,Impeller Key,"{'price': '8.9900', 'url': 'https://www.cpperf...",American Turbine,"{'name': 'American Turbine', 'url': 'https://w...",0.10 lbs

'Product_mississaugahardware.com_September2020.json.gz'

,name,offers,brand,mpn,model
0,Milwaukee 49-16-2564 Protective Boot for R.A I...,"{'pricecurrency': 'CAD', 'category': 'Power To...",Milwaukee,49-16-2564,49-16-2564
1,Milwaukee 2475-20 M12™ Compact Inflator,"{'pricecurrency': 'CAD', 'mpn': '2475-20', 'ca...",Milwaukee,2475-20,2475-20
2,Milwaukee 48-59-2002 REDLITHIUM USB Charger,"{'price': '32.99', 'mpn': '48-59-2002', 'price...",Milwaukee,48-59-2002,48-59-2002
3,Milwaukee 48-35-1111 Responsive Laser Alignmen...,"{'price': '16.99', 'category': 'Power Tools \\...",Milwaukee,48-35-1111,48-35-1111
4,Milwaukee 48-35-1311 360 Laser Bracket,"{'mpn': '48-35-1311', 'category': 'Power Tools...",Milwaukee,48-35-1311,48-35-1311

'Product_blackparrotmaine.com_September2020.json.gz'

,name,offers,brand,itemcondition,gtin13
0,Maria La Rosa Leggings,"{'price': '88.00', 'availability': 'https://sc...",Maria La Rosa,https://schema.org/NewCondition,2.289700e+04
1,Culinary Intelligence: The Art of Eating Healt...,"{'availability': 'https://schema.org/InStock',...",None,https://schema.org/NewCondition,9.780308e+12
2,Hansel From Basel Geometric Socks,"{'availability': 'https://schema.org/InStock',...",Hansel From Basel,https://schema.org/NewCondition,7.429000e+03
3,Redecker 5 Piece Cleaning Brush Set,"{'validfrom': '2020-09-28', 'url': 'https://ww...",Redecker,https://schema.org/NewCondition,4.037892e+12
4,Modern North by Julie Decker,{'url': 'https://www.blackparrotmaine.com/mode...,None,https://schema.org/NewCondition,9.781569e+12

'Product_mercymotorsllc.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,2010 FORD TAURUS LIMITED,"{'availability': 'https://schema.org/InStock',...",{'name': 'FORD'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",1FAHP2FW7AG137893
1,2009 FORD TAURUS SEL,"{'availability': 'https://schema.org/InStock',...",{'name': 'FORD'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",1FAHP24W89G107512
2,2015 Hyundai GENESIS 3.8L,"{'availability': 'https://schema.org/InStock',...",{'name': 'Hyundai'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",KMHGN4JE9FU065329
3,2017 LINCOLN CONTINENTAL PREMIERE,"{'availability': 'https://schema.org/InStock',...",{'name': 'LINCOLN'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",1LN6L9HK9H5618939
4,2011 KIA SORENTO EX,"{'availability': 'https://schema.org/InStock',...",{'name': 'KIA'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",5XYKUCA18BG150456

'Product_gushgush.com_September2020.json.gz'

,name,offers,brand,aggregaterating,category,mpn,itemcondition
0,Knitting Sweater and Pants Tassel Pullovers,"{'price': '70.0', 'pricecurrency': 'USD'}",None,None,None,NaN,None
1,Long Jacket Cartoon Outwear Loose,"{'pricecurrency': 'USD', 'price': '59.0'}",None,None,None,NaN,None
2,Classic Vintage School Casual Street College N...,"{'pricecurrency': 'USD', 'price': '25.0'}",None,None,None,NaN,None
3,Mesh Hollow Long Sleeve Hooded Shirt,[{'availability': 'https://schema.org/InStock'...,{'name': 'GushGush'},"{'bestrating': '5', 'ratingvalue': '5', 'ratin...",Women Hoodies & Sweatshirts,1.738640e+12,https://schema.org/NewCondition
4,New Pattern Fashion Doodle Easy Leisure Time P...,"{'availability': 'https://schema.org/InStock',...",{'name': 'GushGush'},"{'bestrating': '5', 'ratingcount': '46', 'rati...",Women Pants,2.225098e+11,https://schema.org/NewCondition

'Product_mundofantasma.com_September2020.json.gz'

,name,offers,brand,category,itemcondition
0,X-Men 272 2012,"{'price': '3.85', 'availability': 'http://sche...",{'name': 'Marvel'},Comics,http://schema.org/NewCondition
1,Ultimate Fantastic Four 34 2006,"{'price': '3.85', 'availability': 'http://sche...",{'name': 'Marvel'},Comics,http://schema.org/NewCondition
2,Amazing Spider-Man 372 1993,"{'price': '6.25', 'availability': 'http://sche...",{'name': 'Marvel'},Comics,http://schema.org/NewCondition
3,Batman 438 1989,"{'price': '5.63', 'availability': 'http://sche...",{'name': 'DC'},Comics,http://schema.org/NewCondition
4,Alpha Flight 62 1988,"{'availability': 'http://schema.org/InStock', ...",{'name': 'Marvel'},Comics,http://schema.org/NewCondition

'Product_furnitalia.com_September2020.json.gz'

,name,offers,brand,category,releasedate,width,height,depth
0,Elite Modern Atlas Accent Table,"{'pricecurrency': 'USD', 'price': '599.00', 'i...",{'name': 'Elite Modern'},Occasional > All Tables,2020-04-02T19:03:30-07:00,"{'unitcode': 'INH', 'value': '22'}","{'unitcode': 'INH', 'value': '21.5'}","{'unitcode': 'INH', 'value': '28'}"
1,Alf Italia MONT NOIR 2 Door Curio,"{'pricecurrency': 'USD', 'price': '1499.00', '...",{'name': 'Alf Italia'},Uncategorized,2020-03-24T03:16:00-07:00,"{'value': '23', 'unitcode': 'INH'}","{'unitcode': 'INH', 'value': '39'}","{'unitcode': 'INH', 'value': '22'}"
2,Natuzzi Italia Piuma Bed King,"{'pricecurrency': 'USD', 'price': '5219.00', '...",{'name': 'Natuzzi Italia'},Bedroom > Beds / Sets,2020-03-27T19:26:53-07:00,"{'unitcode': 'INH', 'value': '91'}","{'unitcode': 'INH', 'value': '37'}","{'unitcode': 'INH', 'value': '97'}"
3,Alf Italia TIVOLI CK Storage Bed Platform,"{'pricecurrency': 'USD', 'price': '1499.00', '...",{'name': 'Alf Italia'},Bedroom > Beds / Sets,2020-03-24T03:15:24-07:00,"{'unitcode': 'INH', 'value': '92'}","{'unitcode': 'INH', 'value': '49'}","{'unitcode': 'INH', 'value': '81'}"
4,Mobican Sonoma Wide CK Bed,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Mobican'},Bedroom,2020-04-02T19:04:30-07:00,"{'unitcode': 'INH', 'value': '93.5'}","{'unitcode': 'INH', 'value': '36'}","{'value': '132.75', 'unitcode': 'INH'}"

'Product_cotshirt.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review
0,Free Kyle Rittenhouse T Shirt,"{'availability': 'instock', 'highprice': '2.39...",{'name': 'Cotshirt'},"{'reviewcount': '1', 'ratingvalue': '5'}",1455,"{'datepublished': '2020-08-30T08:41:06+00:00',..."
1,Arrest the cops who killed breonna taylor t shirt,"{'availability': 'instock', 'highprice': '2.49...",{'name': 'Cotshirt'},"{'reviewcount': '1', 'ratingvalue': '5'}",3265,{'description': 'Lewis Hamilton is fighting fo...
2,2020 Would Not Recommend Tee Shirt,"{'availability': 'instock', 'highprice': '2.39...",{'name': 'Cotshirt'},"{'reviewcount': '1', 'ratingvalue': '5'}",504,"{'author': 'cotshirt', 'description': '2020 Wo..."
3,Vote In ASL US Elections 2020 Shirt,"{'availability': 'instock', 'highprice': '2.39...",{'name': 'Cotshirt'},"{'reviewcount': '1', 'ratingvalue': '5'}",1070,{'description': 'We have to vote in the upcomi...
4,Funny Quarantine Halloween Pumpkin 2020 Shirt,"{'availability': 'instock', 'highprice': '2.49...",{'name': 'Cotshirt'},"{'reviewcount': '8', 'ratingvalue': '5.00'}",2000,"[{'datepublished': '2020-08-28 15:30:00', 'aut..."

'Product_vinpet.com.vn_September2020.json.gz'

,name,offers,category,releasedate,isrelatedto
0,HƯỚNG DẪN CHÓ MÈO ĐI VỆ SINH ĐÚNG CHỖ,"{'price': '45000', 'pricecurrency': 'VND', 'it...",Phụ Kiện Thú Cưng > Phụ Kiện Cho Chó,2018-08-14T04:38:40+00:00,"[{'name': 'BÁT ĂN CHỐNG KIẾN CHO CHÓ MÈO'}, {'..."
1,SMARTHEART PUPY POWER PACK 3KG,"{'price': '220000', 'pricecurrency': 'VND', 'i...",Thức Ăn Thú Cưng > Thức Ăn Cho Chó,2018-09-13T08:52:01+00:00,[{'name': 'SMARTHEART SMALL BREED 400GR &#8211...
2,THỨC ĂN CHO CHÓ CON MORANDO PUPY,"{'price': '80000', 'pricecurrency': 'VND', 'it...",Thức Ăn Thú Cưng > Thức Ăn Cho Chó,2018-10-12T10:18:02+00:00,"[{'name': 'BÁNH SNACK SMARTHEART CHO CHÓ'}, {'..."
3,BÁT ĐỰNG THỨC ĂN CHO CHÓ - MÈO,"{'pricecurrency': 'VND', 'price': '20000', 'it...",Phụ Kiện Thú Cưng > Phụ Kiện Cho Chó,2018-08-13T11:13:05+00:00,"[{'name': 'KHAY ĐỰNG CÁT VỆ SINH CHO MÈO'}, {'..."
4,THỨC ĂN HẠT KHÔ CHO MÈO BLISK 1.5KG,"{'price': '95000', 'pricecurrency': 'VND', 'it...",Thức Ăn Thú Cưng > Thức Ăn Cho Mèo,2018-08-31T16:39:21+00:00,[{'name': 'THỨC ĂN MÈO TRƯỞNG THÀNH O’FRESH ST...

'Product_uicflames.com_September2020.json.gz'

,name,offers,brand,category,itemcondition
0,Women's Scarlet UIC Flames Proud Mascot Pullov...,"{'availability': 'http://schema.org/InStock', ...",Fanatics Branded,Sweatshirts &gt; Hoodies,http://schema.org/NewCondition
1,Women's Navy UIC Flames Team Strong Long Sleev...,"{'availability': 'http://schema.org/InStock', ...",Fanatics Branded,T-Shirts &gt; Long Sleeve,http://schema.org/NewCondition
2,Men's Navy UIC Flames Big & Tall Classic Prima...,"{'category': 'T-Shirts &gt; Short Sleeve', 'av...",Fanatics Branded,T-Shirts &gt; Short Sleeve,http://schema.org/NewCondition
3,Women's Navy UIC Flames Personalized Basketbal...,"{'availability': 'http://schema.org/InStock', ...",None,None,http://schema.org/NewCondition
4,Men's Navy UIC Flames Personalized Basketball ...,"{'serialnumber': '2432525', 'availability': 'h...",None,None,http://schema.org/NewCondition

'Product_takaski.com_September2020.json.gz'

,name,offers,brand,manufacturer,mainentityofpage
0,KAO Biore Nose Cleansing Blackheads Pore Strip...,"{'pricecurrency': 'USD', 'price': '9.90', 'ava...",{'name': 'Biore'},{'name': 'Biore'},"{'inlanguage': 'en-US', 'name': 'KAO Biore Nos..."
1,MANDOM Lucido Hair Wax Moist & Hard 80g - Made...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'hair wax'},{'name': 'hair wax'},{'description': 'MANDOM Lucido Hair Wax Moist ...
2,DHC Nano-Active Collagen 50ml x 10pcs - Made i...,"{'pricecurrency': 'USD', 'price': '62.50', 'av...",{'name': 'collagen'},{'name': 'collagen'},"{'datemodified': '2020-03-28T22:30:09+00:00', ..."
3,WAKODO Mirufuwa Baby Milky Lotion - 150ml,"{'pricecurrency': 'USD', 'price': '15.00', 'av...",{'name': 'Baby'},{'name': 'Baby'},"{'inlanguage': 'en-US', 'datepublished': '2016..."
4,FUJIYA Nectar Peach Can 380ml - Made in Japan,"{'pricecurrency': 'USD', 'price': '11.80', 'av...",{'name': 'Fujiya'},{'name': 'Fujiya'},{'name': 'FUJIYA Nectar Peach Can 380ml - Made...

'Product_tynansvolkswagen.com_September2020.json.gz'

,name,offers,brand,mpn,identifier
0,Base Carrier Bar Strip - Spare Part - Black Th...,"{'pricevaliduntil': '10/30/2020 2:04:04 PM', '...",Volkswagen,000071727B,{'value': '000071727B'}
1,Base Carrier Bar Strip - Spare Part - Black Th...,{'itemcondition': 'http://schema.org/NewCondit...,Volkswagen,000071727B,{'value': '000071727B'}
2,Alloy Wheel Center Cap,"{'category': 'Wheels > Misc - Wheels', 'url': ...",Volkswagen,3B7601171XRW,{'value': '3B7601171XRW'}
3,Base Carrier Bar Strip - Spare Part - Black Th...,"{'pricevaliduntil': '10/30/2020 3:31:50 PM', '...",Volkswagen,000071727B,{'value': '000071727B'}
4,Side Window Deflectors - Rear (4 door),{'category': 'Comfort and Protection > Air Def...,Volkswagen,1K9072194HU3,{'value': '1K9072194HU3'}

'Product_balkanenergy.net_September2020.json.gz'

,name,offers,brand,weight,releasedate
0,Burner pot for CLAM,"[{'highprice': '205.00', 'lowprice': '205.00',...",None,"{'maxvalue': '200', 'minvalue': '200', 'unitco...",2019-12-10T08:55:30+00:00
1,"Spare filter for ash vacuum cleaner Ribitech, ...","[{'lowprice': '6.00', 'highprice': '6.00', 'of...",None,"{'maxvalue': '100', 'unitcode': 'KGM', 'minval...",2019-12-10T08:50:42+00:00
2,"Rinseable fine filter Honeywell, MiniPlus FF06","[{'sku': '0000007260', 'pricecurrency': 'EUR',...",None,"{'minvalue': '500', 'unitcode': 'KGM', 'maxval...",2019-12-10T08:51:22+00:00
3,"Mateu 60 cm giant flexible hose 1 1/4\""F x 1 1...","[{'lowprice': '17.85', 'highprice': '17.85', '...",None,"{'maxvalue': '100', 'unitcode': 'KGM', 'minval...",2019-12-10T08:53:07+00:00
4,Burner pot BRA_136X92,"[{'sku': '0000007228', 'price': '51.00', 'name...",None,"{'minvalue': '1500', 'maxvalue': '1500', 'unit...",2019-12-10T08:56:08+00:00

'Product_acerobotasloja.com.br_September2020.json.gz'

,name,offers,brand,aggregaterating,itemcondition,weight,width,height,depth
0,Bota Acero Couro Colt Padrão Policia Militar SP,"{'pricecurrency': 'BRL', 'availability': 'http...",{'name': 'Acero Botas'},"{'ratingcount': '1', 'bestrating': '5', 'ratin...",https://schema.org/NewCondition,2000 g,42.0 cm,12.0 cm,35.0 cm
1,Bota Militar Acero Couro Tiger Marrom,"{'pricecurrency': 'BRL', 'price': '209.00', 'a...",{'name': 'Acero Botas'},"{'ratingcount': '1', 'bestrating': '5', 'ratin...",https://schema.org/NewCondition,2000 g,35.0 cm,12.0 cm,42.0 cm
2,Bota Militar Acero Couro Tiger Extra Brilho Preto,"{'pricecurrency': 'BRL', 'price': '209.00', 'a...",{'name': 'Acero Botas'},"{'bestrating': '5', 'ratingvalue': '5.0', 'wor...",https://schema.org/NewCondition,1600 g,42.0 cm,12.0 cm,35.0 cm
3,Bota Militar Acero Couro Atack Preto,"{'price': '189.91', 'pricecurrency': 'BRL', 'a...",{'name': 'Acero Botas'},"{'bestrating': '4', 'ratingcount': '1', 'worst...",https://schema.org/NewCondition,1600 g,42.0 cm,12.0 cm,35.0 cm
4,Bota Acero Bombeiro Elite Preto,"{'price': '304.00', 'pricecurrency': 'BRL', 'a...",{'name': 'Acero Botas'},None,https://schema.org/NewCondition,2000 g,42.0 cm,12.0 cm,35.0 cm

'Product_naughtypossessions.co.uk_September2020.json.gz'

,name,offers,brand,aggregaterating,review,gtin8
0,"[Lurex spandex top and panty, Size: Small]","{'pricecurrency': 'pound', 'url': 'https://www...",8157122054,"{'ratingvalue': '100', 'worstrating': '0', 'ra...","{'datepublished': '2020-01-01', 'author': 'Ell...",12
1,"[Knee-Length Petticoat, Size: Small]","{'pricecurrency': 'pound', 'url': 'https://www...",8304322176,"{'ratingvalue': '100', 'worstrating': '0', 'ra...","{'datepublished': '2020-01-01', 'author': 'Ell...",12
2,"[Deputy Patdown, Size: Large]","{'pricecurrency': 'pound', 'url': 'https://www...",8519203069,"{'ratingvalue': '100', 'worstrating': '0', 'ra...","{'datepublished': '2020-01-01', 'author': 'Ell...",12
3,"[Size: Small And Medium, Sultry Swat Officer]","{'pricecurrency': 'pound', 'url': 'https://www...",8385006001,"{'ratingvalue': '100', 'worstrating': '0', 'ra...","{'datepublished': '2020-01-01', 'author': 'Ell...",12
4,"[SWAT Bombshell, Size: Large]","{'pricecurrency': 'pound', 'url': 'https://www...",8516803001,"{'ratingvalue': '100', 'worstrating': '0', 'ra...","{'datepublished': '2020-01-01', 'author': 'Ell...",12

'Product_royalqueenseeds.com_September2020.json.gz'

,name,offers,brand,aggregaterating,category,review,gtin8
0,CBD Hemp Seed Oil 10%,"{'price': '57.50', 'pricecurrency': 'EUR', 'it...",Royal Queen Seeds,"{'bestrating': '5', 'ratingcount': '5', 'ratin...",CBD oil,None,8.435524e+12
1,RQS Organic Hoodie,"{'highprice': '45.00', 'pricecurrency': 'EUR',...",Royal Queen Seeds,"{'bestrating': '5', 'reviewcount': '11', 'rati...",Merchandise,"[{'author': 'T D', 'itemreviewed': 'RQS Organi...",8.435524e+12
2,Sour Diesel,"{'offercount': '4', 'highprice': '23.00', 'low...",Royal Queen Seeds,"{'bestrating': '5', 'reviewcount': '121', 'rat...",Feminized cannabis seeds,"[{'author': 'C K', 'reviewbody': 'super einfac...",8.435524e+12
3,Diesel Automatic T-shirt Limited Edition,{'url': 'https://www.royalqueenseeds.com/merch...,Royal Queen Seeds,"{'bestrating': '5', 'reviewcount': '2', 'ratin...",Merchandise,"[{'author': 'I A', 'itemreviewed': 'Diesel Aut...",NaN
4,Royal Haze Automatic,"{'price': '8.50', 'itemcondition': 'new', 'pri...",Royal Queen Seeds,"{'bestrating': '5', 'ratingcount': '544', 'rev...",Autoflowering cannabis seeds,"[{'datepublished': '2020-05-25', 'itemreviewed...",8.435524e+12

'Product_welovebags.co.uk_September2020.json.gz'

,name,offers,brand,category,releasedate,additionalproperty,color
0,Katana - Bag 36117,"{'itemcondition': 'NewCondition', 'availabilit...",{'name': 'Katana'},Mens Bags,2019-08-28T05:37:38+00:00,"[{'value': 'Katana', 'name': 'pa_brand'}, {'na...","Black, Brown, chocolate"
1,Leather pouch black leather zipped bag big lea...,"{'price': '115.00', 'availability': 'https://s...",{'name': 'ItalianHandbags'},Handmade Bags,2019-08-28T02:56:32+00:00,"[{'name': 'pa_department', 'value': 'unisex-ad...",Black
2,"Changnoi Boho Wallet, Purse for Women with Red...","{'price': '39.00', 'availability': 'https://sc...",{'name': 'Changnoi'},Handmade Bags,2019-08-28T06:58:29+00:00,"[{'name': 'pa_department', 'value': 'Women's'}...",Red
3,Kisschic Pleated Rhinestones-Studded Satin Bri...,"{'availability': 'https://schema.org/InStock',...",{'name': 'Kisschic'},Fashion Bags,2019-08-27T21:48:24+00:00,"[{'value': 'Women', 'name': 'pa_department'}, ...","Black, Blue, Gold, Silver"
4,Handmade Weaving Formal Briefcase For Men Genu...,"{'availability': 'https://schema.org/InStock',...",{'name': 'MERRYHE'},Mens Bags,2019-08-28T05:29:06+00:00,"[{'name': 'pa_part-number', 'value': '623305'}...",Black

'Product_bayometric.com_September2020.json.gz'

,name,offers,brand,category,weight,isrelatedto,additionalproperty,width,height,depth
0,Nitgen eNBioAccess-T1,[{'itemcondition': 'http://schema.org/NewCondi...,None,"[Access Control, Indoor Access Control, Biomet...",{'value': '4'},"[{'name': 'Nitgen eNBioAccess-T5'}, {'name': '...",None,{'value': '8.5'},{'value': '3'},{'value': '8'}
1,IB Watson Mini,[{'itemcondition': 'http://schema.org/NewCondi...,None,"[Bestsellers, Fingerprint Readers, Two Finger,...",{'value': '0.5'},"[{'name': 'Futronic FS81H'}, {'name': 'Cross M...","[{'value': '1', 'name': 'ships-world-wide'}, {...",{'value': '4.5'},{'value': '3'},{'value': '5.5'}
2,Lumidigm M301 (M30x),"{'pricecurrency': 'USD', 'availability': 'http...",Lumidigm,"[Bestsellers, USB Fingerprint Scanners, Finger...",{'value': '0.5'},"[{'name': 'SecuGen SDU04P'}, {'name': 'Lumidig...",[{'value': 'Griaule Fingerprint SDK Lumidigm F...,{'value': '4'},{'value': '2.5'},{'value': '6'}
3,Nitgen UBio-X Slim,"{'pricecurrency': 'USD', 'availability': 'http...",None,"[Access Control, Indoor Access Control, Biomet...",{'value': '4'},"[{'name': 'Nitgen Fingkey Access'}, {'name': '...",None,{'value': '8.5'},{'value': '3'},{'value': '8'}
4,Futronic FS80,"{'pricecurrency': 'USD', 'price': '95', 'itemc...",Futronic,"[Fingerprint Readers, USB Fingerprint Scanners...",{'value': '0.5'},"[{'name': 'Nitgen Fingkey Hamster II'}, {'name...",[{'value': 'Griaule Fingerprint SDK | Futronic...,{'value': '1'},{'value': '1'},{'value': '1'}

'Product_charleslstevensfuneralhome.com_September2020.json.gz'

,name,offers,aggregaterating,review,itemcondition,model
0,Wildflower Seeds - Build A Memory Garden,"{'pricecurrency': 'USD', 'lowprice': '15.95', ...","{'reviewcount': '1', 'ratingvalue': '5.00'}",{'description': 'A unique idea that people usu...,NewCondition,"{'sku': 'WGB', 'image': 'https://res.cloudinar..."
1,Pink Tribute Spray,"{'pricecurrency': 'USD', 'lowprice': '114.95',...","{'reviewcount': '82', 'ratingvalue': '4.95'}",[{'description': 'I purchased this spray for a...,NewCondition,{'image': 'https://res.cloudinary.com/picasso/...
2,Care and Compassion Spray,"{'pricecurrency': 'USD', 'highprice': '184.95'...","{'ratingvalue': '4.89', 'reviewcount': '9'}","[{'author': 'from Oklahoma City - Oklahoma', '...",NewCondition,{'image': 'https://res.cloudinary.com/picasso/...
3,Katie's Diary,"{'pricecurrency': 'USD', 'lowprice': '44.95', ...",None,None,NewCondition,"{'name': 'Katie's Diary (Standard)', 'url': 'h..."
4,Enchanted Cottage,"{'lowprice': '64.95', 'highprice': '94.95', 'p...","{'reviewcount': '62', 'ratingvalue': '4.98'}","[{'datepublished': '6/6/2020', 'author': 'from...",NewCondition,[{'image': 'https://res.cloudinary.com/picasso...

'Product_yourdeal24.com_September2020.json.gz'

,name,offers,brand,category,mpn
0,HOT- 1 x 3D Glasses Clip on for CINEMA AND 3D ...,"{'availability': 'https://schema.org/InStock',...",{'name': 'yourdeal24.com'},Consumer Electronics,8377
1,2020 NEW Fashion Universal type 3D glasses/Red...,{'name': '2020 NEW Fashion Universal type 3D g...,{'name': 'yourdeal24.com'},Consumer Electronics,8381
2,Artificial Green Purple Red Flocking Succulent...,[{'availability': 'https://schema.org/InStock'...,{'name': 'yourdeal24.com'},"Home &amp; Garden, Appliance",8482
3,Factory Unlocked Original For Apple iPhone 5S ...,[{'availability': 'https://schema.org/InStock'...,{'name': 'yourdeal24.com'},Cellphones &amp; Telecommunications,8317
4,Wholesale 10pcs/lot Elegant White Ostrich Feat...,[{'availability': 'https://schema.org/InStock'...,{'name': 'yourdeal24.com'},"Home &amp; Garden, Appliance",8437

'Product_kinghandlighting.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review
0,Round Mounting Base,"{'price': '0.00', 'pricevaliduntil': '2140-08-...",www.kinghandlighting.com,"{'reviewcount': '1', 'ratingvalue': '5'}",KA0010B,"{'datepublished': '2020-09-20', 'name': 'Round..."
1,Hanging Light,"{'price': '0.00', 'pricevaliduntil': '2140-08-...",www.kinghandlighting.com,"{'reviewcount': '1', 'ratingvalue': '5'}",KN0058B,"{'author': 'Hanging Light', 'datepublished': '..."
2,Deck Light,"{'price': '0.00', 'pricevaliduntil': '2140-08-...",www.kinghandlighting.com,"{'reviewcount': '1', 'ratingvalue': '5'}",KKH5003B,"{'author': 'Deck Light', 'datepublished': '202..."
3,Binding Post,"{'price': '0.00', 'pricevaliduntil': '2140-08-...",www.kinghandlighting.com,"{'reviewcount': '1', 'ratingvalue': '5'}",KA0015B,"{'name': 'Binding Post', 'datepublished': '202..."
4,Deck Light,"{'price': '0.00', 'pricevaliduntil': '2140-08-...",www.kinghandlighting.com,"{'reviewcount': '1', 'ratingvalue': '5'}",KKH5002B,"{'author': 'Deck Light', 'datepublished': '202..."

'Product_uomocollezioni.com_September2020.json.gz'

,name,offers,price,shop-currency
0,Moreschi Black Embossed Calfskin Casual Slip Ons,Moreschi Black Embossed Calfskin Casual Slip O...,$850.00,SGD
1,Uomo Collezioni Black Tucano Shoehorn,Uomo Collezioni Black Tucano Shoehorn Uomo Col...,$550.00,SGD
2,Tecknomonster Black A4 Document Holder,Tecknomonster Black A4 Document Holder Tecknom...,$900.00,SGD
3,Uomo Collezioni Labrador Cane,Uomo Collezioni Labrador Cane Uomo Collezioni ...,$450.00,SGD
4,Tecknomonster Black Akille Scorpion Trolley,Tecknomonster Black Akille Scorpion Trolley Te...,"$2,850.00",SGD

'Product_bluelightful.com_September2020.json.gz'

,name,offers,brand,aggregaterating,category,mpn,review
0,Flexible Black USB LED Desk Lamp with 5X Magni...,"{'availability': 'https://schema.org/InStock',...",{'name': 'bluelightful.com'},None,Lamps,4877,None
1,Flexible Retro Bedroom Wall Lamp,"{'availability': 'https://schema.org/InStock',...",{'name': 'bluelightful.com'},None,Lamps,4592,None
2,Wi-Fi Smart LED Lamp with Voice Control,[{'name': 'Wi-Fi Smart LED Lamp with Voice Con...,{'name': 'bluelightful.com'},"{'ratingvalue': '4.7E0', 'reviewcount': '12'}",Smart Home,1296,[{'reviewbody': 'Fast and free shipping. Thank...
3,Post Modern Chandelier for Living Room,[{'availability': 'https://schema.org/InStock'...,{'name': 'bluelightful.com'},None,Lamps,5931,None
4,Multifunction Wire Stripping Pliers,"[{'pricevaliduntil': '2020-10-22', 'availabili...",{'name': 'bluelightful.com'},"{'reviewcount': '20', 'ratingvalue': '4.7E0'}",Electrical Instruments,4029,[{'reviewbody': 'Actually that's a good price ...

'Product_shoplovestitch.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Quinn Chenille Cable Knit Sweater,[{'availability': 'https://schema.org/InStock'...,{'name': 'Lovestitch'},"{'ratingvalue': '5.0E0', 'ratingcount': '5'}",I-50764K-QPB-Burgundy-Small ~ 2030 L-E
1,Theo Tie Dye Hoodie,[{'availability': 'https://schema.org/InStock'...,{'name': 'Lovestitch'},"{'ratingvalue': '5.0E0', 'ratingcount': '1'}",I-11447K-PHG-AF-Burgundy/Rose/Spice- Small ~ S...
2,Rania Foil Chiffon Dress,[{'availability': 'https://schema.org/InStock'...,{'name': 'Lovestitch'},None,I-71679WL-QTZ-HL-Wine/Gold-Small ~ 16-1-1
3,Deisy Floral Wrap Dress,[{'availability': 'https://schema.org/InStock'...,{'name': 'Lovestitch'},None,I-71445W-QNG-RC-Saddle-Small ~ Sec D 2-2-3
4,Giselle Striped Lace Trim Cami,[{'availability': 'https://schema.org/InStock'...,{'name': 'Lovestitch'},"{'ratingvalue': '5.0E0', 'ratingcount': '4'}",I-11931W-QFT-2 -Black-Small ~ 20-3-1

'Product_kolaypazar.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Schık Kadın Bileklik Lacivert Sck72,"{'availability': 'http://schema.org/SoldOut', ...",{'name': 'Pianoluce'},"{'reviewcount': '1', 'ratingvalue': '4'}",895
1,Schık Kadın Bileklik Siyah Sck56,"{'availability': 'http://schema.org/SoldOut', ...",{'name': 'Pianoluce'},"{'reviewcount': '1', 'ratingvalue': '4'}",926
2,Schık Kadın Bileklik Siyah Sck90,"{'price': '29.99', 'availability': 'http://sch...",{'name': 'Pianoluce'},"{'reviewcount': '1', 'ratingvalue': '5'}",947
3,Schık Kadın Bileklik Gri Sck76,"{'availability': 'http://schema.org/SoldOut', ...",{'name': 'Pianoluce'},"{'reviewcount': '1', 'ratingvalue': '4'}",849
4,Lir Kadın Elbise Gülkurusu 1300,"{'pricecurrency': 'TRY', 'availability': 'http...",{'name': 'Pianoluce'},"{'reviewcount': '1', 'ratingvalue': '4'}",403

'Product_outletonweb.com_September2020.json.gz'

,name,offers,brand,mpn,itemcondition
0,Abito Attic And Barn,"{'price': '110.00', 'itemcondition': 'https://...",ATTIC AND BARN,ADBADODNAC2ST0462529/12,https://schema.org/NewCondition
1,Abito Ralph Lauren,{'itemcondition': 'https://schema.org/NewCondi...,RALPH LAUREN,RALADODNAC2ST0456001/01,https://schema.org/NewCondition
2,Impermeabile Positive Travels,{'itemcondition': 'https://schema.org/NewCondi...,POSITIVE TRAVELS,CORVARACNT201/999,https://schema.org/NewCondition
3,Sneakers EA7,{'itemcondition': 'https://schema.org/NewCondi...,EA7,X8X012XK056/K001,https://schema.org/NewCondition
4,Abito Max Mara,{'itemcondition': 'https://schema.org/NewCondi...,MAX MARA,MAMADODNAC2ST0439349/05,https://schema.org/NewCondition

'Product_autosalesandserviceinc.com_September2020.json.gz'

,name,offers,brand,model,manufacturer,releasedate,color
0,2012 Ford Fiesta SE,None,Ford,Fiesta,Ford,2012,Oxford White
1,1976 Chevrolet Chevette,{'image': 'http://cdn-ds.com/stock/1976-Chevro...,Chevrolet,Chevette,Chevrolet,1976,Beige
2,2011 Dodge Grand Caravan Crew,None,Dodge,Grand Caravan,Dodge,2011,Stone White Clear Coat
3,2006 Mazda Mazda6 I Sports Sedan,None,Mazda,Mazda6,Mazda,2006,Tungsten Gray
4,2013 Ford Explorer XLT,"{'name': '2013 Ford Explorer XLT', 'image': 'h...",Ford,Explorer,Ford,2013,Kodiak Brown Metallic

'Product_overtide.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,jumper shorts for girls,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",jumper shorts for girls,"{'ratingvalue': '4.2', 'reviewcount': '29'}",921
1,mens cargo shorts elastic waist,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",mens cargo shorts elastic waist,"{'ratingvalue': '4.1', 'reviewcount': '19'}",916
2,high waisted rolled shorts,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",high waisted rolled shorts,"{'ratingvalue': '4.1', 'reviewcount': '19'}",919
3,columbia rocky horror shorts,"{'pricecurrency': 'USD', 'price': '38.99', 'pr...",columbia rocky horror shorts,"{'ratingvalue': '4.2', 'reviewcount': '29'}",92
4,black glitter shorts,"{'pricecurrency': 'USD', 'url': 'https://www.o...",black glitter shorts,"{'reviewcount': '11', 'ratingvalue': '4.1'}",1013

'Product_leatherjacket4.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review
0,Mens-Bomber,"{'pricecurrency': 'USD', 'url': 'https://www.l...","[Leather Jacket 4, LeatherJacket4]","{'bestrating': '5', 'ratingvalue': '5.0', 'nam...",LJ4-322,"{'name': 'Leather Jacket', 'reviewbody': 'Grea..."
1,Blazer-Men,"{'pricecurrency': 'USD', 'price': '95', 'price...","[Leather Jacket 4, LeatherJacket4]","{'bestrating': '5', 'ratingvalue': '5.0', 'nam...",LJ4-335,"[{'reviewbody': 'Very nice customer support, I..."
2,Black-Racer,"{'pricecurrency': 'USD', 'url': 'https://www.l...","[Leather Jacket 4, LeatherJacket4]","{'bestrating': '5', 'ratingvalue': '5.0', 'rat...",LJ4-318,"[{'name': 'Leather Jacket', 'reviewbody': 'Gre..."
3,Brad-Black,"{'pricecurrency': 'USD', 'url': 'https://www.l...","[Leather Jacket 4, LeatherJacket4]","{'bestrating': '5', 'ratingcount': '214', 'nam...",LJ4-81,"[{'name': 'Leather Jacket', 'reviewbody': 'It ..."
4,Blouson,"{'pricecurrency': 'USD', 'price': '145', 'url'...","[Leather Jacket 4, LeatherJacket4]","{'bestrating': '5', 'ratingcount': '111', 'nam...",LJ4-345,"[{'name': 'Leather Jacket', 'reviewbody': 'I h..."

'Product_pushys.com.au_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Topeak Sidekick STW Wedge Pack w/17 Pce Toolkit,{'url': 'https://www.pushys.com.au/topeak-side...,Topeak,"{'ratingvalue': '0', 'reviewcount': '0', 'best...",TC2275B
1,Crank Brothers Mallet E Enduro Race Pedals Ele...,"{'price': '249.99', 'url': 'https://www.pushys...",Crank Brothers,"{'ratingvalue': '0', 'reviewcount': '0', 'best...",15991
2,Crank Brothers Stamp 7 Pedals Orange Large,"{'pricevaliduntil': '2020/09/30', 'availabilit...",Crank Brothers,"{'ratingvalue': '0', 'reviewcount': '0', 'best...",16277
3,GU Hydration Drink Tablets Strawberry Lemonade...,"{'pricevaliduntil': '2020/09/24', 'price': '11...",GU,"{'ratingvalue': '0', 'reviewcount': '0', 'best...",123143
4,WTB Horizon Road Plus 27.5x47c (650B) TCS Fold...,"{'pricevaliduntil': '2020/09/21', 'url': 'http...",WTB,"{'ratingvalue': '0', 'reviewcount': '0', 'best...",WT-W010-0640

'Product_farmacias1000.com_September2020.json.gz'

,name,offers,brand,aggregaterating,gtin13
0,Tena Lady Pants Night Talla L 7 Und,"{'price': '9', 'sku': '10400', 'pricevalidunti...",Tena,"{'bestrating': '5', 'reviewcount': '1', 'ratin...",7322540822144
1,Avent Biberón Natural de cristal 240ml,"{'price': '15', 'sku': '15504', 'pricecurrency...",Avent,"{'bestrating': '5', 'reviewcount': '1', 'ratin...",8710103576648
2,Avent Biberón Natural de cristal 240ml,"{'price': '15', 'sku': '15504', 'pricecurrency...",Avent,"{'bestrating': '5', 'reviewcount': '1', 'ratin...",8710103576648
3,Avent Biberón Natural de cristal 240ml,"{'price': '15', 'sku': '15504', 'pricecurrency...",Avent,"{'bestrating': '5', 'reviewcount': '1', 'ratin...",8710103576648
4,Avent Biberón Natural de cristal 240ml,"{'price': '15', 'sku': '15504', 'pricecurrency...",Avent,"{'bestrating': '5', 'reviewcount': '1', 'ratin...",8710103576648

'Product_macpartstore.com_September2020.json.gz'

,name,offers,category,weight,releasedate,width,height,depth
0,"Battery pack - 8-cell lithium-ion (LI-Ion), 2....","{'price': '15.15', 'seller': 'Mac Part Store',...",HP dv9000 8 Cell Battery,14.00 lbs,2018-06-22 10:29:14,0.00 inches,0.00 inches,0.00 inches
1,Matrox Millennium graphics board - Has one VGA...,"{'pricecurrency': 'USD', 'seller': 'Mac Part S...",Compaq Professional 5000 series,14.00 lbs,2018-06-12 09:06:38,0.00 inches,0.00 inches,0.00 inches
2,"iPad mini 3 Logic Board, 16GB, Wi-Fi 820-00008","{'pricecurrency': 'USD', 'availability': 'http...",iPad mini 3 (Wi-Fi Only) MGNR2LL,14.00 lbs,2016-11-16 14:40:26,0.00 inches,0.00 inches,0.00 inches
3,"iPad mini 3 Logic Board, 16GB, Wi-Fi 820-00008","{'pricecurrency': 'USD', 'availability': 'http...",iPad mini 3 (Wi-Fi Only) MGYE2LL,14.00 lbs,2016-11-16 14:40:26,0.00 inches,0.00 inches,0.00 inches
4,"iPad mini 3 Back Case, Wi-Fi, Space Gray","{'price': '15.15', 'seller': 'Mac Part Store',...",iPad mini 3 (Wi-Fi Only) MGP32LL,14.00 lbs,2016-11-16 14:40:26,0.00 inches,0.00 inches,0.00 inches

'Product_officialmemorabilia.com_September2020.json.gz'

,name,brand,mpn,price,pricecurrency,availability,condition
0,Tom Brady Signed Patriots Jersey | Tom Brady S...,OFFICIAL MEMORABILIA,3735EN,2799,AUD,out of stock,new
1,Shaquille O’Neal Signed Jersey | Official Memo...,OFFICIAL MEMORABILIA,3906EN,1495,AUD,in stock,new
2,Giannis Antetokounmpo Signed Milwaukee Bucks J...,OFFICIAL MEMORABILIA,3881EN,1295,AUD,in stock,new
3,Kevin Durant Signed Basketball | Official Memo...,OFFICIAL MEMORABILIA,3747EN,699,AUD,out of stock,new
4,LeBron James Signed LA Lakers Jersey | Officia...,OFFICIAL MEMORABILIA,3873EN,6995,AUD,in stock,new

'Product_vote5shirt.com_September2020.json.gz'

,name,offers,brand,aggregaterating,review
0,Pittsburgh Steelers 87th anniversary 1933 2020...,"{'pricecurrency': 'USD', 'price': '22.99', 'pr...",Vote5shirt,"{'ratingvalue': '5', 'reviewcount': '3'}",[{'reviewbody': 'Will definitely use this comp...
1,The Nightmare Before Christmas Jack Moon shirt,"{'pricecurrency': 'USD', 'price': '22.99', 'pr...",Vote5shirt,"{'ratingvalue': '5', 'reviewcount': '6'}",[{'reviewbody': 'Great printing quality and co...
2,In a world full of princesses be a biker shirt,"{'pricecurrency': 'USD', 'price': '22.99', 'pr...",Vote5shirt,"{'ratingvalue': '5', 'reviewcount': '3'}",[{'datepublished': '2020-09-16T07:24:08+00:00'...
3,Lips Kansas City Chiefs shirt,"{'pricecurrency': 'USD', 'price': '22.99', 'pr...",Vote5shirt,"{'ratingvalue': '5', 'reviewcount': '3'}",[{'reviewbody': 'If you want a Groovy T Shirt ...
4,Fast and Furious Paul Walker Vin Diesel Tyrese...,"{'pricecurrency': 'USD', 'price': '22.99', 'pr...",Vote5shirt,"{'ratingvalue': '5', 'reviewcount': '6'}","[{'reviewbody': 'Great shirt, great printing, ..."

'Product_jimellishyundaiparts.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,identifier
0,"Roof, Cross Bar Set",{'itemcondition': 'http://schema.org/NewCondit...,Hyundai,"{'ratingvalue': '4.8', 'itemreviewed': 'Dealer...",2S021ADU00,{'value': '2S021ADU00'}
1,"Roof, Cross Bar Set",{'itemcondition': 'http://schema.org/NewCondit...,Hyundai,"{'ratingvalue': '4.8', 'itemreviewed': 'Dealer...",2S021ADU00,{'value': '2S021ADU00'}
2,License Plate Frame,{'itemcondition': 'http://schema.org/NewCondit...,Hyundai,"{'ratingvalue': '4.8', 'itemreviewed': 'Dealer...",0040231918,{'value': '0040231918'}
3,Roof Header Panel,"{'price': '69.47', 'itemcondition': 'http://sc...",Hyundai,"{'ratingvalue': '4.8', 'itemreviewed': 'Dealer...",671212S300,{'value': '671212S300'}
4,Roof Luggage Carrier Side Rail,{'itemcondition': 'http://schema.org/NewCondit...,Hyundai,"{'ratingvalue': '4.8', 'itemreviewed': 'Dealer...",872802S000,{'value': '872802S000'}

'Product_getnatty.com_September2020.json.gz'

,name,offers,brand,aggregaterating,category
0,None,"{'availability': 'http://schema.org/InStock', ...",None,"{'ratingvalue': '4.4', 'ratingcount': '89'}",saree
1,Short Kurti Blue,"{'price': '2940', 'availability': 'http://sche...",{'name': 'Short Kurti Blue'},"{'ratingvalue': '4.4', 'ratingcount': '89'}",saree
2,Hand Embroidered Lavender Jumpsuit With Attach...,"{'availability': 'http://schema.org/InStock', ...",{'name': 'Hand Embroidered Lavender Jumpsuit W...,"{'ratingvalue': '4.4', 'ratingcount': '89'}",saree
3,Gold Clematis,"{'availability': 'http://schema.org/InStock', ...",{'name': 'Gold Clematis'},"{'ratingvalue': '4.4', 'ratingcount': '89'}",saree
4,Ode to Polka Dots-DOT PRINT BALCONY BRA,"{'price': '2240', 'availability': 'http://sche...",{'name': 'Ode to Polka Dots-DOT PRINT BALCONY ...,"{'ratingvalue': '4.4', 'ratingcount': '89'}",saree

'Product_metaformtools.com_September2020.json.gz'

,name,offers,breadcrumb
0,Postcard Clip S (the Oranges),"{'pricecurrency': 'USD', 'price': '14'}",Toolshop | Postcard Clip S (the Oranges)
1,Postcard Clip S (the Browns),"{'pricecurrency': 'USD', 'price': '14'}",Toolshop | Postcard Clip S (the Browns)
2,Hook M (the Greens),"{'pricecurrency': 'USD', 'price': '37'}",Toolshop | Hook M (the Greens)
3,Postcard Clip L (the Greens),"{'pricecurrency': 'USD', 'price': '16'}",Toolshop | Postcard Clip L (the Greens)
4,Tape Dispenser (the Reds),"{'pricecurrency': 'USD', 'price': '51'}",Toolshop | Tape Dispenser (the Reds)

'Product_birlikte.com.tr_September2020.json.gz'

,name,offers,brand,category,mpn
0,NİHAYET - EKİM 2019 / SAYI 057,"{'price': '13.00', 'pricevaliduntil': '2020-10...",{'name': 'DERGİ'},Dergiler > Nihayet,9772149036004
1,NİHAYET - HAZİRAN 2020 / SAYI 065,"{'price': '13.00', 'pricevaliduntil': '2020-10...",{'name': 'DERGİ'},Dergiler > Nihayet,9772149036004
2,BİLGE MİNİK- NİSAN 2019 / SAYI 032,"{'availability': 'https://schema.org/InStock',...",{'name': 'DERGİ'},Dergiler > Çocuk Dergileri > Bilge Minik ve Bi...,9772536480007
3,CİNS - OCAK 2019 / SAYI 040,"{'pricevaliduntil': '2020-10-02', 'pricecurren...",{'name': 'DERGİ'},Dergiler > Cins,9772149818006
4,LOKMA - TEMMUZ 2018 / SAYI 044,"{'price': '8.00', 'pricevaliduntil': '2020-10-...",{'name': 'DERGİ'},Dergiler > Lokma,9772148990000

'Product_trollingmotors.net_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Terrova 55,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Minn Kota'},"{'ratingvalue': '4.88421052631579E0', 'reviewc...",1358857
1,Transducer Mounting Kit,"{'pricecurrency': 'USD', 'itemcondition': 'htt...",{'name': 'Minn Kota'},None,1840201
2,X5 80 SW,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'MotorGuide'},"{'reviewcount': '2', 'ratingvalue': '4'}",941400050
3,6 Gauge Marine Battery Cable 25' - Red,"{'pricecurrency': 'USD', 'price': '44.95', 'it...",{'name': 'n/a'},"{'reviewcount': '1', 'ratingvalue': '5'}",31858
4,PowerDrive 54 Pontoon,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Minn Kota'},"{'reviewcount': '18', 'ratingvalue': '4.833333...",1358745

'Product_thefemwear.com_September2020.json.gz'

,name,offers,brand,aggregaterating,category,mpn,review
0,Women’s Anti-Theft Slim Wallet,"{'availability': 'https://schema.org/InStock',...",thefemwear.com,"{'ratingvalue': '4.50', 'reviewcount': '27'}",None,732,None
1,Women’s Business Leather Slim Neck Wallet,"{'availability': 'https://schema.org/InStock',...",thefemwear.com,"{'ratingvalue': '4.50', 'reviewcount': '49'}",None,734,None
2,Hoodies Women 2019 Brand Female Long Sleeve So...,"{'availability': 'https://schema.org/InStock',...",thefemwear.com,"{'ratingvalue': '4.50', 'reviewcount': '108'}",None,838,None
3,CALOFE 2019 Women Hoodies Zipper Girl Autumn L...,"{'availability': 'https://schema.org/InStock',...",thefemwear.com,"{'reviewcount': '17', 'ratingvalue': '4.80'}",None,1764,None
4,XZP 2019 New Fashion Waterproof Portable Makeu...,"{'pricevaliduntil': '2020-10-22', 'availabilit...",thefemwear.com,"{'ratingvalue': '4.80', 'reviewcount': '30'}",None,860,None

'Product_chefbakers.com_September2020.json.gz'

,name,offers,brand,aggregaterating,review,gtin8
0,Mango Magnifique Cake Half Kg,"{'price': '440', 'url': 'https://www.chefbaker...",Chef Bakers,"{'bestrating': '5', 'reviewcount': '21', 'rati...","[{'description': 'Good', 'datepublished': '201...",90.0
1,Premium Duet Swirls Cake Half Kg,{'url': 'https://www.chefbakers.com/bangalore/...,Chef Bakers,"{'bestrating': '5', 'reviewcount': '11', 'rati...","[{'name': 'Premium Duet Swirls Cake Half Kg', ...",1224.0
2,Turkish Nutty Blast Cake Half Kg,"{'price': '600', 'url': 'https://www.chefbaker...",Chef Bakers,"{'bestrating': '5', 'reviewcount': '2', 'ratin...","[{'name': 'Yummy', 'description': 'Yummy cake ...",1308.0
3,Chocolate Cream Gateaux Cake One Kg,"{'price': '825', 'pricevaliduntil': '2020-12-3...",Chef Bakers,"{'bestrating': '5', 'reviewcount': '38', 'wors...","[{'name': 'awsome', 'author': 'Dr. Amritha', '...",63.0
4,Black Forest Cake Half Kg,{'url': 'https://www.chefbakers.com/bangalore/...,Chef Bakers,"{'bestrating': '5', 'worstrating': '1', 'revie...","[{'name': 'Black Forest Cake Half Kg', 'descri...",246.0

'Product_pouceetlina.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review
0,corail and yellow unicorn mobile,"{'price': '57.5', 'pricevaliduntil': '2021-03-...",Pouce et Lina,None,538,None
1,blue and yellow parrot mobile,"{'price': '57.5', 'pricevaliduntil': '2021-03-...",Pouce et Lina,"{'reviewcount': '5', 'ratingvalue': '23', 'bes...",510,"[{'author': 'Olivia C.'}, {'author': 'Laura r...."
2,Music box mechanism The Lion sleeps Tonight,{'url': 'https://www.pouceetlina.com/en/sales/...,Pouce et Lina,None,525,None
3,Nude silver moon and stars mobile,"{'price': '57.5', 'pricevaliduntil': '2021-03-...",Pouce et Lina,"{'ratingvalue': '25', 'reviewcount': '5', 'bes...",341,"[{'author': 'Vanessa T.'}, {'author': 'Delphin..."
4,Purple musical star,"{'price': '24.17', 'pricevaliduntil': '2021-03...",Pouce et Lina,"{'bestrating': '5', 'reviewcount': '1', 'worst...",353,{'author': 'Béatrice B.'}

'Product_staticsolutions.com_September2020.json.gz'

,name,offers,category,weight,width,height,depth
0,Ohm-Stat™ Guardian Plus Constant Monitor,"{'price': '70', 'availability': 'https://schem...","[Monitors, Testers and Monitors]","{'value': '.5', 'unitcode': 'LBR'}","{'unitcode': 'INH', 'value': '4'}","{'unitcode': 'INH', 'value': '4'}","{'unitcode': 'INH', 'value': '8'}"
1,Ohm-Stat™ Earth Ground Checker with Jack to Gr...,"{'pricecurrency': 'USD', 'price': '4.499E1', '...",None,None,None,None,None
2,Ohm-Shield™ &#8211; Floor Cleaner for Ohm-Shie...,"{'pricecurrency': 'USD', 'offercount': '3', 'h...",None,None,None,None,None
3,Wrist Strap: Patented Design In Blue With 4mm ...,"{'pricecurrency': 'USD', 'availability': 'http...",None,None,None,None,None
4,Ohm-Stat™ Calibration Box for Ohm-Stat™ RT-100...,"{'pricecurrency': 'USD', 'price': '285', 'avai...",None,None,None,None,None

'Product_haixusa.com_September2020.json.gz'

,name,offers,brand,aggregaterating,review,releasedate
0,"HAIX Airpower XR2, FS","{'pricecurrency': 'USD', 'price': '229.00', 'i...",HAIX,"{'ratingvalue': '9', 'bestrating': '10', 'wors...","[{'author': 'Robert', 'reviewbody': 'Starting ...",None
1,"HAIX Airpower R2 Womens, FS","{'pricecurrency': 'USD', 'price': '219.00', 'i...",HAIX,None,None,2012-11-01
2,HAIX Airpower P7 High,"{'pricecurrency': 'USD', 'itemcondition': 'htt...",HAIX,"{'bestrating': '10', 'ratingvalue': '7', 'wors...","[{'author': 'Ann Marie Graham', 'reviewbody': ...",None
3,HAIX GSG9-S,"{'pricecurrency': 'USD', 'itemcondition': 'htt...",HAIX,"{'bestrating': '10', 'ratingvalue': '10', 'wor...","[{'datepublished': '2018-05-15', 'name': 'Grea...",2012-11-18
4,"HAIX Protector Ultra Lime Green, FS","{'pricecurrency': 'USD', 'itemcondition': 'htt...",HAIX,"{'bestrating': '10', 'ratingcount': '2', 'wors...","[{'author': 'Arborist707', 'datepublished': '2...",2017-10-06