In [2]:
# import libraries
import os
import pandas as pd
import json
import gzip
import fasttext 
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [34]:
path = '../../src/data/schemafiltereddata/TrainTestTables/Large/Test'
l = [file for file in os.listdir(path) if file.startswith('Product')]
len(l)

4239

In [40]:
l2 = l[3800:4000]
l2

['Product_westsidevw.com_September2020.json.gz',
 'Product_guygunterhome.com_September2020.json.gz',
 'Product_royrobinsonrv.com_September2020.json.gz',
 'Product_goairforcefalcons.com_September2020.json.gz',
 'Product_illusivecomics.com_September2020.json.gz',
 'Product_sterlingmccalllexusclearlake.com_September2020.json.gz',
 'Product_johnhyattclothing.com_September2020.json.gz',
 'Product_ruvalcabafantasias.com_September2020.json.gz',
 'Product_kidoozietoys.com_September2020.json.gz',
 'Product_hartensteincares.com_September2020.json.gz',
 'Product_canfloor.com_September2020.json.gz',
 'Product_luluskinstore.com_September2020.json.gz',
 'Product_essepursemuseum.com_September2020.json.gz',
 'Product_illfitment.com_September2020.json.gz',
 'Product_meimiamibeachcondosforsale.com_September2020.json.gz',
 'Product_shopontime.co.uk_September2020.json.gz',
 'Product_dieteticabarcelona.com_September2020.json.gz',
 'Product_thoitrangnuhoang.com_September2020.json.gz',
 'Product_voitektv.com_September2020.json.gz',
 'Product_wadesrv.com_September2020.json.gz',
 'Product_lightingshop.org_September2020.json.gz',
 'Product_nimnichtbuickgmc.com_September2020.json.gz',
 'Product_annabelleswigs.co.uk_September2020.json.gz',
 'Product_lanellodiresalomone.com_September2020.json.gz',
 'Product_poleoptical.com_September2020.json.gz',
 'Product_fragrancenet.com_September2020.json.gz',
 'Product_shayandblue.com_September2020.json.gz',
 'Product_artock.com.au_September2020.json.gz',
 'Product_dermalogica.com_September2020.json.gz',
 'Product_esmobility.co.uk_September2020.json.gz',
 'Product_arloskye.com_September2020.json.gz',
 'Product_cynth.com_September2020.json.gz',
 'Product_charlestonfabric.com_September2020.json.gz',
 'Product_tungstencarbide-tools.com_September2020.json.gz',
 'Product_shopfakenotes.com_September2020.json.gz',
 'Product_artfinder.com_September2020.json.gz',
 'Product_lcking.com_September2020.json.gz',
 'Product_ebelts.com_September2020.json.gz',
 'Product_caroclic.com_September2020.json.gz',
 'Product_john-anthony.com_September2020.json.gz',
 'Product_skifix.com_September2020.json.gz',
 'Product_pserviceweb.com_September2020.json.gz',
 'Product_dabpress.com_September2020.json.gz',
 'Product_chowdaheadz.com_September2020.json.gz',
 'Product_howig.co.uk_September2020.json.gz',
 'Product_mexicanblankets.com_September2020.json.gz',
 'Product_shop-boots.com_September2020.json.gz',
 'Product_carasutra.com_September2020.json.gz',
 'Product_strokedoctor.com_September2020.json.gz',
 'Product_plantgem.com_September2020.json.gz',
 'Product_landerscdjrnorman.com_September2020.json.gz',
 'Product_godbyhomefurnishings.com_September2020.json.gz',
 'Product_climbers-shop.com_September2020.json.gz',
 'Product_cosmofemina.com_September2020.json.gz',
 'Product_bommeow.com_September2020.json.gz',
 'Product_kostazul.com_September2020.json.gz',
 'Product_nj.com_September2020.json.gz',
 'Product_halilit.co.uk_September2020.json.gz',
 'Product_marinestereo.com_September2020.json.gz',
 'Product_prosonic-studios.com_September2020.json.gz',
 'Product_bolgerfuneral.com_September2020.json.gz',
 'Product_ilcaffeitaliano.com_September2020.json.gz',
 'Product_cicekdiyari.com_September2020.json.gz',
 'Product_acclaimautoparts.com_September2020.json.gz',
 'Product_acewashersupplies.com_September2020.json.gz',
 'Product_iq-uv.com_September2020.json.gz',
 'Product_jennycraig.com.au_September2020.json.gz',
 'Product_escapade.co.uk_September2020.json.gz',
 'Product_chemicalplanet.net_September2020.json.gz',
 'Product_cashforcars.net_September2020.json.gz',
 'Product_allenhonda.com_September2020.json.gz',
 'Product_viasweat.com_September2020.json.gz',
 'Product_homemakersvilla.net_September2020.json.gz',
 'Product_amersonstravel.com_September2020.json.gz',
 'Product_brilliantoutdoors.com_September2020.json.gz',
 'Product_postfallschryslerjeepdodgeram.com_September2020.json.gz',
 'Product_freemyersbestbrands.com_September2020.json.gz',
 'Product_inksupply.com_September2020.json.gz',
 'Product_speed-cat-shoes.org_September2020.json.gz',
 'Product_rhedo.com_September2020.json.gz',
 'Product_codesevenhack.net_September2020.json.gz',
 'Product_artsper.com_September2020.json.gz',
 'Product_gardenma.com_September2020.json.gz',
 'Product_shop2luv.com_September2020.json.gz',
 'Product_mbdiscountparts.com_September2020.json.gz',
 'Product_stanno.com_September2020.json.gz',
 'Product_nallforgovernor.com_September2020.json.gz',
 'Product_flowers4munich.com_September2020.json.gz',
 'Product_artstar.com_September2020.json.gz',
 'Product_bandarqq99.org_September2020.json.gz',
 'Product_sb-components.co.uk_September2020.json.gz',
 'Product_alpinewines.co.uk_September2020.json.gz',
 'Product_giltee.com_September2020.json.gz',
 'Product_dmso-supplier.com_September2020.json.gz',
 'Product_autonationtoyotasouthaustin.com_September2020.json.gz',
 'Product_aslangolf.co.uk_September2020.json.gz',
 'Product_lionelmessijersey.org_September2020.json.gz',
 'Product_us41cars.com_September2020.json.gz',
 'Product_ankethread.com_September2020.json.gz',
 'Product_gilecheese.com_September2020.json.gz',
 'Product_monkeymotorsmn.com_September2020.json.gz',
 'Product_alokitabevi.com_September2020.json.gz',
 'Product_customboxeshub.com_September2020.json.gz',
 'Product_shophouseofnomad.com_September2020.json.gz',
 'Product_deesign.com_September2020.json.gz',
 'Product_chupetesgraciosos.com_September2020.json.gz',
 'Product_reinerplay.com_September2020.json.gz',
 'Product_labfreezers.net_September2020.json.gz',
 'Product_jaxgarage.com.au_September2020.json.gz',
 'Product_hl-grosshandel.com_September2020.json.gz',
 'Product_labuanshoppy.com_September2020.json.gz',
 'Product_lashtavern.com_September2020.json.gz',
 'Product_creoven.co.uk_September2020.json.gz',
 'Product_butikjamtangan.com_September2020.json.gz',
 'Product_tresorbleu.com_September2020.json.gz',
 'Product_kablosepeti.com_September2020.json.gz',
 'Product_4pmti.com_September2020.json.gz',
 'Product_wholesaleleathersupplier.com_September2020.json.gz',
 'Product_prontocharger.com_September2020.json.gz',
 'Product_artimagepublications.com_September2020.json.gz',
 'Product_aplevel.com_September2020.json.gz',
 'Product_childtherapytoys.com_September2020.json.gz',
 'Product_highclassmobile.com_September2020.json.gz',
 'Product_qualite-pieces-auto.com_September2020.json.gz',
 'Product_selwood.com_September2020.json.gz',
 'Product_boutonjaune.com_September2020.json.gz',
 'Product_jeparawoodenfurniture.com_September2020.json.gz',
 'Product_lendingexpert.co.uk_September2020.json.gz',
 'Product_absolutedoor.net_September2020.json.gz',
 'Product_windyhillfarmtoys.com_September2020.json.gz',
 'Product_philipjonesjewellery.com_September2020.json.gz',
 'Product_infinitimv.com_September2020.json.gz',
 'Product_erikapena.com_September2020.json.gz',
 'Product_flowers4armenia.com_September2020.json.gz',
 'Product_icelectdata1.com_September2020.json.gz',
 'Product_elementactivewear.com_September2020.json.gz',
 'Product_usfarmer.com_September2020.json.gz',
 'Product_silksisters.com.au_September2020.json.gz',
 'Product_dchkayhonda.com_September2020.json.gz',
 'Product_nova-megastore.com_September2020.json.gz',
 'Product_nametagwizard.com_September2020.json.gz',
 'Product_mycozycups.com_September2020.json.gz',
 'Product_allbestcbdoil.com_September2020.json.gz',
 'Product_masonlindhart.com_September2020.json.gz',
 'Product_winreal.com.ng_September2020.json.gz',
 'Product_croydon-tyrescentre.co.uk_September2020.json.gz',
 'Product_delivape.com_September2020.json.gz',
 'Product_yachtbooker.com_September2020.json.gz',
 'Product_factorychryslerparts.com_September2020.json.gz',
 'Product_thomasfuneralhomecalhoun.com_September2020.json.gz',
 'Product_jordancamper.com_September2020.json.gz',
 'Product_slamoof.com_September2020.json.gz',
 'Product_iludec.com_September2020.json.gz',
 'Product_bambuskomfort.com_September2020.json.gz',
 'Product_flowers4quarteira.com_September2020.json.gz',
 'Product_gmcarsbynelson.com_September2020.json.gz',
 'Product_aw-lab.com_September2020.json.gz',
 'Product_team-fishing.com_September2020.json.gz',
 'Product_cdhomeproducts.com_September2020.json.gz',
 'Product_bidderlo.com_September2020.json.gz',
 'Product_dienlanhnguyenphat.com_September2020.json.gz',
 'Product_buy-motorcycle.com_September2020.json.gz',
 'Product_bellesmart.com_September2020.json.gz',
 'Product_powerwalker.com_September2020.json.gz',
 'Product_royalepharma.com_September2020.json.gz',
 'Product_stantonsace.com_September2020.json.gz',
 'Product_towelsandbedsheets.co.uk_September2020.json.gz',
 'Product_onestopflooring.co.uk_September2020.json.gz',
 'Product_lucyandcoboutique.com_September2020.json.gz',
 'Product_qcautoplex.com_September2020.json.gz',
 'Product_musicscotland.com_September2020.json.gz',
 'Product_etrailer.com_September2020.json.gz',
 'Product_lepro.com_September2020.json.gz',
 'Product_flagsrus.org_September2020.json.gz',
 'Product_supplyhog.com_September2020.json.gz',
 'Product_ruffandtumbledogcoats.com_September2020.json.gz',
 'Product_childrens-ministry-deals.com_September2020.json.gz',
 'Product_callofdutyleague.com_September2020.json.gz',
 'Product_lucasignition.com_September2020.json.gz',
 'Product_yves-salomon.com_September2020.json.gz',
 'Product_yanbzx.com_September2020.json.gz',
 'Product_netwalkerstore.com_September2020.json.gz',
 'Product_parrottfuneralhome.com_September2020.json.gz',
 'Product_kbctools.com_September2020.json.gz',
 'Product_hubertvestertoyota.com_September2020.json.gz',
 'Product_millerwardfuneralhome.com_September2020.json.gz',
 'Product_3bscientific.co.uk_September2020.json.gz',
 'Product_evybenita.com_September2020.json.gz',
 'Product_lovebirdsb.com_September2020.json.gz',
 'Product_catersuppliesdirect.com_September2020.json.gz',
 'Product_citydrawers.com_September2020.json.gz',
 'Product_artsy.net_September2020.json.gz',
 'Product_topoutdoorsupplies.com_September2020.json.gz',
 'Product_ppssurf.com_September2020.json.gz',
 'Product_wildyakexpeditions.com_September2020.json.gz',
 'Product_goelectrical.com.au_September2020.json.gz',
 'Product_lovelypetzone.com_September2020.json.gz',
 'Product_festapratica.com_September2020.json.gz',
 'Product_perapasha.com_September2020.json.gz',
 'Product_dutchflies.com_September2020.json.gz']

In [41]:
listcolt = pd.read_csv('../../src/data/data/CSV_files/stats_filtered_and_cleaned_tables.csv')
listcolt = listcolt.set_index('filename')
listcolt = listcolt[listcolt.index=='Product']
listcolt

                                              listofcolumns  numtables
filename
Product   ['name', 'offers', 'brand', 'aggregaterating',...      33203

In [42]:
path = '/work-ceph/bizer-tp2021/data_integration_using_deep_learning/src/data/data/CSV_files'
stats = pd.read_csv(path + '/all_files_stats.csv')
files = pd.read_csv(path + '/all_files_cleaned.csv')
files = files.drop(columns={'Unnamed: 0'})
listcol= files.groupby('filename')['column_name'].apply(list).reset_index(name='listofcolumns')
listcol.filename = listcol.filename.str.split('_', expand=True)[0]
listcol.index = listcol['filename']
listcol = listcol[listcol['filename']=='Product']
listcol

         filename                                      listofcolumns
filename
Product   Product  [name, offers, brand, aggregaterating, mpn, ca...

In [43]:
path='../../src/data/schemafiltereddata/TrainTestTables/Large/Test'
files = [file for file in os.listdir(path) if file.endswith('.json.gz')]
for index in listcol.filename:
    setcol = listcol.loc[index]['listofcolumns']
    for file in l2:
    # read file
        df = pd.read_json(os.path.join(path, '{}'.format(file)), compression='gzip', lines=True)
        display(file)
        display(df[df.columns.intersection(setcol)].head())

'Product_westsidevw.com_September2020.json.gz'

,name,offers,brand,mpn,identifier
0,Ski Sac,None,Volkswagen,00V061202,{'value': '00V061202'}
1,Hatch Top Spoiler - Primer,{'itemcondition': 'http://schema.org/NewCondit...,Volkswagen,5G0071644GRU,{'value': '5G0071644GRU'}
2,Base Bar End Cap Set - Black,{'url': 'parts.westsidevw.com/p/volkswagen__pa...,Volkswagen,3B0071738,{'value': '3B0071738'}
3,Base Carrier Bars - Silver,{'itemcondition': 'http://schema.org/NewCondit...,Volkswagen,3C0071126A,{'value': '3C0071126A'}
4,Hatch Top Spoiler - Primer This Fits Your 2015...,{'url': 'parts.westsidevw.com/p/volkswagen_201...,Volkswagen,5G0071644GRU,{'value': '5G0071644GRU'}

'Product_guygunterhome.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,GE&reg; 27&quot; Smart Built-In Convection Sin...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'GE Appliances'},"{'ratingvalue': '4.1', 'reviewcount': '8', 'it...",JKS5000DNWW
1,GE&reg; 27&quot; Built-In Combination Microwav...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'GE Appliances'},{'itemreviewed': 'GE&reg; 27&quot; Built-In Co...,JK3800DHWW
2,GE Profile&trade; Series ENERGY STAR&reg; 27.7...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'GE Appliances'},"{'reviewcount': '133', 'ratingvalue': '4.3', '...",PFE28KMKES
3,1.8 cu. ft. Over-the-Range Microwave Oven with...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'LG'},{'itemreviewed': '1.8 cu. ft. Over-the-Range M...,LMV1831BD
4,7.4 cu. ft. Ultra Large Capacity Smart wi-fi E...,"{'price': '1199.0', 'availability': 'http://sc...",{'name': 'LG'},"{'ratingvalue': '4.6', 'reviewcount': '94', 'i...",DLGX3701V

'Product_royrobinsonrv.com_September2020.json.gz'

,name,brand,model,manufacturer,releasedate,color
0,2002 NATIONAL SEABREEZE CLASS A DIESEL,NATIONAL,SEABREEZE,NATIONAL,2002,White
1,2019 Winnebago VISTA LX CLASS A,Winnebago,VISTA LX,Winnebago,2019,DEEP SEA
2,2018 FOREST RIVER VIBE TRAVEL TRAILER,FOREST RIVER,VIBE,FOREST RIVER,2018,White
3,2005 THOR CITATION CAMPER,THOR,CITATION,THOR,2005,White
4,2020 Winnebago SUNSTAR CLASS A,Winnebago,SUNSTAR,Winnebago,2020,SCARLET

'Product_goairforcefalcons.com_September2020.json.gz'

,name,offers,brand,category,itemcondition
0,Men's Cutter & Buck Gray Air Force Falcons Vau...,"{'serialnumber': '3144514', 'availability': 'h...",None,None,http://schema.org/NewCondition
1,Air Force Falcons Nike Logo Performance Polo -...,"{'availability': 'http://schema.org/InStock', ...",Nike,Polos &gt; Short Sleeve,http://schema.org/NewCondition
2,Men's Fanatics Branded Royal Air Force Falcons...,"{'serialnumber': '2888454', 'availability': 'h...",Fanatics Branded,T-Shirts &gt; Long Sleeve,http://schema.org/NewCondition
3,Men's Cutter & Buck Black Air Force Falcons Bi...,"{'availability': 'http://schema.org/InStock', ...",Cutter & Buck,Polos &gt; Short Sleeve,http://schema.org/NewCondition
4,Men's Cutter & Buck White Air Force Falcons Bi...,"{'serialnumber': '2712384', 'category': 'Shirt...",Cutter & Buck,Shirts & Sweaters,http://schema.org/NewCondition

'Product_illusivecomics.com_September2020.json.gz'

,name,offers,brand,itemcondition,gtin13
0,Z-MAN GAMES INC INFINITY GAUNTLET: A LOVE LETT...,"{'price': '14.99', 'availability': 'https://sc...",Z-MAN GAMES INC,https://schema.org/NewCondition,8.413331e+11
1,FUNKO POP DISNEY: MICKEY'S 90TH - PLANE CRAZY ...,"{'availability': 'https://schema.org/InStock',...",FUNKO,https://schema.org/NewCondition,8.896983e+11
2,FORBIDDEN ISLAND,"{'pricevaliduntil': '2020-12-21', 'availabilit...",None,https://schema.org/NewCondition,7.597510e+11
3,FUNKO POP DISNEY: MICKEY'S 90TH - BAND CONCERT...,"{'availability': 'https://schema.org/InStock',...",FUNKO,https://schema.org/NewCondition,8.896983e+11
4,MARVEL COMICS MARVEL-VERSE GN TP BLACK PANTHER,"{'inventorylevel': '2', 'availability': 'https...",MARVEL COMICS,https://schema.org/NewCondition,NaN

'Product_sterlingmccalllexusclearlake.com_September2020.json.gz'

,name,offers,brand,mpn,model,manufacturer,color
0,New 2020 Lexus IS 300 - In-Stock,{'itemcondition': 'http://schema.org/NewCondit...,Lexus,9502.0,IS 300,{'name': 'Lexus'},Obsidian
1,New 2020 Lexus IS 300 - In-Stock,{'itemcondition': 'http://schema.org/NewCondit...,Lexus,9502.0,IS 300,{'name': 'Lexus'},Obsidian
2,New 2020 Lexus RC 300 - In-Stock,{'itemcondition': 'http://schema.org/NewCondit...,Lexus,9202.0,RC 300,{'name': 'Lexus'},Atomic Silver
3,New 2020 Lexus NX 300 - In-Stock,{'itemcondition': 'http://schema.org/NewCondit...,Lexus,9830.0,NX 300,{'name': 'Lexus'},Matador Red Mica
4,New 2020 Lexus IS 300 - In-Stock,{'itemcondition': 'http://schema.org/NewCondit...,Lexus,9502.0,IS 300,{'name': 'Lexus'},Eminent White Pearl

'Product_johnhyattclothing.com_September2020.json.gz'

,name,offers,brand,additionalproperty,gtin12
0,Johnnie-O Pant Marin Prep-formance Pant,[{'itemcondition': 'http://schema.org/NewCondi...,{'name': 'Johnnie-O'},{'value': '402507431967'},8.415982e+11
1,Peter Millar Salem Performance Short,[{'itemcondition': 'http://schema.org/NewCondi...,{'name': 'Peter Millar'},{'value': '9043831940'},1.906786e+11
2,Crown Soft Merino-Silk Quarter-Zip — Peter Millar,"[{'pricevaliduntil': '2021-09-29', 'itemcondit...",{'name': 'Peter Millar'},{'value': '3945307078774'},1.946241e+11
3,Kribi Beach Aqua Cotton Polo – Peter Millar,[{'itemcondition': 'http://schema.org/NewCondi...,{'name': 'Peter Millar'},{'value': '4428491325558'},1.937133e+11
4,Crown Comfort Interlock Quarter-Zip — Peter Mi...,"[{'pricevaliduntil': '2021-09-29', 'itemcondit...",{'name': 'Peter Millar'},{'value': '4424690040950'},1.906786e+11

'Product_ruvalcabafantasias.com_September2020.json.gz'

,name,offers,brand,category,gtin14
0,R732001 LETRERO ANUNCIO C/LUZ 30 X 22 CM,"{'price': '1.89E2', 'availability': 'https://s...",{'name': 'R732'},Letreros con luz,c7777732001003
1,R304202 VIDRIO BASE PARA PASTEL CHICO 21 X 11 CM,"{'price': '2.09E2', 'availability': 'https://s...",{'name': 'R304'},Cupcake Stand,c7777304202005
2,R116008 NAV.RENO FINO DECORADO 63 * 28 CM,"{'pricevaliduntil': '2020-10-08', 'availabilit...",{'name': 'R116'},Animales Nav,c7777116008000
3,R115001-A NAV. MONO NIEVE COLGANTE 42CM,"{'sku': 'R115001-A', 'availability': 'https://...",{'name': 'R115'},Figuras de Trovicel,c7777115001019
4,R709008 BAJO PLATO 4 GRECAS 35 CMS,"[{'name': 'Plata', 'price': '5.4E1', 'pricecur...",{'name': 'R709'},Bajoplatos,c7777709008011

'Product_kidoozietoys.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Kidoozie Princess Hideaway Playhouse with Fron...,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",{'name': 'International Playthings'},"{'reviewcount': '89', 'ratingvalue': '5'}",768
1,Kidoozie Build-A-Road Expansion Pack,"{'pricecurrency': 'USD', 'price': '9.95', 'ava...",{'name': 'International Playthings'},"{'reviewcount': '89', 'ratingvalue': '5'}",762
2,Kidoozie Funtime Tractor,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",{'name': 'Kidoozie'},"{'reviewcount': '89', 'ratingvalue': '5'}",766
3,Kidoozie Stack 'n Sort Toy - 12 Colorful Piece...,"{'pricecurrency': 'USD', 'price': '21.99', 'pr...",{'name': 'iPlay'},"{'reviewcount': '89', 'ratingvalue': '5'}",750
4,Kidoozie Pogo Jumper,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Kidoozie'},"{'reviewcount': '89', 'ratingvalue': '5'}",743

'Product_hartensteincares.com_September2020.json.gz'

,name,offers,aggregaterating,review,itemcondition,model
0,Cherished Memories - All White,"{'pricecurrency': 'USD', 'highprice': '99.99',...",None,None,NewCondition,[{'image': 'https://res.cloudinary.com/picasso...
1,"Peace, Prayers, & Blessings- All White","{'pricecurrency': 'USD', 'lowprice': '59.99', ...","{'reviewcount': '2', 'ratingvalue': '5.00'}","[{'datepublished': '1/22/2020', 'name': 'Peace...",NewCondition,"[{'sku': '95383S', 'name': 'Peace, Prayers, & ..."
2,White Sympathy Standing Baskets,"{'pricecurrency': 'USD', 'lowprice': '99.99', ...","{'ratingvalue': '5.00', 'reviewcount': '6'}","[{'author': 'from -', 'description': 'Beautifu...",NewCondition,[{'name': 'White Sympathy Standing Baskets (St...
3,Multicolor Pastel Sympathy Standing Basket,"{'pricecurrency': 'USD', 'lowprice': '99.99', ...",None,None,NewCondition,[{'url': 'https://www.hartensteincares.com/sto...
4,"Peace, Prayers, & Blessings- Yellow and White","{'pricecurrency': 'USD', 'lowprice': '59.99', ...","{'ratingvalue': '4.60', 'reviewcount': '5'}","[{'author': 'from -', 'name': 'Peace, Prayers,...",NewCondition,[{'image': 'https://res.cloudinary.com/picasso...

'Product_canfloor.com_September2020.json.gz'

,name,offers,category,color,material
0,"Luxury Vinyl Flooring LifeStepp, Cosmopolitan ...","{'price': '3.49', 'pricecurrency': 'CAD'}",Vinyl Flooring,Grace,None
1,"Engineered Oak Flooring, Fuzion Beaux Arts, Si...","{'price': '11.99', 'pricecurrency': 'CAD'}",Engineered Prefinished,Monet,White Oak
2,"Luxury Vinyl Flooring Canfloor NLV, Rigid Core...","{'price': '2.29', 'pricecurrency': 'CAD'}",Vinyl Flooring,NLV-28005,None
3,"Engineered Beech Panache, Hand-Scraped 6.5\"" x...","{'price': '3.99', 'pricecurrency': 'CAD'}",Engineered Prefinished,Pier,European Beech
4,"Engineered White Oak Panache, 7.5\"" x 3/4\"" Co...","{'price': '6.99', 'pricecurrency': 'CAD'}",Engineered Prefinished,Mink,White Oak

'Product_luluskinstore.com_September2020.json.gz'

,name,offers,brand,aggregaterating,category,manufacturer
0,Timeless Coenzyme Q10 Serum 30ml,"{'price': '10000', 'pricecurrency': 'KZT', 'av...",Timeless,"{'reviewcount': '2', 'ratingvalue': '4.5'}",Активный уход,Timeless
1,ZENOLOGY Спрей для ароматизации воздуха помеще...,"{'pricecurrency': 'KZT', 'price': '16300', 'av...",Zenology,"{'reviewcount': '2', 'ratingvalue': '4.5'}",None,Zenology
2,Babor Perfect Glow 7 amp,"{'pricecurrency': 'KZT', 'availability': 'http...",Babor,"{'reviewcount': '2', 'ratingvalue': '4.5'}",SOS-средства,Babor
3,GIGI Acnon Pore Purifying mask Маска противово...,"{'availability': 'https://schema.org/InStock',...",GIGI,"{'reviewcount': '2', 'ratingvalue': '4.5'}",Активный уход,GIGI
4,Odacite Crystal Contour Gua Sha Green,"{'price': '20000', 'pricecurrency': 'KZT', 'av...",Odacite,"{'reviewcount': '2', 'ratingvalue': '4.5'}",Антивозрастные средства,Odacite

'Product_essepursemuseum.com_September2020.json.gz'

,name,offers,brand,weight,gtin8
0,Fair Anita Earrings: Adela,"{'gtin8': '97216100', 'itemcondition': 'http:/...",{'name': 'Fair Anita'},0.0lb,97216100.0
1,Fair Anita Earrings: Double Moon,[{'itemcondition': 'http://schema.org/NewCondi...,{'name': 'Fair Anita'},0.0lb,27329892.0
2,Fibres of Life Bag: Felt Tote,[{'itemcondition': 'http://schema.org/NewCondi...,{'name': 'Fibres of Life'},1.5lb,36252208.0
3,"Vintage Hat, beige floral","{'price': '30', 'itemcondition': 'http://schem...",{'name': 'ESSE Purse Museum &amp; Store'},0.0lb,16241200.0
4,Gabs G3: Matte Leather,[{'itemcondition': 'http://schema.org/NewCondi...,{'name': 'Gabs'},2.0lb,23790128.0

'Product_illfitment.com_September2020.json.gz'

,name,offers,price,shop-currency
0,NICHE - INTAKE M159,NICHE - INTAKE M159 $230.00 18x8 / 5x112 / 42 ...,$230.00,USD
1,NICHE - MILAN - M135,NICHE - MILAN - M135 $295.00 17X8 / 5X114.3 / ...,$295.00,USD
2,NICHE - TARGA M129,NICHE - TARGA M129 $295.00 17x8 / 5x100 / 40 -...,$295.00,USD
3,NICHE - SURGE M114,NICHE - SURGE M114 $295.00 19x8.5 / 5x112 / 42...,$295.00,USD
4,NICHE - MISANO M117,NICHE - MISANO M117 $295.00 17X8 / 5X100 / 40 ...,$295.00,USD

'Product_meimiamibeachcondosforsale.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Mei Miami Unit 1 - 4 bedroom condo for rent 30...,{'itemcondition': 'http://schema.org/UsedCondi...,{'name': 'apartment'},"{'reviewcount': '1', 'ratingvalue': '5'}",A10848861
1,Mei Miami Unit 1108 - 3 bedroom condo for sale...,{'itemcondition': 'http://schema.org/UsedCondi...,{'name': 'apartment'},"{'reviewcount': '1', 'ratingvalue': '5'}",A10800506
2,Mei Miami Unit 1607 - 2 bedroom condo for sale...,{'itemcondition': 'http://schema.org/UsedCondi...,{'name': 'apartment'},"{'reviewcount': '1', 'ratingvalue': '5'}",A10883714
3,Mei Miami Unit 504 - 1 bedroom condo for sale ...,{'itemcondition': 'http://schema.org/UsedCondi...,{'name': 'apartment'},"{'reviewcount': '1', 'ratingvalue': '5'}",A10874806
4,Mei Miami Unit PH6 - 2 bedroom condo for sale ...,{'itemcondition': 'http://schema.org/UsedCondi...,{'name': 'apartment'},"{'reviewcount': '1', 'ratingvalue': '5'}",A10521967

'Product_shopontime.co.uk_September2020.json.gz'

,name,offers,brand,category,additionalproperty
0,Croft&Barrow 31CB22X019 Men's Brown Leather Sl...,"{'name': 'Brown', 'itemcondition': 'http://sch...",Croft&Barrow,Men's Wallets,"{'value': 'Brown', 'name': 'Colour'}"
1,Emporio Armani AR11085 Men's Dress Watch,"{'name': 'Silver', 'itemcondition': 'http://sc...",Emporio Armani,Men's Watches,"{'name': 'Colour', 'value': 'Silver'}"
2,Versus by Versace SOH020015 Men's Chronograph ...,"{'sku': 'B00VNGL74I', 'itemcondition': 'http:/...",Versus,Men's Watches,"{'name': 'Title', 'value': 'Default Title'}"
3,FCUK Sport FCS040 Men's Sunglasses,{'itemcondition': 'http://schema.org/NewCondit...,FCUK,Men's Sunglasses,"{'name': 'Title', 'value': 'Default Title'}"
4,Michael Kors MK5613 Ladies Mini Blair Rose Gol...,{'itemcondition': 'http://schema.org/NewCondit...,Michael Kors,Ladies Watches,"{'value': 'Rose Gold', 'name': 'Colour'}"

'Product_dieteticabarcelona.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review,gtin13
0,SOLGAR FORMULA VM 75 Uno Al Dia 30 Comp,"{'pricevaliduntil': '2021-12-31}', 'price': '1...","[SOLGAR, {'name': 'SOLGAR'}]","{'ratingcount': '9', 'ratingvalue': '5'}",SOL-0065,"{'author': 'Dietética Online Barcelona', 'date...",3.398401e+10
1,DR.HAUSCHKA TRIO DE SOMBRAS DE OJOS 03 ametrin...,"{'pricevaliduntil': '2021-12-31}', 'url': 'htt...","[DR.HAUSCHKA, {'name': 'DR.HAUSCHKA'}]","{'ratingcount': '9', 'ratingvalue': '5'}",1023-103,"{'author': 'Dietética Online Barcelona', 'date...",4.020829e+12
2,SOLGAR FORMULA VM 75 Uno Al Dia 180 Comp,{'url': 'https://www.dieteticabarcelona.com/so...,"[SOLGAR, {'name': 'SOLGAR'}]","{'ratingcount': '9', 'ratingvalue': '5'}",SOL-0064,"{'datepublished': '2020-09-20', 'author': 'Die...",3.398401e+10
3,SOLGAR FACTORES LIPOTROPICOS 100 Comp,"{'pricevaliduntil': '2021-12-31}', 'price': '2...","[SOLGAR, {'name': 'SOLGAR'}]","{'ratingcount': '9', 'ratingvalue': '5'}",SOL-0054,"{'datepublished': '2020-09-20', 'author': 'Die...",3.398402e+10
4,SOLGAR WHEY TO GO Proteina En Polvo CHOCOLATE ...,"{'pricevaliduntil': '2021-12-31}', 'price': '3...","[SOLGAR, {'name': 'SOLGAR'}]","{'ratingcount': '9', 'ratingvalue': '5'}",SOL-0319,"{'author': 'Dietética Online Barcelona', 'date...",3.398404e+10

'Product_thoitrangnuhoang.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,ĐẦM QUÝ BÀ KÈM LƯỚI THÊU LÔNG CÔNG-HN692,"{'pricevaliduntil': '2022-11-05', 'pricecurren...",{'name': 'Thời Trang Nữ Hoàng'},"{'ratingvalue': '5', 'ratingcount': '326'}",HN692
1,ĐẦM IN HỌA TIẾT CARO CAO CẤP -HN 703,"{'pricevaliduntil': '2022-11-05', 'price': '56...",{'name': 'Thời Trang Nữ Hoàng'},"{'ratingvalue': '5', 'ratingcount': '326'}",HN703
2,SET BỘ HÀNG NHẬP CAO CẤP-HN673,"{'pricevaliduntil': '2022-11-05', 'price': '58...",{'name': 'Thời Trang Nữ Hoàng'},"{'ratingvalue': '5', 'ratingcount': '326'}",HN673
3,ĐẦM CÔNG CHÚA SÁT NÁCH PHỐI LƯỚI ĐÍNH HOA -D15,"{'pricevaliduntil': '2022-11-05', 'availabilit...",{'name': 'Thời Trang Nữ Hoàng'},"{'ratingvalue': '5', 'ratingcount': '326'}",D15
4,ĐẦM LỤA CỔ VEST PHỐI CHỮ - HN651,"{'pricevaliduntil': '2022-11-05', 'pricecurren...",{'name': 'Thời Trang Nữ Hoàng'},"{'ratingvalue': '5', 'ratingcount': '326'}",HN651

'Product_voitektv.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,GE&reg; ENERGY STAR&reg; 16.6 Cu. Ft. Recessed...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'GE Appliances'},"{'ratingvalue': '4.6', 'reviewcount': '24', 'i...",GPE17CTNRWW
1,GE&reg; Dishwasher with Front Controls,"{'pricecurrency': 'USD', 'price': '413.95', 'a...",{'name': 'GE Appliances'},{'itemreviewed': 'GE&reg; Dishwasher with Fron...,GDF510PGMWW
2,GE&reg; Front Control with Plastic Interior Di...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'GE Appliances'},"{'ratingvalue': '4.2', 'itemreviewed': 'GE&reg...",GDF530PGMCC
3,GE&reg; ENERGY STAR&reg; 21.9 Cu. Ft. Top-Free...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'GE Appliances'},"{'reviewcount': '7', 'itemreviewed': 'GE&reg; ...",GTE22JMNRES
4,GE&reg; 30&quot; Slide-In Front-Control Convec...,"{'pricecurrency': 'USD', 'price': '1998.95', '...",{'name': 'GE Appliances'},None,JGS760SPSS

'Product_wadesrv.com_September2020.json.gz'

,name,offers,brand,category,mpn,itemcondition,width,height,depth
0,2021 Dutchmen Aspen Trail 3120BHS,"{'price': '27995.00', 'url': 'https://www.wade...",{'name': 'Dutchmen'},Travel Trailer,3120BHS,NewCondition,8',11' 3\,35' 1\
1,2020 Thor Siesta Sprinter 24MB,"{'pricevaliduntil': '2020-09-29', 'url': 'http...",{'name': 'Thor Motor Coach'},Class C,24MB,NewCondition,7' 6\,10' 10\,25' 10\
2,2016 Freightliner Sportchassis M2,"{'price': '134995.00', 'pricevaliduntil': '202...",{'name': 'Freightliner'},Truck Chassis,M2,NewCondition,None,None,None
3,2021 Newmar Ventana 4037,None,{'name': 'Newmar'},Class A,4037,NewCondition,8' 6\,12' 11\,40' 10\
4,2016 Freightliner SPORTS CHASSIS BUSINESS CLAS...,"{'price': '134995.00', 'pricevaliduntil': '202...",{'name': 'Freightliner'},Truck Chassis,BUSINESS CLASS M2,NewCondition,None,None,None

'Product_lightingshop.org_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,"Newpow S14 Led Light Bulbs, 24 Pack Dimmable E...","{'pricecurrency': 'USD', 'price': '24.99', 'av...",{'name': 'NEWPOW'},"{'reviewcount': '89', 'ratingvalue': '5'}",79529
1,Cal Lighting BO-213-WH Floor Lamp with Frosted...,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",{'name': 'Cal Lighting'},"{'reviewcount': '89', 'ratingvalue': '5'}",3266
2,"Jazava Modern Mini 1-Light Pendant, 2Pack Indu...","{'pricecurrency': 'USD', 'pricevaliduntil': '2...",{'name': 'JAZAVA'},"{'reviewcount': '89', 'ratingvalue': '5'}",81493
3,SHINE HAI Recessed Lighting Kit,"{'pricecurrency': 'USD', 'price': '0.00', 'pri...",{'name': 'Shine Glory Lighting Limted'},"{'reviewcount': '89', 'ratingvalue': '5'}",3207
4,Good Earth Lighting 24-Inch New Castle Bath Bar,"{'pricecurrency': 'USD', 'price': '0.00', 'ava...",{'name': 'Good Earth Lighting'},"{'reviewcount': '89', 'ratingvalue': '5'}",3512

'Product_nimnichtbuickgmc.com_September2020.json.gz'

,name,offers,brand,mpn,model,manufacturer,color
0,Pre-Owned 2019 Chevrolet Suburban LT 4WD,"{'price': '45000', 'itemcondition': 'http://sc...",Chevrolet,CK15906,Suburban,{'name': 'Chevrolet'},Shadow Gray Metallic
1,Pre-Owned 2006 Honda Civic Cpe EX FWD 2dr Car,{'itemcondition': 'http://schema.org/UsedCondi...,Honda,FG1286JW,Civic Cpe,{'name': 'Honda'},Nighthawk Black Pearl
2,Certified Pre-Owned 2017 GMC Sierra 1500 Denal...,{'itemcondition': 'http://schema.org/UsedCondi...,GMC,TK15543,Sierra 1500,{'name': 'GMC'},Dark Slate Metallic
3,Pre-Owned 2010 Acura TL Tech With Navigation,"{'price': '7735', 'itemcondition': 'http://sch...",Acura,UA8F5AKW,TL,{'name': 'Acura'},None
4,Pre-Owned 2009 Jeep Liberty Rocky Mountain 4WD,{'itemcondition': 'http://schema.org/UsedCondi...,Jeep,KKJL74,Liberty,{'name': 'Jeep'},Brilliant Black Crystal

'Product_annabelleswigs.co.uk_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review
0,"Long, wavy dark brown wig: Mandy","{'itemoffered': 'Long, wavy dark brown wig: Ma...",Annabelle's Wigs,"{'reviewcount': '2', 'ratingvalue': '4.5'}",FW 176 EXTRA LONG DARK BROWN 8,"[{'datepublished': '2015-08-04', 'reviewbody':..."
1,Dusty Pink Long Bob Wig (LOB) with textured wa...,{'itemcondition': 'http://schema.org/NewCondit...,Annabelle's Wigs,"{'reviewcount': '2', 'ratingvalue': '5'}",AB-147 Dusty Pink T2312,"[{'datepublished': '2019-11-17', 'reviewbody':..."
2,"Dark brown wig, long, layered, tip flip style:...",{'itemcondition': 'http://schema.org/NewCondit...,Annabelle's Wigs,"{'ratingvalue': '5', 'reviewcount': '6'}",FW 171 DARKBROWN 4,"[{'datepublished': '2019-07-10', 'reviewbody':..."
3,"Auburn 3/4 hairpiece (half wig), long straight...",{'itemcondition': 'http://schema.org/NewCondit...,Annabelle's Wigs,"{'reviewcount': '1', 'ratingvalue': '3'}",Three Quarter AB26 Brown30,"{'datepublished': '2015-02-04', 'reviewbody': ..."
4,"Peluca negro, flequillo recto corto: Maxine",{'itemcondition': 'http://schema.org/NewCondit...,Annabelle's Wigs,None,FW 212A-Black-1B Short Fringe,None

'Product_lanellodiresalomone.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,adidas predator 19.2 firm ground,"{'pricevaliduntil': '2020-11-05', 'url': '/img...",adidas predator 19.2 firm ground,"{'reviewcount': '56', 'ratingvalue': '4.7'}",75852
1,adidas 600 fill,"{'pricevaliduntil': '2020-11-05', 'url': '/img...",adidas 600 fill,"{'ratingvalue': '4.6', 'reviewcount': '63'}",75866
2,adidas 11 pro 3 review,"{'pricevaliduntil': '2020-11-05', 'url': '/img...",adidas 11 pro 3 review,"{'ratingvalue': '4.6', 'reviewcount': '47'}",75869
3,adidas 2010 collection,"{'pricevaliduntil': '2020-11-05', 'url': '/img...",adidas 2010 collection,"{'reviewcount': '66', 'ratingvalue': '4.5'}",75878
4,adidas alexander wang australia,"{'pricevaliduntil': '2020-11-05', 'url': '/img...",adidas alexander wang australia,"{'ratingvalue': '4.8', 'reviewcount': '65'}",75858

'Product_poleoptical.com_September2020.json.gz'

,name,offers,category,releasedate,additionalproperty
0,AM14 - C4 - 48/19,"{'availability': 'https://schema.org/InStock',...",Lunette de vue,2019-11-30T13:46:07+01:00,"[{'name': 'pa_marque', 'value': 'Lou'}, {'name..."
1,Simbo - HVWH - 52/18,"{'price': '171', 'itemcondition': 'NewConditio...",Lunette de soleil,2019-10-07T16:09:48+02:00,"[{'name': 'pa_gamme', 'value': 'Femme'}, {'val..."
2,OV5349S - 162571 - 50/24,"{'price': '289', 'itemcondition': 'NewConditio...",Lunette de soleil,2019-10-11T17:06:24+02:00,"[{'value': 'Prestige', 'name': 'pa_style'}, {'..."
3,Adda - HVBX - 56/17,"{'price': '171', 'itemcondition': 'NewConditio...",Lunette de soleil,2019-10-07T16:28:42+02:00,"[{'name': 'pa_gamme', 'value': 'Femme'}, {'val..."
4,Carini - 9038 - 51/16,"{'price': '255', 'itemcondition': 'NewConditio...",Lunette de vue,2019-10-04T11:07:48+02:00,"[{'value': 'Créateur', 'name': 'pa_style'}, {'..."

'Product_fragrancenet.com_September2020.json.gz'

,name,offers,brand,aggregaterating,manufacturer
0,Elie Saab Le Parfum L'Eau Couture by Elie Saab,None,{'name': 'Elie Saab Le Parfum L'Eau Couture'},"{'bestrating': '5', 'ratingcount': '0', 'ratin...",{'name': 'Elie Saab'}
1,Parfums De Marly Habdan by Parfums De Marly,None,{'name': 'Parfums De Marly Habdan'},None,{'name': 'Parfums De Marly'}
2,Halloween Man Rock On by Jesus Del Pozo,None,{'name': 'Halloween Man Rock On'},"{'bestrating': '5', 'ratingcount': '0', 'ratin...",{'name': 'Jesus Del Pozo'}
3,Merchant Of Venice Flower Fusion by Merchant O...,None,{'name': 'Merchant Of Venice Flower Fusion'},"{'bestrating': '5', 'ratingcount': '0', 'ratin...",{'name': 'Merchant Of Venice'}
4,Giorgio Pink by Giorgio Group,None,{'name': 'Giorgio Pink'},None,{'name': 'Giorgio Group'}

'Product_shayandblue.com_September2020.json.gz'

,name,offers,brand,mpn,review,manufacturer
0,Watermelons Fragrance 100ml,"{'availability': 'http://schema.org/InStock', ...",{'name': 'Shay & Blue'},0110058,"[{'author': 'Kristina M,', 'reviewbody': 'I tr...",{'name': 'Shay &amp; Blue'}
1,English Cherry Blossom Rich Almond Hand Creme ...,"{'price': '14', 'availability': 'http://schema...",{'name': 'Shay & Blue'},2307560,[{'reviewbody': 'This handcream is the perfect...,{'name': 'Shay &amp; Blue'}
2,Discovery Box (Excluded from Promotions),"{'availability': 'http://schema.org/InStock', ...",{'name': 'Shay & Blue'},7070601-B,"[{'name': 'Shay and blue box', 'author': 'Mitt...",None
3,English Cherry Blossom Fragrance 100ml,"{'availability': 'http://schema.org/InStock', ...",{'name': 'Shay & Blue'},0110060,"[{'reviewbody': 'Beautifully light, floral fra...",{'name': 'Shay &amp; Blue'}
4,Amber Oud Ahad Fragrance Concentrate 100ml,"{'availability': 'http://schema.org/InStock', ...",{'name': 'Shay & Blue'},0210083,"[{'datepublished': '2018-01-12 09:40:17', 'rev...",{'name': 'Shay &amp; Blue'}

'Product_artock.com.au_September2020.json.gz'

,name,offers,brand,mpn,mainentityofpage
0,Bunny Small - Speedy Me Bright - French Lavender,"{'price': '34.99', 'availability': 'InStock', ...",La Millou,V31907235201108,"{'copyrightyear': '2020', 'name': 'La Millou |..."
1,Children’s Room – Neo 4pcs,"{'price': '39.44', 'availability': 'OutOfStock...",PlanToys,V30315672961108,"{'copyrightyear': '2020', 'name': 'PlanToys | ..."
2,Smartrod® Set 64 Pieces,"{'availability': 'OutOfStock', 'pricecurrency'...",Neoformers,V13782106931284,{'name': 'Neoformers - Smartrod® Set 64 Pieces...
3,wink classic muslin 1.7 TOG sleeping bag S,"{'availability': 'OutOfStock', 'price': '43.16...",Aden and Anais,V21111598874708,{'name': 'Aden and Anais - wink classic muslin...
4,Washing Machine Set,"{'availability': 'OutOfStock', 'price': '15.51...",Sylvanian Families,V30308160176212,{'name': 'Sylvanian Families | Washing Machine...

'Product_dermalogica.com_September2020.json.gz'

,name,offers,brand,aggregaterating,gtin8
0,renewal lip complex,"[{'pricecurrency': 'USD', 'price': '27.0', 'av...",Dermalogica,"{'bestrating': '5', 'ratingvalue': '4.4', 'wor...",666151061293
1,clearing skin wash,"[{'offercount': '2', 'lowprice': '39.0', 'high...",Dermalogica,"{'bestrating': '5', 'ratingvalue': '4.4', 'wor...",666151011304
2,flashfoliant,"[{'pricecurrency': 'USD', 'url': 'https://www....",Dermalogica,"{'bestrating': '5', 'ratingvalue': '4.4', 'wor...",666151111783
3,active clay cleanser,"[{'pricecurrency': 'USD', 'price': '39.0', 'av...",Dermalogica,"{'bestrating': '5', 'ratingvalue': '4.6', 'wor...",666151011366
4,daily microfoliant refill,"[{'pricecurrency': 'USD', 'price': '52.0', 'av...",Dermalogica,"{'bestrating': '5', 'ratingcount': '1648', 'wo...",0666151111929

'Product_esmobility.co.uk_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Rascal Vision 75AH,"{'price': '2,695.00', 'pricecurrency': 'GBP'}",Rascal Mobility,{'reviewcount': '0'},CE
1,Rascal Vision 100AH,"{'price': '2,850.00', 'pricecurrency': 'GBP'}",Rascal Mobility,{'reviewcount': '0'},CE
2,Rascal Frontier,"{'pricecurrency': 'GBP', 'price': '1,545.00'}",Rascal Mobility,{'reviewcount': '0'},CE
3,Kymco HP Feature Midi XLS,"{'price': '1,845.00', 'pricecurrency': 'GBP'}",Kymco,{'reviewcount': '0'},CE
4,Apex Lite,"{'price': '1,339.00', 'pricecurrency': 'GBP'}",Apex,{'reviewcount': '0'},AL

'Product_arloskye.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,The Zipper Carry-On Max with Front Pocket,"{'pricecurrency': 'USD', 'price': '375.00', 'a...",{'name': 'Arlo Skye'},"{'bestrating': '5', 'ratingvalue': '4.89E0', '...",H3SGP23
1,The Frame Carry-On,"{'pricecurrency': 'USD', 'price': '450.00', 'a...",{'name': 'Arlo Skye'},"{'bestrating': '5', 'reviewcount': '96', 'wors...",H2B0022
2,The Zipper Check-In,"{'pricecurrency': 'USD', 'price': '395.00', 'a...",{'name': 'Arlo Skye'},"{'bestrating': '5', 'reviewcount': '55', 'wors...",H3YL027
3,Online Gift Cards,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Arlo Skye'},"{'bestrating': '5', 'reviewcount': '1', 'ratin...",None
4,The Luggage Tag,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Arlo Skye'},None,S3BL001

'Product_cynth.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Nine West Women's Yesterday Suede Sandal,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",{'name': 'Nine West'},"{'reviewcount': '89', 'ratingvalue': '5'}",940219
1,TOMS Women's Classic Slip-On (6 B(M) US/36-37 ...,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",None,"{'reviewcount': '89', 'ratingvalue': '5'}",977520
2,Ultraclub 8990 UC Ladies Oxford Shirt,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",{'name': 'UltraClub'},"{'reviewcount': '89', 'ratingvalue': '5'}",1620543
3,EleQueen Women's Full Cubic Zirconia Long Ball...,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",{'name': 'EleQueen'},"{'reviewcount': '89', 'ratingvalue': '5'}",1446616
4,Fashion Ladies Women's Retro Vintage Leather B...,"{'pricecurrency': 'USD', 'price': '6.89', 'pri...",{'name': 'Broadfashion'},"{'reviewcount': '89', 'ratingvalue': '5'}",1196669

'Product_charlestonfabric.com_September2020.json.gz'

,name,offers,brand,mpn,itemcondition
0,Duralee Fabric - Pattern #21048-194,"{'sku': '21048-194', 'gtin12': '706927131629',...",{'name': 'duralee.com'},706927131629,https://schema.org/NewCondition
1,Duralee Fabric - Pattern #36292-625,"{'mpn': '706927131563', 'availability': 'https...",{'name': 'duralee.com'},706927131563,https://schema.org/NewCondition
2,Duralee Fabric - Pattern #DU15917-434,"{'availability': 'https://schema.org/InStock',...",{'name': 'duralee.com'},706927131406,https://schema.org/NewCondition
3,Tessuto Lino | Steel Robert Allen Design,"{'pricevaliduntil': '2020-10-27', 'availabilit...",{'name': 'robertallendesign.com'},706927132457,https://schema.org/NewCondition
4,Highbury | Pool Robert Allen Design,"{'pricevaliduntil': '2020-10-27', 'availabilit...",{'name': 'robertallendesign.com'},706927132258,https://schema.org/NewCondition

'Product_tungstencarbide-tools.com_September2020.json.gz'

,name,offers,brand,model,manufacturer
0,YT5 / P30 Model E Brazed Carbide Tools Tungste...,"[{'pricecurrency': 'USD', 'offercount': '10', ...",RiXin,Welding Blades Model E,{'legalname': 'Zhuzhou Mingri Cemented Carbide...
1,Sintered tungsten alloy plates,"[{'pricecurrency': 'USD'}, {'pricecurrency': '...",none,many,{'legalname': 'Zhuzhou Mingri Cemented Carbide...
2,Cemented Tungsten Carbide Plates,"[{'highprice': '69', 'lowprice': '49', 'pricec...",RiXin,Tungsten carbide strip,{'legalname': 'Zhuzhou Mingri Cemented Carbide...
3,YG10XB Tungsten Carbide Inserts For Cutting Gl...,"[{'pricecurrency': 'USD', 'highprice': '45.59'...",rixin,carbide inserts,{'legalname': 'Zhuzhou Mingri Cemented Carbide...
4,"Polished Tungsten Carbide Strips , square Tung...",None,none,many,{'legalname': 'Zhuzhou Mingri Cemented Carbide...

'Product_shopfakenotes.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review
0,Buy Luxembourg Passport Online,"{'offercount': '2', 'highprice': '3500', 'avai...",myresearchemicalshop.co,"{'reviewcount': '100', 'ratingvalue': '5'}",N/A,{'author': 'user'}
1,Buy Austria Passport Online,"{'offercount': '2', 'highprice': '3500', 'avai...",myresearchemicalshop.co,"{'reviewcount': '100', 'ratingvalue': '5'}",N/A,{'author': 'user'}
2,Buy Brazilian Passport online,"{'offercount': '2', 'highprice': '3500', 'avai...",myresearchemicalshop.co,"{'reviewcount': '100', 'ratingvalue': '5'}",N/A,{'author': 'user'}
3,Buy Italian Identity cards,"{'offercount': '2', 'lowprice': '215', 'pricec...",myresearchemicalshop.co,"{'reviewcount': '100', 'ratingvalue': '5'}",N/A,{'author': 'user'}
4,Buy Swedish Krona online,"{'highprice': '40000', 'offercount': '48', 'av...",myresearchemicalshop.co,"{'reviewcount': '100', 'ratingvalue': '5'}",N/A,{'author': 'user'}

'Product_artfinder.com_September2020.json.gz'

,name,offers,brand,aggregaterating,review,manufacturer
0,Red Cross in Guangzhou - Captain America,"{'price': '709.00', 'itemcondition': 'https://...",Dake Wong,"{'ratingvalue': '5.0', 'ratingcount': '3'}",{'reviewbody': 'Shipped per timeline on listin...,{'name': 'Dake Wong'}
1,Shimmering skies of texas,"{'price': '495.00', 'itemcondition': 'https://...",Vandana Mehta,None,None,{'name': 'Vandana Mehta'}
2,Nude girl #2,"{'price': '25.50', 'itemcondition': 'https://s...",Pavel Kuragin,"{'ratingvalue': '5.0', 'ratingcount': '383'}","{'datepublished': '2020-09-22', 'reviewbody': ...",{'name': 'Pavel Kuragin'}
3,Alien Transistor. a pair of sculptures.,{'itemcondition': 'https://schema.org/NewCondi...,ZheKa,"{'ratingvalue': '5.0', 'ratingcount': '10'}","{'datepublished': '2020-09-18', 'reviewbody': ...",{'name': 'ZheKa'}
4,Poppy Dreams 1 - Floral art by Kathy Morton St...,"{'availability': 'OutOfStock', 'itemcondition'...",Kathy Morton Stanion,"{'ratingcount': '204', 'ratingvalue': '4.9'}","{'datepublished': '2020-09-17', 'reviewbody': ...",{'name': 'Kathy Morton Stanion'}

'Product_lcking.com_September2020.json.gz'

,name,offers,brand,gtin8,gtin12
0,Corduroy Rover Shirt - Stone,"{'pricecurrency': 'USD', 'price': '125.00'}",LC King,2.283201e+10,2.283201e+10
1,Olive Canvas Utility Jacket,"{'pricecurrency': 'USD', 'price': '155.00'}",LC King,2.283201e+10,2.283201e+10
2,Indigo Blue Ridge Western Shirt,"{'pricecurrency': 'USD', 'price': '145.00'}",LC King,2.283201e+10,2.283201e+10
3,Washed Denim Western Jacket,"{'pricecurrency': 'USD', 'price': '165.00'}",LC King,NaN,NaN
4,Brown Duck Chore Coat,"{'pricecurrency': 'USD', 'price': '165.00'}",LC King,2.283200e+10,2.283200e+10

'Product_ebelts.com_September2020.json.gz'

,name,offers,brand,aggregaterating,category,mpn,review
0,Formal Automatic Buckle Leather Belt,"{'availability': 'https://schema.org/InStock',...",{'name': 'ebelts.com'},"{'ratingvalue': '5', 'reviewcount': '12'}",Men's Automatic Buckle Belts,53671,[{'reviewbody': 'Very fast delivery in 2 weeks...
1,Black / Brown Genuine Leather Belt,"{'availability': 'https://schema.org/InStock',...",{'name': 'ebelts.com'},"{'ratingvalue': '5', 'reviewcount': '78'}",Custom category,2182,[{'reviewbody': 'Normal belt. I can't say anyt...
2,High Quality Luxury Leather Belt,"{'pricevaliduntil': '2020-10-22', 'availabilit...",{'name': 'ebelts.com'},"{'ratingvalue': '5', 'reviewcount': '229'}",Men's Leather Belts,1273,"[{'reviewbody': 'Strap quality'}, {'reviewbody..."
3,Unisex Canvas Belts,"{'availability': 'https://schema.org/InStock',...",{'name': 'ebelts.com'},"{'reviewcount': '92', 'ratingvalue': '5'}",Men's Canvas Belts,38819,[{'reviewbody': 'Quickly sent. Not yet dressed...
4,100% Genuine Leather Automatic Buckle Belt For...,"{'availability': 'https://schema.org/InStock',...",{'name': 'ebelts.com'},None,Men's Automatic Buckle Belts,109,None

'Product_caroclic.com_September2020.json.gz'

,name,offers,brand,category,itemcondition,manufacturer
0,FACE AVANT,"{'availability': 'http://schema.org/InStock', ...",Caroclic,Face avant,NewCondition,ALFA ROMEO
1,GRILLE DE CALANDRE / SAUF S-LINE / S6,"{'availability': 'http://schema.org/InStock', ...",Caroclic,Calandre,NewCondition,AUDI
2,PARE-CHOCS ARRIERE NOIR,"{'price': '1.6284E2', 'availability': 'http://...",Caroclic,Pare-chocs arrière,NewCondition,ALFA ROMEO
3,PHARE ANTI-BROUILLARD DROIT OU GAUCHE,"{'availability': 'http://schema.org/InStock', ...",Caroclic,Feu antibrouillard,NewCondition,ALFA ROMEO
4,TRAVERSE AVANT SUPERIEURE,"{'availability': 'http://schema.org/InStock', ...",Caroclic,Traverse avant supérieure,NewCondition,AUDI

'Product_john-anthony.com_September2020.json.gz'

,name,offers,brand,mpn,color,audience
0,Skidoo Tribe Nylon Parka,"{'pricecurrency': 'GBP', 'price': '60', 'url':...","{'url': '/napapijri/', 'name': 'Napapijri'}",N0YIE8,Yellow,{'suggestedgender': 'male'}
1,Contemp Cotton-Blend Sweatshirt,"{'price': '69', 'pricecurrency': 'GBP', 'descr...","{'name': 'BOSS Bodywear', 'url': '/boss-bodywe...",50420297,Dark Blue,{'suggestedgender': 'male'}
2,Dev Suede-Leather Chelsea Boots,"{'pricecurrency': 'GBP', 'description': 'Dev S...","{'name': 'Shoe the Bear', 'url': '/shoe-the-be...",STB1354,Sand,{'suggestedgender': 'male'}
3,Slim-Fit Corduroy-Cotton Shirt,{'description': 'Slim-Fit Corduroy-Cotton Shir...,"{'name': 'Kenzo', 'url': '/kenzo/'}",FA65CH2009CX,Fern,{'suggestedgender': 'male'}
4,Alonso Suede-Leather Loafers,{'url': 'https://www.john-anthony.com/shoe-the...,"{'name': 'Shoe the Bear', 'url': '/shoe-the-be...",STB1800,Camel,{'suggestedgender': 'male'}

'Product_skifix.com_September2020.json.gz'

,name,offers,brand,mpn,itemcondition,gtin
0,LINE Sakana/Griffon 13 110mm 2019/20,"{'pricecurrency': 'SEK', 'availability': 'http...",{'name': 'BA Sportprodukter'},19D0001,http://schema.org/NewCondition,8.867458e+11
1,Head Hammered 115,"{'availability': 'http://schema.org/InStock', ...",{'name': 'Head'},None,http://schema.org/NewCondition,NaN
2,Booster Strap Intermediate,"{'price': '670', 'availability': 'http://schem...",None,None,http://schema.org/NewCondition,NaN
3,Armada Carbon Adj Pole,"{'pricecurrency': 'SEK', 'availability': 'http...",{'name': 'Armada'},19ACARBON POLE,http://schema.org/NewCondition,8.423391e+11
4,BLIZ Chin Guard - RAID,"{'pricecurrency': 'SEK', 'availability': 'http...",{'name': 'Bliz'},None,http://schema.org/NewCondition,NaN

'Product_pserviceweb.com_September2020.json.gz'

,name,offers,condition
0,DIAMOND MILLING CUTTER ball,"{'price': '2.7', 'pricecurrency': 'EUR'}",New
1,"KIT SAFE 5, lame sgorbie","{'price': '35', 'pricecurrency': 'EUR'}",Nuovo
2,"BLADES GOUGES KBlade - line \""TOP\","{'price': '14', 'pricecurrency': 'EUR'}",New
3,"STEEL MILL, ball","{'price': '11', 'pricecurrency': 'EUR'}",New
4,TRANSPARENT FILM ROLL,"{'price': '6.81', 'pricecurrency': 'EUR'}",New

'Product_dabpress.com_September2020.json.gz'

,name,offers,brand,aggregaterating,weight,gtin12
0,Personal Rosin Press - Solventess Rosin Extrac...,"[{'sku': 'dp-bj6t35-110', 'itemcondition': 'ht...",{'name': 'Dabpress'},"{'description': 'Judge.me Reviews', 'reviewcou...",19.6kg,6.007369e+11
1,Personal Rosin Press - Solventess Rosin Extrac...,"[{'sku': 'dp-bj6t35-110', 'itemcondition': 'ht...",{'name': 'Dabpress'},"{'description': 'Judge.me Reviews', 'reviewcou...",19.6kg,6.007369e+11
2,Best Industrial Rosin Press - 20 Ton Rosin Ext...,"[{'sku': 'dp-hr20t77-eu', 'gtin12': '789219684...",{'name': 'Dabpress'},None,0.0kg,7.892197e+11
3,"120 Micron Rosin Filters - 25,37,50,90,100,120...","{'gtin12': '600736914697', 'sku': 'dp-rb100n-1...",{'name': 'Dabpress'},None,0.068kg,6.007369e+11
4,Rosin Filter Mold Pack - Including 2x4&quot; M...,[{'itemcondition': 'http://schema.org/NewCondi...,{'name': 'Dabpress'},"{'description': 'Judge.me Reviews', 'ratingval...",0.8kg,7.892197e+11

'Product_chowdaheadz.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,itemcondition
0,Boston Hub T-Shirt,"[{'mpn': 'CH-3181-LT-CC-S', 'availability': 'h...",{'name': 'Chowdaheadz-T-Shirts'},"{'description': 'yotpo', 'ratingvalue': '5.0E0...",CH-3181-UT-CC-S,https://schema.org/NewCondition
1,College Wicked Smaaht T-Shirt,"[{'mpn': 'CH-1605-UT-GY-3XL', 'availability': ...",{'name': 'Chowdaheadz-T-Shirts'},"{'ratingcount': '58', 'ratingvalue': '5.0E0', ...",CH-1605-UT-GY-S,https://schema.org/NewCondition
2,Boston Neighborhood Pint Glass T-Shirt,[{'availability': 'https://schema.org/InStock'...,{'name': 'Chowdaheadz-T-Shirts'},"{'description': 'yotpo', 'ratingvalue': '5.0E0...",CH-2231-UT-CC-S,https://schema.org/NewCondition
3,Socks on Boston Terrier T-Shirt,[{'availability': 'https://schema.org/InStock'...,{'name': 'Chowdaheadz-T-Shirts'},"{'description': 'yotpo', 'ratingvalue': '5.0E0...",CH-2163-UT-GY-S,https://schema.org/NewCondition
4,Wicked Smaaht Boston Skyline T-Shirt,[{'availability': 'https://schema.org/InStock'...,{'name': 'Chowdaheadz-T-Shirts'},"{'description': 'yotpo', 'ratingcount': '9', '...",CH-2999-UT-HB-S,https://schema.org/NewCondition

'Product_howig.co.uk_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Straight Boycuts Black Hairstyles African Amer...,"{'price': '67.00', 'pricecurrency': 'GBP', 'it...",{'name': 'HoWig'},"{'bestrating': '5', 'ratingvalue': '4', 'worst...",HW02142
1,Auburn Boycuts Straight Online Short Wigs,"{'pricecurrency': 'GBP', 'price': '73.00', 'it...",{'name': 'HoWig'},"{'bestrating': '5', 'reviewcount': '4', 'worst...",HW11226
2,Bobs Straight Brown Fabulous Short Wigs,"{'pricecurrency': 'GBP', 'itemcondition': 'htt...",{'name': 'HoWig'},"{'bestrating': '5', 'reviewcount': '2', 'ratin...",HW11295
3,Straight Auburn Without Bangs Fashion Celebrit...,"{'pricecurrency': 'GBP', 'itemcondition': 'htt...",{'name': 'HoWig'},"{'bestrating': '5', 'ratingvalue': '4.6', 'wor...",HW05064
4,Auburn Without Bangs Straight Natural Cheryl C...,"{'price': '67.00', 'pricecurrency': 'GBP', 'it...",{'name': 'HoWig'},"{'bestrating': '5', 'reviewcount': '4', 'ratin...",HW05266

'Product_mexicanblankets.com_September2020.json.gz'

,name,offers,brand,aggregaterating,review
0,"Hot Pink, Gray, and White Vera Cruz Mexican Bl...","{'availability': 'http://schema.org/InStock', ...",{'name': 'Vera Cruz'},None,None
1,Dark Purple Vera Cruz Solid Color Mexican Blanket,"{'availability': 'http://schema.org/InStock', ...",{'name': 'Vera Cruz'},"{'ratingvalue': '5', 'reviewcount': '3', 'rati...",[{'reviewbody': 'I love them. This is my secon...
2,"Mint, Orange and White Vera Cruz Mexican Blanket","{'availability': 'http://schema.org/InStock', ...",{'name': 'Vera Cruz'},"{'ratingvalue': '5', 'reviewcount': '3', 'rati...","[{'name': 'Exactly what I was looking for!', '..."
3,"Turquoise Blue, Dark Purple, and White La Mont...","{'availability': 'http://schema.org/InStock', ...",{'name': 'La Montana'},"{'ratingcount': '4', 'ratingvalue': '5', 'revi...","[{'author': 'Jolene', 'name': 'Sarape', 'revie..."
4,"Hot Pink, Turquoise and Orange Vera Cruz Mexic...","{'availability': 'http://schema.org/InStock', ...",{'name': 'Vera Cruz'},"{'ratingcount': '4', 'ratingvalue': '5', 'revi...","[{'name': 'Mexican blanket', 'author': 'Vicky ..."

'Product_shop-boots.com_September2020.json.gz'

,name,offers,brand,category,gtin13
0,14642 Jaen Prince 431,[{'availability': 'https://schema.org/InStock'...,{'name': 'botasonline'},MUJER,8.434693e+12
1,7228 Torito Snowbut MS007-40,"{'price': '1.49E2', 'sku': '722800000000000004...",{'name': 'botasonline'},ÚLTIMAS TALLAS,8.434693e+12
2,9119 Gorca Negro,"[{'price': '2.89E2', 'sku': '91190000000010000...",{'name': 'Sendra Boots'},MUJER,8.434693e+12
3,Chihuahua Coñac,"[{'name': '95', 'availability': 'https://schem...",{'name': 'Sendra Boots'},COMPLEMENTOS,8.434693e+12
4,8340 Negro,"[{'name': '115', 'availability': 'https://sche...",{'name': 'Sendra Boots'},COMPLEMENTOS,8.434693e+12

'Product_carasutra.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Linx Onyx Sucker Stroker Penis Masturbator Review,"{'pricecurrency': 'GBP', 'availability': 'http...",Linx,"{'reviewcount': '1', 'ratingvalue': '6', 'best...",82009
1,Cal Exotics Apollo Vibrating Power Stroker Rev...,"{'pricecurrency': 'GBP', 'availability': 'http...",Cal Exotics,"{'reviewcount': '1', 'bestrating': '10', 'rati...",101597
2,Cal Exotics Platinum Golden Jack Rabbit Vibrat...,"{'availability': 'https://schema.org/InStock',...",Cal Exotics,"{'ratingvalue': '9', 'reviewcount': '1', 'best...",98747
3,Cal Exotics Booty Call Vibrating Anal Beads Re...,"{'availability': 'https://schema.org/InStock',...",Cal Exotics,"{'bestrating': '10', 'reviewcount': '1', 'rati...",61139
4,Spurt Premium Water Based Lubricant 250ml Revi...,"{'price': '12.99', 'pricecurrency': 'GBP', 'av...",Spurt,"{'reviewcount': '1', 'bestrating': '10', 'rati...",95932

'Product_strokedoctor.com_September2020.json.gz'

,name,offers,brand,aggregaterating,category
0,Stem Cell Therapy,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Dr. David Steenblock'},"{'ratingcount': '16', 'ratingvalue': '5', 'rev...",Services
1,Strokes and Traumatic Brain Injury,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Dr. David Steenblock'},"{'ratingcount': '16', 'ratingvalue': '5', 'rev...",Conditions
2,Stemgevity,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Dr. David Steenblock'},"{'ratingcount': '16', 'ratingvalue': '5', 'rev...",Services
3,Privacy Policy,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Dr. David Steenblock'},"{'ratingcount': '16', 'ratingvalue': '5', 'rev...",Privacy Policy
4,Contact,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Dr. David Steenblock'},"{'ratingcount': '16', 'ratingvalue': '5', 'rev...",Contact

'Product_plantgem.com_September2020.json.gz'

,name,offers,brand,mpn,itemcondition
0,ProCut Plum Sunflower,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'PlantGem'},SF-PP-P,http://schema.org/NewCondition
1,Lady's Mantle Thriller,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'PlantGem'},LM-TH-P,http://schema.org/NewCondition
2,Penhill Watermelon Dahlia Plant,"{'price': '27.0', 'itemcondition': 'http://sch...",{'name': 'PlantGem'},DH-PW-P,http://schema.org/NewCondition
3,Cupcake Pink Zinnia,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'PlantGem'},ZI-CP-P,http://schema.org/NewCondition
4,Narcissus Dick Wilden,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'PlantGem'},NA-DW-B,http://schema.org/NewCondition

'Product_landerscdjrnorman.com_September2020.json.gz'

,name,offers,brand,mpn,model,manufacturer,color
0,PRE-OWNED 2018 JEEP RENEGADE LATITUDE FWD SPOR...,"{'price': '18975', 'itemcondition': 'http://sc...",Jeep,BUTM74,Renegade,{'name': 'Jeep'},Colorado Red
1,PRE-OWNED 2012 DODGE CHARGER RT PLUS WITH NAVI...,{'itemcondition': 'http://schema.org/UsedCondi...,Dodge,LDEP48,Charger,{'name': 'Dodge'},Redline (3) Coat Pearl
2,NEW 2020 JEEP COMPASS SPORT 4X4,{'itemcondition': 'http://schema.org/NewCondit...,JEEP,MPJL74,Compass,{'name': 'JEEP'},Granite Crystal Metallic Clear-Coat Exterior P...
3,NEW 2020 JEEP CHEROKEE LATITUDE PLUS FWD,{'itemcondition': 'http://schema.org/NewCondit...,JEEP,KLTE74,Cherokee,{'name': 'JEEP'},Diamond Black Crystal Pearl-Coat Exterior Paint
4,PRE-OWNED 2013 DODGE JOURNEY SE FWD STATION WAGON,"{'price': '9261', 'itemcondition': 'http://sch...",Dodge,JCDH49,Journey,{'name': 'Dodge'},Fathom Blue Pearl

'Product_godbyhomefurnishings.com_September2020.json.gz'

,name,offers,brand,category,mpn
0,7185 Queen Sleeper,"{'pricecurrency': 'USD', 'price': '0.0E0', 'av...",{'name': 'Hickory Craft'},Sofa Sleepers,718550-68
1,085910 Chair,"{'pricecurrency': 'USD', 'price': '0.0E0', 'av...",{'name': 'Hickory Craft'},Accent Chairs,085910
2,Brighton Dreamquest Chair Sleeper,"{'pricecurrency': 'USD', 'price': '0.0E0', 'av...",{'name': 'Klaussner'},Sofa Sleepers,24900 DCSL
3,090110 Chair,"{'pricecurrency': 'USD', 'price': '0.0E0', 'av...",{'name': 'Hickory Craft'},Accent Chairs,090110
4,Montezuma Leather Studio Sofa,"{'pricecurrency': 'USD', 'price': '0.0E0', 'av...",{'name': 'Klaussner'},Sofas,LD43800 STS

'Product_climbers-shop.com_September2020.json.gz'

,name,offers,brand,itemcondition,manufacturer
0,Petzl Universal Headband,"{'pricecurrency': 'GBP', 'price': '£7.83'}",{'name': 'Petzl'},http://schema.org/NewCondition,Petzl
1,Silva Expedition Compass,"{'price': '£40.50', 'pricecurrency': 'GBP'}",{'name': 'Silva'},http://schema.org/NewCondition,Silva
2,Scarpa Womens Charmoz OD Boot,"{'price': '£240.00', 'pricecurrency': 'GBP'}",{'name': 'Scarpa'},http://schema.org/NewCondition,Scarpa
3,Coghlans Magnesium Fire Starter,"{'price': '£10.00', 'pricecurrency': 'GBP'}",{'name': 'Coghlans'},http://schema.org/NewCondition,Coghlans
4,GSI Outdoors Pinnacle 10 inch Frypan,"{'price': '£41.50', 'pricecurrency': 'GBP'}",{'name': 'GSI'},http://schema.org/NewCondition,GSI

'Product_cosmofemina.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Nuxe Nuxuriance Ultra Replenishing Serum 30ml,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Nuxe'},"{'bestrating': '5', 'reviewcount': '1', 'ratin...",24650
1,Physicians Formula Nude Wear Glowing Nude Bron...,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Physicians Formula'},"{'bestrating': '5', 'reviewcount': '1', 'ratin...",25488
2,Physicians Formula Sexy Booster Cat Eye Maskar...,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Physicians Formula'},"{'bestrating': '5', 'reviewcount': '1', 'ratin...",24689
3,Topicrem AC Purifying Cleansing Gel 200 ml - A...,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Topicrem'},"{'bestrating': '5', 'reviewcount': '1', 'ratin...",24505
4,Bionike Xage Ultimate Repair Filler Night Crea...,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'BioNike'},"{'bestrating': '5', 'reviewcount': '1', 'ratin...",24456

'Product_bommeow.com_September2020.json.gz'

,name,offers,brand,category,gtin12
0,Maxtop APCUSB-MR4074 FTDI USB Programming Cabl...,"{'price': '2.5E1', 'availability': 'https://sc...",{'name': 'Maxtop Optimal'},Programming Cable,669393970521
1,Maxtop ASK2425-Y1 1-Wire Surveillance Kit for ...,"{'availability': 'https://schema.org/InStock',...",{'name': 'Maxtop Optimal'},Clear Tube Surveillance Kit,729798817385
2,Maxtop ASK4038-K3 2-Wire Surveillance Kit for ...,"{'sku': 'ASK4038-K3', 'pricevaliduntil': '2020...",{'name': 'Maxtop Optimal'},Clear Tube Surveillance Kit,669393970156
3,Maxtop AMM300-K30-8PIN Mobile Microphone,"{'pricevaliduntil': '2020-10-08', 'availabilit...",{'name': 'Maxtop Optimal'},Accessories,897462002167
4,Bommeow BHDH40-RD-H1 Noise Isolation Headphone...,"{'availability': 'https://schema.org/InStock',...",{'name': 'BOMMEOW'},Headphone,729798820637

'Product_kostazul.com_September2020.json.gz'

,name,offers,brand,aggregaterating,gtin13,additionalproperty
0,Camiseta Polo Manga Corta Rayas,"{'price': '72000.00', 'pricecurrency': 'COP'}",{'name': 'KOSTA AZUL'},"{'worstrating': '0,0', 'reviewcount': '0', 'ra...",7703975964591,"{'name': 'sellers', 'value': 'kostaazul'}"
1,T-Shirt Basic Vinotinto,"{'price': '30000.00', 'pricecurrency': 'COP'}",{'name': 'KOSTA AZUL'},"{'worstrating': '0,0', 'reviewcount': '0', 'ra...",7703975444222,"{'name': 'sellers', 'value': 'kostaazul'}"
2,Camisa Manga Larga Moda,"{'price': '117000.00', 'pricecurrency': 'COP'}",{'name': 'KOSTA AZUL'},"{'worstrating': '0,0', 'reviewcount': '0', 'ra...",7705231134908,"{'name': 'sellers', 'value': 'kostaazul'}"
3,Pantalón Casual Fondo Entero,"{'price': '119000.00', 'pricecurrency': 'COP'}",{'name': 'KOSTA AZUL'},"{'worstrating': '0,0', 'reviewcount': '0', 'ra...",7705231236190,"{'name': 'sellers', 'value': 'kostaazul'}"
4,Camisa Manga Corta Microdiseño,"{'price': '98000.00', 'pricecurrency': 'COP'}",{'name': 'KOSTA AZUL'},"{'worstrating': '0,0', 'reviewcount': '0', 'ra...",7705231114467,"{'name': 'sellers', 'value': 'kostaazul'}"

'Product_nj.com_September2020.json.gz'

,name,offers,brand,alternatename,address
0,Poster Map of 'New Jerseros',"{'pricecurrency': 'USD', 'price': '83.0'}",None,None,None
1,Framed Map of 'New Jerseros',"{'pricecurrency': 'USD', 'price': '69.0'}",None,None,None
2,Savages hat,"{'pricecurrency': 'USD', 'price': '23.0'}",None,None,None
3,Calories Don't Count Beach Towel,"{'pricecurrency': 'USD', 'price': '39.0'}",None,None,None
4,Color Map of 'New Jerseros' Beach Towel,"{'pricecurrency': 'USD', 'price': '39.0'}",None,None,None

'Product_halilit.co.uk_September2020.json.gz'

,name,offers,brand,category,gtin13
0,Edushape Look N Sea,"{'sku': '525003', 'pricevaliduntil': '2020-10-...",{'name': 'Edushape'},Water Play,7.290017e+12
1,Halilit Castanet (Various Colours),"{'pricevaliduntil': '2020-09-29', 'availabilit...",{'name': 'Halilit'},Music,7.290003e+12
2,Terra Tropical Fish Tube,"{'pricevaliduntil': '2020-10-11', 'price': '12...",{'name': 'Terra'},Dolls and Collectibles,NaN
3,Terra Dog Family,"{'pricevaliduntil': '2020-10-11', 'availabilit...",{'name': 'Terra'},Dolls and Collectibles,NaN
4,TrueDough Colour Set - Favourite Colours,"{'sku': 'TD23009', 'pricecurrency': 'GBP', 'av...",{'name': 'TrueDough'},Arts & Crafts,4.823091e+12

'Product_marinestereo.com_September2020.json.gz'

,name,offers,brand,category,gtin
0,"JL Audio M6 8.8\"" White Sport 4 Speakers + 1 S...","{'price': '3343.95', 'availability': 'OutOfSto...",JL Audio,"JL Audio 8.8\"" Marine Speakers",699440936095
1,Wet Sounds REV Series 6x9 w/ Enclosure & Grill...,"{'availability': 'OutOfStock', 'description': ...",Wet Sounds,Featured Products,814820023138
2,Wet Sounds HTX-2 600 Watt 2 Ch. Amp,"{'price': '599.99', 'name': 'Wet Sounds HTX-2 ...",Wet Sounds,2 Channel Marine Amplifiers,814820022179
3,"JL Audio M6 7.7\"" 6 Speaker Stereo Package","{'sku': 'M6-770X-S-GwGw-60', 'name': 'JL Audio...",JL Audio,"JL Audio 7.7\"" Marine Speakers",699440936019
4,Wet Sounds REVO 6 XSW-SS White 8 Speaker Stere...,"{'availability': 'OutOfStock', 'inventorylevel...",Wet Sounds,None,814820023060

'Product_prosonic-studios.com_September2020.json.gz'

,name,offers,brand,aggregaterating,review
0,Latin & Salsa Midi Drum Library,"{'pricecurrency': 'USD', 'highprice': '99.95',...",{'name': 'Prosonic Patterns'},"{'bestrating': '5', 'ratingvalue': '5', 'ratin...","[{'datepublished': '2018-01-20', 'name': 'a wi..."
1,Prosonic's Midi Browser,"{'pricecurrency': 'USD', 'highprice': '0', 'lo...",{'name': 'Prosonic Patterns'},None,None
2,Jazz & Big Band Midi Drum Library,"{'pricecurrency': 'USD', 'highprice': '99.95',...",{'name': 'Prosonic Patterns'},"{'bestrating': '5', 'ratingvalue': '5', 'ratin...","[{'datepublished': '2018-01-20', 'name': 'a wi..."
3,Heavy Metal & Punk Midi Drum Library,"{'pricecurrency': 'USD', 'highprice': '99.95',...",{'name': 'Prosonic Patterns'},"{'bestrating': '5', 'ratingvalue': '5', 'ratin...","[{'datepublished': '2018-01-20', 'name': 'a wi..."
4,Blues & Rock-n-Roll Midi Drum Library,"{'pricecurrency': 'USD', 'highprice': '99.95',...",{'name': 'Prosonic Patterns'},"{'bestrating': '5', 'ratingvalue': '5', 'ratin...","[{'datepublished': '2018-01-20', 'name': 'a wi..."

'Product_bolgerfuneral.com_September2020.json.gz'

,name,offers,aggregaterating,review,itemcondition,model
0,Peace Eternal Wreath,"{'pricecurrency': 'USD', 'lowprice': '229.95',...","{'reviewcount': '8', 'ratingvalue': '5.00'}","[{'author': 'from -', 'description': 'our orde...",NewCondition,{'image': 'https://res.cloudinary.com/picasso/...
1,Simply Elegant Spathiphyllum,"{'pricecurrency': 'USD', 'highprice': '107.95'...","{'reviewcount': '315', 'ratingvalue': '4.97'}","[{'author': 'from -', 'description': 'I have b...",NewCondition,[{'image': 'https://res.cloudinary.com/picasso...
2,Treasured Lilies Spray,"{'pricecurrency': 'USD', 'highprice': '134.95'...","{'reviewcount': '25', 'ratingvalue': '4.96'}","[{'author': 'from Levittown - Pennsylvania', '...",NewCondition,"{'sku': 'T273-2A', 'image': 'https://res.cloud..."
3,Beautiful Heart Bouquet,"{'pricecurrency': 'USD', 'highprice': '99.95',...","{'reviewcount': '86', 'ratingvalue': '4.98'}","[{'name': 'Beautiful Heart Bouquet', 'datepubl...",NewCondition,[{'image': 'https://res.cloudinary.com/picasso...
4,Enchanted Cottage,"{'lowprice': '64.95', 'highprice': '94.95', 'p...","{'reviewcount': '62', 'ratingvalue': '4.98'}","[{'datepublished': '6/6/2020', 'author': 'from...",NewCondition,"[{'name': 'Enchanted Cottage (Premium)', 'imag..."

'Product_ilcaffeitaliano.com_September2020.json.gz'

,name,offers,brand,aggregaterating,review,gtin13
0,Napoli,"{'availability': 'https://schema.org/InStock',...",{'name': 'Il Caffè Italiano'},"{'ratingvalue': '4.6', 'reviewcount': '202'}","{'reviewbody': 'ottimo, con una gradevole schi...",8.068021e+12
1,Ethiopia,"{'availability': 'https://schema.org/InStock',...",{'name': 'Il Caffè Italiano'},None,None,NaN
2,Chocolate,"{'availability': 'https://schema.org/InStock',...",{'name': 'Il Caffè Italiano'},None,None,6.379135e+11
3,Courtesy Kit,"{'availability': 'https://schema.org/InStock',...",{'name': 'Il Caffè Italiano'},"{'reviewcount': '71', 'ratingvalue': '4.5'}",{'reviewbody': 'tutto ok molto carine estetica...,NaN
4,Ginseng,"{'availability': 'https://schema.org/InStock',...",{'name': 'Il Caffè Italiano'},None,None,6.562728e+11

'Product_cicekdiyari.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Sar� Orkide -Miraflore,"{'price': '249', 'itemcondition': 'http://sche...",{'name': '�i�ek Diyar�'},"{'bestrating': '5', 'ratingvalue': '4', 'ratin...",2807
1,�ans Hep Yan�nda Olsun,"{'price': '211', 'itemcondition': 'http://sche...",{'name': '�i�ek Diyar�'},"{'bestrating': '5', 'ratingcount': '4', 'worst...",2828
2,Tilandisia - Afrodit,"{'price': '266', 'itemcondition': 'http://sche...",{'name': '�i�ek Diyar�'},"{'bestrating': '5', 'ratingvalue': '5', 'ratin...",4133
3,Kanyon Teraryum,"{'price': '252', 'itemcondition': 'http://sche...",{'name': '�i�ek Diyar�'},"{'bestrating': '5', 'worstrating': '1', 'ratin...",3879
4,Dieffenbachia Tropic Snow,"{'price': '199', 'itemcondition': 'http://sche...",{'name': '�i�ek Diyar�'},"{'bestrating': '5', 'ratingvalue': '5', 'ratin...",4316

'Product_acclaimautoparts.com_September2020.json.gz'

,name,brand,aggregaterating,manufacturer,weight
0,Covercraft UVS100 Custom Sunscreen: 2014-19 Fi...,Curt,"{'bestrating': '5', 'ratingvalue': '0', 'revie...",Curt,40.00 LBS
1,Wagner Lighting BP1255H11B Halogen Capsule,Wagner,"{'bestrating': '5', 'ratingvalue': '0', 'revie...",Wagner,0.50 LBS
2,Wagner Lighting BP3457NA Natural Amber Miniatu...,Wagner,"{'bestrating': '5', 'ratingvalue': '0', 'revie...",Wagner,0.50 LBS
3,1PC-SM-422-15S,CoverTrend,"{'bestrating': '5', 'ratingvalue': '0', 'revie...",CoverTrend,5.00 LBS
4,Wagner Lighting BP3457NA Natural Amber Miniatu...,Wagner,"{'bestrating': '5', 'ratingvalue': '0', 'revie...",Wagner,0.50 LBS

'Product_acewashersupplies.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,36&#39;&#39; Gas Cooktop with SuperBoil&trade;,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'LG'},None,LCG3611BD
1,30&quot; Designer Chimney Wall Hood- 600 CFM -...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Verona'},None,VECHW30GSS
2,1.4 Cu. Ft. Built-In Trash Compactor - Stainle...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'KitchenAid'},"{'ratingvalue': '4.4', 'reviewcount': '213', '...",KTTS505ESS
3,29-inch Wide Bottom-Freezer Refrigerator with ...,"{'pricecurrency': 'USD', 'price': '1332.96', '...",{'name': 'Amana'},"{'ratingvalue': '4.6', 'itemreviewed': '29-inc...",ABB1921BRW
4,GE Profile&trade; 1.7 Cu. Ft. Convection Over-...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'GE Appliances'},"{'reviewcount': '41', 'ratingvalue': '4.4', 'i...",PVM9179BLTS

'Product_iq-uv.com_September2020.json.gz'

,name,offers,brand,weight,width,height,depth
0,UV Shirt V-Neck High Visible,"{'price': '36.55', 'pricecurrency': 'EUR'}",iQ-UV Herren,0.255 kg,0.25 cm,0.04 cm,0.18 cm
1,UV Hoodie Herren Strand & Meer enganliegend,"{'price': '63.31', 'pricecurrency': 'EUR'}",iQ-UV Herren,0.188 kg,0.39 cm,0.015 cm,0.39 cm
2,UV Strandhose Hippie Damen,"{'price': '58.44', 'pricecurrency': 'EUR'}",iQ-UV Damen,0.155 kg,0.18 cm,0.04 cm,0.18 cm
3,UV Shirt Hippie Mädchen Langarm,"{'price': '34.07', 'pricecurrency': 'EUR'}",IQ-UV Kinder,0.1 kg,0.18 cm,0.04 cm,0.18 cm
4,UV T-Shirt Hippie Damen Strand & Meer,"{'price': '38.94', 'pricecurrency': 'EUR'}",iQ-UV Damen,0.155 kg,0.18 cm,0.04 cm,0.18 cm

'Product_jennycraig.com.au_September2020.json.gz'

,name,offers,brand,mpn,isrelatedto
0,Vegetable Lasagne,{'itemcondition': 'http://schema.org/NewCondit...,Jenny Craig,521.0,"[{'brand': 'Jenny Craig', 'name': 'Spaghetti B..."
1,Spinach & Ricotta Cannelloni,{'itemcondition': 'http://schema.org/NewCondit...,Jenny Craig,667.0,[{'mainentityofpage': '/products/chicken-cacci...
2,Beef Sausage Roll,{'itemcondition': 'http://schema.org/NewCondit...,Jenny Craig,516.0,"[{'mainentityofpage': '/products/beef-nachos',..."
3,Rapid Results 8400kJ Vegetarian Menu 2,{'itemcondition': 'http://schema.org/NewCondit...,Jenny Craig,NaN,[{'name': 'Rapid Results 8400kJ Vegetarian Men...
4,Nut & Grain Chew,{'itemcondition': 'http://schema.org/NewCondit...,Jenny Craig,123.0,"[{'sku': '101', 'mainentityofpage': '/products..."

'Product_escapade.co.uk_September2020.json.gz'

,name,offers,brand,mpn,itemcondition,gtin13,gtin
0,Achilles Shield,"{'sku': '23992', 'gtin': '5020570239926', 'ava...",{'name': 'Smiffys'},5020570239926,https://schema.org/NewCondition,5.020570e+12,5.020570e+12
1,ABBA Bjorn Costume,"{'sku': '880363std', 'itemcondition': 'https:/...",{'name': 'Escapade'},0883028036301,https://schema.org/NewCondition,8.830280e+11,8.830280e+11
2,Twisty Economy Mask AHS,"{'price': '42.99', 'sku': 'RLFOX101', 'pricecu...",{'name': 'Escapade'},0859182005880,https://schema.org/NewCondition,8.591820e+11,8.591820e+11
3,Badge Generic Age 18,"{'pricecurrency': 'GBP', 'itemcondition': 'htt...",{'name': 'Escapade'},0048419634249,https://schema.org/NewCondition,4.841963e+10,4.841963e+10
4,Ghost Busters XL costume,"{'pricecurrency': 'GBP', 'itemcondition': 'htt...",{'name': 'Smiffys'},30369,https://schema.org/NewCondition,NaN,NaN

'Product_chemicalplanet.net_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,5-MAPB HCL,{'itemcondition': 'http://schema.org/NewCondit...,{'name': '5-MAPB HCL'},None,7315
1,4-MPD,{'itemcondition': 'http://schema.org/NewCondit...,{'name': '4-MPD'},"{'ratingvalue': '100', 'worstrating': '0', 're...",2296
2,MK-677 Nutrobal,"{'price': '35', 'itemcondition': 'http://schem...",{'name': 'MK-677 Nutrobal'},"{'ratingvalue': '100', 'worstrating': '0', 'be...",7191
3,4-HO-EPT,{'itemcondition': 'http://schema.org/NewCondit...,{'name': '4-HO-EPT'},"{'ratingvalue': '100', 'worstrating': '0', 'be...",2268
4,Dynamo,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Dynamo'},"{'reviewcount': '2', 'worstrating': '0', 'rati...",3827

'Product_cashforcars.net_September2020.json.gz'

,name,offers,brand,model,manufacturer,releasedate,color
0,2017 Nissan Versa Sedan S,None,Nissan,Versa Sedan,Nissan,2017,Fresh Powder
1,2017 Nissan Versa Sedan S,None,Nissan,Versa Sedan,Nissan,2017,Gun Metallic
2,2015 Hyundai Sonata 2.4L Sport,None,Hyundai,Sonata,Hyundai,2015,Quartz White Pearl
3,2016 Chrysler 200 Limited,"{'name': '2016 Chrysler 200 Limited', 'url': '...",Chrysler,200,Chrysler,2016,Velvet Red Pearlcoat
4,2015 Chevrolet Malibu LS,"{'name': '2015 Chevrolet Malibu LS', 'serialnu...",Chevrolet,Malibu,Chevrolet,2015,Summit White

'Product_allenhonda.com_September2020.json.gz'

,name,brand,model,manufacturer,releasedate,color
0,2020 Honda Odyssey Touring,Honda,Odyssey,Honda,2020,Modern Steel
1,2020 Honda Fit Sport,Honda,Fit,Honda,2020,Oran Fury
2,2020 Honda Civic Sedan EX-L,Honda,Civic Sedan,Honda,2020,Molten Lava
3,2020 Honda Civic Hatchback EX,Honda,Civic Hatchback,Honda,2020,Gray
4,2020 Honda Odyssey EX-L w/Navi/RES,Honda,Odyssey,Honda,2020,Modern Steel

'Product_viasweat.com_September2020.json.gz'

,name,offers,price,title
0,JOSIE,{'pricecurrency': 'USD'},$16.00 USD,"[SIZING, USE & CARE, SHIPPING]"
1,BEVERLY,{'pricecurrency': 'USD'},$19.70 USD,"[SIZING, USE & CARE, SHIPPING]"
2,LILY,{'pricecurrency': 'USD'},$13.00 USD,"[SIZING, USE & CARE, SHIPPING]"
3,EDEN,{'pricecurrency': 'USD'},$24.00 USD,"[SIZING, USE & CARE, SHIPPING]"
4,HERA 2.0,{'pricecurrency': 'USD'},$35.30 USD,"[SIZING, USE & CARE, SHIPPING]"

'Product_homemakersvilla.net_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,GE Profile&trade; 30&quot; Smart Built-In Conv...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'GE Appliances'},"{'ratingvalue': '4.6', 'itemreviewed': 'GE Pro...",PTS9000SNSS
1,LG SIGNATURE 5.8 cu. ft. Large Smart wi-fi Ena...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'LG'},"{'ratingvalue': '4.3', 'itemreviewed': 'LG SIG...",WM9500HKA
2,22 cu. ft. Smart wi-fi Enabled Side-by-Side Co...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'LG'},"{'ratingvalue': '4.0', 'reviewcount': '58', 'i...",LSXC22426S
3,GE Profile&trade; 1.1 Cu. Ft. Countertop Micro...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'GE Appliances'},"{'reviewcount': '26', 'ratingvalue': '3.7', 'i...",PEM31EFES
4,30-Inch 5-Element Electric Slide-In Convection...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'KitchenAid'},{'itemreviewed': '30-Inch 5-Element Electric S...,KSEG700EBS

'Product_amersonstravel.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review,releasedate
0,Luxury Private Dubai Tours,"{'pricecurrency': 'AED', 'availability': 'http...",{'name': 'Amerson Travel & Tours'},"{'ratingvalue': '4.8', 'reviewcount': '2500'}",13,"{'author': 'Peter', 'description': 'Luxury Pri...",2020-09-22
1,Jet Ski Sea Adventure Trip at Al Mamzar Beach ...,"{'pricecurrency': 'AED', 'availability': 'http...",{'name': 'Amerson Travel & Tours'},"{'ratingvalue': '4.8', 'reviewcount': '2500'}",13,"{'author': 'John', 'datepublished': '2020-09-2...",2020-09-26
2,Full Day Dubai City Tour - World Packages - Fl...,"{'pricecurrency': 'AED', 'availability': 'http...",{'name': 'Amerson Travel & Tours'},"{'ratingvalue': '4.8', 'reviewcount': '2500'}",13,{'description': 'Amersons Travel provides you ...,2020-09-22
3,Beat the Heat this Summer in Dubai Atlantis Aq...,"{'pricecurrency': 'AED', 'availability': 'http...",{'name': 'Amerson Travel & Tours'},"{'ratingvalue': '4.8', 'reviewcount': '2500'}",13,"{'author': 'Pedro', 'datepublished': '2020-09-...",2020-09-22
4,Dubai City Tour | Abu Dhabi City Tour Packages...,"{'pricecurrency': 'AED', 'availability': 'http...",{'name': 'Amerson Travel & Tours'},"{'ratingvalue': '4.8', 'reviewcount': '2500'}",13,{'description': 'Best dubai city tour - Half D...,2020-09-22

'Product_brilliantoutdoors.com_September2020.json.gz'

,name,offers,brand,mpn,gtin12
0,"Kuzco Bailey 10.75\"" LED Outdoor Ceiling Light...","{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Kuzco'},ec44511-gy,6.917590e+11
1,"Kuzco Sunset 5.75\"" LED Exterior Wall Light Fi...","{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Kuzco'},EW35405-BK,6.917591e+11
2,"Hinkley Miles 18.25\"" LED Exterior Hanging Lam...","{'pricecurrency': 'USD', 'price': '329.00', 'a...",{'name': 'Hinkley Lighting'},2552SI,6.406653e+11
3,"Z-Lite Landrum 18\"" LED Exterior Lighting Scon...","{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Z-Lite'},581M-BK-LED,6.856592e+11
4,"Kuzco Sunset 4.875\"" LED Outdoor Wall Sconce L...","{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Kuzco'},EW35404-BK,6.917591e+11

'Product_postfallschryslerjeepdodgeram.com_September2020.json.gz'

,name,offers,brand,mpn,model,manufacturer,color
0,NEW 2020 JEEP CHEROKEE LATITUDE LUX 4X4,{'itemcondition': 'http://schema.org/NewCondit...,JEEP,KLJE74,Cherokee,{'name': 'JEEP'},Bright White Clear-Coat Exterior Paint
1,NEW 2020 JEEP CHEROKEE TRAILHAWK&reg; 4X4,{'itemcondition': 'http://schema.org/NewCondit...,JEEP,KLJH74,Cherokee,{'name': 'JEEP'},Diamond Black Crystal Pearl-Coat Exterior Paint
2,PRE-OWNED 2019 KIA SOUL PLUS FWD 4D HATCHBACK,"{'price': '16995', 'itemcondition': 'http://sc...",Kia,B2522,Soul,{'name': 'Kia'},White
3,NEW 2020 JEEP RENEGADE LATITUDE 4X4,{'itemcondition': 'http://schema.org/NewCondit...,JEEP,BVJM74,Renegade,{'name': 'JEEP'},Black Clear-Coat Exterior Paint
4,CERTIFIED PRE-OWNED 2017 DODGE DURANGO SXT AWD,{'itemcondition': 'http://schema.org/UsedCondi...,Dodge,WDEL75,Durango,{'name': 'Dodge'},White

'Product_freemyersbestbrands.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Range Premium Knob Kit,"{'pricecurrency': 'USD', 'price': '129.99', 'a...",{'name': 'Whirlpool'},None,W10231702
1,"30&quot; Retractable Downdraft System, 600 CFM...","{'pricecurrency': 'USD', 'price': '1299.96', '...",{'name': 'KitchenAid'},{'itemreviewed': '30&quot; Retractable Downdra...,KXD4630YSS
2,36-Inch Wide Side-by-Side Refrigerator with Ex...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Maytag'},"{'ratingvalue': '3.6', 'reviewcount': '5', 'it...",MSS25C4MGB
3,Smart Capable Top Load Washer with Extra Power...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Maytag'},None,MVW7232HC
4,LG WX 65 inch Class Wallpaper 4K Smart OLED TV...,"{'pricecurrency': 'USD', 'price': '4199.96', '...",{'name': 'LG'},None,OLED65WXPUA

'Product_inksupply.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,HP 970/P1000/P1100 4 oz YELLOW,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'HP'},"{'reviewcount': '1', 'ratingvalue': '4'}",HP970-4-Y
1,MISPRO ARCHIVAL ULTRACHROME COMPATIBLE INKSET ...,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'EPSON'},"{'reviewcount': '1', 'ratingvalue': '5'}",MISPRO44-SET-MK
2,Inksupply HP5500 Yellow Ink For HP Dyebase Pri...,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'HP'},"{'reviewcount': '1', 'ratingvalue': '4'}",HP5500-4-Y
3,HP 970/P1000/P1100 4 oz YELLOW,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'HP'},"{'reviewcount': '1', 'ratingvalue': '4'}",HP970-4-Y
4,HP 970/P1000/P1100 4 oz YELLOW,"{'pricevaliduntil': '2020-10-22', 'itemconditi...",{'name': 'HP'},"{'reviewcount': '1', 'ratingvalue': '4'}",HP970-4-Y

'Product_speed-cat-shoes.org_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review
0,M?nner Puma Schuhe Drift Cat L SF In Wei?-Univ...,"{'highprice': '116.1800', 'pricecurrency': 'US...",{'name': 'No Brand'},"{'bestrating': '5', 'ratingvalue': '5', 'revie...",2017-03-17 00:02:55,"{'author': 'personal', 'reviewbody': 'cheap an..."
1,Women's Puma Tour Cat Lo L - Brown / Yellow,"{'lowprice': '59.9900', 'pricecurrency': 'USD'...",{'name': 'No Brand'},"{'bestrating': '5', 'ratingvalue': '5', 'revie...",2015-08-12 10:07:02,"{'author': 'personal', 'reviewbody': 'cheap an..."
2,Puma Cell Fusion II Graphic Golf Shoes,"{'highprice': '108.0000', 'pricecurrency': 'US...",{'name': 'No Brand'},"{'bestrating': '5', 'ratingvalue': '5', 'revie...",2016-09-08 21:08:49,"{'author': 'personal', 'reviewbody': 'cheap an..."
3,Puma Schuhe lazysect Low In Schwarz-Varsity Rot,"{'highprice': '116.1800', 'pricecurrency': 'US...",{'name': 'No Brand'},"{'bestrating': '5', 'ratingvalue': '5', 'revie...",2017-04-28 20:57:39,"{'author': 'personal', 'reviewbody': 'cheap an..."
4,Erm??igung Puma Schuhe Engine Cat Low Wei?-Sch...,"{'availability': 'http://schema.org/InStock', ...",{'name': 'No Brand'},"{'bestrating': '5', 'ratingvalue': '5', 'revie...",2017-02-24 01:08:49,"{'author': 'personal', 'reviewbody': 'cheap an..."

'Product_rhedo.com_September2020.json.gz'

,name,offers,brand,category,mpn
0,2nd HDD Caddy SATA 3.0 To SATA 2.5&#8243; SSD ...,"{'availability': 'https://schema.org/InStock',...",{'name': 'rhedo.com'},HDD ENCLOSURES,3266
1,12pcs/pack Crystal Rhinestone Flower Hair Claw...,{'name': '12pcs/pack Crystal Rhinestone Flower...,{'name': 'rhedo.com'},Buy Baby Products,6445
2,F6 Kingfast 2.5&#8243; internal 32GB 60GB 128G...,"[{'pricevaliduntil': '2020-10-22', 'availabili...",{'name': 'rhedo.com'},SSD,3312
3,2.5D 9H Screen Protector Tempered Glass For Sa...,[{'name': '2.5D 9H Screen Protector Tempered G...,{'name': 'rhedo.com'},SCREEN PROTECTORS,2492
4,Red Practical Case Volume Watermelon Kids Pen ...,"{'availability': 'https://schema.org/InStock',...",{'name': 'rhedo.com'},OFFICE &amp; SCHOOL SUPPLIES,3385

'Product_codesevenhack.net_September2020.json.gz'

,name,offers,aggregaterating,category,mpn,review,model,isrelatedto
0,VERY RARE HEAT SINK x 300,"{'price': '70', 'itemcondition': 'http://schem...",None,None,MODS,None,MODS,"[{'name': 'DESTROY ANY PORTAL x 10 | HUNTER', ..."
1,MODS,"{'pricecurrency': 'USD', 'offercount': '33', '...","{'bestrating': '5', 'ratingcount': '14', 'rati...",None,MODS,None,None,None
2,SOFTWARE,"{'pricecurrency': 'USD', 'highprice': '25', 'o...","{'bestrating': '5', 'ratingvalue': '5', 'ratin...",None,SERVICE,None,None,None
3,PERSONAL L1 MULE ACCOUNT,"{'pricevaliduntil': '2021-09-18', 'price': '1'...","{'reviewcount': '2', 'worstrating': '1', 'best...",ACCOUNTS,ACCOUNT,"[{'author': 'Samson', 'description': 'Very fas...",ACCOUNT,"[{'description': 'HYPER CUBE x 100', 'name': '..."
4,RARE MULTI HACK x 50,"{'pricecurrency': 'USD', 'itemcondition': 'htt...",None,MODS,MODS,None,MODS,[{'description': 'EXTREME PAINTER: GAME-ITEMS ...

'Product_artsper.com_September2020.json.gz'

,name,offers,brand,category,width,height
0,Série Noname Centres 30,{'acceptedpaymentmethod': ['http://purl.org/go...,{'name': 'Artsper'},Painting,{'name': '80 cm'},{'name': '80 cm'}
1,Je ne joue plus,"{'price': '9000', 'acceptedpaymentmethod': ['h...",{'name': 'Artsper'},Painting,{'name': '150 cm'},{'name': '150 cm'}
2,Alfabeto Manual de Pitt,{'sameas': 'http://www.productontology.org/id/...,{'name': 'Artsper'},Print,{'name': '35 cm'},{'name': '50 cm'}
3,Nude,{'sameas': 'http://www.productontology.org/id/...,{'name': 'Artsper'},Edition,{'name': '53 cm'},{'name': '39 cm'}
4,Flow 61,{'acceptedpaymentmethod': ['http://purl.org/go...,{'name': 'Artsper'},Peinture,{'name': '102 cm'},{'name': '102 cm'}

'Product_gardenma.com_September2020.json.gz'

,name,offers,brand,itemcondition,gtin13
0,AUTUMN AUTUMN HI TEK HOOD MASK BURGUNDY,"{'availability': 'https://schema.org/InStock',...",AUTUMN,https://schema.org/NewCondition,NaN
1,VANS VANS ROWAN PRO,"{'availability': 'https://schema.org/InStock',...",VANS,https://schema.org/NewCondition,7.722044e+11
2,AUTUMN AUTUMN HI TEK HOOD MASK BLACK,{'url': 'https://www.gardenma.com/autumn-hi-te...,AUTUMN,https://schema.org/NewCondition,NaN
3,DICKIES DICKIES FLEX REGULAR FIT STRAIGHT LEG ...,"{'pricevaliduntil': '2020-12-21', 'validfrom':...",DICKIES,https://schema.org/NewCondition,2.931137e+10
4,VOLCOM VOLCOM FRICKIN MODERN STREET CHINO PANT,"{'availability': 'https://schema.org/InStock',...",VOLCOM,https://schema.org/NewCondition,8.866086e+11

'Product_shop2luv.com_September2020.json.gz'

,name,offers,brand,aggregaterating,category,mpn,review
0,Waterproof Fitness Pedometer Smart Watches,"[{'price': '18.11', 'itemcondition': 'https://...",shop2luv.com,"{'ratingvalue': '4.8', 'ratingcount': '17'}",Smart Watches,86,[{'reviewbody': 'Thank you very much to the st...
1,Waterproof Fitness Tracker Pedometer Smart Wat...,"[{'price': '9.92', 'itemcondition': 'https://s...",shop2luv.com,None,Smart Watches,88,None
2,Waterproof Steel Fitness Pedometer Smart Watches,[{'name': 'Waterproof Steel Fitness Pedometer ...,shop2luv.com,"{'ratingvalue': '4.8', 'ratingcount': '17'}",Smart Watches,255,"[{'author': 'S***v', 'reviewbody': 'Item recei..."
3,Women’s Watches Bracelet Feminino,[{'url': 'https://shop2luv.com/womens-watches-...,shop2luv.com,None,New Arrivals,521,None
4,2019 New Pink Casual Wrist watches,"[{'price': '4.48', 'itemcondition': 'https://s...",shop2luv.com,None,New Arrivals,564,None

'Product_mbdiscountparts.com_September2020.json.gz'

,name,offers,brand,mpn,manufacturer
0,Thermostat Spring,"{'pricecurrency': 'USD', 'itemcondition': 'htt...",{'name': 'Mercedes-Benz'},9931202,{'name': 'Mercedes-Benz'}
1,Thermostat Seal,"{'pricecurrency': 'USD', 'itemcondition': 'htt...",{'name': 'Mercedes-Benz'},276201068064,{'name': 'Mercedes-Benz'}
2,Thermostat Unit,"{'pricecurrency': 'USD', 'price': '1.0614E2', ...",{'name': 'Mercedes-Benz'},1132030375,{'name': 'Mercedes-Benz'}
3,Engine Coolant Thermostat Gasket,"{'pricecurrency': 'USD', 'itemcondition': 'htt...",{'name': 'Mercedes-Benz'},6012030076,{'name': 'Mercedes-Benz'}
4,Engine Coolant Thermostat Housing,"{'price': '2.794E1', 'itemcondition': 'http://...",{'name': 'Mercedes-Benz'},6032030474,{'name': 'Mercedes-Benz'}

'Product_stanno.com_September2020.json.gz'

,name,offers,brand,color,gtin14
0,Drive Match Shirt LS,"{'mpn': '411003-5220', 'availability': 'https:...",{'name': 'Stanno'},Blue,8718726678770
1,Pride Top Round Neck,"{'mpn': '408017-5800', 'availability': 'https:...",{'name': 'Stanno'},Blue,8718726592625
2,FH Granite JR,"{'price': '1.299E1', 'availability': 'https://...",{'name': 'Stanno'},Blue,8718726497784
3,Centro Micro Pants Ladies,"{'mpn': '431201-8000', 'availability': 'https:...",{'name': 'Stanno'},Black,8718726207086
4,Lanyards,"{'mpn': '489809-0000', 'availability': 'https:...",{'name': 'Stanno'},Multi Colour,8714575238837

'Product_nallforgovernor.com_September2020.json.gz'

,name,offers,aggregaterating,review,releasedate
0,1Z0-1081-20 Pruefungssimulationen,"{'pricecurrency': 'USD', 'price': '39', 'avail...","{'reviewcount': '3622', 'ratingvalue': '4.9'}","{'author': 'Guest', 'description': 'Oracle 1Z0...",2020-08-13
1,C_TS4FI_1909-Deutsch PDF,"{'pricecurrency': 'USD', 'price': '39', 'avail...","{'reviewcount': '1654', 'ratingvalue': '4.9'}","{'author': 'Guest', 'datepublished': '2020-08-...",2020-08-09
2,70-486 Originale Fragen,"{'pricecurrency': 'USD', 'price': '39', 'avail...","{'reviewcount': '4042', 'ratingvalue': '4.9'}","{'author': 'Guest', 'description': 'Microsoft ...",2020-08-13
3,Marketing-Cloud-Developer Prüfungen,"{'pricecurrency': 'USD', 'price': '39', 'avail...","{'reviewcount': '3614', 'ratingvalue': '4.9'}","{'author': 'Guest', 'datepublished': '2020-08-...",2020-08-20
4,Advanced-RPA-Professional PDF,"{'pricecurrency': 'USD', 'price': '39', 'avail...","{'reviewcount': '2538', 'ratingvalue': '4.9'}","{'author': 'Guest', 'datepublished': '2020-08-...",2020-08-04

'Product_flowers4munich.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,model,manufacturer
0,Азалия в плантатор,"{'price': '104.99', 'pricecurrency': 'USD', 'u...",{'name': 'Paradise Promotions LTD.'},"{'reviewcount': '911', 'ratingvalue': '4.5'}",3002m,Азалия в плантатор,{'name': 'Paradise Promotions LTD.'}
1,Soul of Russia Basket,"{'price': '144.99', 'pricecurrency': 'USD', 'a...",{'name': 'Paradise Promotions LTD.'},"{'reviewcount': '911', 'ratingvalue': '4.5'}",8,Soul of Russia Basket,{'name': 'Paradise Promotions LTD.'}
2,18 червени рози,"{'pricevaliduntil': '30-10-2020', 'pricecurren...",{'name': 'Paradise Promotions LTD.'},"{'reviewcount': '911', 'ratingvalue': '4.5'}",29-18,18 червени рози,{'name': 'Paradise Promotions LTD.'}
3,Spirito dell'amore Bouquet,"{'price': '129.99', 'pricecurrency': 'USD', 'a...",{'name': 'Paradise Promotions LTD.'},"{'reviewcount': '911', 'ratingvalue': '4.5'}",4160m,Spirito dell'amore Bouquet,{'name': 'Paradise Promotions LTD.'}
4,Cesto regalo Madre Russia,"{'pricecurrency': 'USD', 'availability': 'InSt...",{'name': 'Paradise Promotions LTD.'},"{'reviewcount': '911', 'ratingvalue': '4.5'}",22,Cesto regalo Madre Russia,{'name': 'Paradise Promotions LTD.'}

'Product_artstar.com_September2020.json.gz'

,name,offers,price,shop-currency
0,WATERWALK,WATERWALK by ANDREW ZHAO by Andrew Zhao 10.1x1...,$150.00,USD
1,INFRARED PERU,INFRARED PERU by PAOLO PETTIGIANI by Paolo Pet...,$150.00,USD
2,THE LINE OF MY LIFE,THE LINE OF MY LIFE by IOANNIS LASSITHIOTAKIS ...,$150.00,USD
3,TIDES,TIDES by ANDREW ZHAO by Andrew Zhao 10.1x13.5 ...,$150.00,USD
4,THE RETURN OF NATURE NEW YORK,THE RETURN OF NATURE NEW YORK by TIMO HELGERT ...,$150.00,USD

'Product_bandarqq99.org_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,SITUS BANDAR99 ONLINE TERPERCAYA,"{'availability': 'https://schema.org/InStock',...",{'name': 'BANDARQQ - Hokikiu Situs Agen Bandar...,"{'ratingvalue': '4.5', 'reviewcount': '18372'}",925872
1,SITUS BANDAR99 ONLINE TERPERCAYA,"{'availability': 'https://schema.org/InStock',...",{'name': 'BANDARQQ - Teskiu Agen Bandar Domino...,"{'ratingvalue': '4.5', 'reviewcount': '18372'}",925872
2,SITUS BANDAR99 ONLINE TERPERCAYA,"{'availability': 'https://schema.org/InStock',...",{'name': 'BANDARQQ - Hokikiu Agen Penyedia Per...,"{'ratingvalue': '4.5', 'reviewcount': '18372'}",925872
3,SITUS BANDAR99 ONLINE TERPERCAYA,"{'availability': 'https://schema.org/InStock',...",{'name': 'BANDARQQ - Judi DominoQQ Disitus Hok...,"{'ratingvalue': '4.5', 'reviewcount': '18372'}",925872
4,SITUS BANDAR99 ONLINE TERPERCAYA,"{'availability': 'https://schema.org/InStock',...",{'name': 'BANDARQQ - Taruhan Di Agen Judi Band...,"{'ratingvalue': '4.5', 'reviewcount': '18372'}",925872

'Product_sb-components.co.uk_September2020.json.gz'

,name,offers,brand,category,gtin13
0,Official Raspberry Pi 4 Type-C Power Supply - ...,"{'pricevaliduntil': '2020-10-08', 'availabilit...",{'name': 'SB Components Ltd'},Power Supply,5.055653e+12
1,BBC micro:bit Header 40P 180 Degree Angle SMT ...,"{'availability': 'https://schema.org/InStock',...",{'name': 'SB Components'},Header,5.055653e+12
2,4N35 - 6-Pin DIP Phototransistor,"{'pricecurrency': 'GBP', 'name': 'Default Titl...",{'name': 'SB Components Ltd'},None,NaN
3,Edge Breakout for Micro:bit,"{'pricevaliduntil': '2020-10-05', 'availabilit...",{'name': 'SB Components Ltd'},Expansion Board,5.055653e+12
4,Protective Bumper Case for UNO Boards,"{'price': '2.99E0', 'availability': 'https://s...",{'name': 'SB Components'},Cases,5.055653e+12

'Product_alpinewines.co.uk_September2020.json.gz'

,name,offers,brand,model,releasedate
0,"Riesling Auslese 2009, KOLLMANN-LEX",{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Kollmann-Becker'},https://www.alpinewines.co.uk/alpineshop/riesl...,2009
1,Beaujolais Villages Blanc Cuvée Chantemerle 20...,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Jérome Lacondemine'},https://www.alpinewines.co.uk/alpineshop/beauj...,2017
2,Château de Malessert Grand Cru Féchy 2019 Cave...,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Cave de La Cote Uvavins'},https://www.alpinewines.co.uk/alpineshop/chate...,2019
3,Merlot d&#039;Yvorne &quot;Lettres de Noblesse...,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Badoux Vins'},https://www.alpinewines.co.uk/alpineshop/merlo...,2011
4,"Blaufränkisch Classic 2017, Triebaumer",{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Günter & Regina Triebaumer'},https://www.alpinewines.co.uk/alpineshop/blauf...,2017

'Product_giltee.com_September2020.json.gz'

,name,offers,brand,category,gtin8
0,The Eastside Bolt Red Triblend Women's Tee,"[{'price': '2.5E1', 'availability': 'https://s...",{'name': 'GILTEE'},tshirt,NaN
1,Have A Happy Kenosha Varsity Pullover,"[{'price': '3.5E1', 'availability': 'https://s...",{'name': 'GILTEE'},pullover,NaN
2,Wow Wee Wow Wisconsin Ringer Onesie - Navy & W...,"[{'sku': 'WW21-WW21-06NV-2', 'availability': '...",{'name': 'GILTEE'},onesie,87690312.0
3,This Is Cow We Roll Wisconsin Youth Triblend Tee,"[{'sku': 'WI-CWR-T-1', 'name': 'S(6-8)', 'pric...",{'name': 'GILTEE'},tshirt,41565256.0
4,The Wauwatosa Standard Ice Blue Triblend Unise...,[{'availability': 'https://schema.org/InStock'...,{'name': 'GILTEE'},tshirt,24509000.0

'Product_dmso-supplier.com_September2020.json.gz'

,name,offers,price,title
0,3 x Sodium Chlorite 25% + 3 x Citric Acid 50% ...,{'pricecurrency': 'EUR'},"€49,90","[Shipping Costs, FAQs | Frequently Asked Quest..."
1,2 x 750 g (1.65 lb) Natron,{'pricecurrency': 'EUR'},"€13,90","[Shipping Costs, FAQs | Frequently Asked Quest..."
2,Outlet tap for HDPE canisters,{'pricecurrency': 'EUR'},"€7,90","[Shipping Costs, FAQs | Frequently Asked Quest..."
3,Dropping Pipette,{'pricecurrency': 'EUR'},"€1,20","[Shipping Costs, FAQs | Frequently Asked Quest..."
4,500 ml (16.9 fl oz) Purified Water,{'pricecurrency': 'EUR'},"€9,90","[Shipping Costs, FAQs | Frequently Asked Quest..."

'Product_autonationtoyotasouthaustin.com_September2020.json.gz'

,name,offers,brand,mpn,manufacturer
0,Mud Guard,"{'pricecurrency': 'USD', 'price': '7.523E1', '...",{'name': 'Toyota'},7662106010j1,{'name': 'Toyota'}
1,Oxygen Sensor,"{'pricecurrency': 'USD', 'price': '1.973E2', '...",{'name': 'Lexus'},8946560150,{'name': 'Lexus'}
2,Solenoid,"{'pricecurrency': 'USD', 'itemcondition': 'htt...",{'name': 'Toyota'},4721735070,{'name': 'Toyota'}
3,Brake Pads,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Lexus'},0446533121,{'name': 'Lexus'}
4,Cargo Liner W/O Spare Wheel,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Toyota'},pt90847162,{'name': 'Toyota'}

'Product_aslangolf.co.uk_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,SKLZ Massage Bar,"{'pricecurrency': 'GBP', 'availability': 'OutO...",{'name': 'Sklz'},"{'reviewcount': '16', 'ratingvalue': '4.3'}",SSZMAS
1,Sharpie Fine Line Pen - Purple,"{'pricecurrency': 'GBP', 'url': 'https://aslan...",{'name': 'Sharpie'},"{'reviewcount': '16', 'ratingvalue': '4.3'}",PEN02PU
2,Nike Air Max 1 G Golf Shoes - Particle Grey/Un...,"{'pricecurrency': 'GBP', 'pricevaliduntil': '2...",{'name': 'Nike Golf'},"{'reviewcount': '16', 'ratingvalue': '4.3'}",CI7576-002
3,Sun Mountain 2020 H2NO Lite Stand Bag - Cadet/...,"{'pricecurrency': 'GBP', 'price': '249', 'avai...",{'name': 'Sun Mountain Golf'},"{'reviewcount': '16', 'ratingvalue': '4.3'}",20H2NOL-CWR
4,Nike Air Max 97 G Golf Shoes - Black/White,"{'pricecurrency': 'GBP', 'url': 'https://aslan...",{'name': 'Nike Golf'},"{'reviewcount': '16', 'ratingvalue': '4.3'}",CI7538-002

'Product_lionelmessijersey.org_September2020.json.gz'

,name,offers,brand,aggregaterating,category,mpn,review
0,Lionel Messi Youth Away LS Soccer Jersey 2019 ...,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",Soccer,"{'reviewcount': '5', 'ratingvalue': '4.5'}",Lionel Messi Jersey,AJ4398-100-143277,"{'description': 'Excellent quality, very good ..."
1,Lionel Messi Authentic Away LS Soccer Jersey 1...,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",Soccer,"{'reviewcount': '5', 'ratingvalue': '4.5'}",Lionel Messi Jersey,AJ4398-100-143277,"{'description': 'Excellent quality, very good ..."
2,Lionel Messi Women's Away Soccer Jersey 15/16 ...,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",Soccer,"{'reviewcount': '5', 'ratingvalue': '4.5'}",Lionel Messi Jersey,AJ4398-100-143277,"{'description': 'Excellent quality, very good ..."
3,Lionel Messi Authentic Away Soccer Jersey 2019...,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",Soccer,"{'reviewcount': '5', 'ratingvalue': '4.5'}",Lionel Messi Jersey,AJ4398-100-143277,"{'description': 'Excellent quality, very good ..."
4,Lionel Messi Authentic Home LS Soccer Jersey 1...,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",Soccer,"{'reviewcount': '5', 'ratingvalue': '4.5'}",Lionel Messi Jersey,AJ4398-100-143277,"{'description': 'Excellent quality, very good ..."

'Product_us41cars.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,2014 FORD FOCUS SE,"{'availability': 'https://schema.org/InStock',...",{'name': 'FORD'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",1FADP3F22EL213759
1,2013 DODGE DART SE,"{'availability': 'https://schema.org/InStock',...",{'name': 'DODGE'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",1C3CDFAA4DD304219
2,2007 CHEVROLET UPLANDER LS,"{'availability': 'https://schema.org/InStock',...",{'name': 'CHEVROLET'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",1GNDV23157D119482
3,2009 FORD F150,"{'price': '8995', 'availability': 'https://sch...",{'name': 'FORD'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",1FTRF12W49KC07327
4,2016 CHEVROLET CRUZE LT,"{'availability': 'https://schema.org/InStock',...",{'name': 'CHEVROLET'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",1G1BE5SM9G7246322

'Product_ankethread.com_September2020.json.gz'

,name,offers,brand,aggregaterating,review
0,100 Polyester Bag Closing Thread 10s/3/4/5,"{'price': '0.00', 'pricevaliduntil': '2140-08-...",Anke Industrial Thread,"{'reviewcount': '1', 'ratingvalue': '5'}",{'name': '100 Polyester Bag Closing Thread 10s...
1,20/6 Raw White Polyester Bag Closing Thread,"{'price': '0.00', 'pricevaliduntil': '2140-08-...",Anke Industrial Thread,"{'reviewcount': '1', 'ratingvalue': '5'}",{'description': '20/6 Raw White Polyester Bag ...
2,20/5 Polyester Sewing Thread,"{'price': '0.00', 'pricevaliduntil': '2140-08-...",Anke Industrial Thread,"{'reviewcount': '1', 'ratingvalue': '5'}","{'datepublished': '2020-09-27', 'description':..."
3,20/5 Polyester Sewing Thread,"{'price': '0.00', 'availability': 'http://sche...",Anke Industrial Thread,"{'reviewcount': '1', 'ratingvalue': '5'}","{'datepublished': '2020-09-28', 'description':..."
4,Ne10s/4 Virgin White Polyester Bag Closing Sew...,"{'price': '0.00', 'pricevaliduntil': '2140-08-...",Anke Industrial Thread,"{'reviewcount': '1', 'ratingvalue': '5'}",{'name': 'Ne10s/4 Virgin White Polyester Bag C...

'Product_gilecheese.com_September2020.json.gz'

,name,offers,brand,mpn,itemcondition
0,Aged Brick,"{'pricecurrency': 'USD', 'availability': 'http...",Gile Cheese,Aged-Brick,http://schema.org/NewCondition
1,Mild Brick,"{'price': '6.49', 'availability': 'http://sche...",Gile Cheese,Mild-Brick,http://schema.org/NewCondition
2,Buffalo Wing Cheddar,"{'pricecurrency': 'USD', 'price': '6.69', 'ava...",Gile Cheese,Buffalo-Wing-Cheddar,http://schema.org/NewCondition
3,Vegetable Garden Jack,{'pricevaliduntil': '2021-09-18T19:26:23-05:00...,Gile Cheese,Vegetable-Garden-Jack,http://schema.org/NewCondition
4,Smoked Farmers Cheese,"{'pricecurrency': 'USD', 'price': '6.79', 'ava...",Gile Cheese,Smoked-Farmers-Cheese,http://schema.org/NewCondition

'Product_monkeymotorsmn.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,1997 Dodge Viper GTS 2dr Coupe,"{'availability': 'https://schema.org/InStock',...",{'name': 'Dodge'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",1B3ER69E9VV300354
1,2009 Volkswagen Tiguan SEL 4Motion AWD 4dr SUV,"{'availability': 'https://schema.org/InStock',...",{'name': 'Volkswagen'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",WVGBV75N99W526298
2,2013 GMC Acadia Denali AWD 4dr SUV,"{'availability': 'https://schema.org/InStock',...",{'name': 'GMC'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",1GKKVTKD1DJ124441
3,2017 Ford F-250 Super Duty XL 4x4 4dr Crew Cab...,"{'price': '29995', 'availability': 'https://sc...",{'name': 'Ford'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",1FT7W2B68HED43292
4,2006 GMC Canyon SLE 4dr Crew Cab 4WD SB,"{'availability': 'https://schema.org/InStock',...",{'name': 'GMC'},"{'ratingvalue': '4.4', 'reviewcount': '89'}",1GTDT136068154359

'Product_alokitabevi.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Pearson Cutting Edge Intermediate,"{'price': '367.50', 'itemcondition': 'http://s...",{'name': 'Pearson Yayınları'},"{'bestrating': '5', 'reviewcount': '1', 'ratin...",1564
1,Cambridge Prism Listening and Speaking 1,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Cambridge Yayınları'},"{'bestrating': '5', 'reviewcount': '1', 'ratin...",1453
2,Cambridge Unlock Reading and Writing Skills 4 ...,"{'price': '208.50', 'itemcondition': 'http://s...",{'name': 'Cambridge Yayınları'},"{'bestrating': '5', 'reviewcount': '1', 'ratin...",1497
3,Pearson 3rd Edition Top Notch Fundamentals,"{'price': '379.50', 'itemcondition': 'http://s...",{'name': 'Pearson Yayınları'},"{'bestrating': '5', 'reviewcount': '1', 'ratin...",1533
4,Pearson Big English Plus 3,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Pearson Yayınları'},"{'bestrating': '5', 'reviewcount': '1', 'ratin...",1545

'Product_customboxeshub.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review
0,Custom stationery boxes,"{'price': '0.15', 'availability': 'https://sch...",{'name': 'CBH'},"{'ratingvalue': '5', 'reviewcount': '28'}",118842,{'reviewbody': 'Custom boxes was great. effici...
1,Custom cardboard boxes,"{'price': '0.15', 'availability': 'https://sch...",{'name': 'CBH'},"{'ratingvalue': '5', 'reviewcount': '28'}",118854,{'reviewbody': 'Custom boxes was great. effici...
2,Custom pizza boxes,"{'price': '0.15', 'availability': 'https://sch...",{'name': 'CBH'},"{'ratingvalue': '5', 'reviewcount': '28'}",118909,{'reviewbody': 'Custom boxes was great. effici...
3,Custom gable boxes,"{'price': '0.15', 'availability': 'https://sch...",{'name': 'CBH'},"{'ratingvalue': '5', 'reviewcount': '28'}",118903,{'reviewbody': 'Custom boxes was great. effici...
4,Custom muffin boxes,"{'price': '0.15', 'availability': 'https://sch...",{'name': 'CBH'},"{'ratingvalue': '5', 'reviewcount': '28'}",118898,{'reviewbody': 'Custom boxes was great. effici...

'Product_shophouseofnomad.com_September2020.json.gz'

,name,offers,brand,category,gtin8
0,"2'7\"" x 11'6.5\"" Brown Accents Vintage Runner","{'availability': 'https://schema.org/InStock',...",{'name': 'Shop House of Nomad'},RUGS,37780547
1,Black Loop Atelier Vase,"{'sku': 'UV.10164', 'pricevaliduntil': '2020-1...",{'name': 'Silver Nemesis'},Home & Garden,37205827
2,South Africa Woven Basket 27\,"{'availability': 'https://schema.org/InStock',...",{'name': 'Shop House of Nomad'},BASKETS,73426499
3,"3'8\"" x 8'10\"" Rose Vintage Persian Serab Runner","{'availability': 'https://schema.org/InStock',...",{'name': 'Shop House of Nomad'},RUGS,11388739
4,Grounding Stuffed Tribal Cat,"{'availability': 'https://schema.org/InStock',...",{'name': 'Shop House of Nomad'},Decor & Accessories,92180803

'Product_deesign.com_September2020.json.gz'

,name,offers,brand,category,itemcondition,model,manufacturer,availability,audience
0,18x24%20Corrugated%20Sign%20Panel,"{'pricevaliduntil': '2020-11-05', 'url': 'http...",DeeSign,Open House & Directional Signs,NEW,Y74_18X24_BLD_8,DeeSign,InStock,Real Estate Agents
1,Holds%2012x18%20or%2018x24%204mm%20corrugated%...,"{'pricevaliduntil': '2020-11-05', 'price': '1....",DeeSign,Frames Only,NEW,Y74_FO_8,DeeSign,InStock,Real Estate Agents
2,18x24%20Personalized%20Corrugated%20Foldover%2...,"{'pricevaliduntil': '2020-11-05', 'url': 'http...",DeeSign,Open House & Directional Signs,NEW,292_FHE_200,DeeSign,InStock,Real Estate Agents
3,Brochure%20Box,"{'pricevaliduntil': '2020-11-05', 'url': 'http...",DeeSign,Brochure Box,NEW,BROCHUREBOX_187,DeeSign,InStock,Real Estate Agents
4,18x24%20Main%20panel%20space%3CBR%3E%20One%206...,"{'pricevaliduntil': '2020-11-05', 'price': '24...",DeeSign,Frames Only,NEW,IND207FO,DeeSign,InStock,Real Estate Agents

'Product_chupetesgraciosos.com_September2020.json.gz'

,name,offers,brand,reviewcount,ratingvalue
0,Niño Estampadas Flores 7 Talla 31,"{'pricevaliduntil': '2021-09-24', 'price': '12...",Chupetes de Billy Bob Teth,1,5
1,Niño Estampadas Flores 7 Talla 32,"{'pricevaliduntil': '2021-09-24', 'price': '12...",Chupetes de Billy Bob Teth,1,5
2,Niño Estampadas Flores 7 Talla 34,{'url': 'https://www.chupetesgraciosos.com/chu...,Chupetes de Billy Bob Teth,1,5
3,Niño Estampadas Verano 12 Talla 31,"{'price': '12.00', 'pricecurrency': 'EUR', 'ur...",Chupetes de Billy Bob Teth,1,5
4,Billy Bob CLGOMA Alpargata Clásica Niño Suela ...,"{'price': '5.50', 'url': 'https://www.chupetes...",Chupetes de Billy Bob Teth,1,5

'Product_reinerplay.com_September2020.json.gz'

,name,offers,condition
0,Children play mat: Farm animals 150x150x3cm,"{'price': '160,55 €', 'pricecurrency': 'EUR'}",New
1,Playground tuff pads,"{'price': '174,24 €', 'pricecurrency': 'EUR'}",New
2,Set of seats with square,"{'price': '342,53 €', 'pricecurrency': 'EUR'}",New
3,Children's mat with ladybug,"{'price': '126,60 €', 'pricecurrency': 'EUR'}",New
4,Bee mat,"{'price': '103,60 €', 'pricecurrency': 'EUR'}",New

'Product_labfreezers.net_September2020.json.gz'

,name,offers,brand,mpn,itemcondition
0,So-Low Platinum Series Refrigerators,"{'pricecurrency': 'USD', 'lowprice': '5145', '...",So-Low,DHP4-23GD,NewCondition
1,ABS Standard Hazardous Location Refrigerator a...,"{'pricecurrency': 'USD', 'highprice': '6739', ...",American BioTech Supply,ABT-ERCS-30,NewCondition
2,"Marvel Scientific 24\"" All Refrigerator Flamma...","{'pricecurrency': 'USD', 'highprice': '3953', ...",Marvel Scientific,MS24RASFRW,NewCondition
3,Padlock adapter kit,"{'pricecurrency': 'USD', 'highprice': '181', '...",Eppendorf,P0625-1170,NewCondition
4,Eppendorf TCA-3 Temperature Monitor,"{'lowprice': '458', 'highprice': '2000', 'offe...",Eppendorf,P0625-1920,NewCondition

'Product_jaxgarage.com.au_September2020.json.gz'

,name,offers,category,weight,releasedate,additionalproperty,width,height,depth
0,JAX Garage: Motogadget Motoscope Mini - Digita...,"{'price': '345.00', 'pricecurrency': 'AUD', 'a...",Motogadget,"{'unitcode': 'KGM', 'value': '0.15'}",2020-08-05T12:46:19+10:00,"[{'name': 'pa_brand', 'value': 'Motogadget'}, ...","{'value': '10', 'unitcode': 'CMT'}","{'value': '8', 'unitcode': 'CMT'}","{'value': '10', 'unitcode': 'CMT'}"
1,JAX Garage: YSS Suspension ME302 Ecoline - BMW...,"{'offercount': '153', 'lowprice': '320.00', 'h...",YSS Custom Shocks,"{'value': '2.5', 'unitcode': 'KGM'}",2020-08-18T19:54:52+10:00,"[{'value': 'YSS Shocks', 'name': 'pa_brand'}, ...","{'value': '30', 'unitcode': 'CMT'}","{'value': '15', 'unitcode': 'CMT'}","{'value': '45', 'unitcode': 'CMT'}"
2,JAX Garage: motogadget Ignition Signal Sensor,"{'pricecurrency': 'AUD', 'price': '55.00', 'it...",Motogadget > Electrics,"{'unitcode': 'KGM', 'value': '0.15'}",2020-08-04T23:30:25+10:00,"[{'name': 'additional-information', 'value': '...","{'value': '10', 'unitcode': 'CMT'}","{'value': '8', 'unitcode': 'CMT'}","{'value': '20', 'unitcode': 'CMT'}"
3,JAX Garage: Honda CB750 F Top Triple Clamp Rep...,"{'pricecurrency': 'AUD', 'availability': 'http...",Jax Garage Originals,"{'unitcode': 'KGM', 'value': '0.85'}",2019-10-20T10:27:41+10:00,"[{'name': 'additional-information', 'value': '...","{'value': '12.5', 'unitcode': 'CMT'}","{'value': '6.5', 'unitcode': 'CMT'}","{'value': '42', 'unitcode': 'CMT'}"
4,JAX Garage: motogadget m.blaze pin indicator,"{'pricecurrency': 'AUD', 'price': '59.00', 'av...",Motogadget,"{'value': '0.20', 'unitcode': 'KGM'}",2020-08-05T10:43:52+10:00,"[{'value': 'Universal', 'name': 'pa_fitment'},...","{'value': '10', 'unitcode': 'CMT'}","{'value': '8', 'unitcode': 'CMT'}","{'value': '10', 'unitcode': 'CMT'}"

'Product_hl-grosshandel.com_September2020.json.gz'

,name,offers,category,manufacturer,weight,identifier,width,height,depth
0,Pricess Heartstrong - 24 Cupcake Förmchen (Pap...,"{'price': '0.00', 'serialnumber': 'PRO81115', ...",Disney,{'name': 'Procos'},{'value': '0'},5997,{'value': '0'},{'value': '0'},{'value': '0'}
1,Multicolour Balloons Fantasy - 1 Türbanner,"{'price': '0.00', 'serialnumber': 'PRO8701', '...","Banner, Kette, Girlanden &amp; Mobiles",{'name': 'Procos'},{'value': '0'},5862,{'value': '0'},{'value': '0'},{'value': '0'}
2,Cars Neon - 1 Happy Birthday Banner,"{'price': '0.00', 'serialnumber': 'PRO82634', ...",Disney Cars,{'name': 'Procos'},{'value': '0'},6246,{'value': '0'},{'value': '0'},{'value': '0'}
3,20 Golden Greatest - Dean Martin / CD,"{'price': '0.00', 'serialnumber': '90029864275...",Pop,{'name': 'MCP Sound &amp; Media GmbH'},{'value': '0'},4109,{'value': '0'},{'value': '0'},{'value': '0'}
4,ONE PIECE Piratenflagge / Fahne / Jolly Roger:...,"{'serialnumber': 'ABYDCT001', 'pricecurrency':...",One Piece,{'name': 'ABYstyle'},{'value': '0'},2854,{'value': '0'},{'value': '0'},{'value': '0'}

'Product_labuanshoppy.com_September2020.json.gz'

,name,offers,price,shop-currency
0,99026-07VM H-D® Men's Original Boot Cut Jeans,99026-07VM H-D® Men's Original Boot Cut Jeans ...,RM285.00 MYR,MYR
1,97388-17VM H-D Mens Temple Textile Faux Leathe...,97388-17VM H-D Mens Temple Textile Faux Leathe...,RM249.00 MYR,MYR
2,97366-16VW H-D Womens Trellis Criss-Cross Desi...,97366-16VW H-D Womens Trellis Criss-Cross Desi...,RM199.00 MYR,MYR
3,981019613 Summer 13 Man`s Jacket,981019613 Summer 13 Man`s Jacket VendorDUCATI ...,"RM1,199.00 MYR",MYR
4,HDKD336 - 3D B&S 2 Color Flame,HDKD336 - 3D B&S 2 Color Flame VendorHARLEY DA...,RM39.00 MYR,MYR

'Product_lashtavern.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review,itemcondition
0,Volume Essentials Kit,"{'pricecurrency': 'USD', 'price': '130.00', 'p...",Lash Tavern Eyelash Supplies,"{'reviewcount': '2', 'ratingvalue': '5.00'}",ESS-vlm,[{'datepublished': '2017-02-06T10:45:36-07:00'...,https://schema.org/NewCondition
1,5V Tweezers,"{'pricecurrency': 'USD', 'availability': 'http...",Lash Tavern Eyelash Supplies,"{'reviewcount': '2', 'ratingvalue': '5.00'}",TW-5V,[{'datepublished': '2017-10-17T21:24:42-07:00'...,https://schema.org/NewCondition
2,Clip-on Photo Magnifier,"{'pricecurrency': 'USD', 'price': '15.00', 'av...",Lash Tavern Eyelash Supplies,None,IMG-MG,None,https://schema.org/NewCondition
3,5D Premade Volume Fans,{'itemcondition': 'https://schema.org/NewCondi...,Lash Tavern Eyelash Supplies,"{'ratingvalue': '4.50', 'reviewcount': '6'}",None,[{'datepublished': '2017-12-15T23:19:24-07:00'...,None
4,Lash Nebulizer,"{'price': '75.00', 'itemcondition': 'https://s...",Lash Tavern Eyelash Supplies,"{'reviewcount': '5', 'ratingvalue': '5.00'}",None,[{'datepublished': '2017-02-13T10:47:24-07:00'...,None

'Product_creoven.co.uk_September2020.json.gz'

,name,offers,category,manufacturer,weight,identifier,width,height,depth,disambiguatingdescription
0,LEDS-C4 Design Ceiling Fan Belmont 132 cm / 52...,"{'serialnumber': '30-4357-81-82 + PAN 146-', '...",120 - 139 cm / 47&quot; - 55&quot;,{'name': 'LEDS C4'},{'value': '7400'},2118,{'value': '0'},{'value': '0'},{'value': '0'},• max. 50 Watts current consumption • Ø 132 cm...
1,Westinghouse ceiling fan Vegas White 105cm / 4...,"{'serialnumber': '72185', 'price': '92.50', 'i...",100 - 119 cm / 40&quot; - 47&quot;,{'name': 'Westinghouse'},{'value': '5000'},1419,{'value': '209'},{'value': '227'},{'value': '430'},&lt;p&gt;max. 39 W motor wattage&lt;/p&gt; &lt...
2,Ceiling fan Petite antique brass with pull cor...,"{'serialnumber': '78603', 'itemcondition': 'Ne...",&lt; 100 cm / 40&quot;,{'name': 'Westinghouse'},{'value': '5200'},2697,{'value': '18'},{'value': '26'},{'value': '44'},• max. power consumption 52 Watt • Ø 76cm / 30...
3,Ceiling fan Steel-Star with pull cord 132cm / ...,"{'serialnumber': 'BC 803-XXL', 'price': '189.0...",120 - 139 cm / 47&quot; - 55&quot;,{'name': 'Deko-Elektro'},{'value': '7300'},1100,{'value': '0'},{'value': '0'},{'value': '0'},&lt;p&gt;max. 65 W motor wattage&lt;/p&gt; &lt...
4,Blade holder set for Eco Neo ceiling fan in va...,"{'price': '29.50', 'serialnumber': '41322311',...",Spare parts for ceiling fans,{'name': 'CasaFan'},{'value': '1300'},8565,{'value': '0'},{'value': '0'},{'value': '0'},• Blade holders for Eco Neo ceiling fan • Diff...

'Product_butikjamtangan.com_September2020.json.gz'

,name,offers,brand,category,mpn
0,ZAZPIGARREN 17 GAIZKO TXANODUNA (10 VARIAN),"{'pricevaliduntil': '2020-10-29', 'availabilit...",butikjamtangan.com,None,18058
1,HAMARGO HIRUGARREN KANPOKO TXANGOA (6 VARIAN),"{'pricevaliduntil': '2020-10-29', 'availabilit...",butikjamtangan.com,None,7444
2,KPOP ZAZPIKO MUNDUKO TOUR TXIKIA (8 VARIAN),"{'pricevaliduntil': '2020-10-29', 'availabilit...",butikjamtangan.com,None,16423
3,Zazpigarren manga motza HOODIE (15 VARIAN),"{'pricevaliduntil': '2020-10-29', 'availabilit...",butikjamtangan.com,None,8420
4,LOSE YOU TO LOVE ME SELENA GOMEZ IPHONE CASE (...,"{'availability': 'https://schema.org/InStock',...",butikjamtangan.com,None,16287

'Product_tresorbleu.com_September2020.json.gz'

,name,offers,price,title
0,Gold Beaded Necklace,{'pricecurrency': 'USD'},$95.00,"[We think Outside (and Inside) the Box, Reviews]"
1,Anniversary d'Lourdes Necklace - Reproduction/...,{'pricecurrency': 'USD'},$50.00,"[We think Outside (and Inside) the Box, Reviews]"
2,Croix d' Lourdes Necklace - 1958,{'pricecurrency': 'USD'},$150.00,"[We think Outside (and Inside) the Box, Reviews]"
3,Maria de la Salut Necklace - c. 1940,{'pricecurrency': 'USD'},$100.00,"[We think Outside (and Inside) the Box, Reviews]"
4,Gold Saint Benedict Medal - Non-Vintage,{'pricecurrency': 'USD'},$100.00,"[We think Outside (and Inside) the Box, Reviews]"

'Product_kablosepeti.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,HDMI Splitter 8 Port - Ultra HD 4K*2K - 3D,"{'availability': 'http://schema.org/InStock', ...",{'name': 'upTech'},"{'reviewcount': '1', 'ratingvalue': '4'}",552
1,Vention USB 3.0 Uzatma Kablosu 1.5 Metre,"{'availability': 'http://schema.org/SoldOut', ...",{'name': 'Vention'},"{'reviewcount': '1', 'ratingvalue': '4'}",1137
2,USB 3.1 Type C - USB 2.0 Dönüştürücü Kablo 20 Cm,"{'pricecurrency': 'TRY', 'availability': 'http...",{'name': 'Kablosepeti'},"{'reviewcount': '1', 'ratingvalue': '5'}",931
3,Orjinal Apple Lightning to USB Kablo 1 Metre M...,"{'availability': 'http://schema.org/SoldOut', ...",{'name': 'Apple'},"{'reviewcount': '1', 'ratingvalue': '4'}",1067
4,Stereo 3.5mm to 3.5mm Aux Kablo 10 Metre,"{'price': '47.01', 'availability': 'http://sch...",{'name': 'Kablosepeti'},"{'reviewcount': '1', 'ratingvalue': '4'}",1494

'Product_4pmti.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,PMP Training in Fort-Lauderdale,"{'pricevaliduntil': '2020-12-31', 'price': '19...",{'description': 'Join our guaranteed to run PM...,"{'ratingvalue': '5', 'reviewcount': '2500'}",pmp01
1,PMP Training in Princeton,"{'pricevaliduntil': '2020-12-31', 'pricecurren...",{'description': 'Join our guaranteed to run PM...,"{'ratingvalue': '5', 'reviewcount': '2500'}",pmp01
2,PMP Training in Rockville,"{'pricevaliduntil': '2020-12-31', 'pricecurren...",{'description': 'Join our guaranteed to run PM...,"{'ratingvalue': '5', 'reviewcount': '2500'}",pmp01
3,PMP Training in Alexandria,"{'pricevaliduntil': '2020-12-31', 'price': '19...",{'description': 'Join our guaranteed to run PM...,"{'ratingvalue': '5', 'reviewcount': '2500'}",pmp01
4,PMP Training in Manassas,"{'pricevaliduntil': '2020-12-31', 'price': '19...",{'description': 'Join our guaranteed to run PM...,"{'ratingvalue': '5', 'reviewcount': '2500'}",pmp01

'Product_wholesaleleathersupplier.com_September2020.json.gz'

,name,offers,brand,mpn,itemcondition
0,Casual Messenger CrossBody Leather Shoulder Bag,[{'availability': 'https://schema.org/InStock'...,{'name': 'WholesaleLeatherSupplier.com'},797337631532,https://schema.org/NewCondition
1,Unisex Genuine Leather Bi-fold Zip Around Larg...,"[{'pricevaliduntil': '2020-10-27', 'mpn': '797...",{'name': 'WholesaleLeatherSupplier.com'},797337647816,https://schema.org/NewCondition
2,Fringe Hobo Bag - Soft Genuine Leather Black C...,[{'availability': 'https://schema.org/InStock'...,{'name': 'WholesaleLeatherSupplier.com'},797337636278,https://schema.org/NewCondition
3,Leather Cigarette Case,"[{'pricevaliduntil': '2020-10-27', 'sku': 'MA-...",{'name': 'WholesaleLeatherSupplier.com'},766544162849,https://schema.org/NewCondition
4,Genuine Leather Magnetic Money Clip,[{'availability': 'https://schema.org/InStock'...,{'name': 'WholesaleLeatherSupplier.com'},797337649018,https://schema.org/NewCondition

'Product_prontocharger.com_September2020.json.gz'

,name,offers,brand,aggregaterating,weight
0,Acer Aspire 6930ZG Series Laptop Power AC Adap...,"{'pricecurrency': 'USD', 'price': '$17.85'}",{'name': 'Acer'},"{'ratingvalue': '0', 'reviewcount': '0'}",1.00 LBS
1,Acer Aspire 4520 Series Laptop Power AC Adapte...,"{'pricecurrency': 'USD', 'price': '$17.85'}",{'name': 'Acer'},"{'ratingvalue': '0', 'reviewcount': '0'}",1.00 LBS
2,Acer Aspire 5235 Series Laptop Power AC Adapte...,"{'pricecurrency': 'USD', 'price': '$17.85'}",{'name': 'Acer'},"{'ratingvalue': '0', 'reviewcount': '0'}",1.00 LBS
3,Acer Ferrari 5000 Series Laptop Power AC Adapt...,"{'pricecurrency': 'USD', 'price': '$17.85'}",{'name': 'Acer'},"{'ratingvalue': '0', 'reviewcount': '0'}",1.00 LBS
4,Acer Aspire 5552 Series Laptop Power AC Adapte...,"{'pricecurrency': 'USD', 'price': '$17.85'}",{'name': 'Acer'},"{'ratingvalue': '0', 'reviewcount': '0'}",1.00 LBS

'Product_artimagepublications.com_September2020.json.gz'

,name,offers,breadcrumb
0,Inside the Sugar-Shack,"{'pricecurrency': 'USD', 'price': '8.65'}",Home/Art Reproductions/Inside the Sugar-Shack
1,Yellow Street II,"{'pricecurrency': 'USD', 'price': '8.65'}",Home/Art Reproductions/Yellow Street II
2,Snack for Two,"{'pricecurrency': 'USD', 'price': '8.65'}",Home/Art Reproductions/Snack for Two
3,Art First Nations: Elementary Teacher’s Guide,"{'pricecurrency': 'USD', 'price': '46.95'}",Home/Teachers’ Resources/Guides/Art First Nati...
4,Haymakers,"{'pricecurrency': 'USD', 'price': '8.65'}",Home/Art Reproductions/Haymakers

'Product_aplevel.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review
0,Bluetooth scales floor Body Weight Bathroom Sc...,{'url': 'https://aplevel.com/product/bluetooth...,https://aplevel.com,"{'reviewcount': '36', 'ratingvalue': '4.97'}",3344,None
1,LCD Wireless Weather Station Alarm Clock Digit...,{'url': 'https://aplevel.com/product/lcd-wirel...,https://aplevel.com,"{'reviewcount': '14', 'ratingvalue': '4.79'}",2867,None
2,Smoking Tobacco Pouch Genuine Leather Tobacco ...,"{'price': '27.99', 'pricecurrency': 'USD', 'pr...",https://aplevel.com,"{'reviewcount': '13', 'ratingvalue': '4.92'}",2883,None
3,Eco-Friendly Bamboo Fiber Cleaning Cloths Set,"{'price': '9.99', 'pricecurrency': 'USD', 'url...",https://aplevel.com,"{'reviewcount': '1', 'ratingvalue': '5.00'}",990,None
4,LED Motion Sensor Light Cupboard Wardrobe Bed ...,"{'price': '9.99', 'pricecurrency': 'USD', 'pri...",https://aplevel.com,"{'ratingvalue': '5.00', 'reviewcount': '18'}",7605,None

'Product_childtherapytoys.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,LifeSteps: Developing Healthy Relationships DVD,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",{'name': 'ChildTherapyToys'},"{'ratingvalue': '4.8', 'reviewcount': '50'}",249163700
1,Portable Child & Play Therapy Games Set,"{'price': '307.43', 'pricecurrency': 'AUD', 'a...",{'name': 'ChildTherapyToys'},"{'ratingvalue': '4.8', 'reviewcount': '50'}",221161400
2,Doctor Puppet/Dr. Coz,"{'pricevaliduntil': '2024-11-11', 'pricecurren...",{'name': 'ChildTherapyToys'},"{'ratingvalue': '4.8', 'reviewcount': '50'}",138H53000
3,Doll Clothes - Career Set,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",{'name': 'ChildTherapyToys'},"{'ratingvalue': '4.8', 'reviewcount': '50'}",103482100x
4,All-In-One Kitchen Island,"{'price': '3.4995E2', 'pricevaliduntil': '2024...",{'name': 'ChildTherapyToys'},"{'ratingvalue': '4.8', 'reviewcount': '50'}",999492400

'Product_highclassmobile.com_September2020.json.gz'

,name,offers,brand,category,gtin12
0,LG V30 - H932 - 64GB - T-Mobile Smartphone 10/10,"{'pricevaliduntil': '2020-10-06', 'availabilit...",{'name': 'LG'},Cell Phones & Smartphones,2.289517e+11
1,Samsung Galaxy A50 SM-A505U - 64GB - GSM Unloc...,"[{'pricecurrency': 'USD', 'price': '204.50', '...",{'name': 'Samsung'},Cell Phones & Smartphones,8.987235e+11
2,Samsung Galaxy Note 5 N920 - 32GB - GSM Unlock...,"[{'name': 'Gold / OPEN BOX', 'pricevaliduntil'...",{'name': 'Samsung'},Cell Phones & Smartphones,3.240883e+11
3,LG Series K10 - K428 - 16GB - T-Mobile Smartph...,"{'price': '43.50', 'sku': 'D70-3686', 'availab...",{'name': 'LG'},Cell Phones & Smartphones,5.347731e+11
4,Google Pixel 3A - 64GB - T-Mobile Smartphone 9/10,"{'price': '174.50', 'pricecurrency': 'USD', 'a...",{'name': 'Google'},Cell Phones & Smartphones,3.837596e+11

'Product_qualite-pieces-auto.com_September2020.json.gz'

,name,offers,brand,aggregaterating,review,itemcondition,gtin8
0,1 Pouce Douille Hex Petit Du 67MM,{'url': 'https://www.qualite-pieces-auto.com/f...,None,"{'ratingvalue': '4.8', 'ratingcount': '96'}",{'author': 'null'},None,8435034103373
1,1/2 Pouce DOUILLE HEX PETIT DU 10MM,{'url': 'https://www.qualite-pieces-auto.com/f...,None,"{'ratingvalue': '4.8', 'ratingcount': '96'}",{'author': 'null'},None,8435034100617
2,1/2 Pouce DOUILLE HEX PETIT DU 20MM,"{'price': '3.5', 'pricevaliduntil': '2020-09-2...",None,"{'ratingvalue': '4.8', 'ratingcount': '96'}",{'author': 'null'},None,8435034100716
3,10x SOUPAPES POUR RÉF. 53599 - 6x22 mm,"{'price': '8.9', 'url': 'https://www.qualite-p...",None,"{'ratingvalue': '4.8', 'ratingcount': '96'}",{'author': 'null'},None,8435034146004
4,3 POUCE KIT POUR LA MACHINE DE POLISSAGE PNEUM...,{'url': 'https://www.qualite-pieces-auto.com/f...,None,"{'ratingvalue': '4.8', 'ratingcount': '96'}",{'author': 'null'},None,8435034535761

'Product_selwood.com_September2020.json.gz'

,name,offers,brand,aggregaterating,review,model,gtin13,weight
0,Selwood Knotted Climbing Rope,"{'price': '1.999E1', 'pricecurrency': 'GBP', '...",Selwood,None,None,216691,5.060222e+12,2.0000 kg
1,Hazelwood Climbing Frame,"{'pricecurrency': 'GBP', 'price': '599', 'acce...",Selwood,"{'bestrating': '5', 'ratingvalue': '4.9E0', 'w...","[{'datepublished': '12/04/2018 10:37', 'descri...",216509,5.060222e+12,84.0000 kg
2,Selwood 2-Child Back-to-Back Glider Swing,"{'price': '99', 'pricecurrency': 'GBP', 'accep...",Next Generation,None,None,B24968,8.752570e+11,7.0000 kg
3,Kettler Double Swing,"{'price': '1.1999E2', 'pricecurrency': 'GBP', ...",Selwood,None,None,8383100,5.060222e+12,19.0000 kg
4,Selwood Vinyl Chalk Sheet,"{'pricecurrency': 'GBP', 'acceptedpaymentmetho...",Selwood,None,None,216707,NaN,1.0000 kg

'Product_boutonjaune.com_September2020.json.gz'

,name,offers,price,shop-currency
0,Chaussons de ratine de velours,Picottin Gris - $10.00 Picottin Corail - $10.0...,$10.00,CAD
1,Housse de couette - Petite Bohémienne,Fleuri/Crème / Avec - $148.00 Fleuri/Crème / S...,$88.00,CAD
2,Cache oreiller 10/13 bande plate - Liberté en ...,Rayure grise / Avec - $27.00 Rayure grise / Sa...,$15.00,CAD
3,Chaussons de coton organique,Crème - $10.00 Blanc - $10.00 Gris - $10.00 Bl...,$10.00,CAD
4,Grande Sortie de bain,Petite rayure - $68.00 Fleurs fond blanc - $68...,$68.00,CAD

'Product_jeparawoodenfurniture.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review
0,Coin Wooden Wall Decor,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Wisanka Furniture'},"{'ratingvalue': '5', 'reviewcount': '1543'}",866,"{'datepublished': '2019-07-26T10:20:22+07:00',..."
1,Uraina Master Classic Bed Room,{'pricevaliduntil': '2020-02-21T10:11:48+07:00...,{'name': 'Jepara Wooden Furniture'},"{'reviewcount': '1', 'ratingvalue': '5'}",594,"{'author': 'gagat', 'description': 'If you nee..."
2,Valerry Classic Bed Room,{'pricevaliduntil': '2020-02-21T10:11:26+07:00...,{'name': 'Jepara Wooden Furniture'},"{'reviewcount': '1', 'ratingvalue': '5'}",595,"{'datepublished': '2019-07-25T08:43:51+07:00',..."
3,Matahari Reclaimed Teak Mirror,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Wisanka Furniture'},"{'ratingvalue': '5', 'reviewcount': '1543'}",762,"{'author': 'gagat', 'description': 'Matahari T..."
4,Charlotte Classic Dining Furniture,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Wisanka Furniture'},"{'ratingvalue': '5', 'reviewcount': '1543'}",242,"{'author': 'gagat', 'datepublished': '2019-07-..."

'Product_lendingexpert.co.uk_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Logbook Loans,None,Logbook Loans,"{'bestrating': '5', 'reviewcount': '2', 'ratin...",NaN
1,Mortgages,None,Mortgages,"{'bestrating': '5', 'reviewcount': '2', 'ratin...",NaN
2,Saving Accounts,{'price': '0.00'},Saving Accounts,"{'bestrating': '5', 'ratingvalue': '4', 'ratin...",1.0
3,Credit Cards,{'price': '0.00'},Credit Cards,"{'bestrating': '5', 'ratingvalue': '5', 'ratin...",1.0
4,Lendfair Review 2018 [Read Our Experts Opinion],{'price': '0.00'},Lendfair Review 2018 [Read Our Experts Opinion],"{'bestrating': '5', 'ratingvalue': '4', 'ratin...",1.0

'Product_absolutedoor.net_September2020.json.gz'

,name,offers,brand,aggregaterating,review
0,New Garage Door Roller Replacement Free Estimate,"{'availability': 'https://schema.org/InStock',...",Absolute Overhead Door,"{'worstrating': '1.0', 'ratingvalue': '5.0', '...","[{'datepublished': '2020-09-19T18:48:10.450Z',..."
1,[Garage Door Panel Repair Diagnostic: After Ho...,[{'availability': 'https://schema.org/InStock'...,Absolute Overhead Door,"[{'worstrating': '1.0', 'ratingvalue': '5.0', ...","[{'author': 'Angel Ortiz', 'datepublished': '2..."
2,Free Garage Door Opener Repair Diagnostic,"{'availability': 'https://schema.org/InStock',...",Absolute Overhead Door,"{'worstrating': '1.0', 'ratingvalue': '5.0', '...","[{'datepublished': '2020-09-19T18:48:10.450Z',..."
3,Free Garage Door Roller Repair Diagnostic,"{'availability': 'https://schema.org/InStock',...",Absolute Overhead Door,"{'worstrating': '1.0', 'ratingvalue': '5.0', '...","[{'datepublished': '2020-09-19T18:48:10.450Z',..."
4,Garage Door Seal Maintenance + No Breakdown Gu...,{'name': 'Garage Door Seal Maintenance + No Br...,Absolute Overhead Door,"{'worstrating': '1.0', 'ratingvalue': '5.0', '...","[{'datepublished': '2020-09-15T23:02:55.320Z',..."

'Product_windyhillfarmtoys.com_September2020.json.gz'

,name,offers,brand,itemcondition,weight
0,1/64 Cody Shay’s Red Edge Pro International 12...,"{'pricecurrency': 'USD', 'price': '42'}",{'name': 'International'},New,1.00 LBS
1,1/64 After Midnight Pulling truck,"{'pricecurrency': 'USD', 'price': '45'}",{'name': 'Chevy'},New,1.00 LBS
2,1/64 John Deere Forage Harvester,"{'pricecurrency': 'USD', 'price': '9'}",{'name': 'John Deere'},Used,2.00 LBS
3,1/43 John Deere 8020,"{'pricecurrency': 'USD', 'price': '50'}",{'name': 'John Deere'},Used,1.00 LBS
4,1/64 New Holland 125th Anniversary Set,"{'pricecurrency': 'USD', 'price': '31.89'}",{'name': 'New Holland'},New,2.00 LBS

'Product_philipjonesjewellery.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,itemcondition,gtin13
0,Silver Angel Wing Earrings,"{'pricevaliduntil': '2020-12-21', 'itemconditi...",{'name': 'Philip Jones Jewellery'},"{'ratingvalue': '4.62', 'ratingcount': '8'}",5060684822270,http://schema.org/NewCondition,5.060685e+12
1,Initial Earrings Letter Y Created with Swarovs...,"{'price': '14.99', 'itemcondition': 'http://sc...",{'name': 'Philip Jones Jewellery'},None,5060684826254,http://schema.org/NewCondition,5.060685e+12
2,Capricorn Zodiac Necklace Created with Swarovs...,"{'pricevaliduntil': '2020-12-21', 'itemconditi...",{'name': 'Philip Jones Jewellery'},"{'ratingvalue': '5.0', 'ratingcount': '1'}",5056362412093,http://schema.org/NewCondition,5.056362e+12
3,Silver Five Stone Hoop Earrings Created with S...,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Philip Jones Jewellery'},"{'ratingvalue': '5.0', 'ratingcount': '3'}",5060684826445,http://schema.org/NewCondition,5.060685e+12
4,Big Sister Heart Necklace with Quote Card Crea...,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Philip Jones Jewellery'},None,5056362412611,http://schema.org/NewCondition,5.056362e+12

'Product_infinitimv.com_September2020.json.gz'

,name,offers,brand,mpn,model,manufacturer,color
0,New 2020 INFINITI QX60 PURE FWD,{'itemcondition': 'http://schema.org/NewCondit...,INFINITI,84110,QX60,{'name': 'INFINITI'},Majestic White
1,New 2020 INFINITI QX60 LUXE FWD,{'itemcondition': 'http://schema.org/NewCondit...,INFINITI,84310,QX60,{'name': 'INFINITI'},Deep Bordeaux
2,Certified Pre-Owned 2019 INFINITI QX60 LUXE FWD,{'itemcondition': 'http://schema.org/UsedCondi...,INFINITI,84319,QX60,{'name': 'INFINITI'},MAJESTIC WHITE
3,New 2020 INFINITI QX60 LUXE AWD,{'itemcondition': 'http://schema.org/NewCondit...,INFINITI,84210,QX60,{'name': 'INFINITI'},BLACK OBSIDIAN
4,New 2020 INFINITI Q50 3.0t LUXE RWD,"{'price': '39875', 'itemcondition': 'http://sc...",INFINITI,90310,Q50,{'name': 'INFINITI'},Liquid Platinum

'Product_erikapena.com_September2020.json.gz'

,name,offers,brand,category,gtin8
0,Lola + Ella Maternity Dress Bundle,"[{'price': '7.56E2', 'name': 'SIENNA / O/S', '...",{'name': 'Erika Peña'},BUNDLE,42234957.0
1,Giza Pyramid Stack Ring,"[{'sku': 'GIZASTACKPYRRINGSP9', 'pricevalidunt...",{'name': 'Erika Peña'},RINGS,13357575.0
2,Ana Rumba Skirt,"[{'pricevaliduntil': '2020-10-06', 'name': 'DE...",{'name': 'Erika Peña'},SKIRT,58927181.0
3,Toka Bracelet,"[{'pricevaliduntil': '2020-10-06', 'availabili...",{'name': 'Erika Peña'},BRACELET,36408141.0
4,Eva Rumba Shirt Dress,"[{'pricevaliduntil': '2020-10-05', 'availabili...",{'name': 'Erika Peña'},MAXI DRESS,17784653.0

'Product_flowers4armenia.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,model,manufacturer
0,"6 trandafiri roz, 4 cală crini","{'price': '54.00', 'pricevaliduntil': '28-10-2...",{'name': 'Paradise Promotions LTD.'},"{'reviewcount': '911', 'ratingvalue': '4.5'}",BQP113,"6 trandafiri roz, 4 cală crini",{'name': 'Paradise Promotions LTD.'}
1,20 mekane ružičaste ruže,"{'price': '79.00', 'pricevaliduntil': '22-10-2...",{'name': 'Paradise Promotions LTD.'},"{'reviewcount': '911', 'ratingvalue': '4.5'}",BQP110,20 mekane ružičaste ruže,{'name': 'Paradise Promotions LTD.'}
2,24 crvenih ruža u košari,"{'price': '79.00', 'pricecurrency': 'USD', 'av...",{'name': 'Paradise Promotions LTD.'},"{'reviewcount': '911', 'ratingvalue': '4.5'}",BQR112,24 crvenih ruža u košari,{'name': 'Paradise Promotions LTD.'}
3,"Trandafiri, crini si Geberas","{'price': '54.00', 'pricecurrency': 'USD', 'av...",{'name': 'Paradise Promotions LTD.'},"{'reviewcount': '911', 'ratingvalue': '4.5'}",BQM105,"Trandafiri, crini si Geberas",{'name': 'Paradise Promotions LTD.'}
4,100 trandafiri albi,"{'pricevaliduntil': '25-10-2020', 'url': 'arma...",{'name': 'Paradise Promotions LTD.'},"{'reviewcount': '911', 'ratingvalue': '4.5'}",BQW118,100 trandafiri albi,{'name': 'Paradise Promotions LTD.'}

'Product_icelectdata1.com_September2020.json.gz'

,name,offers,brand,category,mpn
0,1N4004G,"{'description': '1N4004G Part Search,1N4004G S...",ONS MOTOROLA PHILIPS FAIRCHILD VISHAY TOSHIBA ...,"Electronic Components : Hard to Find, Obsolete",1N4004G
1,1N4938,"{'description': '1N4938 Part Search,1N4938 Sea...",FAIRCHILD,"Electronic Components : Hard to Find, Obsolete",1N4938
2,1N4682,"{'price': '1.00', 'pricecurrency': 'USD', 'sel...",UNKNOWN,"Electronic Components : Hard to Find, Obsolete",1N4682
3,106404570,"{'price': '1.00', 'url': 'https://icelect.com/...",UNKNOWN,"Electronic Components : Hard to Find, Obsolete",106404570
4,13680281,"{'price': '1.00', 'pricecurrency': 'USD', 'sel...",UNKNOWN,"Electronic Components : Hard to Find, Obsolete",13680281

'Product_elementactivewear.com_September2020.json.gz'

,name,offers,brand,mpn,identifier,gtin8,gtin
0,Puffer Vest Black - XS / Black,"{'price': '2480.0', 'pricecurrency': 'MXN', 'u...",Alala,82696757,82696757,82696757,82696757
1,Bolt Tight - M / Black/Yellow/White,"{'price': '2880.0', 'url': '/products/bolt-tig...",Alala,37271093,37271093,37271093,37271093
2,Jacquard Midi Pant - S,"{'url': '/products/jacquard-midi-pant', 'price...",The Upside,5477429,5477429,5477429,5477429
3,Body Bra Army - XS / Army,"{'url': '/products/body-bra-army', 'pricecurre...",Heroine Sport,58619445,58619445,58619445,58619445
4,Edge Ankle Tight - S / Ultraviolet,"{'url': '/products/edge-ankle-tight', 'price':...",Alala,44938805,44938805,44938805,44938805

'Product_usfarmer.com_September2020.json.gz'

,name,offers,brand,itemcondition,availability
0,Farmall Grill Pinstripe T-Shirt,"{'pricecurrency': 'USD', 'price': '$13.50'}",Farmall,new,Out of stock
1,Smith & Wesson Distressed Tea Stained Cap,"{'pricecurrency': 'USD', 'price': '$17.00'}",Smith & Wesson,new,In stock
2,Smith & Wesson Eagle Cap,"{'pricecurrency': 'USD', 'price': '$19.00'}",Smith & Wesson,new,Out of stock
3,IH Mesh Trucker Cap - Black,"{'pricecurrency': 'USD', 'price': '$25.95'}",International Harvester,new,Out of stock
4,John Deere Farm Animal Squares T-Shirt,"{'pricecurrency': 'USD', 'price': '$11.50'}",John Deere,new,Out of stock

'Product_silksisters.com.au_September2020.json.gz'

,name,offers,price,shop-currency
0,Emma Pants Red Spot,"Emma Pants Red Spot $78.00 Beautiful, comforta...",$78.00,AUD
1,Tulip dress print,Tulip dress print $110.00 The unique curve of ...,$110.00,AUD
2,Cotton Camisole,Cotton Camisole $42.00 White / XS - $42.00 Whi...,$42.00,AUD
3,Linen Lantern Pants Black,Linen Lantern Pants Black $139.00 Our favourit...,$139.00,AUD
4,Suzy Dress,Suzy Dress $98.00 Long sleeve dress with strai...,$98.00,AUD

'Product_dchkayhonda.com_September2020.json.gz'

,name,brand,model,manufacturer,releasedate,color
0,2019 Honda Civic Sedan Sport Touring,Honda,Civic Sedan,Honda,2019,Crystal Black Pearl
1,2019 Honda Civic Sedan Sport Touring,Honda,Civic Sedan,Honda,2019,Aegean Blue Metallic
2,2020 Honda Accord Sedan LX,Honda,Accord Sedan,Honda,2020,Crystal Black Pearl
3,2020 Honda Civic Coupe LX,Honda,Civic Coupe,Honda,2020,Crystal Black Pearl
4,2020 Honda Civic Coupe LX,Honda,Civic Coupe,Honda,2020,Crystal Black Pearl

'Product_nova-megastore.com_September2020.json.gz'

,name,offers,brand,gtin13,weight,width,height,depth
0,"GE CP81 FSK 240V/300W GY-9,5 150h 3200K","{'price': '13.00', 'url': 'https://nova-megast...",GE,43168884440,1 kg,0.12 cm,0.04 cm,0.04 cm
1,"OSRAM EVD 64663HLX A1/239 36V/400W G-6,35","{'price': '7.00', 'url': 'https://nova-megasto...",OSRAM,"4,05E+12",1 kg,0.105 cm,0.032 cm,0.032 cm
2,"GE GKV800 240V/800W G-9,5 250h 3200K","{'price': '26.00', 'url': 'https://nova-megast...",GE,43168884327,1 kg,0.12 cm,0.04 cm,0.04 cm
3,"GE T18 GCW 240V/500W GY-9,5 400h 3050K",{'url': 'https://nova-megastore.com/ge-t18-gcw...,GE,43168884655,1 kg,0.125 cm,0.04 cm,0.04 cm
4,"OMNILUX JC 12V/50W G-6,35 2000h","{'price': '1.00', 'url': 'https://nova-megasto...",OMNILUX,"4,03E+12",1 kg,0.065 cm,0.02 cm,0.02 cm

'Product_nametagwizard.com_September2020.json.gz'

,name,offers,brand,pricecurrency,availability
0,Reusable Chalkboard Black Oval Name Tag,"{'pricecurrency': 'USD', 'price': '3.95'}",{'name': 'Name Tag Wizard'},USD,https://schema.org/InStock
1,Silver Military Style Name Tag - Two Line,"{'price': '13.95', 'pricecurrency': 'USD'}",{'name': 'Name Tag Wizard'},USD,https://schema.org/InStock
2,Brown ADA Braille Men's & Women's Handicap Res...,"{'pricecurrency': 'USD', 'price': '19.95'}",{'name': 'Custom Signs'},USD,https://schema.org/InStock
3,Jalepeno Pepper Oval Mexican Restaurant Name Tag,"{'pricecurrency': 'USD', 'price': '7.45'}",{'name': 'Name Tag Wizard'},USD,https://schema.org/InStock
4,Custom Brushed Silver Name Tag - 1.5 x 3.5,None,None,None,None

'Product_mycozycups.com_September2020.json.gz'

,name,offers,brand,review,price,pricecurrency
0,World's Best Aunt 11oz 15oz Coffee Mug,"{'pricecurrency': 'USD', 'price': '12.97'}",MyCozyCups,{'datepublished': '2011-03-25'},12.97,USD
1,Best Ahole Sister Ever 11oz 15oz Coffee Mug,"{'pricecurrency': 'USD', 'price': '12.97'}",MyCozyCups,{'datepublished': '2011-03-25'},12.97,USD
2,Best Effin Dad 11oz 15oz Coffee Mug,"{'pricecurrency': 'USD', 'price': '12.97'}",MyCozyCups,{'datepublished': '2011-03-25'},12.97,USD
3,To My Wife I Love You 11oz 15oz Coffee Mug,"{'pricecurrency': 'USD', 'price': '12.97'}",MyCozyCups,{'datepublished': '2011-03-25'},12.97,USD
4,Best Ahole Boyfriend Ever 11oz 15oz Coffee Mug...,"{'pricecurrency': 'USD', 'price': '12.97'}",MyCozyCups,{'datepublished': '2011-03-25'},12.97,USD

'Product_allbestcbdoil.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review
0,Provacan Reviews,"{'availability': 'https://schema.org/InStock',...",Provacan,"{'ratingvalue': '8.80', 'reviewcount': '488', ...",PROVACAN-68,{'author': 'Aaron S.'}
1,Blessed CBD Review,"{'availability': 'https://schema.org/InStock',...",Blessed CBD,"{'ratingvalue': '9.20', 'bestrating': '10', 'r...",BLESSED CBD-60,{'author': 'Aaron S.'}
2,Koi CBD Review,"{'availability': 'https://schema.org/InStock',...",Koi CBD,"{'ratingvalue': '7.80', 'reviewcount': '652', ...",KOI CBD-76,{'author': 'Aaron S.'}
3,Diamond CBD Reviews,"{'availability': 'https://schema.org/InStock',...",Diamond CBD Oil,"{'ratingvalue': '6.70', 'reviewcount': '665', ...",DIAMOND CBD OIL-64,{'author': 'Aaron S.'}
4,CBD Brothers Review,"{'availability': 'https://schema.org/InStock',...",CBD Brothers,"{'ratingvalue': '8.20', 'bestrating': '10', 'w...",CBD BROTHERS-71,{'author': 'Aaron S.'}

'Product_masonlindhart.com_September2020.json.gz'

,name,offers,aggregaterating,review,itemcondition,model
0,Thoughts & Prayers,"{'pricecurrency': 'USD', 'lowprice': '49.99', ...","{'reviewcount': '1', 'ratingvalue': '5.00'}","{'author': 'from Newport News - Virginia', 'na...",NewCondition,"{'name': 'Thoughts & Prayers (Standard)', 'url..."
1,Memories In Crystal - Pet Urn,"{'pricecurrency': 'USD', 'lowprice': '159.95',...",None,None,NewCondition,{'url': 'https://www.masonlindhart.com/store/p...
2,Simply Elegant Spathiphyllum,"{'pricecurrency': 'USD', 'highprice': '107.95'...","{'reviewcount': '315', 'ratingvalue': '4.97'}","[{'author': 'from -', 'description': 'I have b...",NewCondition,[{'url': 'https://www.masonlindhart.com/store/...
3,Emerald Garden Basket,"{'pricecurrency': 'USD', 'lowprice': '67.95', ...","{'reviewcount': '111', 'ratingvalue': '4.90'}","[{'author': 'from Bartlesville - Oklahoma', 'n...",NewCondition,"{'name': 'Emerald Garden Basket (Standard)', '..."
4,Country Basket Blooms,"{'pricecurrency': 'USD', 'lowprice': '67.95', ...","{'reviewcount': '145', 'ratingvalue': '4.97'}","[{'name': 'Country Basket Blooms', 'descriptio...",NewCondition,"[{'sku': 'T48-3B', 'url': 'https://www.masonli..."

'Product_winreal.com.ng_September2020.json.gz'

,name,offers,brand,category,releasedate
0,10 Layers Blue Crystal Necklace With Brooch,"{'availability': 'https://schema.org/InStock',...",{'name': 'Winreal Store'},Womens Fashion > Womens Jewelry,2019-05-24T12:07:02+01:00
1,Anti-Aging Face Conditioner,"{'price': '4000', 'availability': 'https://sch...",{'name': 'Winreal Store'},Skin Care > Oils,2019-05-12T06:17:58+01:00
2,Face Whitening Cream - Moonlight Face Cream,"{'availability': 'https://schema.org/InStock',...",{'name': 'Winreal Store'},Skin Care > Creams,2019-05-27T13:00:21+01:00
3,Green and White Sheda Mix With Organza Dress,"{'availability': 'https://schema.org/InStock',...",{'name': 'Winreal Store'},Girls Fashion,2019-06-02T18:13:29+01:00
4,Hot Whitenizer,"{'price': '5000', 'pricecurrency': 'NGN', 'ite...",{'name': 'Winreal Store'},Skin Care > Creams,2019-05-12T06:16:27+01:00

'Product_croydon-tyrescentre.co.uk_September2020.json.gz'

,name,offers,brand,category,itemcondition
0,Altimax One S,{'url': ['/TyreSearch/Details/110723/General+A...,General,Tyre > Mid-Range,NewCondition
1,Altimax One S,{'url': ['/TyreSearch/Details/107142/General+A...,General,Tyre > Mid-Range,NewCondition
2,Altimax One S,{'url': ['https://www.croydon-tyrescentre.co.u...,General,Tyre > Mid-Range,NewCondition
3,Altimax One S,"{'price': '127.98', 'url': ['https://www.croyd...",General,Tyre > Mid-Range,NewCondition
4,Altimax One S,{'url': ['https://www.croydon-tyrescentre.co.u...,General,Tyre > Mid-Range,NewCondition

'Product_delivape.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,DeliVape Shop E-Liquid Coconut Candy,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'DeliVape'},"{'ratingvalue': '5.0', 'reviewcount': '136'}",DV239
1,DeliVape Shop E-Liquid Pineapple,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'DeliVape'},"{'reviewcount': '136', 'ratingvalue': '4.5'}",DV101
2,Aspire Atlantis,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Aspire'},"{'ratingvalue': '5.0', 'reviewcount': '136'}",HC300
3,DeliVape Shop E-Liquid Virginia Tobacco,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'DeliVape'},"{'ratingvalue': '4.6', 'reviewcount': '136'}",DV243
4,DeliVape Shop E-Liquid Honey Peach,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'DeliVape'},"{'reviewcount': '136', 'ratingvalue': '4.7'}",DV132

'Product_yachtbooker.com_September2020.json.gz'

,name,offers,brand,mpn,identifier
0,Azimut 39 Fly 302 KK,"{'lowprice': '5350.00', 'pricecurrency': 'EURO...",Azimut,27141,https://www.yachtbooker.com//countries/croatia...
1,Galeon 640 Fly,"{'lowprice': '25000.00', 'pricecurrency': 'EUR...",Galeon,37483,https://www.yachtbooker.com//countries/spain/m...
2,Cranchi 41 Gin Tonic,"{'pricecurrency': 'EURO', 'highprice': '8484.0...",Cranchi,33258,https://www.yachtbooker.com//countries/spain/m...
3,Oceanis 40 IMAGINE,"{'highprice': '1980.00', 'pricecurrency': 'EUR...",Beneteau,26883,https://www.yachtbooker.com//countries/croatia...
4,Bavaria Virtess 420 Fly,"{'pricecurrency': 'EURO', 'lowprice': '7680.00...",Bavaria,37518,https://www.yachtbooker.com//countries/greece/...

'Product_factorychryslerparts.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,identifier
0,Cargo Tote is a handy way to secure items in t...,{'itemcondition': 'http://schema.org/NewCondit...,Chrysler,"{'ratingvalue': '4.4', 'itemreviewed': 'Dealer...",82208566,{'value': '82208566'}
1,Collapsible Pet Kennel to keep your pet secure...,{'itemcondition': 'http://schema.org/NewCondit...,Chrysler,"{'ratingvalue': '4.4', 'itemreviewed': 'Dealer...",82213729AB,{'value': '82213729AB'}
2,PANEL. Body Side Aperture Rear. Right. This Fi...,{'itemcondition': 'http://schema.org/NewCondit...,Chrysler,"{'ratingvalue': '4.4', 'reviewcount': '3393', ...",05139158AJ,{'value': '05139158AJ'}
3,Cargo Tote is a handy way to secure items in t...,"{'pricevaliduntil': '10/26/2020 12:06:25 PM', ...",Chrysler,"{'ratingvalue': '4.4', 'itemreviewed': 'Dealer...",82208566,{'value': '82208566'}
4,"Cabin Air Filter, complete kit. Replacement fi...",{'itemcondition': 'http://schema.org/NewCondit...,Chrysler,"{'ratingvalue': '4.4', 'reviewcount': '3393', ...",82208300,{'value': '82208300'}

'Product_thomasfuneralhomecalhoun.com_September2020.json.gz'

,name,offers,aggregaterating,review,itemcondition,model
0,Emerald Garden Basket,"{'pricecurrency': 'USD', 'lowprice': '67.95', ...","{'reviewcount': '111', 'ratingvalue': '4.90'}","[{'author': 'from Bartlesville - Oklahoma', 'n...",NewCondition,{'image': 'https://res.cloudinary.com/picasso/...
1,Sweet Remembrance Spray,"{'pricecurrency': 'USD', 'highprice': '184.95'...","{'ratingvalue': '5.00', 'reviewcount': '3'}","[{'author': 'from -', 'datepublished': '3/2/20...",NewCondition,{'url': 'https://www.thomasfuneralhomecalhoun....
2,Fall Fantasia,"{'pricecurrency': 'USD', 'highprice': '82.95',...","{'reviewcount': '5', 'ratingvalue': '5.00'}",[{'description': 'We were greatly pleased with...,NewCondition,"[{'sku': 'T167-1A', 'url': 'https://www.thomas..."
3,Heart's Companion Bouquet,"{'pricecurrency': 'USD', 'lowprice': '104.95',...","{'reviewcount': '5', 'ratingvalue': '5.00'}","[{'datepublished': '10/4/2019', 'author': 'fro...",NewCondition,{'name': 'Heart's Companion Bouquet (Standard)...
4,Never Forget™ Pendant & Chain (Reversible),"{'highprice': '109.95', 'lowprice': '109.95', ...",None,None,NewCondition,"{'sku': 'R41699', 'name': 'Never Forget™ Penda..."

'Product_jordancamper.com_September2020.json.gz'

,name,offers,brand,category,mpn,model,manufacturer,weight,width,depth
0,CargoGlide WSL024 LED Light Kit 1-24,"{'pricecurrency': 'USD', 'price': '96.0000', '...",CargoGlide,Automotive Lighting > LED Auxiliary Lights,WSL024,WSL024,CargoGlide,5.000,3.0,6.0
1,Race Sport Lighting 1157-SPY-AMBER LED Illumin...,"{'pricecurrency': 'USD', 'inventorylevel': '0'...",Race Sport Lighting,Automotive Lighting > Replacement Bulbs,1157-SPY-AMBER,1157-SPY-AMBER,Race Sport Lighting,0.100,5.0,7.0
2,Weather Guard 7096-2PK Gas Spring (2 Pk),"{'pricecurrency': 'USD', 'price': '92.8200', '...",Weather Guard,Truck Bed and Tailgate > Truck Bed Toolboxes a...,7096-2PK,7096-2PK,Weather Guard,0.000,0.0,0.0
3,Weather Guard 7102-3 Low-Side Legs,"{'pricecurrency': 'USD', 'price': '41.4000', '...",Weather Guard,Truck Bed and Tailgate > Truck Bed Toolboxes a...,7102-3,7102-3,Weather Guard,0.000,0.0,0.0
4,Firestone Ride-Rite 2533 Elec Level Command-S,"{'pricecurrency': 'USD', 'inventorylevel': '0'...",Firestone Ride-Rite,Chassis and Suspension > Air Suspension Compre...,2533,2533,Firestone Ride-Rite,10.234,9.0,11.0

'Product_slamoof.com_September2020.json.gz'

,name,offers,brand,aggregaterating,category,mpn,review
0,Bicycle GPS Tracker Bike Taillight 2600mAh Bat...,"{'availability': 'https://schema.org/InStock',...",slamoof.com,"{'reviewcount': '8', 'ratingvalue': '5.00'}",None,49157,None
1,TOSHIBA Canvio Basics 3.0 Portable Hard Drive ...,"{'availability': 'https://schema.org/InStock',...",slamoof.com,"{'ratingvalue': '4.80', 'reviewcount': '6'}",None,5614,None
2,Screen Protector For iWatch 1 2 3 4 5 size 40 ...,"{'availability': 'https://schema.org/InStock',...",slamoof.com,"{'ratingvalue': '4.70', 'reviewcount': '50'}",None,4200,None
3,1m 2m 3m Wireless PIR Motion Sensor LED Bed Cl...,{'url': 'https://slamoof.com/1m-2m-3m-wireless...,slamoof.com,"{'ratingvalue': '4.90', 'reviewcount': '44'}",None,4463,None
4,Hand Sweep Scanning Motion Sensor LED Night li...,"{'availability': 'https://schema.org/InStock',...",slamoof.com,"{'ratingvalue': '4.80', 'reviewcount': '24'}",None,4464,None

'Product_iludec.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Controlador con mando RGBW WIFI DC12V DC24V,"{'pricevaliduntil': '2019-10-12T15:00:50Z', 'p...",{'name': 'Iludec'},"{'reviewcount': '1', 'ratingvalue': '5'}",6228
1,Grapa con muelle para perfiles led,"{'availability': 'instock', 'pricevaliduntil':...",{'name': 'Iludec'},None,6396
2,Rollo tira led adhesiva neón DC24v IP67 8mm,"{'lowprice': '1.0579E2', 'offercount': '2', 'a...",{'name': 'Iludec'},None,15025
3,"Rollo Tira led 19,2w 120 RGB +120 neutra 240le...","{'availability': 'instock', 'price': '87.94', ...",{'name': 'Iludec'},None,15009
4,"Rollo Tira led 15,35w IP20 4020K DC24v. Marisq...","{'pricevaliduntil': '2020-05-11T21:10:14Z', 'p...",{'name': 'iludec'},"{'reviewcount': '1', 'ratingvalue': '5'}",8755

'Product_bambuskomfort.com_September2020.json.gz'

,name,offers,category,releasedate,additionalproperty
0,Bambusplatte Karamell vertikal 2440x1220x20mm ...,"{'price': '260.49', 'itemcondition': 'NewCondi...",Bambusplatten,2017-05-16T10:41:34+02:00,"[{'value': '2440 mm', 'name': 'laenge'}, {'val..."
1,Bambus Terrassendiele Bamboo X-treme geölt 185...,"{'price': '20.22', 'itemcondition': 'NewCondit...",Terrassendielen,2016-12-10T21:59:20+01:00,"[{'name': 'breite', 'value': '137 mm'}, {'name..."
2,Bambusplatte Karamell horizontal 3000x700x40mm...,"{'price': '318.15', 'itemcondition': 'NewCondi...",Bambusplatten,2017-05-16T17:43:24+02:00,"[{'name': 'pa_btstaerke', 'value': '40 mm'}, {..."
3,Bambus Sockelleiste Karamell horizontal geölt ...,"{'price': '16.02', 'itemcondition': 'NewCondit...",Sockelleisten,2017-05-14T18:30:53+02:00,"[{'value': '18 mm', 'name': 'breite'}, {'value..."
4,Bambusparkett Topbamboo Karamell vertikal geöl...,"{'price': '0', 'itemcondition': 'NewCondition'...",Muster,2018-05-16T22:11:08+02:00,None

'Product_flowers4quarteira.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,model,manufacturer
0,8 Red Roses,"{'price': '29.00', 'pricecurrency': 'EUR', 'pr...",{'name': 'Paradise Promotions LTD.'},"{'reviewcount': '911', 'ratingvalue': '4.5'}",BQR133,8 Red Roses,{'name': 'Paradise Promotions LTD.'}
1,8 червени рози,"{'price': '29.00', 'pricevaliduntil': '24-10-2...",{'name': 'Paradise Promotions LTD.'},"{'reviewcount': '911', 'ratingvalue': '4.5'}",BQR133,8 червени рози,{'name': 'Paradise Promotions LTD.'}
2,6 Червени рози и 3 Лилии,"{'pricevaliduntil': '24-10-2020', 'url': 'bg/r...",{'name': 'Paradise Promotions LTD.'},"{'reviewcount': '911', 'ratingvalue': '4.5'}",BQ111,6 Червени рози и 3 Лилии,{'name': 'Paradise Promotions LTD.'}
3,100 White Roses,{'url': 'snow-white-100-white-roses-flower-del...,{'name': 'Paradise Promotions LTD.'},"{'reviewcount': '911', 'ratingvalue': '4.5'}",BQW118,100 White Roses,{'name': 'Paradise Promotions LTD.'}
4,12 розови рози,"{'pricevaliduntil': '22-10-2020', 'url': 'bg/p...",{'name': 'Paradise Promotions LTD.'},"{'reviewcount': '911', 'ratingvalue': '4.5'}",BQP132,12 розови рози,{'name': 'Paradise Promotions LTD.'}

'Product_gmcarsbynelson.com_September2020.json.gz'

,name,offers,brand,mpn,model,manufacturer,color
0,Pre-Owned 2015 Chevrolet Tahoe LT,"{'price': '29991', 'itemcondition': 'http://sc...",Chevrolet,CK15706,Tahoe,{'name': 'Chevrolet'},Silver Ice Metallic
1,Pre-Owned 2016 Jeep Compass Sport,{'itemcondition': 'http://schema.org/UsedCondi...,Jeep,MKJE49,Compass,{'name': 'Jeep'},Granite Crystal Metallic Clearcoat
2,New 2020 Chevrolet Malibu LS,{'itemcondition': 'http://schema.org/NewCondit...,Chevrolet,1ZC69,Malibu,{'name': 'Chevrolet'},Black Cherry Metallic
3,Pre-Owned 2019 Chevrolet Silverado 2500HD LT,"{'pricecurrency': 'USD', 'availability': 'http...",Chevrolet,CK25743,Silverado 2500HD,{'name': 'Chevrolet'},Summit White
4,Pre-Owned 2015 Nissan Murano SL,{'itemcondition': 'http://schema.org/UsedCondi...,Nissan,23415,Murano,{'name': 'Nissan'},Magnetic Black Metallic

'Product_aw-lab.com_September2020.json.gz'

,name,offers,brand,category,mpn
0,NIKE AIR MAX DIA,"{'price': '7.99E1', 'availability': 'http://sc...",{'name': 'NIKE'},Calzado,5011204.0
1,SUDADERA CHAMPION CREWNECK,"{'price': '3.99E1', 'availability': 'http://sc...",{'name': 'CHAMPION'},Ropa,9190448.0
2,adidas Superstar,"{'availability': 'http://schema.org/InStock', ...",{'name': 'ADIDAS'},Chicos,3011551.0
3,CAMISETA PARAMOUNT SMALL LOGO,"{'availability': 'http://schema.org/InStock', ...",{'name': 'DOWN UP'},Ropa,9399445.0
4,Converse All Star Hi Canvas,"{'price': '0', 'availability': 'http://schema....",{'name': 'CONVERSE'},Scarpe,8896130.0

'Product_team-fishing.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Abu Garcia Revo Beast Low Profile Baitcasting ...,"{'pricecurrency': 'USD', 'price': '259.95', 'a...",None,None,NaN
1,Abu Garcia Revo AL-F Low Profile Baitcasting R...,"{'pricecurrency': 'USD', 'availability': 'http...",None,None,NaN
2,Abu Garcia Ambassadeur CS Pro Rocket Reels &#8...,"{'price': '179.95', 'availability': 'http://sc...",None,None,NaN
3,Abu Garcia Revo MGX Baitcasting Reels &#8211; ...,"{'pricecurrency': 'USD', 'availability': 'http...",None,None,NaN
4,Abu Garcia CS-7000 Ambassadeur CS Pro Rocket B...,"{'pricecurrency': 'USD', 'price': '159.95', 'a...",None,None,NaN

'Product_cdhomeproducts.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,25.5 cu. ft 42-Inch Width Built-In Side by Sid...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'KitchenAid'},"{'reviewcount': '51', 'ratingvalue': '4.1', 'i...",KBSN602ESS
1,Top Control Powerful Dishwasher at Only 47 dBA,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Maytag'},"{'ratingvalue': '4.6', 'reviewcount': '76', 'i...",MDB7959SHZ
2,"28 cu. ft. 3-Door French Door, Full Depth Refr...","{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Samsung'},"{'reviewcount': '7', 'ratingvalue': '4.3', 'it...",RF28R6301SG
3,30&#39;&#39; 4-Burner Dual Fuel Freestanding R...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'KitchenAid'},{'itemreviewed': '30&#39;&#39; 4-Burner Dual F...,KDRS407VBK
4,25 cu. ft. Side-by-Side Refrigerator with LED ...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Samsung'},"{'reviewcount': '26', 'itemreviewed': '25 cu. ...",RS25J500DWW

'Product_bidderlo.com_September2020.json.gz'

,name,offers,shop-currency
0,Full Bangs Long Half Curly Hair Wig Heat Resis...,Full Bangs Long Half Curly Hair Wig Heat Resis...,USD
1,Portable Mini MP3 Player,Portable Mini MP3 Player Go to Auction Easy to...,USD
2,Chopper's Finger Guard,Chopper's Finger Guard Go to Auction Keep thos...,USD
3,Engine Cylinder Pressure Gauge Diagnostic Tool...,Engine Cylinder Pressure Gauge Diagnostic Tool...,USD
4,USB Powered DC 5V 6W Eye-protection Touch Cont...,USB Powered DC 5V 6W Eye-protection Touch Cont...,USD

'Product_dienlanhnguyenphat.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,Su1eeda mu00e1y lu1ea1nh u0110u1ed3ng Nai,"{'pricecurrency': 'VND', 'price': '2000000', '...",{'name': 'u0110iu1ec7n lu1ea1nh Nguyu1ec5n Phu...,"{'reviewcount': '50', 'ratingvalue': '4'}",973266693422
1,Su1eeda mu00e1y giu1eb7t Quu1eadn 2,"{'pricecurrency': 'VND', 'price': '2000000', '...",{'name': 'u0110iu1ec7n lu1ea1nh Nguyu1ec5n Phu...,"{'reviewcount': '50', 'ratingvalue': '4'}",973266693422
2,Su1eeda mu00e1y lu1ea1nh Gu00f2 Vu1ea5p,"{'pricecurrency': 'VND', 'price': '2000000', '...",{'name': 'u0110iu1ec7n lu1ea1nh Nguyu1ec5n Phu...,"{'reviewcount': '50', 'ratingvalue': '4'}",973266693422
3,Lu1eafp u0111u1eb7t mu00e1y lu1ea1nh tu1ea1i D...,"{'pricecurrency': 'VND', 'price': '2000000', '...",{'name': 'u0110iu1ec7n lu1ea1nh Nguyu1ec5n Phu...,"{'reviewcount': '50', 'ratingvalue': '4'}",973266693422
4,Su1eeda mu00e1y giu1eb7t tu1ea1i Bu00ecnh Du01...,"{'pricecurrency': 'VND', 'price': '2000000', '...",{'name': 'u0110iu1ec7n lu1ea1nh Nguyu1ec5n Phu...,"{'reviewcount': '50', 'ratingvalue': '4'}",973266693422

'Product_buy-motorcycle.com_September2020.json.gz'

,name,brand,model,manufacturer,releasedate
0,1982 Harley-Davidson Other,{'name': 'Harley-Davidson'},Other,Harley-davidson,1982.0
1,yamaha tdm 850,{'name': 'Yamaha'},1999,Yamaha,NaN
2,MOTO GUZZI 1200 SPORT 01/2012 MODEL PROJECT MA...,{'name': 'Moto Guzzi'},1200,Moto guzzi,NaN
3,2017 Harley-Davidson Dyna,{'name': 'Harley-Davidson'},Dyna,Harley-davidson,2017.0
4,1964 Ducati Mach 1 250,{'name': 'Ducati'},Mach 1 250,Ducati,1964.0

'Product_bellesmart.com_September2020.json.gz'

,name,offers,brand,aggregaterating,category,mpn,review
0,Set Holographic Starry Laser Nail Foil Stickers,"{'availability': 'https://schema.org/InStock',...",{'name': 'bellesmart.com'},"{'ratingvalue': '4.9E0', 'reviewcount': '18'}",Nail &amp; Nail Tools,587,"[{'reviewbody': 'Foil is excellent, there are ..."
1,Organic Depilatory Almond Cream,"{'name': 'Organic Depilatory Almond Cream', 'a...",{'name': 'bellesmart.com'},"{'ratingvalue': '4.7E0', 'reviewcount': '29'}",Beauty Tools,197,[{'reviewbody': 'Thanks for the order. Went lo...
2,Round Hair Comb with Wooden Handle,"{'availability': 'https://schema.org/InStock',...",{'name': 'bellesmart.com'},"{'ratingvalue': '4.9E0', 'reviewcount': '30'}",Hair Care &amp; Accessories,267,[{'reviewbody': 'Description corresponds. I or...
3,Waterproof Eyebrow Makeup Set,"{'availability': 'https://schema.org/InStock',...",{'name': 'bellesmart.com'},"{'reviewcount': '17', 'ratingvalue': '4.8E0'}",Gifts &amp; Packs,379,"[{'reviewbody': 'Good！'}, {'reviewbody': 'All ..."
4,UV LED Nail Gel Polish 10 ml,"{'name': 'UV LED Nail Gel Polish 10 ml', 'avai...",{'name': 'bellesmart.com'},"{'reviewcount': '33', 'ratingvalue': '4.8E0'}",Nail &amp; Nail Tools,789,"[{'reviewbody': 'Lacquer came, the color is be..."

'Product_powerwalker.com_September2020.json.gz'

,name,offers,itemcondition,model,manufacturer,gtin13
0,"PowerWalker MBS 19\"" Zoll","{'gtin13': '4260074974195', 'price': '181.26',...",NewCondition,10120501,{'name': 'BlueWalker GmbH'},4.260075e+12
1,Battery CSB UPS12360,"{'pricevaliduntil': '2100-01-01 00:00:00', 'pr...",NewCondition,91010109,None,NaN
2,Retourenware PowerWalker VI 2000RT LCD,"{'price': '682.34', 'gtin13': '4260074974324',...",NewCondition,10120028,{'name': 'BlueWalker GmbH'},4.260075e+12
3,IEC 10A Kabel C14 -> Schuko,"{'pricevaliduntil': '2100-01-01 00:00:00', 'av...",NewCondition,91015003,None,NaN
4,Retourenware PowerWalker VFI 2000RM LCD,"{'pricecurrency': 'EUR', 'pricevaliduntil': '2...",NewCondition,10120146,{'name': 'BlueWalker GmbH'},4.260075e+12

'Product_royalepharma.com_September2020.json.gz'

,name,offers,brand,mpn,review
0,DARLIE TOOTHPASTE ENAMEL PROTECT MILD 200G,"{'pricevaliduntil': '2020-11-05', 'name': 'DAR...",DARLIE,925872,"{'name': 'A masterpiece of literature', 'revie..."
1,REXONA TEENS SPRAY TROPICAL ENERGY 102ML,"{'pricevaliduntil': '2020-11-05', 'pricecurren...",REXONA,925872,"{'name': 'A masterpiece of literature', 'revie..."
2,SCOTT'S VITAMIN C PASTTILES ORANGE 50'S,{'name': 'SCOTT'S VITAMIN C PASTTILES ORANGE 5...,SCOTT'S,925872,"{'name': 'A masterpiece of literature', 'revie..."
3,OK HABATUS SAUDA LOTION 100ML(ORANG KAMPUNG),{'name': 'OK HABATUS SAUDA LOTION 100ML(ORANG ...,ORANG KAMPUNG,925872,"{'name': 'A masterpiece of literature', 'revie..."
4,COLGATE TOOTHPASTE TOTAL CLEAN MINT 150GX2,"{'pricevaliduntil': '2020-11-05', 'pricecurren...",COLGATE,925872,"{'name': 'A masterpiece of literature', 'revie..."

'Product_stantonsace.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,36&quot; 5 Burner Gas Downdraft Cooktop - Stai...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'KitchenAid'},"{'ratingvalue': '4.6', 'reviewcount': '101', '...",KCGD506GSS
1,KitchenAid&reg; 18&#39;&#39; Automatic Ice Mak...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'KitchenAid'},"{'ratingvalue': '5.0', 'itemreviewed': 'Kitche...",KUID508HWH
2,24&#39;&#39; Slow Cook Warming Drawer - Stainl...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'KitchenAid'},"{'reviewcount': '4', 'itemreviewed': '24&#39;&...",KOWT104ESS
3,27&quot; Combination Wall Oven with Even-Heat&...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'KitchenAid'},"{'reviewcount': '39', 'ratingvalue': '4.1', 'i...",KOCE507EBS
4,36-inch Side-by-Side Refrigerator with Dual Pa...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Amana'},"{'ratingvalue': '5.0', 'reviewcount': '2', 'it...",ASI2575GRS

'Product_towelsandbedsheets.co.uk_September2020.json.gz'

,name,offers,brand,mpn,model
0,Double Bed Duvet Cover with Pillowcases Spring...,"{'pricevaliduntil': '2021-09-30', 'itemconditi...",{'name': 'Renoazul'},S-528772,SD2591
1,King Size Fitted Sheet Pale Lemon,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Renoazul'},MNSHD764,QW2644
2,Double Bed Duvet Cover with Pillowcases Triang...,"{'pricevaliduntil': '2021-09-29', 'itemconditi...",{'name': 'Renoazul'},K-365233,SD2582
3,Super King Duvet cover with Pillowcases Beach ...,{'itemcondition': 'http://schema.org/NewCondit...,{'name': 'Renoazul'},BU87G25,SD2578
4,Unisex bathrobe in White colour with 2 pockets,"{'pricevaliduntil': '2021-09-30', 'price': '16...",{'name': 'Renoazul'},FR4273,AB2798

'Product_onestopflooring.co.uk_September2020.json.gz'

,name,offers,brand,manufacturer,mainentityofpage
0,Boen Prestige Herringbone Walnut American Natu...,"{'price': '75.50', 'availability': 'http://sch...",None,None,{'name': 'Boen Prestige Herringbone Walnut Ame...
1,Kahrs Calder CLW 218 6mm Click Vinyl Flooring,"{'availability': 'http://schema.org/InStock', ...",{'name': 'Kahrs'},{'name': 'Kahrs'},"{'inlanguage': 'en-US', 'description': 'Unbeat..."
2,Malmo Dante Rigid Narrow Plank,"{'price': '26.39', 'pricecurrency': 'GBP', 'av...",{'name': 'Malmo'},{'name': 'Malmo'},"{'datemodified': '2019-10-01T16:22:06+00:00', ..."
3,Tuscan Forte Toffee Oak Hand Scraped Lacquered...,"{'availability': 'http://schema.org/InStock', ...",None,None,"{'datemodified': '2019-12-15T22:29:42+00:00', ..."
4,Quickstep Balance Click Cottage Oak Natural,"{'availability': 'http://schema.org/InStock', ...",{'name': 'Quickstep'},{'name': 'Quickstep'},{'name': 'Quickstep Balance Click Cottage Oak ...

'Product_lucyandcoboutique.com_September2020.json.gz'

,name,offers,brand,mpn,itemcondition
0,Mauve/ivory sweater poncho,"[{'mpn': '26311510', 'availability': 'https://...",{'name': 'Lucy & Co Curvy Boutique'},26311510,https://schema.org/NewCondition
1,"Embroidered top in royal, red and burgundy",[{'availability': 'https://schema.org/InStock'...,{'name': 'Lucy & Co Curvy Boutique'},72979286,https://schema.org/NewCondition
2,Weekend t-shirt,"[{'gtin14': '18732886', 'availability': 'https...",{'name': 'Lucy & Co Curvy Boutique'},18732886,https://schema.org/NewCondition
3,Thankful rainbow t-shirt,[{'availability': 'https://schema.org/InStock'...,{'name': 'Lucy & Co Curvy Boutique'},50859350,https://schema.org/NewCondition
4,Vintage t-shirt,"[{'mpn': '13887830', 'availability': 'https://...",{'name': 'Lucy & Co Curvy Boutique'},13887830,https://schema.org/NewCondition

'Product_qcautoplex.com_September2020.json.gz'

,name,offers,brand,mpn,model,manufacturer,releasedate,color
0,2014 Honda Odyssey EX L 4dr Mini Van,{'name': '2014 Honda Odyssey EX L 4dr Mini Van...,Honda,5FNRL5H67EB109178,Odyssey,Honda,2014,Silver
1,2008 Honda Odyssey EX L w/DVD w/Navi 4dr Mini ...,"{'pricecurrency': 'USD', 'availability': 'http...",Honda,5FNRL38768B038914,Odyssey,Honda,2008,Blue
2,2016 Honda Odyssey Touring Elite 4dr Mini Van,"{'serialnumber': '5FNRL5H93GB080937', 'itemcon...",Honda,5FNRL5H93GB080937,Odyssey,Honda,2016,Gray
3,2018 Jeep Wrangler Unlimited Sport 4x4 4dr SUV...,"{'pricecurrency': 'USD', 'availability': 'http...",Jeep,1C4HJXDG1JW274905,Wrangler Unlimited,Jeep,2018,Black
4,2015 Jeep Wrangler Unlimited Rubicon 4x4 4dr SUV,"{'pricecurrency': 'USD', 'availability': 'http...",Jeep,1C4BJWFG4FL592488,Wrangler Unlimited,Jeep,2015,White

'Product_musicscotland.com_September2020.json.gz'

,name,offers,mpn,itemcondition,gtin13
0,Gordon Duncan - Thunderstruck,"{'price': '�12.85', 'pricecurrency': 'GBP'}",CDTRAX241,new,5018081024124
1,The Highland Bagpipe Tutor Book 2 - Transition...,"{'price': '�16.05', 'pricecurrency': 'GBP'}",COPT2,new,None
2,"Piping Live Masters - Angus MacColl, Bruce Gan...","{'price': '�17.04', 'pricecurrency': 'GBP'}",DVTRAX2020,new,5018081202027
3,Alistair McCulloch - Four Seasons In One Day,"{'price': '�13.45', 'pricecurrency': 'GBP'}",RTRLCD014,new,0793573595744
4,St Laurence O'Toole Pipe Band - Evolution,"{'price': '�16.84', 'pricecurrency': 'GBP'}",DVMON112,new,0611454011292

'Product_etrailer.com_September2020.json.gz'

,name,offers,brand,aggregaterating,category,mpn,review
0,HappiJac Truck-Mounted Camper Tie-Downs,{'url': 'https://www.etrailer.com/Camper-Tie-D...,{'name': 'HappiJac'},"{'ratingvalue': '5.0', 'reviewcount': '1'}",Camper Tie-Downs,LC182908-182928,None
1,Mighty Cord RV Power Cord Adapter - 30 Amp Twi...,"{'pricecurrency': 'USD', 'availability': 'http...",{'name': 'Mighty Cord'},"{'ratingvalue': '5.0', 'reviewcount': '19'}",RV Plug Adapters,A10-1530DBK,"[{'author': 'Mark', 'description': ['I've only..."
2,"Aluminum HWT Series S5 Trailer Wheel - 16\"" x ...","{'availability': 'https://schema.org/InStock',...",{'name': 'HWT'},"{'reviewcount': '263', 'ratingvalue': '4.9'}",Trailer Tires and Wheels,AM22659HWTB,"[{'datepublished': '02/10/2018', 'description'..."
3,CE Smith Spool Roller Assembly for Boat Traile...,"{'pricevaliduntil': '9/23/2020 11:59:59 PM', '...",{'name': 'CE Smith'},"{'ratingvalue': '4.8', 'reviewcount': '15'}",Boat Trailer Parts,CE10451G,"[{'author': 'Todd.S', 'datepublished': '08/07/..."
4,Firestone Ride-Rite Gloves - Large,"{'availability': 'https://schema.org/InStock',...",{'name': 'Firestone'},"{'ratingvalue': '5.0', 'reviewcount': '1'}",Tools,F9346,"{'datepublished': '11/18/2018', 'author': 'Jos..."

'Product_lepro.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn
0,4 Pack Portable LED Camping Lantern Outdoor 30...,"{'price': '27.99', 'availability': 'https://sc...",{'name': 'LE'},None,3300007-c-4
1,2 Pack 100W Outdoor LED Flood Light 10000lm Su...,"{'pricecurrency': 'USD', 'price': '59.9', 'ava...",{'name': 'LE'},"{'worstrating': '1', 'bestrating': '5', 'itemr...",340007-DW-US-2
2,16.4ft RGB LED Lights Strip with 44 Keys IR Re...,"{'pricecurrency': 'USD', 'price': '12.99', 'av...",{'name': 'LE'},"{'worstrating': '1', 'bestrating': '5', 'itemr...",410107-RGB-US
3,"LE USB Rechargeable LED Bike Headlight, Super ...","{'pricecurrency': 'USD', 'price': '17.99', 'av...",{'name': 'LE'},"{'worstrating': '1', 'bestrating': '5', 'revie...",2700011-US
4,"Solar Lights Outdoor, Motion Sensor Security L...","{'pricecurrency': 'USD', 'price': '19.99', 'av...",{'name': 'LE'},"{'worstrating': '1', 'itemreviewed': 'Solar Li...",640003-DW

'Product_flagsrus.org_September2020.json.gz'

,name,offers,brand,mpn,itemcondition,gtin12
0,Thanks to All Who Serve Double Sided Garden Flag,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",Evergreen,EV14S9799,None,NaN
1,Life Is Better With A Dog Burlap Double Sided ...,"{'pricecurrency': 'USD', 'price': '17.99', 'pr...",Evergreen,EV14B3728BL,None,NaN
2,Beach Afternoon Welcome Double Sided Flags Set...,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",Carson,CA49124-X,None,NaN
3,Back To School Crayons Appliqued Double Sided ...,"{'price': '16.99', 'url': 'https://www.flagsru...",Carson,CA55420,None,NaN
4,Come In For A Bite Appliqued Double Sided Gard...,"{'pricecurrency': 'USD', 'price': '17.99', 'ur...",Carson,CA55407,None,NaN

'Product_supplyhog.com_September2020.json.gz'

,name,offers,mpn,itemcondition,gtin14,issimilarto
0,Cedarberry Hill Cedar Hang Up 3 In. W. X 9 In....,{'itemcondition': 'http://schema.org/NewCondit...,319,http://schema.org/NewCondition,2.549132e+10,"[{'mpn': '306', 'description': '100% natural a..."
1,Walker's Child Size Earmuffs,"{'price': '16.91', 'itemcondition': 'http://sc...",GWP-FKDM-LG,http://schema.org/NewCondition,8.881510e+11,"[{'sku': '320366', 'mpn': '10088835', 'descrip..."
2,GarageEscape Slatwall Shelf Bracket,{'itemcondition': 'http://schema.org/NewCondit...,ABKB-10K,http://schema.org/NewCondition,8.531400e+11,"[{'sku': '214019', 'description': 'National Ca..."
3,Nite Ize Sideways Clip Case Cell Phone Case 5....,{'itemcondition': 'http://schema.org/NewCondit...,CCSL-03-01,http://schema.org/NewCondition,9.466402e+10,"[{'mpn': 'CCSXL-03-01', 'description': 'Horizo..."
4,Irwin Quick-Grip C-Clamp,{'itemcondition': 'http://schema.org/NewCondit...,225108,http://schema.org/NewCondition,3.854801e+10,"[{'sku': '319747', 'description': 'Double roll..."

'Product_ruffandtumbledogcoats.com_September2020.json.gz'

,name,offers,brand,category,gtin13
0,Dog Drying Mitts,"[{'name': 'Heather', 'pricevaliduntil': '2020-...",{'name': 'Ruff and Tumble'},Dog Drying Mitts,5.060468e+12
1,Sofa Throws,"[{'pricevaliduntil': '2020-10-06', 'pricecurre...",{'name': 'Ruff and Tumble'},Sofa Throws,5.060468e+12
2,Country Dog Drying Coat (faux leather trim),"[{'pricevaliduntil': '2020-10-06', 'availabili...",{'name': 'Ruff and Tumble'},Dog Drying Coat,5.060468e+12
3,Personalise Your Christmas Editon Coat?,"{'pricecurrency': 'GBP', 'availability': 'http...",{'name': 'Ruff and Tumble'},OPTIONS_HIDDEN_PRODUCT,NaN
4,Dog Leads,"[{'sku': 'SNLSB', 'name': 'Sandringham Blue / ...",{'name': 'Ruff and Tumble'},Dog Leads,5.060468e+12

'Product_childrens-ministry-deals.com_September2020.json.gz'

,name,offers,brand,aggregaterating,category
0,Halloween Themed Minute to Win It Games,"{'availability': 'https://schema.org/InStock',...",{'name': 'Children's Ministry Deals'},"{'reviewcount': '58', 'ratingvalue': '4.7'}",Minute To Win It Games
1,Ten Commandments Word Jumble,"{'availability': 'https://schema.org/InStock',...",{'name': 'Children's Ministry Deals'},"{'ratingvalue': '5.0', 'reviewcount': '4'}",Games
2,2020 52-Week Youth Ministry Scope And Sequence,"{'availability': 'https://schema.org/InStock',...",{'name': 'Children's Ministry Deals'},"{'ratingvalue': '5.0', 'reviewcount': '3'}",None
3,Bible Quiz: The Lion's Den Church Game Video f...,"{'availability': 'https://schema.org/InStock',...",{'name': 'Digital Felt Productions'},None,Children's Ministry Videos
4,With You Dance Worship Video for Kids,"{'availability': 'https://schema.org/InStock',...",{'name': 'Gateway Kids Worship'},None,Children's Ministry Videos

'Product_callofdutyleague.com_September2020.json.gz'

,name,offers,brand,category,itemcondition
0,ULT Chicago Huntsmen Crew Socks,"{'serialnumber': '3790641', 'availability': 'h...",ULT,Footwear &gt; Socks &gt; Accessories &gt; Socks,http://schema.org/NewCondition
1,Men's ACHES Black Los Angeles Guerrillas Away ...,"{'serialnumber': '3901317', 'availability': 'h...",Outerstuff,Jerseys &gt; Authentic,http://schema.org/NewCondition
2,Men's Octane Black Seattle Surge Away Jersey,"{'availability': 'http://schema.org/InStock', ...",Outerstuff,Jerseys &gt; Authentic,http://schema.org/NewCondition
3,Men's Ash Call of Duty League Launch Weekend T...,"{'availability': 'http://schema.org/InStock', ...",None,None,http://schema.org/NewCondition
4,Men's Black Call of Duty League Launch Weekend...,"{'availability': 'http://schema.org/InStock', ...",None,None,http://schema.org/NewCondition

'Product_lucasignition.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review
0,45D4 Top Entry Distributor Cap DDB108 54427109,"{'availability': 'instock', 'pricevaliduntil':...",{'name': 'Retro Ignition'},"{'reviewcount': '1', 'ratingvalue': '5'}",34563,"{'datepublished': '2020-07-28T13:59:31+01:00',..."
1,"Contact Set For Lucas 25D4, 25D6 DSB101 54419946","{'availability': 'instock', 'price': '5.1', 'p...",{'name': 'Retro Ignition'},"{'reviewcount': '1', 'ratingvalue': '5'}",29038,"{'description': 'Contact Set for Lucas 25D6, 2..."
2,Remax ES3 Ignition 12V Sports Coil Push - Eqv ...,"{'price': '36', 'availability': 'outofstock', ...",{'name': 'Retro Ignition'},"{'reviewcount': '1', 'ratingvalue': '5'}",50406,"{'author': 'Matthew', 'description': 'Ignition..."
3,Distributor Acorn Nut 410600 CYB305,"{'availability': 'instock', 'price': '0.972', ...",{'name': 'Retro Ignition'},"{'reviewcount': '1', 'ratingvalue': '5'}",30792,{'description': 'Distributor cap acorn nut. Lu...
4,Remax ES6 Ignition 6V Coil Push In,"{'availability': 'outofstock', 'pricevalidunti...",{'name': 'Retro Ignition'},"{'reviewcount': '1', 'ratingvalue': '5'}",50414,{'description': 'Ignition coil Remax ES6 Made ...

'Product_yves-salomon.com_September2020.json.gz'

,name,offers,brand,category,gtin13
0,Parka courte,"[{'pricevaliduntil': '2020-10-06', 'sku': '21W...",{'name': 'Yves Salomon'},Parka,3614756074757
1,Veste courte multicolore,"[{'sku': '21WYV63358TOMUB238038', 'pricevalidu...",{'name': 'Yves Salomon'},Jacket,3614756088440
2,Doudoune courte,"[{'sku': '21WHV02775A31GB176356', 'pricecurren...",{'name': 'Yves Salomon'},Down Jacket,3614756175744
3,Doudoune courte,[{'availability': 'https://schema.org/InStock'...,{'name': 'Yves Salomon'},Down Jacket,3614755353686
4,Manteau long agneau merinos,"[{'price': '2.97E3', 'availability': 'https://...",{'name': 'Yves Salomon'},Coat,3614756050102

'Product_yanbzx.com_September2020.json.gz'

,name,offers,brand,aggregaterating,mpn,review
0,Airline Bowl,"{'pricevaliduntil': '2140-08-06', 'availabilit...",EUROHOME,"{'reviewcount': '1', 'ratingvalue': '5'}",A12,"{'datepublished': '2020-09-04', 'author': 'Air..."
1,Color Mug,"{'pricevaliduntil': '2140-08-06', 'availabilit...",EUROHOME,"{'reviewcount': '1', 'ratingvalue': '5'}",CS005-Color,"{'datepublished': '2020-09-04', 'author': 'Col..."
2,Color Bowl,"{'pricevaliduntil': '2140-08-06', 'availabilit...",EUROHOME,"{'reviewcount': '1', 'ratingvalue': '5'}",CG051,"{'datepublished': '2020-09-04', 'description':..."
3,Porcelain Teapot,"{'pricevaliduntil': '2140-08-06', 'availabilit...",EUROHOME,"{'reviewcount': '1', 'ratingvalue': '5'}",H011-B,"{'datepublished': '2020-09-04', 'name': 'Porce..."
4,Dark Green Porcelain Set,"{'pricevaliduntil': '2140-08-06', 'availabilit...",EUROHOME,"{'reviewcount': '1', 'ratingvalue': '5'}",S05,"{'datepublished': '2020-09-04', 'description':..."

'Product_netwalkerstore.com_September2020.json.gz'

,name,offers,brand,mpn,gtin13
0,1000BASE-T SFP Copper Module SonicWall,"{'price': '543.94', 'itemcondition': 'http://s...",{'name': 'SonicWall'},01-SSC-9791,NaN
1,"Cable PatchSee Cat. 6a U/UTP croisé 2,1 m à re...","{'pricecurrency': 'EUR', 'availability': 'http...",{'name': 'PatchSee'},845026,1.062010e+12
2,Cordon téléphone 2 m blanc RJ11 - RJ45,"{'price': '5', 'availability': 'http://schema....",{'name': 'Dexlan'},911740,3.524891e+12
3,Supervisor 2 Gold,"{'availability': 'http://schema.org/InStock', ...",{'name': 'NetWalker'},supervisor_gold_2,NaN
4,"Cable PatchSee fin Cat. 6a U/UTP 2,1 m à repér...","{'availability': 'http://schema.org/InStock', ...",{'name': 'PatchSee'},845155,3.700820e+12

'Product_parrottfuneralhome.com_September2020.json.gz'

,name,offers,aggregaterating,review,itemcondition,model
0,Full Of Love Bouquet,"{'pricecurrency': 'USD', 'highprice': '69.95',...","{'reviewcount': '122', 'ratingvalue': '4.98'}","[{'name': 'Full Of Love Bouquet', 'author': 'f...",NewCondition,[{'url': 'https://www.parrottfuneralhome.com/s...
1,Lovely One Spathiphyllum Plant,"{'pricecurrency': 'USD', 'highprice': '74.95',...","{'reviewcount': '23', 'ratingvalue': '4.96'}",[{'description': 'PAID $125.00 FOR A $15 FLOWE...,NewCondition,{'url': 'https://www.parrottfuneralhome.com/st...
2,Sacred Duty Spray,"{'pricecurrency': 'USD', 'lowprice': '149.95',...","{'reviewcount': '34', 'ratingvalue': '4.82'}","[{'author': 'from -', 'datepublished': '2/21/2...",NewCondition,{'image': 'https://res.cloudinary.com/picasso/...
3,Country Basket Blooms,"{'pricecurrency': 'USD', 'lowprice': '67.95', ...","{'reviewcount': '145', 'ratingvalue': '4.97'}","[{'name': 'Country Basket Blooms', 'descriptio...",NewCondition,"[{'sku': 'T48-3A', 'name': 'Country Basket Blo..."
4,Peaceful White Lilies Basket,"{'pricecurrency': 'USD', 'highprice': '89.95',...","{'reviewcount': '250', 'ratingvalue': '4.93'}","[{'datepublished': '6/10/2020', 'description':...",NewCondition,{'url': 'https://www.parrottfuneralhome.com/st...

'Product_kbctools.com_September2020.json.gz'

,name,offers,brand,category,mpn,weight
0,SD-3 MA FORD DOUBLE CUT BUR,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",{'name': 'M.A. FORD'},Rotary Burrs,43157,"{'value': '0.06', 'unittext': 'lbs'}"
1,33/64X3/4 DRILL JIG BUSHING,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",{'name': 'KBC'},Drill Jig Bushings,P-56-12 33/64 (135),"{'unittext': 'lbs', 'value': '0.2'}"
2,NO.250ID 90DEG. HIGH SPEED BURR,"{'pricecurrency': 'USD', 'price': '5.79', 'pri...",{'name': 'RICO'},Rotary Burrs,40341,"{'value': '0.05', 'unittext': 'lbs'}"
3,NO.19X3/4 DRILL JIG BUSHING,"{'pricecurrency': 'USD', 'pricevaliduntil': '2...",{'name': 'KBC'},Drill Jig Bushings,P-20-12 #19 (135),"{'unittext': 'lbs', 'value': '0.2'}"
4,SM-41 MA FORD CARBIDE BUR,"{'pricecurrency': 'USD', 'price': '6.9', 'avai...",{'name': 'M.A. FORD'},Rotary Burrs,69393,"{'value': '0.06', 'unittext': 'lbs'}"

'Product_hubertvestertoyota.com_September2020.json.gz'

,name,offers,brand,mpn,model,manufacturer,color
0,New 2020 Toyota Camry LE FWD 4,{'itemcondition': 'http://schema.org/NewCondit...,Toyota,2532,Camry,{'name': 'Toyota'},BROWNSTONE
1,New 2020 Toyota Corolla LE FWD 4,{'itemcondition': 'http://schema.org/NewCondit...,Toyota,1852,Corolla,{'name': 'Toyota'},CLASSIC SILVER MET
2,New 2020 Toyota C-HR XLE FWD 5,{'itemcondition': 'http://schema.org/NewCondit...,Toyota,2404,C-HR,{'name': 'Toyota'},SILVER KNOCKOUT MET
3,New 2020 Toyota Corolla SE FWD 4,"{'price': '25269', 'itemcondition': 'http://sc...",Toyota,1864,Corolla,{'name': 'Toyota'},CLASSIC SILVER MET
4,Certified Pre-Owned 2020 Toyota Corolla Hybrid...,{'itemcondition': 'http://schema.org/UsedCondi...,Toyota,1882,Corolla Hybrid,{'name': 'Toyota'},Blue

'Product_millerwardfuneralhome.com_September2020.json.gz'

,name,offers,aggregaterating,review,itemcondition,model
0,Arrive in Style,"{'pricecurrency': 'USD', 'highprice': '69.95',...","{'reviewcount': '132', 'ratingvalue': '4.91'}","[{'datepublished': '6/1/2020', 'description': ...",NewCondition,"[{'name': 'Arrive in Style (Standard)', 'sku':..."
1,Heavenly Sentiments Spray,"{'pricecurrency': 'USD', 'lowprice': '202.95',...","{'reviewcount': '4', 'ratingvalue': '5.00'}","[{'author': 'from -', 'description': 'Arrangem...",NewCondition,"{'sku': 'T247-2A', 'name': 'Heavenly Sentiment..."
2,Pink Tribute Spray,"{'pricecurrency': 'USD', 'lowprice': '114.95',...","{'reviewcount': '82', 'ratingvalue': '4.95'}",[{'description': 'I purchased this spray for a...,NewCondition,{'url': 'https://www.millerwardfuneralhome.com...
3,Beautiful in Blue,"{'lowprice': '64.95', 'highprice': '84.95', 'p...","{'reviewcount': '311', 'ratingvalue': '4.92'}",[{'description': 'Unfortunately I didn't get t...,NewCondition,"[{'name': 'Beautiful in Blue (Premium)', 'imag..."
4,Emerald Garden Basket,"{'pricecurrency': 'USD', 'lowprice': '67.95', ...","{'reviewcount': '111', 'ratingvalue': '4.90'}","[{'author': 'from Bartlesville - Oklahoma', 'n...",NewCondition,{'url': 'https://www.millerwardfuneralhome.com...

'Product_3bscientific.co.uk_September2020.json.gz'

,name,offers,brand,mpn,weight
0,Replica Homo Erectus Pekinensis Skull (Weidenr...,"{'price': '157.92', 'pricecurrency': 'GBP'}",3B Scientific,VP750/1,"{'value': '1.21', 'unitcode': 'KGM'}"
1,Functional Human Hip Joint Model with Ligament...,"{'pricecurrency': 'GBP', 'price': '103.79'}",3B Scientific,A81/1,"{'unitcode': 'KGM', 'value': '0.74'}"
2,Acupuncture needles MOXOM TCM 100 pcs. (Uncoat...,"{'price': '3.96', 'pricecurrency': 'GBP'}",Moxom,CW-3030,"{'unitcode': 'KGM', 'value': '0.063'}"
3,Acupuncture needles MOXOM TCM 1000 pcs. (silic...,"{'price': '34.68', 'pricecurrency': 'GBP'}",Moxom,CC10-3030,"{'value': '0.281', 'unitcode': 'KGM'}"
4,Injection Belly,"{'price': '136.80', 'pricecurrency': 'GBP'}",None,WA28395U,"{'unitcode': 'KGM', 'value': '0.91'}"

'Product_evybenita.com_September2020.json.gz'

,name,offers,brand,mpn,itemcondition,color
0,Clouded Leopard Enamel Pin,"{'price': '12.90', 'availability': 'http://sch...",Evy Benita,clouded-leopard-enamel-pin,https://schema.org/NewCondition,None
1,SECONDS: Whale Shark (RAINBOW) - Galactic Reef...,"{'pricecurrency': 'AUD', 'availability': 'http...",Evy Benita,seconds-whale-shark-rainbow-galactic-reef-coll...,https://schema.org/NewCondition,Blue / Lilac
2,SECONDS: Full Set: Galactic Reef Collection (G...,"{'pricecurrency': 'GBP', 'pricevaliduntil': '2...",Evy Benita,seconds-full-set-galactic-reef-collection-gold-2,https://schema.org/NewCondition,Lilac / Pink / White
3,Arctic Fox (Gold)- Arctic Nova Collection,"{'price': '10.00', 'availability': 'http://sch...",Evy Benita,seconds-arctic-fox-gold-arctic-nova-collection-2,https://schema.org/NewCondition,White
4,SECONDS: Whale Shark (RAINBOW) - Galactic Reef...,"{'availability': 'http://schema.org/InStock', ...",Evy Benita,seconds-whale-shark-rainbow-galactic-reef-coll...,https://schema.org/NewCondition,Blue / Lilac

'Product_lovebirdsb.com_September2020.json.gz'

,name,offers,brand,mpn,itemcondition
0,Rag Poets Fulton Sweater,"{'validfrom': '2020-09-28', 'pricevaliduntil':...",Rag Poets,RW203323,https://schema.org/NewCondition
1,ElizabethW Body Lotion,"{'availability': 'https://schema.org/InStock',...",ElizabethW,None,https://schema.org/NewCondition
2,Metro Tote,"{'validfrom': '2020-09-28', 'url': 'https://ww...",None,None,https://schema.org/NewCondition
3,Inizio Linen Magic Capri Pant,"{'availability': 'https://schema.org/InStock',...",Inizio,3443,https://schema.org/NewCondition
4,Driftwood Saydi Jean Skirt,"{'price': '88.00', 'pricecurrency': 'USD', 'va...",Driftwood,K40266A,https://schema.org/NewCondition

'Product_catersuppliesdirect.com_September2020.json.gz'

,name,offers,brand,mpn,itemcondition
0,Bolsius Dinner Candle Glass Holder,"{'price': '1.20', 'availability': 'http://sche...",bolsius,103684140300,new
1,Mixology Spritz 57cl 20oz,"{'pricecurrency': 'GBP', 'availability': 'http...",Cater Supplies Direct,15-42-137,new
2,Martini Cocktail Black Light 21cl,"{'price': '6.43', 'pricevaliduntil': '2021-12-...",Cater Supplies Direct,H2389,new
3,5L Maxima Bactericidal Food Safe Cleaner/Sanit...,"{'pricevaliduntil': '2021-12-31', 'price': '12...",Cater Supplies Direct,C128MAX,new
4,Peacock Flute 20cl,"{'price': '10.00', 'availability': 'http://sch...",Cater Supplies Direct,ART51184,new

'Product_citydrawers.com_September2020.json.gz'

,name,offers,brand,mpn,itemcondition,reviewcount,ratingvalue,bestrating,worstrating
0,Boody - Boody BK Classic Bikini,"{'pricecurrency': 'USD', 'price': '11.95'}",Boody,BOODY BK-XS-Nude,http://schema.org/NewCondition,0,0,5,1
1,Natori - Natori 7462111 Statement pieced cup u...,"{'pricecurrency': 'USD', 'price': '68.00'}",Natori,None,http://schema.org/NewCondition,0,0,5,1
2,Boody - Boody BR Shaper Bra,"{'pricecurrency': 'USD', 'price': '16.95', 'av...",Boody,BOODY BR-M/L-Nude,http://schema.org/NewCondition,0,0,5,1
3,Evelyn+Bobbie - EVEBOB 17102 Midrise Hipster,"{'pricecurrency': 'USD', 'price': '22.00', 'av...",Evelyn+Bobbie,None,http://schema.org/NewCondition,0,0,5,1
4,Boody - Boody RBB Active Racerback Bra,"{'pricecurrency': 'USD', 'price': '39.95', 'av...",Boody,None,http://schema.org/NewCondition,0,0,5,1

'Product_artsy.net_September2020.json.gz'

,name,offers,brand,category,width,height
0,David Hockney | David Hockney A Bigger Book Ha...,None,{'name': 'David Hockney'},Books and Portfolios,27 3/5 in,19 7/10 in
1,Kumikaho Oshima | legs2 (2009) | Available for...,"{'pricecurrency': 'EUR', 'availability': 'http...",{'name': 'Kumikaho Oshima'},Painting,55 1/10 in,42 1/10 in
2,"Newcomb College, Small Two-handled Vase with S...",None,None,Design/Decorative Art,4 in,5 in
3,"Attributed to Syrie Maugham | Desk, England (1...",None,{'name': 'Attributed to Syrie Maugham'},Design/Decorative Art,31 1/2 in,64 in
4,Awol Erizku | Girl with a Bamboo Earring (2009...,None,{'name': 'Awol Erizku'},Photography,64 in,49 in

'Product_topoutdoorsupplies.com_September2020.json.gz'

,name,offers,brand,category,mpn
0,24&#8243;-29&#8243; Bicycle Bike Kick Stand MT...,"{'pricevaliduntil': '2020-10-17', 'availabilit...",{'name': 'topoutdoorsupplies.com'},Kickstand,10071
1,original supacaz tape road bike bar tape carbo...,"[{'price': '42.97', 'pricevaliduntil': '2020-1...",{'name': 'topoutdoorsupplies.com'},Handlebar Tape,8766
2,Adjustable Unisex Bike Cycling Helmet Baseball...,"{'price': '26.73', 'name': 'Adjustable Unisex ...",{'name': 'topoutdoorsupplies.com'},Bicycle Helmet,8149
3,MTB Road Bike Stand Parking Adjustable Aluminu...,{'name': 'MTB Road Bike Stand Parking Adjustab...,{'name': 'topoutdoorsupplies.com'},Kickstand,10045
4,WEST BIKING Bicycle Water Bottle Portable Leak...,"{'pricevaliduntil': '2020-10-16', 'availabilit...",{'name': 'topoutdoorsupplies.com'},Bicycle Water Bottle,8602

'Product_ppssurf.com_September2020.json.gz'

,name,offers,price,shop-currency
0,FACE MASK,FACE MASK VISSLA $10.00 Quantity: Subtotal: $1...,$10.00,AUD
1,FK PSYCHO,FK PSYCHO FK $40.00 Quantity: Subtotal: $40.00...,$40.00,AUD
2,4020 GROMS STINGER,4020 GROMS STINGER CARVE GROMS STINGER $29.99 ...,$29.99,AUD
3,RIFLES MIDSIZE TIDE,RIFLES MIDSIZE TIDE RIP CURL Surf Watches $199...,$199.99,AUD
4,THE JAM H2O FLOATABLE,THE JAM H2O FLOATABLE DRAGON Product Informati...,$230.00,AUD

'Product_wildyakexpeditions.com_September2020.json.gz'

,name,brand,aggregaterating,review,gtin8
0,AMA DABLAM,{'name': 'Wildyak Expeditions.'},"{'reviewcount': '7', 'ratingvalue': '5'}","{'description': '<p>The Ama Dablam, 6856 meter...",WYES810
1,TSUM VALLEY Trek,{'name': 'Wildyak Expeditions.'},"{'reviewcount': '7', 'ratingvalue': '5'}","{'name': 'TSUM VALLEY Trek', 'author': 'Wild Y...",WYES236
2,TIBET Tour,{'name': 'Wildyak Expeditions.'},"{'reviewcount': '7', 'ratingvalue': '5'}",{'description': '<p>WILD YAK EXPEDITIONS bring...,WYES4045
3,ISLAND Peak,{'name': 'Wildyak Expeditions.'},"{'reviewcount': '7', 'ratingvalue': '5'}",{'description': '<p>WILD YAK EXPEDITIONS welco...,WYES678
4,LOBUCHE Peak,{'name': 'Wildyak Expeditions.'},"{'reviewcount': '7', 'ratingvalue': '5'}","{'author': 'Wild Yack Expeditions', 'descripti...",WYES646

'Product_goelectrical.com.au_September2020.json.gz'

,name,mpn,model,color,gtin8
0,Building Wire 1 Core 1.5mm PVC Blue 0.6/1kV,ADVBW1.5BL,Building Wire 1 Core 1.5mm PVC Blue 0.6/1kV,Black,ADVBW1.5BL
1,Building Wire 1 Core 2.5mm PVC Grn/Ylw 0.6/1kV,APEIVM205E-1,Building Wire 1 Core 2.5mm PVC Grn/Ylw 0.6/1kV,Black,APEIVM205E-1
2,Building Wire 1 Core 1.5mm V90HT PVC Grey 450/...,ELCSR1015-GRY,Building Wire 1 Core 1.5mm V90HT PVC Grey 450/...,Black,ELCSR1015-GRY
3,Building Wire 1 Core 4.0mm PVC White 0.6/1kV,OLX7/085BWWA5,Building Wire 1 Core 4.0mm PVC White 0.6/1kV,Black,OLX7/085BWWA5
4,SDI 1 Core 10mm Cu PVC/PVC Red Core Wht,TYCBDM17135-WH-500,SDI 1 Core 10mm Cu PVC/PVC Red Core Wht,Black,TYCBDM17135-WH-500

'Product_lovelypetzone.com_September2020.json.gz'

,name,offers,brand,aggregaterating,category,mpn,review
0,Dog’s Warm Coral Fleece Bed Blankets,"{'availability': 'https://schema.org/InStock',...",lovelypetzone.com,"{'reviewcount': '14', 'ratingvalue': '4.40'}",None,1566,None
1,Absorbent Soft Dog’s Adjustable Towel,"{'price': '19.96', 'availability': 'https://sc...",lovelypetzone.com,"{'ratingvalue': '4.30', 'reviewcount': '12'}",None,1525,None
2,Large Space Themed Blanket for Pets,"{'availability': 'https://schema.org/InStock',...",lovelypetzone.com,"{'ratingvalue': '4.60', 'reviewcount': '18'}",None,1568,None
3,Pet Paw and Heart Shaped Pendant Necklace,"{'availability': 'https://schema.org/InStock',...",lovelypetzone.com,"{'ratingvalue': '4.60', 'reviewcount': '14'}",None,2050,None
4,Portable Dog Water Bottle for Outdoor Use,"{'price': '15.98', 'availability': 'https://sc...",lovelypetzone.com,"{'ratingvalue': '4.50', 'reviewcount': '14'}",None,1626,None

'Product_festapratica.com_September2020.json.gz'

,name,offers,brand,gtin13,weight
0,Balão Metalizado Letra Gigante Dourada 95cm,"[{'pricecurrency': 'BRL', 'itemcondition': 'ht...",{'name': 'Festa Prática'},9.990000e+12,10g
1,Vela Estrela Azul - Curifest,"[{'pricecurrency': 'BRL', 'itemcondition': 'ht...",{'name': 'Festa Prática'},7.896902e+12,20g
2,Balão Metalizado Letra Gigante Dourada 95cm,"[{'pricecurrency': 'BRL', 'itemcondition': 'ht...",{'name': 'Festa Prática'},9.990000e+12,10g
3,Balão Metalizado Número Gigante Preto 95cm,"[{'pricecurrency': 'BRL', 'sku': '999000015276...",{'name': 'Festa Prática'},9.990000e+12,10g
4,Balão Metalizado Número Gigante Rosa 95cm,"[{'pricecurrency': 'BRL', 'itemcondition': 'ht...",{'name': 'Festa Prática'},9.990000e+12,10g

'Product_perapasha.com_September2020.json.gz'

,name,brand,category,review,model,breadcrumb,offerdetails
0,Scheepjes Maxi Sugar Rush 50 g Tangerine,Scheepjeswol,Home » Scheepjes Maxi Sugar Rush 50 g Tangerine,"{'count': '0', 'rating': '0'}",SSURUSH281,Home » Scheepjes Maxi Sugar Rush 50 g Tangerine,"{'currency': 'EUR', 'seller': 'perapasha', 'pr..."
1,Lang Yarns Merino 120 Degrade Gerbera (37.0008),Lang Yarns,Home » Lang Yarns Merino 120 Degrade Gerbera (...,"{'count': '0', 'rating': '0'}",LY37.0008,Home » Lang Yarns Merino 120 Degrade Gerbera (...,"{'currency': 'EUR', 'seller': 'perapasha', 'pr..."
2,DMC Mouline Color Variations Embroidery Thread...,DMC,Home » DMC Mouline Color Variations Embroidery...,"{'count': '0', 'rating': '0'}",DMCC4200,Home » DMC Mouline Color Variations Embroidery...,"{'price': '1.750023', 'currency': 'EUR', 'sell..."
3,Opti Zipper 20 cm 4801-0542,Opti,Home » Opti Zipper 20 cm 4801-0542,"{'count': '0', 'rating': '0'}",OP4801-0020-0542,Home » Opti Zipper 20 cm 4801-0542,"{'currency': 'EUR', 'seller': 'perapasha', 'pr..."
4,Durable Cosy Denim (290),Durable,Home » Durable Cosy Denim (290),"{'count': '0', 'rating': '0'}",DUCO290,Home » Durable Cosy Denim (290),"{'price': '3.599992', 'currency': 'EUR', 'sell..."

'Product_dutchflies.com_September2020.json.gz'

,name,offers,brand,mpn,gtin13
0,Quick release indicators,"{'price': '6.25', 'availability': 'https://sch...",{'name': 'Glomavis'},Phill-quick-in,Phill-quick-in
1,Whipfinisher,"{'price': '3.95', 'availability': 'https://sch...",{'name': 'Glomavis'},Whipfinisher,Whipfinisher
2,Worm body,"{'price': '2.25', 'availability': 'https://sch...",None,Worm body,Worm body
3,RIO Mainstream 12ft Sink Tip Line,"{'price': '49.90', 'availability': 'https://sc...",{'name': 'Rio'},RM12ftSink,RM12ftSink
4,Hard Varnish,"{'price': '2.75', 'availability': 'https://sch...",{'name': 'Glomavis'},Hard Varnish,Hard Varnish